### ISSUE TITLE
reference：https://github.com/wbkd/react-flow/issues/916

### ISSUE THREAD

**Issue by sunWoodsen** [xyflow/xyflow#1836]
I had a similar problem. When I dynamically add a handler on a custom node, I find that the node's handlerDOM is updated, but when I create an edge for the node at the same time after the addition is successful, I find that the targetNode cannot be found (I specified targetNode), followed by I used useUpdateNodeInternals when the handler was successfully created. I found that getHandle still cannot get the latest handler dom. I suspect that there is a bug in the state synchronization.
![image](https://user-images.githubusercontent.com/39180485/149318262-ce50c5a0-87cd-4749-ad21-44db5c5adcf5.png)

here i can't get the latest handlers

_Originally posted by @sunWoodsen in https://github.com/wbkd/react-flow/issues/916#issuecomment-1012030847_

**Comment by Ipicky22** [comment]
Hi @sunWoodsen !

Can you share an example or your code ?
I created a custom node that allows to dynamically manage the number of handles. I also had a state problem for the handles, and I was able to solve it thanks to a useEffect containing the updateNodeInternals function.
I share my issue with you, maybe it can help you : [https://github.com/wbkd/react-flow/issues/1641](#1641 )

I'm not sure I fully understand your problem, but hope my answer helps you.

**Comment by siavashg87** [comment]
I experience same issue.

Using dynamic handles looks fine in the browser as added handles are visible. 
However connecting the new generated handle (outbound) to an existing input handle will not draw the line.

This also results in following warning: "couldn't create edge for source handle id: __handle__id__; edge id: __edge_id__"

I guess that @sunWoodsen is programmatically generating an edge, which will lead to the same issue I'm experiencing.

**Comment by sunWoodsen** [comment]
> 
Yes, it is this situation that causes the error, when I create the handler dynamically, it looks normal, but when I create a new edge for the new handler, I get an exception

**Comment by sunWoodsen** [comment]
> I experience same issue.
> 
> Using dynamic handles looks fine in the browser as added handles are visible. However connecting the new generated handle (outbound) to an existing input handle will not draw the line.
> 
> This also results in following warning: "couldn't create edge for source handle id: **handle__id**; edge id: **edge_id**"
> 
> I guess that @sunWoodsen is programmatically generating an edge, which will lead to the same issue I'm experiencing.

Yes, it is this situation that causes the error, when I create the handler dynamically, it looks normal, but when I create a new edge for the new handler, I get an exception

**Comment by moklick** [comment]
Hey @sunWoodsen ,

could you create a codesandbox for this issue?
