### ISSUE TITLE
Incorrect custom connectionline sourceposition with onEdgeUpdate

### ISSUE THREAD

**Issue by AndrewRayCode** [xyflow/xyflow#1853]
### Describe the Bug

In this screenshot, I'm updating the edge, by dragging the right side of it. The solid red line is the existing edge. The dotted line is the edge being dragged with a custom ConnectionLine.

<img width="442" alt="Screen Shot 2022-01-24 at 10 48 50 PM" src="https://user-images.githubusercontent.com/79215/150925931-60ace8f5-20b7-43a6-b514-db377e4e3c1e.png">

You can see the dotted lined connection edge is incorrectly attaching to the bottom of the node, not the right side. That seems to be because, in this line: 

https://github.com/wbkd/react-flow/blob/6b9d5ef5e4f464fd40aa037584ab2f8131318dd3/src/components/ConnectionLine/index.tsx#L73

There is no sourceHandle, so `isRightOrLeft` defaults to false.

This means the custom ConnectionLine component gets `targetPosition: top` and `sourcePosition: undefined`, so the custom bezier line I make in my ConnectionLine:

```
  const edgePath = getBezierPath({
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition,
  });
```

is treated as a vertical path, not a horizontal path.

### Steps to Reproduce the Bug or Issue

Create a custom connectionline for a right/left handled setup, make the edges draggable, and drag an edge connected to a left handle.

### Expected behavior

The custom connectionline receives the proper source and target information.

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 9.7.2

### Additional context

I'm using custom handles:
```
<Handle
          type="source"
          position={Position.Right}
          id="out"
          style={{ top: `${handleTop}px` }}
        />
```
and
```

            <Handle
              id={name}
              type="target"
              position={Position.Left}
              style={{ top: `${handleTop + index * 20}px` }}
            />
```

If that's relevant

**Comment by moklick** [comment]
Thanks! We'll check that.

**Comment by doflo-dfa** [comment]
I think we are seeing something similar ... we have a scenario where we are programmatically updating the the position via the style of the handle and or hiding / showing the handle ... upon doing so the origin of all new dragged edges is at the old location or in the case of previously hidden handles the origin of a newly dragged edge line originating from the previously hidden handle appears to be at the 0,0 coordinate of the flow container.

**Comment by mehecip** [comment]
This seems to still be a problem in 11.10.1. And it affects also getSmoothStepPath and  getSimpleBezierPath.
@AndrewRayCode did you find a way to overcome this?

**Comment by peterkogo** [comment]
@mehecip @AndrewRayCode 
ConnectionLines have been refactored in v12. Now the unavailable handle (either source or handle) will be assumed to be on the opposite side. 
Meaning, if you update an edge from a target handle that has `Position.Left` the ConnectionLine is assumed to originate from `Position.Right`.  You can check out [v12 beta](https://github.com/xyflow/xyflow/issues/3766) to see if this solves your problem.

**Comment by moklick** [comment]
This is fixed in React Flow 12!

If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12
