### ISSUE TITLE
useReactFlow: `setNodes([])` does nothing

### ISSUE THREAD

**Issue by RunDevelopment** [xyflow/xyflow#2147]
### Describe the Bug

Calling `setNodes([])` in an effect or event callback does nothing. It's only the `setNodes` from `useReactFlow`. The `setNodes` from `useNodesState()` works.

### Steps to Reproduce the Bug or Issue

As described above. This will happen in any application.

### Expected behavior

`setNodes([])` should remove all nodes.

### Platform

- OS: Win10
- Browser: na. Electron
- Version: "10.0.8

### Additional context

[This](https://github.com/wbkd/react-flow/blob/415fc77a3cfe17dc3d4a0cfa2e60766680593a65/src/hooks/useReactFlow.ts#L32) is the implementation for `setNodes`. In my debugging, `hasDefaultNodes` was `false` and `onNodesChange` was a function, so we take the `else if` branch.

```js
      const changes = nextNodes.map((node) => ({ item: node, type: 'reset' } as NodeResetChange<NodeData>));
      onNodesChange(changes);
```

Since my `nextNodes` is empty, `changes` will also be empty. Hence, [`applyChanges`](https://github.com/wbkd/react-flow/blob/415fc77a3cfe17dc3d4a0cfa2e60766680593a65/src/utils/changes.ts#L47) find no `c.type === 'reset'` change.

---

`setEdges` has the same bug.

**Comment by RunDevelopment** [comment]
@moklick, @chrtze Is there an interest in fixing this?

**Comment by moklick** [comment]
Hey @RunDevelopment 

I will check your PR now. I think, that we made a mistake by allowing users to use these functions for controlled flows. They were only meant to be used with uncontrolled flows and also not necessary for controlled flows. Not 100% sure if I want to go this road further or remove the functionality completely for controlled flows.

**Comment by RunDevelopment** [comment]
It would be nice if `useReactFlow` could continue to work for both. It's simply very convenient to have access to all nodes and edges (and their setters) without having to do the context work/props passing yourself. 

We currently work around this bug by passing the `setNodes` and `setEdges` function around using a context.

**Comment by moklick** [comment]
Thanks for your help! This was a good fix for the issue and you are right, that it's very convenient to have these helper functions.

**Comment by moklick** [comment]
released in v10.2.3

**Comment by RunDevelopment** [comment]
Thank you, @moklick!

**Comment by nathanqueija** [comment]
I am facing the same thing with version 11.7.3 calling `setNodes` from `useReactFlow` doesn't update the nodes defined with:

```typescript
 const [nodes, setNodes, onNodesChange] = useNodesState(props.nodes);
 ``` 
 
 Only calling `setNodes` from `useNodesState` seems to update the state. Is this known or is there any workaround? Similar to @RunDevelopment I don't want to prop drill setNodes in the tree.

**Comment by moklick** [comment]
Can you create a codesandbox for this? I can't repro your issue: https://codesandbox.io/s/summer-pine-vvt7h6?file=/src/NodeResetter.tsx:175-233

**Comment by dongtc** [comment]
> @moklick Thanks for taking the time to prepare the sandbox. I found what the problem was:
> 
> I was using the `useReactFlow` from within a sibling component from `<ReactFlow />`. I moved the sibling component to be a child and rendered it inside a Panel and now the `setNodes` function works.
> 
> What I don't understand is that my structure was:
> 
> ```ts
> <ReactFlowProvider>
>     <SettingsMenu />
>     <ReactFlow />
> </ReactFlowProvider>
> ```
> 
> From the SettingsMenu component I was calling the `setNodes` function. Shouldn't the SettingsMenu be able to call the `setNodes` function in this structure?
> 
> In any case, I changed the structure to be:
> 
> ```ts
> <ReactFlowProvider>
>     <ReactFlow>
>         <SettingsMenu />
>     <ReactFlow />
> </ReactFlowProvider>
> ```
> 
> And it works fine now!

I found the same thing.  Can you explain why the `setNodes` function was only effective within the `ReactFlow` component's subtree? @moklick

**Comment by moklick** [comment]
That's a bit weird indeed and shouldn't be the case. I will take a look.

**Comment by dongtc** [comment]
> That's a bit weird indeed and shouldn't be the case. I will take a look.

Sorry, I made a mistake, it actually works, thanks for your reply
