### ISSUE TITLE
When creating the edge cursor becomes "text" in Safari.

### ISSUE THREAD

**Issue by enshtein06** [xyflow/xyflow#2287]
### Describe the Bug

Hey guys! With a team we want to customize the cursor during the edge/node updates and met a problem in Safari browser. For edge updates it works as if we'd try to select the text on the website. I've tried to check that with examples that you've provided in the docs and there is the same problem.

### Steps to Reproduce the Bug or Issue

1. Using Safari browser to go https://reactflow.dev/docs/examples/overview/
2. Try to connect any nodes between each other.
3. Pay attention to what happens to the cursor.

### Expected behavior

It should work the same as it does for chrome - which is `cursor: "default"` and could be customized.

### Screenshots or Videos

https://user-images.githubusercontent.com/34091239/179011549-4773673d-02b5-416e-b7f5-2b2b6cfcd530.mov

### Platform

- OS: macOS
- Browser: Safari
- Version: 15.5 (17613.2.7.1.8)

**Comment by moklick** [comment]
Thanks for bringing this up! I tried to set the cursor explicitly and `user-select: none` but none of that worked. If anyone has an idea how to solve this, please let us know!

**Comment by moklick** [comment]
@stevensona will be fixed by https://github.com/wbkd/react-flow/pull/2833

**Comment by peterkogo** [comment]
This shouldn't happen in v12 anymore.
