### ISSUE TITLE
UserSelection gets canceled when mouse hovers on any other elements.

### ISSUE THREAD

**Issue by Alireza29675** [xyflow/xyflow#2399]
### Please describe the feature that you want to propose

Hi, React Flow Team 👋

I have a layout with React Flow in the middle and some panels around it, as well as a Floating Toolbar over my React Flow frame. My users are likely to work with node selection quite often. What happens is that whenever the mouse goes on Floating div over React Flow or goes a bit outside of React Flow frame, all the selection gets canceled.

### What I have:
![wrong](https://user-images.githubusercontent.com/2771377/188157846-03224876-a55d-4cbc-874e-38b5bc81681f.gif)

### What I expect:
![correct](https://user-images.githubusercontent.com/2771377/188157837-9d0edc02-af1a-49e2-be42-1d5be0080b07.gif)

Based on my investigation:

In the `UserSelection` component, we bound our mouse event callbacks such as `onMouseMove` and `onMouseLeave` to a `div`, which makes this happen.

One solution to this can be binding `mouseMove`, `mouseUp`, and `mouseLeave` to the `window` instead of `div`, but not touching the `mouseDown`, so the dragging will always start inside the frame and will go anywhere, it wants. We can also give the user an option to choose if they want the selection to go further than the react-flow box and not get canceled.

What is your opinion on this and what is the most optimized way to solve it in your opinion? I would be also happy to contribute, especially on this because it's getting blocker for me.

**Comment by moklick** [comment]
I won't change the current behaviour but it would be helpful to know if there is an active selection. By that you could set `pointer-events: none` for the panels on top of the pane. I will keep this open for now.

**Comment by cgross** [comment]
I will echo what @Alireza29675 says and add that it happens with the built-in components too like the toolbar and the minimap.  Other diagramming tools don't have this behavior and its really jarring for user experience.  I hope you reconsider the current behavior and look into ensuring the selection is not canceled by hovering over other elements or moving outside the container.

**Comment by moklick** [comment]
In v11.1.1 the selection doesn't break anymore when you drag over the controls, minimap or attribution. It's still not 100% perfect, but better than before. If you want this behaviour for a custom component, you can set pointer events to `'none'` when there is an active user selection: https://github.com/wbkd/react-flow/blob/main/packages/core/src/components/Panel/index.tsx#L15

**Comment by livwvil** [comment]
Hi all!
I faced with the same behaviour and it was unexpected for me.
On the one hand, I can move a node outside the browser window, return it back, move it inside the Reactflow container, and it will still be attached to the mouse pointer until I release the mouse button.
On the other hand, I can't do the same with "shift selection border", it just detaches from the mouse pointer and cancel.
@moklick You still don't want to change this behavior?

**Comment by peterkogo** [comment]
Good news everyone, this will be fixed in v12. You can track progress in this pull request #4379.

**Comment by moklick** [comment]
Fixed in React Flow 12! If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12
