### ISSUE TITLE
Plugin Components position issue when focusing on a node outside of the canvas

### ISSUE THREAD

**Issue by ysds** [xyflow/xyflow#2524]
### Describe the Bug

Background, Controls, MiniMap, and Attribution positions are not rendered correctly when focusing on a node or edge that is outside of the canvas.

### Your Example Website or App

https://reactflow.dev/docs/examples/overview/

### Steps to Reproduce the Bug or Issue

1. Access the basic example in https://reactflow.dev/docs/examples/overview/
2. Drag and move a node out of the area
3. Press Tab key to move focus to another node
4. Press Shift + Tab key to back focus to the node
5. Plugin Components' positions are wrong

### Expected behavior

They remain in their original position.

### Screenshots or Videos

https://user-images.githubusercontent.com/4065765/197756956-760dc748-ff20-4137-be24-951634dbb406.mov

### Platform

- OS: macOS
- Browser: Chrome

**Comment by AnsonH** [comment]
Before the fix is ready, a workaround is to prevent nodes from being keyboard-focusable by setting the value of [`nodesFocusable`](https://reactflow.dev/docs/api/react-flow-props/#nodesfocusable) prop to `false` in `<ReactFlow />`:

```tsx
<ReactFlow
  nodesFocusable={false}
  // ...
/>
```

**Comment by ysds** [comment]
my workaround is:
```css
.react-flow__renderer {
  overflow: hidden;
}
```
