### ISSUE TITLE
Zoom support for panOnScrollMode={PanOnScrollMode.Vertical}

### ISSUE THREAD

**Issue by vharadkou** [xyflow/xyflow#2574]
### Please describe the feature that you want to propose

When I set panOnScrollMode to Vertical, I expect zoom to zoomIn and zoomOut only for the center of the diagram Vertically (Not Horizontally).
Currently, zoom will happen to the current mouse location for all modes.

Currently, I implemented it with a custom onPaneScroll handler, and every time calculated the correct X for the viewport and remained Y the same. _**(Find the video below)**_
But I expect the library to support this behavior when Vertical is set or when a corresponding flag is provided.

https://user-images.githubusercontent.com/5987672/202851975-954505bf-b356-48ef-bad1-ea8193df27fd.mov

<img width="605" alt="Screenshot 2022-11-19 at 1 58 44 PM" src="https://user-images.githubusercontent.com/5987672/202852043-1f9173ef-ee34-49fe-81fe-5384ad670937.png">

<img width="497" alt="Screenshot 2022-11-19 at 1 51 42 PM" src="https://user-images.githubusercontent.com/5987672/202851979-3f385881-0231-4d44-a17a-ed48d67c56b9.png">

**Comment by moklick** [comment]
`panOnScrollMode` as the name implies, only is about panning. A zoom always affects both axis.

**Comment by vharadkou** [comment]
@moklick we need a property for zoom to affect only selected axis. Please :)
