### ISSUE TITLE
Option to position handle at center `Position="center"

### ISSUE THREAD

**Issue by cliffordfajardo** [xyflow/xyflow#2665]
### Please describe the feature that you want to propose

A use case which is common in other node/graph libraries is to render an edge handle at the center of the node.
Currently to achieve this in reactflow, you need to fully opt into using a custom node & custome edge.

## Feature Suggestion
Introduce `center` value for the `targetPosition` and `sourcePosition` attributes on a node so that users don't have to resort to custom node and edges so early.

## Things I attempted:
**1. Attempted to not use Custom Nodes or Edges.**
By default when you render a node, it will show 2 handles if you don't specify it `type` ([nodeOptions docs](https://reactflow.dev/docs/api/nodes/node-options/#type-1)).

![CleanShot 2022-12-09 at 11 55 54@2x](https://user-images.githubusercontent.com/6743796/206786110-ac1fadb8-9cc1-4897-a3a1-7ab3e9585a30.png)

The extra handles seemed confusing and redundant for our users of our app, so I added `sourcePosition` and `targePosition` to my nodes to be the same value so they stack on each other:

```js
// we could have made both values "top" as well
sourcePosition: 'bottom',
targePosition: 'bottom'
```

This definitely helped remove some confusion as there only appears to be one handle on the node
![CleanShot 2022-12-09 at 11 57 32@2x](https://user-images.githubusercontent.com/6743796/206786313-153cb1a2-08de-43a3-94c8-99ee882e5623.png)

Currently, there doesnt seem to be a way to position the edge handle at the center of the node without having to drop down to creating a custom node and edge. 

 
**2. Using Custom Node and Custom Edge**
To get my handle to render directly in the center of my node, I had to opt into creatingL
- custom node
- custom edge
- learn about handles and how to configure them
![CleanShot 2022-12-09 at 12 02 35@2x](https://user-images.githubusercontent.com/6743796/206787022-1dc73fa6-4a89-4521-b773-24585247662b.png)

### Suggestion
Dropping down to custom edge and custom nodes to achieve placing a handle at the center feels like a lot of work for a seemingly simple use case
It would be nice to be able to pass in array of `nodes` and `edges` & set the following on my node objects

```ts
sourcePosition: 'center',
targetPosition: 'center'
```

The value of `center` would center the edge at the center of the node using something like this:
```tsx
    style={{
       position: "absolute",
       top: "50%",
       right: "50%",
       transform: "translate(50%,-50%)"
    }}
```

## Codesandbox
https://codesandbox.io/s/react-flow-render-edge-in-middle-custom-vs-standard-flow-powrkf?file=/src/components/Example1/index.tsx
![CleanShot 2022-12-09 at 12 09 55@2x](https://user-images.githubusercontent.com/6743796/206788143-93cbfb7b-d1c1-41f4-97f3-75d64a7f0556.png)

### References
- `targetPosition` and `sourcePosition` docs: https://reactflow.dev/docs/api/nodes/node-options/#targetposition

**Comment by moklick** [comment]
Hey @cliffordfajardo 

thanks for the suggestion! I will discuss it with the team :) 

For now you could adjust the position with CSS (there is no need for a custom node):

```css
.react-flow .react-flow__handle {
  top: 50%;
  left: 50%;
  right: auto;
  bottom: auto;
  transform: translate(-50%, -50%);
}
```

https://codesandbox.io/s/inspiring-hooks-sm809y?file=/styles.css:134-261

**Comment by tuannguyenhoangit-droid** [comment]
I cried when see that
@moklick 

> Hey @cliffordfajardo
> 
> thanks for the suggestion! I will discuss it with the team :)
> 
> For now you could adjust the position with CSS (there is no need for a custom node):
> 
> ```css
> .react-flow .react-flow__handle {
>   top: 50%;
>   left: 50%;
>   right: auto;
>   bottom: auto;
>   transform: translate(-50%, -50%);
> }
> ```
> 
> https://codesandbox.io/s/inspiring-hooks-sm809y?file=/styles.css:134-261

I cried when see that

**Comment by ArianSha** [comment]
Hi @moklick, are there any further development/information for this feature?

I'm new to using React Flow, and I want to commend you guys for creating such a powerful tool with great DX. However, I find that this feature is sorely missed.

I'm currently designing a network graph, with a custom circular Node, and where the handle is both source and target (ConnectionMode.Loose). As the graph scales, it becomes quite messy and unaesthetic.

Suggestion:
I +1 on @cliffordfajardo  suggestion to have 'center' as an option for position in <Handle />

Additionally, an implementation could involve making the handle invisible, and to connect to a node you can just drag the edge anywhere inside the node. With an invisible handle, a double click on a node could initiate a drag, or a double click on two nodes could establish a connection.

**Comment by moklick** [comment]
@ArianSha This is already possible and we have an example for this https://reactflow.dev/docs/examples/nodes/easy-connect/

**Comment by mcmxcdev** [comment]
Seems related -> I am actually looking for Position allowing e.g. `top-left` and `top-right` since our nodes are having a header body and footer and we want to attach the edges to the headers in this case.

**Comment by bcakmakoglu** [comment]
> Seems related -> I am actually looking for Position allowing e.g. `top-left` and `top-right` since our nodes are having a header body and footer and we want to attach the edges to the headers in this case.

The position of a handle is mainly used to determine from what angle an edge has towards the handle.
Positions like top-left etc. make this, imo, more complicated than it needs to be - what angle do we use for a top-left/top-right etc. handle? How is that supposed to look?

For the use-case you describe you don't even need such a position.
Handles use `position: absolute`, which means that if you wrap your Handle inside another element that has `position: relative` the handle will be absolutely positioned relative to that element.
So just move your handle into the header (or whatever other element), add `position: relative` to your header element and use `<Handle position={Position.Left} ...>` (or whatever position your handle is supposed to have) and you're done.

**Comment by moklick** [comment]
Positioning a handle in the center of a node is a special case that only works for straight edges out of the box. Since it's already possible with CSS to display a handle in the center of the node, we will not add another Position type to the library.
