### ISSUE TITLE
[BUG] Invalid assignment / no type checking between the data field of Node<NodeData> types

### ISSUE THREAD

**Issue by dabdine** [xyflow/xyflow#2729]
### Describe the Bug

The `Node` type does not properly validate the `data` field when the receiving type is more specific than the source type during assignment.

### Your Example Website or App

[See this live on typescriptlang.org](https://www.typescriptlang.org/play?ts=4.9.4&noStrictGenericChecks=false#code/CYUwxgNghgTiAEBbA9sArhBBhNM4DsAXeAbwCh5L4QAPAB2RmMIE86EA5VEAHgBV4AXnhR8LAHxDSFKrICWwAFzwAzoRhz8AcwDcM2ZWBRCUZXz2yAvnutkyoSLAQp0meADE5NEMGmzW7PBcoAAiICZyECpSJPAKymoa2jrwtv5snNz8Umj4ANb4yADu+JLCwSBhEVHwAGR+BobGpvDm+qk2dgD0XfAAkhxYAPIASiMAolh8CQAWyBi+hcQARggMKipyy5hk5LKYxPgAjMo4eCBEAHQVPPhoiKswZaRxSvAARABmyMjvADTwIwmZQAVlS7TAyHwang+AATKdcARCNduDFXsp3stYP9Ac1MSD3uDZMcpPCUj14AEQMhPrCjpcgVA4tFCkUPolNFoiZo1CAoL5abD7o8ASAAG4XKlzNBaGbShDUllBLJ3B4gJ5kSzdXrDMaTabUGjqKBgQhc+AAAyZZktcSIyBEVIy8E+MCgWkQF2Iol8mkIGpU4HN2ngRTkhHlkYQ+BARQgLHgYDgxh8VoqVSgkRUds+XhA0Qjl3gAHUELR2GaRPhqHhGGGZlKoBs5Fp8Bbjrt2gd6cpPN5gKjQLcRRrnrF4h9vr8ATb4GDtftwrCER584OKujJ1icbP8R9CcSqKThOT2vCyUcKb05kUJRqAYVazB683Nm2O3CRIXiHJoszMA2VRKzkPMwGdQIAAotB+YAAEotR1eA9QmKZlDfVt21DYBQM+DVvQggsw0iCARAgIooBYaJPizCAuyXQ4TjXAch14NVHnHDEpx+XE5wXbtl3hPt11YnhOW0Tjt2xGBeP3d5D0XY8jjJOFOjISkUINZQhmWAArYNoiKRg8ipH5iz4Iz4GQPSDOlYxAShAByYgVGMP9PkTfkwHlZBoxgVQZQgXwaMiS56KoJV3B+GJ2lkaSEnULkLCobV2iVAAhKAAC8YsaSh4uFdUYGSyhUoY3tmJ8USouQSS3i+Hi92BF4CveGY5CJSwj0oHshMqjcskyrK6sxaTZOa2ICoXbr6RUtSNNGVDDR0-SzWiSN7MQOQ638ryfL8gL5iCsiIGKb933wL0rnCyhIui4Q9jygrxN0doyoil0AEU0BoXKntgBKkleqw7HK45hJYm4apG7iZzxCb4Fa9rOpm3rV37Kqbm+mgYZ3GSmpaSaAY+FhflSGaTxXebdUWrTSwQNQSKNSsfRbNsrpWcI7ylLQLg1ORwMKUB1sdIyYDyMLHp6wSmIxgbQC3erp3Glp+NkSFoUOdGRM3B6uLxlWCU689lNPVStSAA)

### Steps to Reproduce the Bug or Issue

1. Create a variable "foo" of type `Node<A>`
2. Create a variable "bar" of type `Node` (or `Node<any>` -- same thing, since Node defines T as having the default type any)
3. Assign bar to foo: foo = bar;

### Expected behavior

I expect a typescript error because the more generic type should not satisfy the more specific type parameter.

### Platform

- OS: macOS
- react-flow: 11.1.2
- typescript: 4.9.4 (and 4.7.4)

**Comment by dabdine** [comment]
Notes:
1. You could also use `Node<T extends unknown = unknown>`, preventing the use of `any`, which would force folks to typecast before using `data`.
2. I did try just using `unknown` instead of any. In the typescript sandbox it works (you get an error), but outside (vscode, specifically) you don't get an error. I think it has to do with module exports but i'm no expert with typescript generics.

**Comment by dabdine** [comment]
woops, closed accidentally.

**Comment by moklick** [comment]
Hey @dabdine 

thanks for your suggestions. Since this would be a breaking change, I will put it on hold until we start to work on the next major release. Did you see the recent changes about the Node type? You can now also passes the type as a string to be able to distinguish more easily between different custom nodes types.

**Comment by moklick** [comment]
In v12 the `Node` type has new generic specs:

```js
type Node = <
  NodeData extends Record<string, unknown> = Record<string, unknown>,
  NodeType extends string | undefined = string | undefined>{
  ...
}
```
