### ISSUE TITLE
Resize on rotated node is not accurate.

### ISSUE THREAD

**Issue by Maquinours** [xyflow/xyflow#2777]
### Describe the Bug

The NodeResizer does not take into account the rotation of the node.

### Your Example Website or App

https://reactflow.dev/docs/examples/nodes/resize-rotate/

### Steps to Reproduce the Bug or Issue

Rotate a node to 90degrees and then, try to resize it. You'll see that the resizing is logical but not accurate for a human.

### Expected behavior

As a user, I expected to resize a rotated node easily, but I am seeing that the node is not rotated like a human could expect.

### Platform

- OS: Windows
- Browser: Firefox
- Version: 11.3.3

**Comment by NikMsh** [comment]
the same issue

**Comment by moklick** [comment]
The `NodeResizer` doesn't really support rotated nodes, because the rotation is not a built-in feature. I will leave this open until we make a decision if we want to integrate rotation.

**Comment by moklick** [comment]
We will not add rotation as a built-in feature for React Flow. If you need resizing and rotation, you would need to implement resizing in the custom node on your own since the built-in NodeResizer doesn't work with rotated nodes.

We will update the docs to make this more clear.
