### ISSUE TITLE
Stuck when zooming in for the first time

### ISSUE THREAD

**Issue by banana-test** [xyflow/xyflow#2794]
### Describe the Bug

When there are a large number of nodes, there will be a stuck problem when zooming the canvas for the first time

### Your Example Website or App

https://codesandbox.io/s/react-flow-test-0eft9e?file=/src/App.tsx

### Steps to Reproduce the Bug or Issue

Zoom at first time

### Expected behavior

it should be smooth

### Screenshots or Videos

![58700BD6-7746-4B9D-B13F-E201B79AFD60](https://user-images.githubusercontent.com/124160924/216049033-eab70f4c-da83-4a1d-b013-6024a0753852.png)

### Platform

- OS: macOS
- Browser:  Chrome,

### Additional context

The problem looks like it didn't have time to free memory, after canvas refresh

**Comment by moklick** [comment]
we addressed this issue in v12.

**Comment by jbownzino** [comment]
@moklick I'm experiencing this issue also. Do we have an ETA on v12?

**Comment by moklick** [comment]
There is no ETA for 12 stable, but you can already check out the current status https://github.com/xyflow/xyflow/discussions/3764

**Comment by moklick** [comment]
please re-open if issue persists.
