### ISSUE TITLE
Pan or drag-selection when clicking the non-drag handle

### ISSUE THREAD

**Issue by Max-ChenFei** [xyflow/xyflow#2947]
### Please describe the feature that you want to propose

Hi, here is an [example ](https://reactflow.dev/docs/examples/nodes/drag-handle/) from the official website that set customized the drag handle. But when I pan on the non-drag handle, it does nothing.  
If I set the `draggable =false`, we cannot drag anymore.

Will there be a new feature that allows the user to drag the node via drag-handle and pan the background if clicking the non-drag-handle?

Thanks a lot.

**Comment by peterkogo** [comment]
It's unfortunately impossible for us to support this on the library side. 

However you can achieve this by setting `pointerEvents: 'none'` either in the style of your node or globally on `react-flow__node-{yourCustomNode}` and then adding `pointerEvents: 'all'` on your drag handle.
