### ISSUE TITLE
Support Mutiple useOnSelectionChange Hook

### ISSUE THREAD

**Issue by zta7** [xyflow/xyflow#2980]
### Please describe the feature that you want to propose

I can't use `useOnSelectionChange `in different components, it will be merged into one in the end. I think this hook should allow me to monitor selection changes in different components.

**Comment by moklick** [comment]
Good catch. We will check how/ if we can support this.

**Comment by jrdn91** [comment]
Any update on this? I'm running into this exact issue currently

**Comment by juspky** [comment]
I'm running into this issue too.

**Comment by moklick** [comment]
Thanks for your help @juspky . This is released in 11.10.1
