### ISSUE TITLE
Add a `deselectOnClick` prop to configure if nodes/edges get unselected click

### ISSUE THREAD

**Issue by RichSchulz** [xyflow/xyflow#2989]
### Please describe the feature that you want to propose

I want to allow users to de-select a (selected) node by clicking it again. Currently I have to use `onNodeClick` and check whether the clicked node is selected and if so, de-select it. I would like to move this logic into `onNodesChange` so that when a selected node is clicked again `onNodesChange` gets called with the following node changes:
`{id: '$nodeID', type: 'select', selected: false}`

Wdyt? Does this make sense?

**Comment by solidprinciples** [comment]
Prop `deselectOnClick` or similar could make sense as a prop for `<ReactFlow />`

**Comment by moklick** [comment]
I like this idea. We will check it for the v12 release.

**Comment by moklick** [comment]
We decided not add a new prop for this specific use case. If you want to implement it, you can use the new `updateNode` helper like:  
  
```js
const onNodeClick = () => {
  if (selected) {
    updateNode(id, { selected: false });
  }
};
```
