### ISSUE TITLE
Missing Generic Node type in `applyNodeChanges`

### ISSUE THREAD

**Issue by Esequiel378** [xyflow/xyflow#3030]
### Describe the Bug

`applyNodeChanges` should have generics for the Node type.

The current type definition of `applyNodeChanges` is:

```tsx
export declare function applyNodeChanges<NodeData = any>(changes: NodeChange[], nodes: Node<NodeData>[]): Node<NodeData>[];
```

But this is problematic when you use it with custom nodes, with NodeData and NodeType

![image](https://user-images.githubusercontent.com/40343304/235921165-cfb8dfce-aac9-4b72-a16d-669825627f37.png)

To fix this, we should have a type definition of `applyNodeChanges` like this:

```tsx
export declare function applyNodeChanges<NodeData = any, NodeTypes = any>(changes: NodeChange[], nodes: Node<NodeData, NodeTypes>[]): Node<NodeData, NodeTypes>[];
```

### Steps to Reproduce the Bug or Issue

1. Follow the [Zustand guide](https://reactflow.dev/docs/guides/state-management/)
2. Create and use custom Nodes with a custom NodeData & NodeType with the following type definitions

```tsx
type CustomNodeData = {
  name: string;
};

type WidgetType = 'port' | 'adapter';

Node<CustomNodeData, WidgetType>[];
```

### Expected behavior

As a developer, I expect the return type of `applyNodeChanges` to be the same as the input nodes from the parameter so that I can have a full type-safe code.

### Screenshots or Videos

Return type error with the current `applyNodeChanges` type definition

![image](https://user-images.githubusercontent.com/40343304/235923037-3a3624bf-d06b-4250-ba8f-8857a5236b00.png)

Fixed with the proposed type definition

![image](https://user-images.githubusercontent.com/40343304/235923533-81f496f9-5bb5-436c-b313-fa90d3e90f0a.png)

### Platform

- OS: all
- Browser: all 
- Version: 11.7.0

**Comment by moklick** [comment]
That's a good point. We will add it in the next release.

**Comment by moklick** [comment]
I thought about this issue again and I think that a real fix for this would be a breaking change. We could add another generic as you said like `applyNodeChanges<NodeData, NodeType>` but this would only help if you always use the same NodeData. If you have multiple types with different data structures like:

```ts
type CustomNodeA = Node<{ label: 'string' }, 'type-a'>;
type CustomNodeB = Node<{ number: 2 }, 'type-b'>;
```

you would loose the information which type belongs to which data structure. I would suggest that we wait for the next major release and change the types for applyNodeChanges like this:

```ts
function applyNodeChanges<CustomNode extends Node>(changes: NodeChange[], nodes: CustomNode[]): CustomNode[] {
  return applyChanges(changes, nodes) as CustomNode[];
}
```

After such a change we could define different nodes with different data structures:

```ts
type NodeA = Node<{ label: string }, 'str'>;
type NodeB = Node<{ value: number }, 'num'>;

type CustomNode = NodeA | NodeB;
```

and pass them to the `applyNodeChanges` like this:

```ts
applyNodeChanges<CustomNode>(changes, nodes))
```

This would be easier and more flexible. There are probably lots of other parts in the code where we could use this structure.

**Comment by agauravdev** [comment]
hey @Esequiel378 so how did you solve it in the meantime? 😅 
I am facing the same issue.

**Comment by Esequiel378** [comment]
Hello there! I've ended up creating an external function that returns the expected types like this 

```ts
function applyNodeChangesWithTypes(changes: NodeChange[], nodes: CustomNode[]) {
  // @ts-ignore
  return applyNodeChanges(changes, nodes) as unknown as CustomNode[];
}
```

**Comment by agauravdev** [comment]
Oh thank you.. that's super helpful.

**Comment by FelipeEmos** [comment]
Hi, I'm sorry to bother if I'm by some chance missing something but [the comment above](https://github.com/xyflow/xyflow/issues/3030#issuecomment-1539959479) that proposes the solution seems to already be what's going on in the `main` branch of the project at the current  time I'm commenting this:




> ...
> you would loose the information which type belongs to which data structure. I would suggest that we wait for the next major release and change the types for applyNodeChanges like this:
> 
> ```ts
> function applyNodeChanges<CustomNode extends Node>(changes: NodeChange[], nodes: CustomNode[]): CustomNode[] {
>   return applyChanges(changes, nodes) as CustomNode[];
> }
> ```

Current `MAIN` branch
https://github.com/xyflow/xyflow/blob/14c4f6512465425ad3c977cc88b45705631fa7d3/packages/react/src/utils/changes.ts#L191-L193


The only piece of the puzzle I believe is to pass down the generic into the `NodeChange` event and I believe I fixed it in this PR without adding a breaking change
- https://github.com/xyflow/xyflow/pull/3791

**Comment by FelipeEmos** [comment]
I'm pretty sure the way this issue is framed is *outdated* but the problem still exists 🙂

**Comment by moklick** [comment]
Fixed in React Flow 12! If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12
