### ISSUE TITLE
Selection on drag inside a parent node not working

### ISSUE THREAD

**Issue by joaocustodioc** [xyflow/xyflow#3041]
### Describe the Bug

I am using the **selectionOnDrag**, but I have a use case where I have multiple nodes inside a big parent box (that is another node).
That parent node should be **selectable** (not draggable).

When I start a **dragging selection** outside that parent node everything works fine, but if I try to start the selection inside I doesn't work. I think that this is caused by the **selectable** property, because if I set it to false, everything works fine. But in my use case I really need it to be true.

In the image example, if I start the selection outside the "Functional" box, it allows me to drag and select (creating a selection box) but if I start from inside the "Functional" node, I doesn't work. If I set the selectable to false it works. But I need the selectable to have a configuration panel and to resize the box when selected.

### Steps to Reproduce the Bug or Issue

1. Create a big node.
2. Create another node and drag it inside of the one created before.
3. Link the parent node to the big one.
4. Set selectionOnDrag to true.
5. Try to select the smaller node dragging a selection inside the big one.

### Expected behavior

I was expecting that the dragging selection could be created inside parent nodes.

### Screenshots or Videos

![reactflowbugexample](https://user-images.githubusercontent.com/132997675/237054428-2c1c8bea-fe3b-4978-8be5-a851ab17e445.png)

### Platform

- Version: Current one

**Comment by Max-ChenFei** [comment]
Hi @joaocustodioc, I have the same issue,  any update?

**Comment by dm-candeias** [comment]
@moklick Any update on this issue?

**Comment by MatheusRoichman** [comment]
@moklick any updates on it? Not working here too. Already tried to sort the nodes;

**Comment by MatheusRoichman** [comment]
I'm with the same issue. On my case, every node has a parentNode. The default is ROOT_ELEMENT_ID, which is the main container of what the user is building. Here's my sort function:

```ts
const ROOT_ELEMENT_ID = "ROOT_ELEMENT";

export const sortNodes = (a: Node, b: Node): number => {
  if (a.id === ROOT_ELEMENT_ID) {
    return -1;
  }

  if (b.id === ROOT_ELEMENT_ID) {
    return 1;
  }

  if (a.parentNode === ROOT_ELEMENT_ID && b.parentNode === ROOT_ELEMENT_ID) {
    return 0;
  }

  return a.parentNode !== ROOT_ELEMENT_ID && b.parentNode === ROOT_ELEMENT_ID
    ? 1
    : -1;
};
```

I checked the sorted nodes on the console, and the root element is in front of all:
![image](https://github.com/xyflow/xyflow/assets/75812510/a63fa6d6-1a3e-45f0-929a-7a30f7a40f8a)

Obs: I already tried to change the root element node z-index to a higher and a lower z-index than the other node's z-index, and it is not working yet.

@moklick

**Comment by chandreshpatidar** [comment]
@moklick Any updated on the issue? or any workaround to achieve this?

I also need this functionality

**Comment by Jenish-cloudairy** [comment]
@moklick 

Is this bug resolved? I still not able to select child nodes while doing drag in parentNode.

**Comment by moklick** [comment]
You can solve this by setting pointer events "none" for the group nodes and "all" for the drag handles. I updated the codesandbox from @Max-ChenFei to show how to achieve it https://codesandbox.io/p/sandbox/modest-sara-3gtylz?file=/styles.css

**Comment by vupt-2418** [comment]
@moklick If you fix it by adjusting the CSS as mentioned above, you won't be able to click to select the current group anymore.

**Comment by anshikashukla-723** [comment]
> [@moklick](https://github.com/moklick) If you fix it by adjusting the CSS as mentioned above, you won't be able to click to select the current group anymore.

@ghost did you find any solution?
