### ISSUE TITLE
Add new Handle property for choosing attachment side

### ISSUE THREAD

**Issue by semenilchuk** [xyflow/xyflow#3047]
### New handle property, for example, "attachmentPosition"

First of all, amazing library, thanks for your work.
I have proposal to add new property for Handle element, which can specify the attachment side for handle.
Now, connection line connects to side, which is specified by `position` Handle property.
I think sometimes it is useful to have attachment side different from default.

For example, if I create `<Handle position={Position.Left}>`, the connection line can be started only from left side of the handle.
If one needs to implement rotate logic (as in [this example](https://reactflow.dev/docs/examples/nodes/resize-rotate/)), and node has multiple handles, after rotation their connection lines may intersect, and it is not obvious to which handle connection belongs to. Image below:
![Screenshot from 2023-05-11 17-27-26](https://github.com/wbkd/react-flow/assets/89793593/785066fd-7cd5-4b6f-96d4-fc6675a9031a)
Here handle4 is connected to Node1, handle2 to Node2. (on screenshot, it is not obvious). Here screenshot before rotation:
![Screenshot from 2023-05-11 17-28-06](https://github.com/wbkd/react-flow/assets/89793593/541f03ec-0c5e-44b4-afea-e128566d023a)
If such new property was in reactflow Handle, I could change this property dynamically and avoid this problem.
P.S. I can't change `position` property dynamically, because it also changes handle position relative to the node, it is not correct in this situation.

**Comment by moklick** [comment]
couldn't you overwrite all default handle styles and then work with inline styles for your handles to solve this?

**Comment by moklick** [comment]
please re-open if the issue persists.
