### ISSUE TITLE
Movement with Controls does not trigger onMoveEnd or onMoveStart

### ISSUE THREAD

**Issue by backlands** [xyflow/xyflow#3062]
### Describe the Bug

Based on reviewing the documentation and past issues in this tracker (#696, #674) it appears that it is expected for the interactions with the buttons that change the viewport in the `<Controls />` panel to trigger `onMove`, `onMoveEnd`, and `onMoveStart` however only `onMove` is currently triggered.

### Your Example Website or App

https://codesandbox.io/s/jolly-dirac-6k9xxh

### Steps to Reproduce the Bug or Issue

1. Navigate to provided sandbox.
2. Scroll zoom - you will see console messages for onMoveStart, onMove, and onMoveEnd
3. Click zoom control button - you will only see console message for onMove
4. Pan in the viewport - you will see console messages for onMoveStart, onMove, and onMoveEnd
5. Click the "fit" control button - you will only see console message for onMove

### Expected behavior

Zooming or moving by any means should trigger all move events in sequence (onMoveStart, onMove, and onMoveEnd).

### Screenshots or Videos

![image](https://github.com/wbkd/react-flow/assets/12586299/bbe00f13-80fc-4bed-a482-d8824444adfe)

### Platform

- OS: Windows
- Browser: Firefox
- Version: 113.0.1

### Additional context

If this is the expected behaviour the documentation should be updated to reflect that only the `onMove` event is triggered when movement occurs from interaction with the `<Controls />` elements.

**Comment by moklick** [comment]
Thanks for the report. That's a good catch. Lot's of people are using `fitView` and this would mean that `onMoveStart` and `onMoveEnd` would be triggered on every initial render. Maybe we can change it with the next minor, but definitely with the next major release.

**Comment by backlands** [comment]
Great, thank you for the response @moklick, we will look forward to the next release for this change as it will help us improve the logic around keeping and clearing some timeouts we have around zooming that we only want firing on start/end.

Love the library and how extensible it is, keep up the great work!

**Comment by backlands** [comment]
> Thanks for the report. That's a good catch. Lot's of people are using `fitView` and this would mean that `onMoveStart` and `onMoveEnd` would be triggered on every initial render. Maybe we can change it with the next minor, but definitely with the next major release.

@moklick with v11 being closed out for finalization of v12 I was wondering if this adjustment is still planned for the v12 release?

**Comment by moklick** [comment]
It's planned for the v12 release!
