### ISSUE TITLE
[onNodesChange] select: false event is not sent when dragging

### ISSUE THREAD

**Issue by bodinsamuel** [xyflow/xyflow#3187]
### Describe the Bug

When using onNodesChange you receive an event when clicking on a node:
`{ id, select: true}`

When clicking elsewhere you receive an event:
`{ id, select: false}`

However when you drag nodes, it show them as unselected but it won't send the `{ select: false }` to `onNodesChange` while the Nodes themselves are correctly updated. 
Incidentally when you start dragging directly (not clicking first the node) it shortly set the node to selected but no event `{ select: true }` is sent.

### Steps to Reproduce the Bug or Issue

1. Click a node
2. Receive an event `{ select: true }` 
3. Start dragging 
4. Do not receive an `{ select: false }`

### Expected behavior

Events should reflect what is displayed and computed internally.

- Receive an event `{ select: true }` when click/dragging directly
- Receive an event `{ select: false }` when dragging start (or end)

OR

Dragging should not unselect

### Platform

- OS:macOs
- Browser: Chrome 
- Version: 11.7.4

### Temporary solution

`useOnSelectionChange` does not suffer the same issue but it triggers very often (~on hover too which I don't get~ nvm it was my setup)

**Comment by moklick** [comment]
When you drag a node it should not get de-selected. Where did you see this?

**Comment by moklick** [comment]
Please re-open if it's still an issue.
