### ISSUE TITLE
Exporting more functions from react-flow/packages/core/src/utils/graph.ts

### ISSUE THREAD

**Issue by rzvxa** [xyflow/xyflow#3193]
### Please describe the feature that you want to propose

Hello,

I'm using react-flow for creating a moderately complex project. For my use cases I need to translate points to renderer point and vice versa(for adding nodes and context menu positioning for example), Fortunately we already have the very needed utilities in the library in the form of 2 functions called `pointToRendererPoint` and `rendererPointToPoint` located at `react-flow/packages/core/src/utils/graph.ts` but they are not exported in the `packages/core/src/index.ts` file.
May I ask if there is a reason for this decision? If not, Could I export the functions mentioned above in the form of a PR? Or if you are not accepting PRs currently, Maybe one of maintainers can export them in the next release.
Right now I'm copying these methods in my own project as utils but it can be much cleaner if i could use internal helper methods for keeping some consistency across versions.

Thanks for reading this!

**Comment by moklick** [comment]
Good point! We are currently working on the next major release and we are only doing path releases for v11. I will put this on the list for v12.

**Comment by rzvxa** [comment]
@moklick Thanks!

**Comment by JoeHart** [comment]
Just commenting here to also plus one this feature. Being able to essentially have an opposite of the `project` method that converts from client window space to react-flow space would be :chefs_kiss:

Also love the project, thanks for all your hard work maintaining the project! ✨

**Comment by moklick** [comment]
We already worked on this and you can now use `flowToScreenPosition` and `screenToFlowPosition` from `useReactFlow` to translate coordinates from screen to flow and vice versa: https://reactflow.dev/api-reference/types/react-flow-instance#screen-to-flow-position .
