### ISSUE TITLE
data-id can conflict in case of nested flows

### ISSUE THREAD

**Issue by strblr** [xyflow/xyflow#3196]
### Describe the Bug

Information of the node ids is stored directly on the dom nodes (`data-id`, `data-testid`, `data-nodeid`, etc.).
When you have a reactflow nested inside another, which happens to show a subset of the nodes of the parent flow, this creates conflicts and prevents certain events.

For example, I have the following scenario:

A control button on the main graph opens a modal with a secondary graph. This modal is used to manipulate data before importing it into the main graph. But it is possible in my app that they share nodes with the same id. When the modal is open, two flows are in the DOM, with potentially nodes of the same id.

In this exact scenario, the magnetic connect effect on nodes when drawing edges doesn't work on the "duplicate" nodes.

In the following screenshot, the blue node is a conflicting id with a node from the main graph:

![CPT2307031646-589x279](https://github.com/wbkd/react-flow/assets/30187797/37f0f957-1216-49cc-a8c6-f9ed9f878057)

I suggest the following:

That each flow instance has its own id and appends it to every `data-id`, `data-nodeid`, etc.

### Steps to Reproduce the Bug or Issue

1. Create a nested reactflow
2. Render nodes with same id in both
3. Magnetic connect doesn't work

### Expected behavior

That dom nodes are identified uniquely not only by node id but also by graph id.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
This is an interesting bug. Can you work around this by by prefixing your ids of the preview nodes? I will check if we can fix this somehow on our end.

**Comment by strblr** [comment]
Yes I could prefix it but it would end up quite messy. In my opinion it would make more sense that react-flow takes care of isolation on a per-context basis.

This bug can happen no matter the relationship of the two flows in the React tree, as long as they're both in the dom and share at least one node id. I can imagine other scenarios where this can be the case and where it would not be reasonable to just count on prefixing the ids manually. 

What about generating an id for the main div internally and then just changing your querying of dom nodes as "graph-id node-id" instead of just "graph-id"?

**Comment by moklick** [comment]
We won't prefix the `data-nodeid` attributes but the ones from the handles. This makes it possible to connect nodes within nested flows. This change will be part of v12.

**Comment by moklick** [comment]
This is supported since React Flow 12!

If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12
