### ISSUE TITLE
Multiselect in mobile

### ISSUE THREAD

**Issue by leolorenzoluis** [xyflow/xyflow#3207]
### Please describe the feature that you want to propose

Hello, I know multiselect is supported in desktop. Ideally it’s better if we support multi select in phones by holding a node then select multiple nodes by tapping.

**Comment by moklick** [comment]
Interesting idea, thanks! I will discuss this feature with the team.

**Comment by moklick** [comment]
It's a good idea but we will not implement it as a built-in feature.
