### ISSUE TITLE
Handle onDisconnect & onConnect trigger for target handle

### ISSUE THREAD

**Issue by lancemao** [xyflow/xyflow#3277]
### Please describe the feature that you want to propose

according to the doc
https://reactflow.dev/docs/api/nodes/handle/

`Gets triggered on connect. This callback only gets executed on source handles.`

Handle's onConnect is only triggered for source handle. I'm wondering why we made such decision? Maybe some scenarioes beyond my reach. In my case, However, I really want to get notified for the **target** handle as well since I need to update UI for the target node

I also would like to have onDisconnect event for both source & target handle whenever edge has been updated

Thansk in advance

**Comment by moklick** [comment]
Hey, what exactly are you looking for? You can check if a handle is connected inside a custom node https://codesandbox.io/s/check-handle-connected-zcibuo?file=/src/CustomNode.tsx:238-418

**Comment by lancemao** [comment]
Hi thanks for quick reply. This works fine. Some questions:
1. s.edges.find will iterate all edges, performance ok?
2. according to doc [useStore ](https://reactflow.dev/docs/api/hooks/use-store/) should be avoided
3. still wondering why not simply add onConnection callback for target handle, isn't it much simpler and much more straight forward?

**Comment by CubicDog** [comment]
I totallly agree with the request. The API for the handle just feels incomplete without events disconnect and the target handle.

**Comment by moklick** [comment]
We added a new `useHandleConnections` hook for v12. You can use it to receive the connections of a handle and to get notified on connect or on disconnect:

```js
const onConnect = useCallback(
  (connections: Connection[]) => console.log('onConnect handler, node id:', nodeId, connections),
  [nodeId]
);

const onDisconnect = useCallback(
  (connections: Connection[]) => console.log('onDisconnect handler, node id:', nodeId, connections),
  [nodeId]
);

const connections = useHandleConnections({
  type: 'target',
  onConnect,
  onDisconnect
});
``` 

It's still beta, but you can already check it: https://github.com/xyflow/xyflow/discussions/3764

**Comment by rhathas** [comment]
Is there a way to use it onConnectEnd or onConnectStart? The use case is when i create a new node by dragging the edge from the handle and dropping it into an empty space, i want to check if there is any other connection from that handle before creating that new node.
