### ISSUE TITLE
Add `selectable` attribute to edges

### ISSUE THREAD

**Issue by psychedelicious** [xyflow/xyflow#3298]
### Please describe the feature that you want to propose

I'd like to be have access to a `selectable` attribute on individual edges.

My use case is related to collapsible nodes, in which I'd like to "freeze" all edges between two nodes when both nodes are collapsed.

https://github.com/wbkd/react-flow/assets/4822129/3eb26baa-df02-4854-9978-a68abe54b985

The closest I can get is to set `edge.deletable = true` for each edge. Maybe I could set `pointerEvents = 'none'` on those specific edges, but it would be nice if the library could handle this.

(My workaround plan is to hide those edges and render a dummy edge between the collapsed nodes. This will provide a better user experience anyways, but I still think this would be a nice improvement to the library.)

**Comment by moklick** [comment]
This will be possible in v12.

**Comment by psychedelicious** [comment]
Thanks @moklick !

**Comment by nalvarezdiaz** [comment]
I'm currently using `selectable` inside edges and it is still possible to select them. 

`reactflow`: 11.10.3

The following code is enough to reproduce it (https://codesandbox.io/p/sandbox/withered-bush-8kgf2v?file=%2FApp.js)

```jsx
import React from "react";
import ReactFlow, { useNodesState, useEdgesState } from "reactflow";

import "reactflow/dist/style.css";

const INITIAL_NODES = [
  {
    id: "1",
    data: {
      label: "Default Node",
    },
    position: { x: 100, y: 100 },
  },
  {
    id: "2",
    data: {
      label: "Default Node",
    },
    position: { x: 100, y: 500 },
  },
];

const INITIAL_EDGES = [
  {
    id: "e1-2",
    source: "1",
    target: "2",
    selectable: false,
    label: "selectable: false",
  },
];

const Flow = () => {
  const [nodes, setNodes, onNodesChange] = useNodesState(INITIAL_NODES);
  const [edges, setEdges, onEdgesChange] = useEdgesState(INITIAL_EDGES);

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
    />
  );
};

export default Flow;
```

**Comment by moklick** [comment]
This is supported since React Flow 12!

If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12
