### ISSUE TITLE
Allow styling of background with tailwind

### ISSUE THREAD

**Issue by RichSchulz** [xyflow/xyflow#3325]
### Please describe the feature that you want to propose

It would be great to have a better/more thorough support of tailwind for styling. The Background for example is not possible to be styled entirely with tailwind. As the `color`, `gap` and `size` of the pattern needs to be passed in as css classes. It would be great to also expose something like a pattern classname, so that the pattern can be styled via tailwind

**Comment by moklick** [comment]
Thanks @RichSchulz :) This will be part of the v12 release.

**Comment by Lokolin** [comment]
@moklick, hi. So, until you release version 12, how can I style a custom node using tailwind? 
In examples I saw that it works https://reactflow.dev/docs/examples/styling/tailwind/ (even can't see codesandbox) , but does not work in a real project. 
Tried to add `important: true` to  _tailwind.config.ts_ but it did not help, сolor styles are not applied. 
Maybe there is temporary hack or solution for this issue?

**Comment by moklick** [comment]
Hey @Lokolin 

1. codesandbox: we can't forward `externalRessources` to codesandbox. That's why we are hiding the button for that example. I already opened an issue for that: https://github.com/codesandbox/sandpack/issues/624 
2. tailwind: what is not working for you? There are some things like the background pattern that you can't style with tailwind, but for a custom node, it should work.

**Comment by rreeves8** [comment]
Same issue here, tailwind + daisyui modify some react flow styles, they have a fix [here](https://tailwindcss.com/docs/preflight#border-styles-are-reset-globally) for google maps but I don't think it works for here.

**Comment by moklick** [comment]
Since React Flow 12 you can use `patternClassName` for this.

If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12
