### ISSUE TITLE
Dynamic node height with dynamic contents causes unpredictable behaviour

### ISSUE THREAD

**Issue by fpendovski** [xyflow/xyflow#3354]
### Describe the Bug

Having nodes with dynamic height and dynamic content within them in ocassions when the content reaches off-screen, causes react flow's internal elements, to be more precise the renderer, to not be full-height any longer.

### Your Example Website or App

https://codesandbox.io/s/determined-http-z2x6wq?file=/src/Flow.js

### Steps to Reproduce the Bug or Issue

Create a CustomNode that doesn't have fixed height, insert a contenteditable div within that node, paste in a larger amount of text, so that a portion of it goes off-screen, the `react-flow__renderer` and `react-flow__pane` elements both lose their positioning and aren't on screen any longer, which results in the controls (drag-to-pan/zoom) not functioning.

As a possible workaround, setting the `react-flow__renderer`'s position to `fixed` solves the issue.

### Expected behavior

The elements should not have lost their positioning.

### Screenshots or Videos

https://github.com/wbkd/react-flow/assets/33331199/2c7b3c83-8a7d-4b69-a1db-7f8541c6c25d

### Platform

- OS: both macOS and Windows
- Browser: Chrome
- Version: 116.0.5845.96 (Official Build) (arm64)

**Comment by fpendovski** [comment]
Anyone else with this issue, any insight on this?

**Comment by moklick** [comment]
The reason for this is the native browser behaviour that wants to scroll to the input element (the text area in this case) when it's off screen. I don't think that we can solve this within React Flow.

**Comment by fpendovski** [comment]
@moklick Thanks for answering this, are there any suggestions or ideas that you might have on "bypassing" this issue other than setting the position to fixed?

**Comment by moklick** [comment]
you could try to prevent the default behaviour and call `focus` by yourself using the `preventScroll` option https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#parameters (I don't know if this works)

**Comment by pluveto** [comment]
I'm having the same issue

**Comment by moklick** [comment]
maybe related #3483

**Comment by moklick** [comment]
We will continue the discussion in #3483
