### ISSUE TITLE
Set `ConnectionLineComponentProps.toPosition` to target handle within `connectionRadius`

### ISSUE THREAD

**Issue by gulsharan** [xyflow/xyflow#3359]
### Please describe the feature that you want to propose

`ConnectionLineComponentProps.toPosition` is always set to the opposite of source position, e.g. `left` is source position is `right`, `bottom` if source position is `top`.

Is it possible to fix it such that it shows the position of the target handle within the `connectionRadius`?

**Comment by peterkogo** [comment]
@gulsharan This is fixed in the newest update of React Flow 12  🎉
