### ISSUE TITLE
Scroll/navigate through flow with two finger on touch-pad

### ISSUE THREAD

**Issue by SmackdabDevOps** [xyflow/xyflow#3408]
### Please describe the feature that you want to propose

I want to be navigated through the chart area with using two finger on touch pad like Figma or google map does. I are not being able to do this in the current implementation. Please provide the solution regarding this, if this can be possible by modifying anything. Thank you!

**Comment by juspky** [comment]
The panOnScroll prop in the <ReactFlow> component does exactly this for me.

**Comment by SmackdabDevOps** [comment]
@juspky Thanks for the solution, it did worked! I have one issue that is with the zooming, when I click on ctrl and zoom with the touch-pad, it zooms quite slow. Do you have any solutions in regards to that? Thanks!

**Comment by moklick** [comment]
@SmackdabDevOps which OS are you using? You can also try to increase `panOnScrollSpeed` (default 0.5)

**Comment by SmackdabDevOps** [comment]
Okay, we were mentioning the zoom in and out speed.

**Comment by moklick** [comment]
`panOnScrollSpeed` is a prop that you can set. You could also change its value only if ctrl is pressed.

**Comment by SmackdabDevOps** [comment]
> `panOnScrollSpeed` is a prop that you can set. You could also change its value only if ctrl is pressed.

https://www.loom.com/share/b7352b3bcd494defb563daa2ac03adee 

this is where we are trying to implement the zoom in out speed

**Comment by moklick** [comment]
got it. Are you using macOS?

**Comment by SmackdabDevOps** [comment]
> got it. Are you using macOS?

windows

**Comment by moklick** [comment]
please follow this issue to track the progress on this: #3481
