### ISSUE TITLE
Edges with source or targetHandle behave inconsistent if handle is missing

### ISSUE THREAD

**Issue by juspky** [xyflow/xyflow#3409]
### Describe the Bug

If I have a custom node with 2 handles using IDs and remove one of the handles. Edges belonging to one handle go into the other handle without having the proper handle ID.

### Your Example Website or App

https://reactflow.dev/docs/guides/custom-nodes/#using-multiple-handles

### Steps to Reproduce the Bug or Issue

You can reproducte the bug on https://reactflow.dev/docs/guides/custom-nodes/#using-multiple-handles by changing the code and reloading.

<img width="962" alt="Screenshot 2023-09-19 at 10 42 48" src="https://github.com/wbkd/react-flow/assets/11074890/a475d165-9b2a-4fe1-86e9-630f38a22d3a">

This is the example code.

If we change the handle ID to "c" the edge with "b" as target does not render as I would expect
<img width="962" alt="Screenshot 2023-09-19 at 10 43 18" src="https://github.com/wbkd/react-flow/assets/11074890/35111ec3-019c-497c-9db9-4bb79aec302d">

If we remove then handle completely the Edge targeting "b" does render but also goes into handle "a"
<img width="962" alt="Screenshot 2023-09-19 at 10 43 36" src="https://github.com/wbkd/react-flow/assets/11074890/05b19a02-ea5a-4dbd-a732-dbcd6326f423">

### Expected behavior

I would expect the edge targeting "b" to never go into a "a" handle. And simply not appear.
Like in the example where I set the 2nd handles ID to "c"

### Platform

- OS: macOS
- Browser: Firefox

**Comment by moklick** [comment]
This is supposed to be a feature 😅 When there is only one source or target handle we just use it. The handle ids are only necessary when you are working with multiple handles but I understand that this behaviour is a bit weird when you specify sourceHandle/targetHandle ids. I will discuss it with the team.

**Comment by juspky** [comment]
This feature is actually an issue in a app I'm making. Since nodes can switch from having multiple ID handles back to one.

Personally I would be happy if I could toggle this behavior off or if you changed it to only happen when the "fallback" handle has no id set.

**Comment by moklick** [comment]
Good idea! How could we name this? "useDefaultHandle={true/false}", "strictHandleMode={true/false}" ?

**Comment by bcakmakoglu** [comment]
Wouldn't it be possible to use a fallback handle id if none is passed to the Handle component (which would be assuming that there is only *one* handle of each type, otherwise an id has to be provided anyway) and use that for the handle bounds lookup?

**Comment by moklick** [comment]
I checked this issue again and I think the better default for v12 not to choose the first handle if a handle id is passed but look for that specific handle. We will change this behaviour and add a note to the migration guide.

**Comment by moklick** [comment]
This is the new behaviour in v12.
