### ISSUE TITLE
Movement with Minimap does not trigger onMoveEnd or onMoveStart

### ISSUE THREAD

**Issue by BigTimeJason** [xyflow/xyflow#3441]
### Describe the Bug

When using the panning using mimimap component, onMoveEnd and onMoveStart are not called

### Your Example Website or App

https://codesandbox.io/s/reactflow-11-7-0-onmove-bugs-mlk28c?file=/src/Flow.tsx

### Steps to Reproduce the Bug or Issue

1. Go to the sandbox above
2. Pan the graph normally (drag via anywhere on the page)
3. Notice that onMoveStart, onMove, and onMoveEnd are called
4. Pan the graph using the minimap
3. Notice that onMoveStart and onMoveEnd are not called, but onMove is

### Expected behavior

I expect that onMoveStart, onMove, and onMoveEnd are called when panning via the minimap component.

### Screenshots or Videos

![image](https://github.com/wbkd/react-flow/assets/49235257/9516631b-fd45-4b5a-99c1-99d5d7f23116)

The first 3 logs are panning via the graph
The final log is panning via the minmap

### Platform

- OS: Windows
- Browser: Chrome
- Version: 117.0

### Additional context

Similar to #3062 - I would expect the same behaviour from the minimap component for those events. I'm unsure if it's fixed in the v12 release as well 🙏.

**Comment by moklick** [comment]
Hey, this will be fixed in v12, too!

**Comment by BigTimeJason** [comment]
That's awesome, I wasn't sure if I needed to make a new issue for it because of the other similar post, but I did anyway to be safe. Thanks!

**Comment by moklick** [comment]
that's fine, thanks for the reminder to check that case too :)

**Comment by moklick** [comment]
This works in React Flow 12 - If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12
