### ISSUE TITLE
useReactFlow's setNodes's behavior not same as normal hooks

### ISSUE THREAD

**Issue by kainstar** [xyflow/xyflow#3458]
### Describe the Bug

When I call twice `useReactFlow`'s `setNodes` with a callback argument in one click callback, only the second `setNodes`'s return result make effect, the first `setNodes`'s return result is ignored.

### Your Example Website or App

https://codesandbox.io/s/immutable-http-xgmzzr?file=/src/BugPanel.tsx

### Steps to Reproduce the Bug or Issue

1. click "Trigger Bug" button

### Expected behavior

Expected: "Node 1" and "Node 2"'s label both changed
Actual: Only "Node 2" changed

### Platform

System:
  OS: macOS 12.5
  CPU: (8) arm64 Apple M2
  Memory: 110.80 MB / 24.00 GB
  Shell: 5.8.1 - /bin/zsh
Browsers:
  Chrome: 117.0.5938.92
  Safari: 15.6
Version: 11.9.2

**Comment by eamador** [comment]
Hey @kainstar, as workaround you can wrap the second `updateNodeData` within a `setTimeout`

```ts
const onClick = useCallback(() => {
    updateNodeData("1", {
      label: "Node 1-1"
    });
    setTimeout(() => {
      updateNodeData("2", {
        label: "Node 2-1"
      });
    });
  }, [updateNodeData]);
  ```
  
  https://codesandbox.io/s/exciting-mopsa-28n8xz?file=/src/BugPanel.tsx

**Comment by kainstar** [comment]
It works but the `setTimeout` is confusing and will cause unnecessary re-render, in [React's `useState`'s setState parameter](https://react.dev/reference/react/useState#setstate-parameters), if we pass a function as nextState, it will be treated as an updater function and run it in a queue, that means the second updater function will receive first function's update result as arguement and only once render at last.
Is there has any better way to implement my wish?

**Comment by moklick** [comment]
Please follow this issue for the progress about the exported `setNodes` and `setEdges` handlers https://github.com/orgs/xyflow/projects/2/views/1?sliceBy%5Bvalue%5D=xyflow/xyflow&pane=issue&itemId=49807546
