### ISSUE TITLE
Get an error when I try to "undo" copied-pasted node.

### ISSUE THREAD

**Issue by Kost927** [xyflow/xyflow#3462]
### Describe the Bug

I use Collaborative, undo-redo, and copy-paste functionality, so I had to modify a bit of code which is in the examples. There is an error from some files under the hood of the library. So If I add a new node and press the "undo" button all works excellent. But If I copy and paste a new node, and after trying to "undo" the pasted node I get an error. I Will share the video with the problem, but I do not know if can I share the code, coz this is a paid functionality.

### Steps to Reproduce the Bug or Issue

1. add node
2. copy node
3. paste node
4. press the "undo" button
5. get error 

### Expected behavior

remove a pasted node from the chart.

### Screenshots or Videos

https://github.com/wbkd/react-flow/assets/64188262/cc834de0-5ca6-4175-8c15-8d1737ba2379

### Platform

- OS: [e.g. macOS]
- Browser: [e.g. Chrome, Safari]

**Comment by Kost927** [comment]
<img width="473" alt="Screenshot 2023-09-28 at 17 16 10" src="https://github.com/wbkd/react-flow/assets/64188262/9f2ae778-7933-430b-bbe5-0d919da9deb5">
If this can help, I take the previous past state where I have only one node and update the current nodes. nodes are updated as we can see there were 2 nodes before and only one left. But I can't get where this error comes from

**Comment by Kost927** [comment]
after some debugging, I saw that the node was removed from the layout, and "nextNodeInternals" became undefined, and the error came only after that.
<img width="1728" alt="Screenshot 2023-09-28 at 17 46 23" src="https://github.com/wbkd/react-flow/assets/64188262/6d7ee83b-592d-4a46-8c37-2f699e517888">

**Comment by moklick** [comment]
We revised the pro examples. Could you check if the issue persists? There was an issue with the copy/paste example because we didn't reset the node when it got pasted. You need to set dragging: false / selected: false as seen in the current example. Does this help?

**Comment by Kost927** [comment]
Hi, Apologies for missing your message earlier. I'll review it shortly and get back to you as soon as possible. Thank you.

**Comment by Kost927** [comment]
Sorry, I think we can close this issue, you are right. I reset the selected state to false after pasting and do the same, before pressing the back button. Coz if you select the pasted node manually and press back, you will see the same issue.
