### ISSUE TITLE
Background and panel positions are not updated when tabbing to off-screen node

### ISSUE THREAD

**Issue by ahmacleod** [xyflow/xyflow#3483]
### Describe the Bug

Hi all, big fan of ReactFlow here. I noticed this bug this morning when working on some accessibility features and thought I should flag:

When navigating the graph with the tab button, if the focus shifts to a node that is off screen, the background and panels are not re-rendered in the correct new position. This can be seen on the website examples.

Thank you!

### Steps to Reproduce the Bug or Issue

1. Open https://reactflow.dev/docs/examples/overview/
2. Zoom in enough for some nodes to be off-screen
3. Click a node to provide focus
4. Tab until a node that is off-screen becomes focused
5. The background and panels will be in the wrong position

### Expected behavior

Background and panels should remain stationary throughout.

### Screenshots or Videos

https://github.com/wbkd/react-flow/assets/2594635/3535ae30-2943-43b9-971c-d4ee1a1c71cc

### Platform

- OS: macOS
- Browser: Chrome
- Version: 117.0.5938.92
- `reactflow`: 11.9.2

**Comment by moklick** [comment]
It's not easy to fix, because it's a native browser behaviour but we will have a look for v12.

**Comment by moklick** [comment]
A solution could be to set `.react-flow__pane` to `position: fixed`. We will investigate.

**Comment by peterkogo** [comment]
Also happens when input fields extend off-screen #3598 #3354
