### ISSUE TITLE
Center node position is not correct with Custom Node

### ISSUE THREAD

**Issue by gtanchak** [xyflow/xyflow#3503]
### Describe the Bug

While using custom node with custom styling the center node position is not at correct place. It is little bit different then normal node position.

### Steps to Reproduce the Bug or Issue

1. Create Custom Node
2. Add Custom Styling for Parent Node and different styling for all the children node
3. Add One Parent and add their three children
4. Center one position is little bit slide to left side it is not in exact centre. 

### Expected behavior

Expected behaviour should be centre node position needs to be in exact center.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 11.9.3]

**Comment by bcakmakoglu** [comment]
A sandbox demonstrating the issue would be helpful, as I for one can't really tell what the problem is supposed to be just from this description.

A sandbox template can be found here: https://new.reactflow.dev/react-ts

**Comment by gtanchak** [comment]
> A sandbox demonstrating the issue would be helpful, as I for one can't really tell what the problem is supposed to be just from this description.
> 
> A sandbox template can be found here: https://new.reactflow.dev/react-ts

Okay @bcakmakoglu I will add one example

**Comment by moklick** [comment]
Please re-open with a codesandbox.

**Comment by ZaneH** [comment]
Excuse me for digging this up, I thought I ran into this issue as well. Turns out I just needed to make use of `origin` in Svelte or `nodeOrigin` in React. Here's a sandbox showing centered nodes with custom nodes: https://codesandbox.io/p/sandbox/great-voice-v74nmh
