### ISSUE TITLE
Node extent property doesn't update while dragging node

### ISSUE THREAD

**Issue by dsoklic** [xyflow/xyflow#3519]
### Describe the Bug

I'm trying to create an application where the child node can't exit the parent node, except when the Ctrl key is being pressed.

It seems to me that the `extent` property is only updated after the drag stops, but not during the drag.

### Your Example Website or App

https://codesandbox.io/s/changing-extent-drag-n8y5x6

### Steps to Reproduce the Bug or Issue

1. Try to drag 'Node 2' out of its parent.
2. Now hold down the Ctrl key and try to drag the node out of the parent.
3. First drop the node and after that release the Ctrl key.
4. Drag the node again without pressing any keys and try to drag it out of the parent.

### Expected behavior

When you first try to drag the node out of the parent without pressing down Ctrl, it can't exit the parent. This is as expected.
But when you hold down Ctrl, the node still can't exit the parent.
After releasing the node, releasing Ctrl and trying to drag it out again, the node can exit the parent even though the Ctrl key isn't pressed.

### Platform

- OS: Windows
- Browser: Brave and Electron
- Version: Brave is 1.59.117

**Comment by moklick** [comment]
thanks, we will check it.

**Comment by moklick** [comment]
This will be fixed in v12 🚀

**Comment by moklick** [comment]
This is fixed in v12
