### ISSUE TITLE
Position of node and edges are not rendering correctly 

### ISSUE THREAD

**Issue by ankit90202** [xyflow/xyflow#3523]
### Describe the Bug

React is rendering it correctly for the first time but edges are distorted and nodes placement are not correct

Current functionality is we are rending the parent 3 child at first render. Then user can click on any of the nodes to push it's child nodes. If it's an folder then it's expandable else it's can be expanded

First Render
![image](https://github.com/wbkd/react-flow/assets/23663644/5ad162c2-18fb-4d7c-a1b5-030408654e85)

When I navigate back from other route to this flow route
![image](https://github.com/wbkd/react-flow/assets/23663644/4473c1b9-da50-4047-a9c0-04d09b9f6686)

Nodes Array
https://justpaste.it/btubk

Edges Array
https://justpaste.it/alwha

### Steps to Reproduce the Bug or Issue

1. Create two different routes suppose home and flow
2. Navigate to flow and it will render parent and it's all children
3. Click on children if they are of type folder to further expand
4. Now navigate to home after expanding 2-3 levels
5. Come back to flow route

### Expected behavior

As a user i expect it to render as it rendered first time

### Platform

Windows
Chrome
Version 118.0.5993.71 (Official Build) (64-bit)

**Comment by moklick** [comment]
could you try to wrap each flow with a `<ReactFlowProvider>` component?

**Comment by StellarLogic** [comment]
@moklick , it is already wrapped inside a ReactFlowProvider

The scenario is as follows.

The parent node "Sample Test Plan" has three children.

Clicking on a child will call an API that will return a list of the child's. The response can either be a folder or a file.

After adding certain connection values, we push those children into the node state and the edge state.

When we expand it to a certain level, we navigate to another screen and then we return to the original current screen we get parent with three children with distorted connections

**Comment by moklick** [comment]
If this is still an issue, please re-open with a codesandbox or repository.
