### ISSUE TITLE
zIndex causes incorrect node dragging behavior

### ISSUE THREAD

**Issue by lancemao** [xyflow/xyflow#3539]
### Describe the Bug

Suppose I have two nodes as follow:

![Screenshot 2023-10-25 170223](https://github.com/wbkd/react-flow/assets/5020396/ba06c77f-bf70-4703-a7e1-5728f4c16ff3)

the bigger one node has smaller zIndex, say -100, it acts like a parent (or group in ReactFlow context), and is currently selected. Now if I drag the smaller one (no zIndex set) inside, the smaller one won't be selected and won't be dragged. It is still the parent node that is moving. I have to click anywhere outside the parent node to diselect it, only then I can drag the smaller one

### Steps to Reproduce the Bug or Issue

as described above

### Expected behavior

smaller node should be selected and dragged if it has bigger zIndex

### Platform

- OS:Windows
- Browser: Chrome
- Version: 11.9.4

**Comment by moklick** [comment]
I can't reproduce this. The parent node needs to be before the child node in the nodes array. If that's the case, the child node should adjust to the parent zIndex as seen here: https://codesandbox.io/p/sandbox/distracted-wilson-8gtdvp

Please re-open if the issue persists.
