### ISSUE TITLE
Testing: e2e with Playwright for React Flow and Svelte Flow

### ISSUE THREAD

**Issue by moklick** [xyflow/xyflow#3540]
## Nodes
  - [x] select
  - [x] mutli select
  - [x] drag
  - [x] delete
  - [x] connect
  - [x] options: draggable, connectable, selectable , deletable, dragHandle, hidden, style, className
 
## Edges
  - [x] select
  - [x] mutli select
  - [x] delete
  - [x] options, defaultEdgeOptions: updatable, interactionWidth, hidden, style, className

## Pane
  - [x] pan and zoom: panOnDrag, panOnScroll, etc 
  - [x] autoPanOnConnect, autoPanOnNodeDrag
  - [ ] panActivationKey, zoomActivationKey
  - [x] minZoom, maxZoom
  - [x] defaultViewport

## Components
  - [ ] Panel
  - [ ] Controls
  - [ ] Background
  - [ ] MiniMap
  - [ ] NodeToolbar (React only)
  - [ ] NodeResizer (React only)

**Comment by peterkogo** [comment]
Edge Props:
deletable, selectable, focusable, updatable, animated, markerStart, markerEnd, zIndex, ariaLabel, hidden

**Comment by peterkogo** [comment]
focusable?

**Comment by peterkogo** [comment]
- [ ] default edge options

**Comment by moklick** [comment]
closed since there are separate issues for component tests
