### ISSUE TITLE
Allow Zoom when panOnScroll and zoomActivationKeyCode is enabled

### ISSUE THREAD

**Issue by aleib** [xyflow/xyflow#3543]
### Describe the Bug

When `panOnScroll=true` zooming does not work on nodes when using the `zoomActivationKeyCode` (e.g. 'Meta').
It works on the canvas fine, just not on nodes.

This is may be due to this line of code not respecting the `zoomActivationKeyCode`? But not sure
https://github.com/wbkd/react-flow/blob/a93c85ed82677b53c76cb774655afb20a475855d/packages/core/src/container/ZoomPane/index.tsx#L348 

### Your Example Website or App

https://codesandbox.io/s/wt2y2z?file=/App.js&utm_medium=sandpack

### Steps to Reproduce the Bug or Issue

1. Go to this [codesandbox example](https://codesandbox.io/s/wt2y2z?file=/App.js&utm_medium=sandpack)
(This is just the [Figma example from the docs site](https://reactflow.dev/docs/guides/panning-and-zooming/#figma-like-viewport-controls))
2. Hold 'Meta' to zoom while the cursor is over a node

### Expected behavior

Zooming is allowed on nodes while `zoomActivationKeyCode` is active

### Platform

- OS: macOS
- Browser: Chrome
- Version: 11.9.4

### Additional context

It seems like the functionality changed recently in the last few updates.

**Comment by moklick** [comment]
Thanks for the report. I will check it!

**Comment by KortesmakiAB** [comment]
+1 ☝️ 

fwiw, I'm seeing `control + scroll` will zoom as expected for both the canvas and nodes (on a Mac with `panOnScroll={true}`)

**Comment by rsdouglas** [comment]
+1 We have users logging issues on our product as a result of this 😬

**Comment by moklick** [comment]
Fixed in 11.10.1
