### ISSUE TITLE
Add ability to keep edge snapped to a handle when cursor is on top of the handle

### ISSUE THREAD

**Issue by cescoferraro-savant** [xyflow/xyflow#3552]
### Please describe the feature that you want to propose

First off, thanks you guys! We love using reactflow as Savant Labs.
But we need a way to force the edges to snap to a handle even when the cursor is on top of the handle.
My product team really wants the edge to always snap & keep it snapped to the handle.
Current behavior is proven problematic for our users as they expect to edge to keep snapped as the hover the curser over the Handle component. This issue was originally a question on Discord and @moklick instructed me to open this issue/feature-request

<img width="1389" alt="Screenshot 2023-10-27 at 13 57 09" src="https://github.com/wbkd/react-flow/assets/132388093/f1ced00e-6f20-40c4-87d5-f2522e4f2808">

**Comment by moklick** [comment]
This is fixed in 11.10.1 ✌️
