### ISSUE TITLE
React Beautiful DnD problem with component position

### ISSUE THREAD

**Issue by tonvital** [xyflow/xyflow#3553]
### Describe the Bug

Hey guys!

I'm using React Beautiful DnD to try to make a list component with the drag and drop event inside the react flow node.
https://github.com/atlassian/react-beautiful-dnd

However, when I start dragging the component's translate points to:

'transform: translate(0px, 0px)'

And the component goes to a position much lower than it should.

### Steps to Reproduce the Bug or Issue

Install the React Beautiful DnD 
Create a node with Droppable and Draggable elements
Start draggin any item 

### Expected behavior

Can anyone help me make the component follow the exact mouse position?

### Screenshots or Videos

![image](https://github.com/wbkd/react-flow/assets/50684920/3c242b53-2cea-41b9-bc0a-ec3bf3b24021)

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [91.1]

**Comment by moklick** [comment]
Hey! How is this related to react flow? Can you give us a bit more context?

**Comment by tonvital** [comment]
I just want to make a drag and drop system inside a react flow node. However, every "transform: translate()" I use teleports the node component very far from the parent node.

**Comment by moklick** [comment]
can you create a simplified codesandbox for this example?

https://new.reactflow.dev/react-ts

**Comment by moklick** [comment]
Please re-open with a codesandbox.
