### ISSUE TITLE
Custom Edge position incorrect (xyflow/svelte)

### ISSUE THREAD

**Issue by xpluscal** [xyflow/xyflow#3567]
### Describe the Bug

I'm trying to get Custom Edges to work in the svelte version.

Here's my code:

```
<script lang="ts">
    import { createEventDispatcher } from 'svelte';
    import { BaseEdge, EdgeLabelRenderer, type EdgeProps, getBezierPath } from '@xyflow/svelte';
    const dispatch = createEventDispatcher();

    type $$Props = EdgeProps;

    export let sourceX, sourceY, targetX, targetY, sourcePosition, targetPosition, markerEnd;

    let edgePath = getBezierPath({sourceX, sourceY, targetX, targetY, sourcePosition, targetPosition});
</script>

<BaseEdge path={edgePath} markerEnd={markerEnd} style="stroke:blue; stroke-width: 3px;" />
<EdgeLabelRenderer>
<div
    class="nodrag nopan"
>
    <button class="edgebutton" on:click={(event) => console.log("CLICK EDGE")}>
    XXX
    </button>
</div>
</EdgeLabelRenderer>
```

But my edges keep coming up like this:
<img width="265" alt="Screenshot 2023-11-01 at 18 05 26" src="https://github.com/wbkd/react-flow/assets/3706722/42e531ad-d9fe-4435-bed8-495234c80938">

Any help much appreaciated.

### Steps to Reproduce the Bug or Issue

1. Create a CustomEdge component
2. Pass as edgeType to SvelteFlow as default

### Expected behavior

Edge position correctly.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Hey! There are two things you need to fix here. The edgePath needs to be reactive and the `getBezierPath` returns an array. This should do it:

```svelte
$: [edgePath] = getBezierPath({sourceX, sourceY, targetX, targetY, sourcePosition, targetPosition});
```

**Comment by moklick** [comment]
Please re-open if the issue persists.
