### ISSUE TITLE
node.data is not reactive in svelte in Custom Node

### ISSUE THREAD

**Issue by xpluscal** [xyflow/xyflow#3574]
### Describe the Bug

When I update a node and it's data changes, the node doesn't update.
This is due to the data being passed as a prop and not a reactive store, hence it's node reactive.

### Steps to Reproduce the Bug or Issue

1. Create a custom node
2. update the node

e.g. $nodes = $nodes.map((n) => ... your changes)

### Expected behavior

Changing a node with its data should update the node

### Platform

svelte flow

**Comment by peterkogo** [comment]
This was raised in the Discord as well. We just updated [our example on this topic](https://svelteflow.dev/examples/nodes/update-node). 

Essentially you need to mutate the data object for updates to be triggered.

```{javascript}
node.data.label = 'New Label'; // this does not work

node.data = {
  ...node.data,
  label: 'New Label'
}; // this works
```

**Comment by KaiyuanMa** [comment]
> This was raised in the Discord as well. We just updated [our example on this topic](https://svelteflow.dev/examples/nodes/update-node).
> 
> Essentially you need to mutate the data object for updates to be triggered.
> 
> ```
> node.data.label = 'New Label'; // this does not work
> 
> node.data = {
>   ...node.data,
>   label: 'New Label'
> }; // this works
> ```

I tried doing that but it is not working for me, did I do anything wrong?
https://stackblitz.com/edit/bs5ylk?file=src%2Fexample%2FApp.svelte

**Comment by keedyc** [comment]
That suggestion didn't work for me either, but a similar change to my custom node worked!

```ts
// Before
<script lang="ts">
    export let data: any
    let { foo } = data
    $: bar = foo + 1
</script>

// After
<script lang="ts">
    export let data: any
    $: bar = data.foo + 1
</script>
```

Out of curiosity, @KaiyuanMa, does that solution also help for you?
