### ISSUE TITLE
Examples link on Quickstart page goes to a 404 page

### ISSUE THREAD

**Issue by timmparsons** [xyflow/xyflow#3579]
### Describe the Bug

In the Quickstart guide, the Examples link at the bottom goes to a 404 page.

It looks like the link [here](https://github.com/xyflow/web/blob/main/sites/reactflow.dev/src/pages/learn/index.mdx#L295) should be `<Card title="Examples" href="/examples" />` and not `<Card title="Examples" href="/examples/overview" />`

### Steps to Reproduce the Bug or Issue

1. Go to Qucikstart page
2. Scroll down to bottom
3. Click Examples

### Expected behavior

As a user, I expect the link to go to the Examples page

### Screenshots or Videos

<img width="1438" alt="Screenshot 2023-11-07 at 9 53 05 PM" src="https://github.com/xyflow/xyflow/assets/20852851/f586a924-ad1f-44e4-bb5c-fcad1f2cb800">
<img width="1440" alt="Screenshot 2023-11-07 at 9 53 14 PM" src="https://github.com/xyflow/xyflow/assets/20852851/385bacaa-0aed-4bcd-8b77-b88eea6aaad1">

### Platform

macOs

**Comment by moklick** [comment]
Thanks, fixed!
