### ISSUE TITLE
Maximum update depth exceeded error while use Zustand store.

### ISSUE THREAD

**Issue by xXAvoraXx** [xyflow/xyflow#3590]
### Describe the Bug

I get a maximum update depth exceeded error when using zustand store. I just applied the article below to my own app. As you can see in the video, this error occurs when I move the component out of the background. If I use the useNodesState hook instead of zustand, this error does not occur. How can I solve this?

https://reactflow.dev/learn/advanced-use/state-management#install-zustand

### Your Example Website or App

https://reactflow.dev/learn/advanced-use/state-management#install-zustand

### Steps to Reproduce the Bug or Issue

It happens when I quickly take the component out of the background and put it back in. I also get this error because I use zustand store.

### Expected behavior

prevent this error from occurring when using zustand store.

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/6988989/6b670ac5-be07-4e45-9125-dbc3fdd1f278

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
could you create a codesandbox for this? https://new.reactflow.dev/ts

**Comment by xXAvoraXx** [comment]
> could you create a codesandbox for this? https://new.reactflow.dev/ts

https://codesandbox.io/s/affectionate-franklin-jjxkgp

**Comment by moklick** [comment]
I can't reproduce the issue with your codesandbox.

**Comment by xXAvoraXx** [comment]
> I can't reproduce the issue with your codesandbox.

have you tried opening it from a different browser? the app opens for me.

![image](https://github.com/xyflow/xyflow/assets/6988989/4e74a18b-9c58-40c8-9316-f4af281cac05)

**Comment by xXAvoraXx** [comment]
Uploading bug2.mp4…

**Comment by xXAvoraXx** [comment]
Is there any solution?

**Comment by xXAvoraXx** [comment]
Also onNodesDelete not working with zustand @moklick

**Comment by moklick** [comment]
The app opens, but I can't reproduce the error. `onNodesDelete` is not needed if you have an `onNodesChange` handler. You get the remove events in that one.

**Comment by xXAvoraXx** [comment]
If the node is dragged out continuously, an error occurs. For example, after dragging the node outwards and returning it to its original position, release it, then select it again with the mouse and drag it again. If you do this several times, a warning is generated.

**Comment by moklick** [comment]
Which browser are you using?

**Comment by xXAvoraXx** [comment]
> Which browser are you using?

Chrome

**Comment by szpytfire** [comment]
This isn't a zustand-only issue. I have an application using a bare React Context to manage state and can reproduce exactly the same behaviour (i.e. dragging a node around throwing the `Maximum update depth exceeded` error). I've yet to figure out what's causing it. All I know so far is that it occurred after upgrading from react-flow 10 -> 11

**Comment by goliney** [comment]
I cannot reproduce either. Apart from an unrelated issue at start, there is nothing else:

https://github.com/xyflow/xyflow/assets/2017344/335c9e0a-32c6-463e-8491-41bc2c8e8cba

<img width="531" alt="image" src="https://github.com/xyflow/xyflow/assets/2017344/627f5de3-ad53-42d5-99d2-35951dd7e6a0">

**Comment by xXAvoraXx** [comment]
Hold the card component and pull it out of the window. The problem is that the card component gives the error when it is moved out of the context. When doing so, very quickly move it out from the edges and bring it back into the context. You can see the error.

![image](https://github.com/xyflow/xyflow/assets/6988989/cc8f92fb-d6e9-4105-9647-496e5db601a5)

**Comment by goliney** [comment]
I was able to reproduce the issue you mentioned. 

https://github.com/xyflow/xyflow/assets/2017344/a7d924c6-9f8a-447e-9da2-545feb2cba99

But I'm not sure it relates to reactflow 🤷

**Comment by moklick** [comment]
I am still not able to reproduce this, but I see a lot of room for improvement here. Doing stuff like 

```js 
<Dropdown
    menu={{ items }}
    trigger={["contextMenu"]}
    getPopupContainer={(triggerNode) => triggerNode}
>
    {children}
</Dropdown>
```

could lead to problems since you are re-rendering the Dropdown every time a node gets dragged. In this case you could define:

```js
const trigger = ['contextMenu'];
const getPopupContainer = (triggerNode) => triggerNode;
```

outside of the component to prevent re-creations of those props. Please refactor your example and re-open this issue if you still get the maximum depth issue.
