### ISSUE TITLE
"react-flow__renderer", "react-flow__pane" incorrect size after typing in partially hidden block textarea

### ISSUE THREAD

**Issue by ivanksh** [xyflow/xyflow#3598]
### Describe the Bug

"react-flow__renderer", "react-flow__pane" have incorrect size after typing in partially hidden block textarea.

https://github.com/xyflow/xyflow/assets/95905841/5b816fe7-078d-4a16-996d-e7660558dc6f

### Steps to Reproduce the Bug or Issue

https://codesandbox.io/s/dynamic-handles-forked-h2llqj?file=/src/CustomNode.tsx
1) move block to the right and make it partially hidden (e.g 80% hidden)
2) type into block textarea
3) After cursor reachs right canvas border block moves to the left and background and "react-flow__renderer", "react-flow__pane"  are shifted

### Expected behavior

"react-flow__renderer", "react-flow__pane" have correct size

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
maybe related to #3483

**Comment by peterkogo** [comment]
Duplicate, we will continue discussion in #3483
