### ISSUE TITLE
Get current min / max zoom level for renderer?

### ISSUE THREAD

**Issue by sushantdhiman** [xyflow/xyflow#3599]
### Please describe the feature that you want to propose

I am trying to use the [download image](https://reactflow.dev/examples/misc/download-image) example. It works but I need to provide min / max zoom level as `getTransformForBounds` arguments.

As min / max zoom level may change in the future, I would like this info expose by [ReactFlowInstance](https://reactflow.dev/api-reference/types/react-flow-instance), so I can directly access that information from `react-flow` without the need of hard-coding it. 

Can you provide a hook something like `getZoomBounds() : ({ min: number, max: number })`?

**Comment by bcakmakoglu** [comment]
You can access this information using `useStore`

```ts
const selector = (s: ReactFlowState) => {
	return {
		minZoom: s.minZoom,
		maxZoom: s.maxZoom,
	}
}

const { minZoom, maxZoom } = useStore(selector);
```

[Here's an example.](https://codesandbox.io/s/keen-browser-pzdkhw?file=/src/Flow.tsx:1130-1245)

**Comment by moklick** [comment]
Yep! Or set them by yourself via `minZoom` / `maxZoom` props.
