### ISSUE TITLE
E2E: Controls Plugin

### ISSUE THREAD

**Issue by peterkogo** [xyflow/xyflow#3608]
- [ ] Add a new test case in `examples/react/src/generic-tests` &  `examples/svelte/src/generic-tests`
- [ ] Create new E2E tests in `tests/playwright` for checking the functionality of the `<Controls />` Component

**Comment by Ankuristic** [comment]
Could You assign this task for End to End End Testing for the Controls component to me.

**Comment by moklick** [comment]
Hey @Ankuristic thanks for your offer to help. How does it come that you are interested in React Flow? Are you using it for a project or at work? We normally don't assign people who are not working at our company to any GH issues. If you are willing to help, you can always open a PR and I am happy to review it.
