### ISSUE TITLE
E2E: defaultEdgeOptions

### ISSUE THREAD

**Issue by peterkogo** [xyflow/xyflow#3612]
- [ ] Add a new test case in `examples/react/src/generic-tests` &  `examples/svelte/src/generic-tests`
- [ ] Create new E2E tests in `tests/playwright` for checking the functionality of the `defaultEdgeOptions`

**Comment by Danish-Belal** [comment]
@peterkogo  can you please guide me on how I should understand it?
I would love to contribute.

**Comment by moklick** [comment]
Hey @Ankuristic and @Danish-Belal thanks for your offer to help. How does it come that you are interested in React Flow? Are you using it for a project or at work? We normally don't assign people who are not working at our company to any GH issues. If you are willing to help, you can always open a PR and I am happy to review it.

**Comment by Ankuristic** [comment]
@moklick  ok i start working on the E2E testing and when completed then then open the PR.
