### ISSUE TITLE
Svelte: selectionKey set to null

### ISSUE THREAD

**Issue by 1bye** [xyflow/xyflow#3618]
### Please describe the feature that you want to propose

I hope this message finds you well. I've been thoroughly impressed with the recent Svelte port – fantastic work!

I'm currently delving into its functionalities and have a couple of queries:

1. **Compatibility with Svelte: #1001**
   I've noticed an issue tagged as #1001. Could you please provide clarity on whether the Svelte port supports the functionality outlined in this issue? I want to make sure I'm not overlooking anything.

2. **Feature Request: `selectionKey` in `useSvelteFlow`**
   Additionally, I'm interested in the possibility of integrating a `selectionKey` parameter into the `useSvelteFlow` feature. This addition, if feasible, would significantly enhance its adaptability in specific use cases.

Thank you!

**Comment by moklick** [comment]
good call! We will allow to disable a key by using `null` with the next release. 
Why do you want to integrate it with `useSvelteFlow`? What is your use case here?

**Comment by 1bye** [comment]
Hey @moklick, I'm working on letting users choose different tools in my project. For example, they can switch to the `selection` tool, similar to how it works in Photoshop. I'm also exploring the possibility of implementing events like `noderemove` and `edgeremove` while using this library.

Currently, I have a code snippet that looks something like this (and it a little bit strange):
```js
const unsubscribeNodes = nodeStore.subscribe((value, old) => {
     nodes = value;
     if (old.length > value.length) dispatch('noderemove');
     else if (value.length > old.length) dispatch('nodeadd')
})
const unsubscribeEdges = edgeStore.subscribe((value, old) => {
     edges = value;
     if (old.length > value.length) dispatch('edgeremove');
     else if (value.length > old.length) dispatch('edgeadd')
})
```
Does it possible to add onEdge remove and onNode remove event? Or it can be implement by another way?
Thanks, and waiting for release

**Comment by moklick** [comment]
we will add a `ondelete({ nodes, edges })` in the next release :)

**Comment by 1bye** [comment]
👍 thanks, waiting for the next release.

**Comment by 1bye** [comment]
@moklick  I've got one more feature, while doing project. Does it possible to add `let:connected` to handle?
For example:
```js
<Handle id="some-id" class="..." let:connected>
    {#if connected}
        // show some content
    {/if}
</Handle>
``` 
Thanks

**Comment by moklick** [comment]
Since 0.0.28 you can set any key to `null` to disable it. We also added an `ondelete` handler. Please open a new issue for the connected forwarding.
