### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/react-dom/index.js?v=622b9013' does not provide an export named 'createPortal'

### ISSUE THREAD

**Issue by cliffordfajardo** [xyflow/xyflow#3637]
### Describe the Bug

When attempting to load reacflow, I get an error from in browser console regarding an import that reactflow is trying to make `createPortal` (source code of [reactflow importing createPortal](https://github.com/search?q=repo%3Axyflow%2Fxyflow%20createPortal&type=code)):

```
Uncaught SyntaxError: The requested module '/node_modules/react-dom/index.js?v=0f421ad3' does not provide an export named 'createPortal'
```

![CleanShot 2023-11-17 at 16 35 26@2x](https://github.com/xyflow/xyflow/assets/6743796/3f12e1f4-f8d6-4183-b6bf-a2f51a005bfa)

### Steps to Reproduce the Bug or Issue
Work in progress

### Expected behavior

.

### Platform

- Mac OS Sonomoa
- Browser:  Chrome latest
- reactflow version `11.10.1`

**Comment by moklick** [comment]
This is weird. `createPortal` is a named export of react-dom. Which version of React are you using? Does this happen with the latest remix version?

**Comment by moklick** [comment]
Please re-open if it's still an issue for you.
