### ISSUE TITLE
My first language is not English, can I customize this content? about <Controls> "title "

### ISSUE THREAD

**Issue by zxhycxq** [xyflow/xyflow#3639]
### Please describe the feature that you want to propose

![image](https://github.com/xyflow/xyflow/assets/11674203/bd98b643-5b70-4d6f-b55d-925501c79898)
<Controls> title

**Comment by zxhycxq** [comment]
Can you change the zoom in/out to another language？

**Comment by moklick** [comment]
That's only possible with a custom controls panel. You could the some built-in `Controls` and `ControlButton` components like this: https://codesandbox.io/s/interesting-bardeen-gy4hkx?file=/src/CustomControls.tsx:279-579
