### ISSUE TITLE
Edge label position was changed in V11

### ISSUE THREAD

**Issue by chkp-yaelg** [xyflow/xyflow#3644]
### Describe the Bug

I was using React Flow V10, the edge label of type "step" was located in the corner of the edge by default.
After I upgraded my code to use V11 I noticed that the behavior was changed, now the label locates in the middle of the edge.
Is there an option to provide me the old behavior? 

V10:  
![image](https://github.com/xyflow/xyflow/assets/44432942/cd11f1a8-c9f3-4ccd-89e3-57ccd1521899)

V11:
![image](https://github.com/xyflow/xyflow/assets/44432942/f2a1b754-5b7e-4b82-af26-44c760c16ccc)

### Steps to Reproduce the Bug or Issue

1. Use the code from the[ Edge Types example](https://reactflow.dev/examples/edges/edge-types)
2. install version 10
3. see the difference from the example you published.

### Expected behavior

As a user, I expect the the behavior of V10 will be available in V11 as well

### Screenshots or Videos

V10:  
![image](https://github.com/xyflow/xyflow/assets/44432942/cd11f1a8-c9f3-4ccd-89e3-57ccd1521899)

V11:
![image](https://github.com/xyflow/xyflow/assets/44432942/f2a1b754-5b7e-4b82-af26-44c760c16ccc)

### Platform

- OS: Windows
- Browser: Chrome

**Comment by moklick** [comment]
This was an optimization in v11.8.0 for better edge label position defaults:
 
![edge-labels](https://github.com/xyflow/xyflow/assets/2857535/7062db8f-ee96-4493-9d31-00f4b0c74917)

If you want to display the edge labels at a different position, the only solution is to implement a custom edge.

**Comment by chkp-yaelg** [comment]
Thank you,
I tried to create a custom edge based on step edge but I didn't understand how do I locate the label in the place I want
Can you share with me the code from V11.7.4 so I will use it in my code?
