### ISSUE TITLE
getNodesBounds returns wrong values for nested flows

### ISSUE THREAD

**Issue by moklick** [xyflow/xyflow#3645]
### Describe the Bug

getNodesBounds returns wrong values for nested flows because it uses position absolute. For the bounds, we should always use the position value. 

### Steps to Reproduce the Bug or Issue

..

### Expected behavior

return correct bounds.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by jnoerm19** [comment]
Could this result in my selection being messed up, and looking like this?:

https://github.com/xyflow/xyflow/assets/60742511/cea4283c-847f-46c5-aa8d-74cb37ccf231

**Comment by moklick** [comment]
which version of React Flow is this @jnoerm19 ?

**Comment by jnoerm19** [comment]
Version 11.10.2 @moklick

**Comment by moklick** [comment]
should be fixed in 11.10.3 !

**Comment by jnoerm19** [comment]
Awesome, thank you!

**Comment by moklick** [comment]
and a better version of `getNodesBounds` will be released with v12.
