### ISSUE TITLE
useReactFlow().setNodes does not batch updates (race condition)

### ISSUE THREAD

**Issue by insolite** [xyflow/xyflow#3653]
### Describe the Bug

`useReactFlow().setNodes` callback doesn't get the latest `nodes` argument when called sequentially right after another `setNodes` invocation.

Note:
1. The same issue is relevant for `useReactFlow().setEdges`.
2. `useNodesState().setNodes` and `useNodesState().setEdges` works just fine though.

### Your Example Website or App

https://codesandbox.io/p/sandbox/dreamy-thunder-56dlyw?file=%2Fsrc%2FFlow.js%3A11%2C4

### Steps to Reproduce the Bug or Issue

```tsx
const { setNodes } = useReactFlow();

// ...

setNodes((nodes) => {
  // nodes = []
  return [{ data: 1 }];
});
setNodes((nodes) => {
  // ER: nodes = [{ data: 1 }]
  // AR: nodes value is still []
  return nodes;
});
```

See the attached example for the comprehensive use case.

### Expected behavior

Updates are sequentially batched so that further `setNodes` callback gets the updated value.

### Platform

- OS: Linux
- Browser: Chrome
- Version: 114.0.5735.198

### Additional context

Despite the primitive example, this can happen in real use cases. For example, two separate nodes are performing their own data updates. But since we have to provide an entire `nodes` array, the updates are overriding each other.

**Comment by moklick** [comment]
Good catch. The reason for are our change based updates via `onNodesChange`. We will look into this and see if there is a way to fix it.

**Comment by yarinsa** [comment]
I am having the same issue 🙏🏼

**Comment by moklick** [comment]
We have a solution for this, that is already pushed in the next branch, but it introduces new issues that we need to address. I will close this issue and you can follow the progress here: https://github.com/xyflow/xyflow/issues/3790

For now in a controlled flow it's better not use `setNodes` but implement your own `setNodes` that does updates directly in your state/store.
