### ISSUE TITLE
Type '"dots"' is not assignable to type 'BackgroundVariant | undefined'.

### ISSUE THREAD

**Issue by polooner** [xyflow/xyflow#3655]
### Describe the Bug

I was just playing around with the demo from the docs and immediately I have this TypeScript error scream at me. Not a breaking bug but would be nice not to have it out of the box. 

### Your Example Website or App

https://github.com/polooner/xyflow-background-bug

### Steps to Reproduce the Bug or Issue

1. Go to https://github.com/polooner/xyflow-background-bug
2. Clone the repository
3. Run it locally with npm
4. Look at page.tsx

### Expected behavior

TS not screaming at me

### Screenshots or Videos

<img width="780" alt="Screenshot 2023-11-22 at 11 41 13 PM" src="https://github.com/xyflow/xyflow/assets/114031148/72d02e93-9c7d-40a7-9e2b-28024b6a69cc">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by polooner** [comment]
Hey I am also working on it right now I would love to push a quick fix for this if you would like to assign it to me!

**Comment by polooner** [comment]
As I dug down Idk if it's an easy fix anymore

**Comment by moklick** [comment]
For no good reason we are using an enum for the background variant. You need to write: 

```jsx 
<Background variant={BackgroundVariant.Dots} />
```
