### ISSUE TITLE
Edge label not elevating on node select

### ISSUE THREAD

**Issue by vicentel89** [xyflow/xyflow#3658]
### Describe the Bug

When `elevateEdgesOnSelect` prop is added to `ReactFlow`, edges are elevated, but edge labels are not elevated.

![image](https://github.com/xyflow/xyflow/assets/60248266/6ec82210-0245-4513-a803-84bf6437e9be)

### Steps to Reproduce the Bug or Issue

1. Add `elevateEdgesOnSelect` to `ReactFlow`.
2. Create a custom edge and add `EdgeLabelRenderer`.
3. Select a node that have an edge connected.

### Expected behavior

Labels are elevated too, so that edges are not on top of labels.
![image](https://github.com/xyflow/xyflow/assets/60248266/bec058e8-0738-41da-a2d5-433d17a1cc4a)

### Platform

- OS: macOS
- Browser: Chrome 119.0.6045.123
- Version: 11.9.4

**Comment by moklick** [comment]
How can we reproduce this. It looks fine to me: https://codesandbox.io/p/sandbox/trusting-maxwell-fk8rg3?file=%2FApp.js%3A102%2C27

**Comment by vicentel89** [comment]
I am using EdgeLabelRenderer in a custom edge.

I notice you create another svg to render elevated edges:
![image](https://github.com/xyflow/xyflow/assets/60248266/f9ba2a8a-d656-4199-98f0-f5fdb728785c)

But there is only one container for edge labels, and the label of the elevated edge is not elevated.
![image](https://github.com/xyflow/xyflow/assets/60248266/f0413754-07f5-4405-ab0b-1f36a61a45de)

**Comment by vicentel89** [comment]
As I don't have access to the selected node in the custom edge component, I cannot increase the label z-index manually either. Using the store and getIncomers/getOutgoers in the custom edge component to check if it is connected to a selected node would be bad for performance (in my app we have more than 500 nodes and edges).

A simple solution would to have an option only to elevate the edge when it is selected and not when a related node is selected.

The elevate-edge-on-node-select feature is nice, so it would be good if it could work well and you elevated labels too.

**Comment by moklick** [comment]
you can access the selected node or check if the edge itself is selected. That should be enough to specify a zIndex.

`const nodeSelected = useStore(s => s.nodeInternals.get(targetId)?.selected)`
