### ISSUE TITLE
Add child nodes only to specific areas of parent node

### ISSUE THREAD

**Issue by devvid8607** [xyflow/xyflow#3664]
### Describe the Bug

I have a drag drop menu from which I am adding items as children to a parent node.

My parent node has the following structure
Header
InputArea
Area to drop in child items

how do I ensure that items are not dropped into the header and input area. It should be only dropped in the area to drop items. There seems to be no way to do this.
![git](https://github.com/xyflow/xyflow/assets/118784101/4356ab5b-29e2-4272-83a2-eb5596531788)
![git2](https://github.com/xyflow/xyflow/assets/118784101/a6ded95d-1b10-461d-91c2-134bcb417795)

### Steps to Reproduce the Bug or Issue

1. Create a parent node
2. While dropping child node, prevent dropping in certain areas withing the parent node

### Expected behavior

Maybe while defining the parent I can say do not allow drop on this particular class 
{
    id: '2',
    data: { label: 'Group A' },
    position: { x: 100, y: 100 },
    className: 'light',
    style: { backgroundColor: 'rgba(255, 0, 0, 0.2)', width: 200, height: 200 },
   nodropZone:"noDropClass"
  },

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
There is no built-in functionality for dragging nodes into other nodes. For this you need to check the pointer position on node drag stop and decide if you want to add the node. You can use the helper function `isNodeIntersecting` for this https://reactflow.dev/api-reference/types/react-flow-instance#is-node-intersecting
