### ISSUE TITLE
Drag select bug(?): When using specific sequence, selection is dropped

### ISSUE THREAD

**Issue by Bartel-C8** [xyflow/xyflow#3665]
### Describe the Bug

onSelectionChange is triggered extra time with empty nodes when releasing shift before the mouse button:

When not moving mouse a bit after releasing the shift key, onSelectionChange is triggered correctly with the selected nodes.
But when the mouse is still moved a bit, 2 times onSelectionChange is triggered , first time with the actual nodes, but quickly thereafter with empty nodes, clearing the selection.

I experience this quite regularly with an external keyboard and mouse, where if I do the drag (shift) select very quickly, the ordering of releasing buttons is not in sequence.

In our application moving the mouse (4.) is not even needed to deselect the nodes, but can't reproduces that in a codesandbox for some reason..

### Steps to Reproduce the Bug or Issue

1. Start Shift select (Shift + press mouse)
2. Drag box around nodes
3. First release shift
4. Move mouse a bit
5. Release mouse button

### Expected behavior

If shift was released early, stop drag select as well and fire the selected nodes once?

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/76486925/b2f621c5-72c2-4bf7-b398-b3e2098e62f4

### Platform

- OS: macOS
- Browser: Electron 27.1.0 (Chromium)
- Version: latest, 11.10.1

### Additional context

Application has custom redux store (uncontrolled) and custom nodes.

Codebox reproduction attempt

```
import React, { useCallback, useEffect, useState } from 'react';
import ReactFlow, { useNodesState, useEdgesState, addEdge, MiniMap, Controls, SelectionMode } from 'reactflow';
import 'reactflow/dist/style.css';

const initialNodes = [
  { id: '1', data: { label: 'Node 1' }, position: { x: 250, y: 5 }, },
  { id: '2', data: { label: 'Node 2' }, position: { x: 100, y: 100 } },
  { id: '3', data: { label: 'Node 3' }, position: { x: 400, y: 100 } },
  { id: '4', data: { label: 'Node 4' }, position: { x: 400, y: 200 } },
];

const initialEdges = [
  { id: 'e1-2', source: '1', target: '2' },
  { id: 'e1-3', source: '1', target: '3' },
  { id: 'e3-4', source: '3', target: '4' },
];

const Flow = () => {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

  const onSelectionStart = useCallback(() => console.log("onSelectionStart"), []);
  const onSelectionEnd = useCallback(() => console.log("onSelectionEnd"), []);
  const onSelectionChange = useCallback((params) =>  console.log("onSelectionChange", params), []);
  const nodeChangeCallback = useCallback((params) =>  console.log("nodeChangeCallback", params), []);


  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      // onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      onSelectionStart={onSelectionStart}
      onSelectionEnd={onSelectionEnd}
      onSelectionChange={onSelectionChange}
      selectNodesOnDrag={false}
      selectionMode={SelectionMode.Partial}
      onNodesChange={nodeChangeCallback}
    >
      <MiniMap />
      <Controls />
    </ReactFlow>
  );
};

export default Flow;
```

**Comment by peterkogo** [comment]
This will be fixed in v12

**Comment by moklick** [comment]
This was fixed in React Flow 12!

If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12
