### ISSUE TITLE
Type eds is not asignable to Edge<any>[]

### ISSUE THREAD

**Issue by FurkanCodes** [xyflow/xyflow#3670]
### Describe the Bug

I have been following the docs to set up a project. applyEdgeChanges() does not seem to work well with initialEdges described inside the docs.

### Steps to Reproduce the Bug or Issue

1. Go to https://reactflow.dev/learn/getting-started/adding-interactivity#handle-change-events
2. Copy and  Paste the code.
3. Error occurs.

### Expected behavior

The corresponding types should be correctly set.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

I am a bit inexperienced so this error's occurrence might be related to this. 
I have solved it by adding "any" to the    
` const [edges, setEdges] = useState<any>(initialEdges);`
I also tried writing my own types;
`export interface Types {
    id: string;
    source: string;
    target: string;
    label: string;
    type: string;
}
`
And tied passing those, but no avail.
I just wanted to bring this up.

**Comment by bcakmakoglu** [comment]
The example you copy pasted wasn't in TypeScript to begin with, so you'll have to make a couple adjustments yourself.

- Start by adding types to the initialNodes/initilEdges arrays
```ts
import type { Node, Edge } from 'reactflow';

const initialNodes: Node[] = [
  {
    id: '1',
    data: { label: 'Hello' },
    position: { x: 0, y: 0 },
    type: 'input',
  },
  {
    id: '2',
    data: { label: 'World' }, 
    position: { x: 100, y: 100 },
  },
];

const initialEdges: Edge[] = [
  { id: '1-2', source: '1', target: '2', label: 'to the', type: 'step' },
];
```

2. Type the change handlers accordingly
```ts
import type { NodeChange, EdgeChange } from 'reactflow';

const onNodesChange = useCallback(
  (changes: NodeChange[]) => setNodes((nds) => applyNodeChanges(changes, nds)),
  [],
);
const onEdgesChange = useCallback(
  (changes: EdgeChange[]) => setEdges((eds) => applyEdgeChanges(changes, eds)),
  [],
);
```

There you go, your type errors should be resolved.

[Here's a sandbox for this example.](https://codesandbox.io/p/sandbox/jolly-breeze-wjcxwn?file=%2Fsrc%2FFlow.tsx%3A15%2C4)

**Comment by FurkanCodes** [comment]
Thank you very much! I have totally missed the part where  I needed to define my own types...

**Comment by FurkanCodes** [comment]
Thank you very much. I totally forgot to import the types.
