### ISSUE TITLE
Node with nodrag becomes selectable with selectionKeyCode

### ISSUE THREAD

**Issue by jt6677** [xyflow/xyflow#3674]
### Describe the Bug

Node with nodrag class can still being selected with selection key and deleted with delete key.  I wanted to make some "none interactive" nodes that is always present and discovered this. 

### Steps to Reproduce the Bug or Issue

1. shift select  node with 'nodrag'
2. backspace 

### Expected behavior

nodrag node should be unselectable 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [ Chrome, Safari, Firefox]
- Version: [11.10.1]

**Comment by bcakmakoglu** [comment]
Where'd you read that `nodrag` makes a node un-interactive?

It's a class name you use to specify elements *which should not cause the node to be dragged*, like an Input-Field for example.

You can disable a node being selectable by setting `node.selectable = false`, same for `deletable`.

**Comment by jt6677** [comment]
great. 
draggable:false
selectable: false,
 deleteable: false,
