### ISSUE TITLE
Svelte Flow: getIntersectingNodes bug when passing Rect

### ISSUE THREAD

**Issue by mcgain** [xyflow/xyflow#3675]
### Describe the Bug

In Svelte Flow, `SvelteFlowProvider`'s `getIntersectingNodes` function does not work with `Rect` passed as the first parameter.

What I think is going on here is  that https://github.com/xyflow/xyflow/blob/main/packages/svelte/src/lib/hooks/useSvelteFlow.ts#L139 should use `&&` instead of `||`. The line above calls `getNodeRect` when a node is passed, so both the `nodeRect` and `node` variables are populated, but when a `Rect` is passed, only the nodeRect variable is populated, so line 139 fails and returns `[]`.

### Your Example Website or App

https://stackblitz.com/edit/cozxhv-sv6ngc?file=src%2Fexample%2FInner.svelte

### Steps to Reproduce the Bug or Issue

Call `getIntersectingNodes` with a `Rect` that does actually overlap one or more Nodes.

### Expected behavior

The function should return the intersected Node(s) in an array.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by mcgain** [comment]
If my logic makes sense to you, I'm happy to fix this, add some tests etc.

**Comment by peterkogo** [comment]
You are absolutely right! I can fix this promptly and it will be in the new release - if you are eager to contribute please tell me. 
We are currently rethinking the way we do testing, so a test will not be necessary.

**Comment by moklick** [comment]
released in 0.0.29 https://svelteflow.dev/whats-new/2023-12-13
