### ISSUE TITLE
Errors reference

### ISSUE THREAD

**Issue by pavelloz** [xyflow/xyflow#3679]
Hello,

I'm getting an error #008 with a link, but when i click on the link, 404 appears.
Is there any other reference for errors?

> (stub-2)warn("[React Flow]: Couldn't create edge for target handle id: "undefined", edge id: edge:1 '-->' 1. Help: https://reactflow.dev/error#008")

It would be nice to get some more information on whats going on (or at least not a broken link :) ), even though error message is pretty self explanatory.

**Comment by moklick** [comment]
Duplicate of xyflow/web#266  I'll try to fix this today.

**Comment by moklick** [comment]
should work again!
