### ISSUE TITLE
Unable to Copy Tooltip Text in ReactFlow

### ISSUE THREAD

**Issue by Cristhianzl** [xyflow/xyflow#3687]
### Describe the Bug

I'm attempting to replicate the tooltip text using the Ctrl+C and Ctrl+V commands, but unfortunately, it doesn't seem to be working. Has anyone discovered a workaround to address this issue?

![image](https://github.com/xyflow/xyflow/assets/72977554/dbc72b68-57d0-4dd8-ae2c-c6289c575bda)

### Steps to Reproduce the Bug or Issue

Insert a node containing a tooltip.
Attempt to duplicate the text within the tooltip using Ctrl+C and Ctrl+V.
Verify the accuracy of the copied text.

### Expected behavior

When using Ctrl+C and Ctrl+V to copy and paste text, the selected text is successfully copied.

### Platform

Chrome

**Comment by moklick** [comment]
please re-open with a codesandbox.
