### ISSUE TITLE
expose ReactFlowContext to be able to access ReactFlowInstance in class components

### ISSUE THREAD

**Issue by joesonw** [xyflow/xyflow#3689]
### Please describe the feature that you want to propose

expose ReactFlowContext, currently with only `useReactFlow`, we can only access `ReactFlowInstance` in function components.

but there are situations where class components are requried/used.

currently, it can only be achived by wrapping `useReactFlow` in a function component wrapper with custom context holding `ReactFlowInstance`

**Comment by moklick** [comment]
Thanks for the idea here but this is not planned. The solution you described is a good workaround already.
