### ISSUE TITLE
Canvas error when I used chart canvas

### ISSUE THREAD

**Issue by Sangwon-sim-simacro** [xyflow/xyflow#3698]
### Describe the Bug

I used in create Node with chart canvas.
And mouse event ( click drag hover ) not working I expected, 

const {x, y, zoom} = useViewport()
And when I apply on canvas parent div ( transform : scale( 1/ zoom), It works correctly.

But outer transfrom scale ruin the node wrapper, and size not shrink because of 1/zoom * zoom  = 1.
How can I fix this bug?

### Steps to Reproduce the Bug or Issue

1. Install Lightning Chart / React Flow
2. Create Sample react chart and insert in a node.
3. When zoom in out, at specific zoom, it works fine but not working almost zoom 

### Expected behavior

Chart Canvas works well,,, 
It be affected react flow, ( zoom in out , node resize ) but inner mouse event works fine also
I expected someone else(use canvas chart ) have same iuuse for it, but there is no similar issue when I search with zoom, scale option. 

### Platform

- OS: [Windows, ]
- Browser: [Chrome]
- Version: ^11.8.3

**Comment by moklick** [comment]
could you create a codesandbox for this? https://new.reactflow.dev

**Comment by Sangwon-sim-simacro** [comment]
![image](https://github.com/xyflow/xyflow/assets/134468978/9b3dd72b-c1fe-4452-8793-5b983ef0db6a)

[Sandbox Link](https://codesandbox.io/p/sandbox/optimistic-snyder-g6j9jm?file=%2Fsrc%2FCustomNode.tsx%3A772%2C51&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clps6al6w0006356h9yuaoj7w%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clps6al6w0002356hie8xl98w%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clps6al6w0003356hng5tt7cc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clps6al6w0005356h4gn6wbfk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50.79247092674739%252C49.20752907325261%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clps6al6w0002356hie8xl98w%2522%253A%257B%2522id%2522%253A%2522clps6al6w0002356hie8xl98w%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpt38see0002356h4eabjvz1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A772%252C%2522startColumn%2522%253A51%252C%2522endLineNumber%2522%253A772%252C%2522endColumn%2522%253A51%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FCustomNode.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpt38see0002356h4eabjvz1%2522%257D%252C%2522clps6al6w0005356h4gn6wbfk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clps6al6w0004356hz0li9o8r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clps6al6w0005356h4gn6wbfk%2522%252C%2522activeTabId%2522%253A%2522clps6al6w0004356hz0li9o8r%2522%257D%252C%2522clps6al6w0003356hng5tt7cc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clps6al6w0003356hng5tt7cc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A21.04982206405694%257D)


When I mouse over on canvas, at zoom 1 It works fine.
But at zoom 2~ 3 or  0.8 ~ 0.2 , Canvas mouse action doesn't working well.

The scale of the view port changes depending on the zoom, 
and the affected canvas appears normal, 
but the actual range to which the mous event is applied appears to shrink or expand.

I'm not sure if this is a general error that occurs when using a package with a mouse event in a canvas, or if it only occurs in a specific package. 
It appears that there is no way to customize the mouse event range in the Lightning chart, so I asked a question wondering if this could be solved in React Flow options .

I solved this by applying a scale of 1/zoom to the child properties and setting the width and height to 100*zoom to fool it as if the transfrom was 0, 
then setting the position to a relative property on the top node div of the custom node and applying absolute to the div below. , I don't think this is a normal way ..

**Comment by moklick** [comment]
It seems that the charting library doesn't work in a scaled/transformed container. Unfortunately we can't fix this. Maybe they offer an option to support it somehow.
