### ISSUE TITLE
Prevent viewport from moving outside graph boundary

### ISSUE THREAD

**Issue by lounsbrough** [xyflow/xyflow#3701]
### Please describe the feature that you want to propose

It would be cool if we could prevent the viewport from scrolling beyond the boundaries of the graph.

### Use case:
We have a graph where we allow users to set filters on the nodes that they're looking at. If we apply a filter that removes many nodes, we can easily end up in a place where the user no longer sees anything on their screen because the location they were at no longer has any nodes present. In that case we would like it if the viewport would shift over far enough so that some nodes were visible again, unless of course there are no more nodes in the graph. Essentially the viewport would detect that it is outside the boundaries of the space where nodes are present, and move itself back into the valid 2D space.

It doesn't seem useful to let the user scroll beyond the boundary of the nodes that exist in the graph, since there would be nothing to see. If that is still a valid use case though, maybe an optional property could still allow that behavior.

**Comment by moklick** [comment]
Hey @lounsbrough 

It should be possible to use `translateExtent` for this. You need to measure the bounds of the current flow and set the translate extent accordingly. I found this example, that might help you with this https://codesandbox.io/p/sandbox/translateextent-2s66rg?file=/App.js:62,42 - you can only drag the pane as far as the node bounds. If you remove some nodes, the translate extent gets smaller.

**Comment by lounsbrough** [comment]
Cool, will check that out, thanks!
