### ISSUE TITLE
Module '"reactflow"' has no exported member...

### ISSUE THREAD

**Issue by ajmeese7** [xyflow/xyflow#3704]
### Describe the Bug

I get a bunch of errors running `tsc -b` like the following:

```shell
error TS2614: Module '"reactflow"' has no exported member 'ReactFlowProvider'. Did you mean to use 'import ReactFlowProvider from "reactflow"' instead?
error TS2614: Module '"reactflow"' has no exported member 'Background'. Did you mean to use 'import Background from "reactflow"' instead?
...
```

### Steps to Reproduce the Bug or Issue

Using Reactflow v11.10.1 with the following code:

```js
import ReactFlow, {
  Controls,
  useReactFlow,
  ReactFlowProvider,
  Background,
  BackgroundVariant,
  Connection,
  ConnectionLineType,
  useEdgesState,
  useNodesState,
} from "reactflow";
```

### Expected behavior

I expect the imported modules to work, because using the actual repository doesn't seem to experience any issues.

### Platform

- OS: Windows
- Browser: N/A
- Version: N/A

### Additional context

I am using `pnpm` 8.11.0 to install all packages, not normal `npm`. I am running Node v18.19.0.

**Comment by moklick** [comment]
I can't reproduce this. Is it still an issue for you?

**Comment by moklick** [comment]
please re-open if it's still an issue for you.
