### ISSUE TITLE
node with deletable:false gets deleted on del|backspace key press

### ISSUE THREAD

**Issue by kuldeepkeshwar** [xyflow/xyflow#3706]
### Describe the Bug

node with deletable:false gets deleted on del|backspace key press.

A possible fix for this can be filtering out nodes/edges which has `deletable` set as `false`

File: packages/core/src/hooks/useGlobalKeyHandler.ts
```diff
-            const selectedNodes = getNodes().filter((node) => node.selected);
-            const selectedEdges = edges.filter((edge) => edge.selected);
+            const selectedNodes = getNodes().filter(item=>item.deletable??true).filter((node) => node.selected);
+            const selectedEdges = edges.filter(item=>item.deletable??true).filter((edge) => edge.selected);
```

### Steps to Reproduce the Bug or Issue

1. set deletable as false on any node
2. press del|backspace key
3. node gets deleted

### Expected behavior

Node with deletable:false should not get deleted on pressing del|backspace key

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
As @bcakmakoglu this should work fine. Please re-open with a sandbox if the issue persists.
