### ISSUE TITLE
Drag and drop connection position

### ISSUE THREAD

**Issue by furkanbicak** [xyflow/xyflow#3709]
### Please describe the feature that you want to propose

The ability to change the position of the link between two nodes. For example, the user should be able to grab the link and drag it to the desired position. Can we make this feature possible?

**Comment by bcakmakoglu** [comment]
Are you talking about [*Updatable Edges*](https://reactflow.dev/examples/edges/updatable-edge)?

That functionality already exists and is available :)

**Comment by furkanbicak** [comment]
> Are you talking about [_Updatable Edges_](https://reactflow.dev/examples/edges/updatable-edge)?
> 
> That functionality already exists and is available :)

When I grab and drag one of the nodes the link position also changes, but what I want is to be able to drag and drop the link itself and this feature is not available

**Comment by bcakmakoglu** [comment]
I think you have to a bit more clear in your description of what feature you're looking for.
To me, it's still not quite clear.
Are you talking about "editable" edges? Like editing their path?

**Comment by furkanbicak** [comment]
> I think you have to a bit more clear in your description of what feature you're looking for. To me, it's still not quite clear. Are you talking about "editable" edges? Like editing their path?

I'm talking about being able to drag and drop the edges. 
Just as we can drag the nodes to the x,y position we want, I'm talking about dragging and dropping them to the x,y position I want on the edges.

**Comment by furkanbicak** [comment]
> Excuse me, I am also having a hard time understanding this. It sounds to me like editable edges, too!
> 
> Just for clarification: If I drag an edge, does the path of the edge change but nothing happens with the nodes it is connected to?

![Ekran Resmi 2024-01-05 15 38 01](https://github.com/xyflow/xyflow/assets/80355473/60c9d3fb-9d1c-44c6-babe-b46974aadca5)


I want to change the position of the link like in the image above. In the example above, a fraudulent method was tried with the node

**Comment by Bartel-C8** [comment]
Looking for the same functionality, if I understand it correctly:

To be able to drag an edge (path piece) itself. To alter its path.

**Comment by moklick** [comment]
This issue is about editable edges. Please use this discussion #1029

It's already possible to implement with a custom edge implementation. It's on our list to create an example for this but it's a lot of work.
