### ISSUE TITLE
Svelte: Use isInputDOMNode before handling delete key press

### ISSUE THREAD

**Issue by futurGH** [xyflow/xyflow#3712]
### Describe the Bug

Unlike react-flow, svelte-flow doesn't check if focus is inside an input or a `.nokey` element using `isInputDOMNode` before handling keypresses. This results in backspace in an input deleting a node in some cases.

### Steps to Reproduce the Bug or Issue

1. Create node with `<input>` element
2. Select node then focus input
3. Backspace
4. :(

### Expected behavior

Backspace in input or `.nokey` elements shouldn't delete the selected node.

### Platform

@xyflow/svelte 0.0.28

**Comment by moklick** [comment]
We will do a release this week. It's fixed in this PR https://github.com/xyflow/xyflow/pull/3688

**Comment by moklick** [comment]
fixed in 0.0.29 https://svelteflow.dev/whats-new/2023-12-13
