### ISSUE TITLE
ReactFlow: Left a shadow while dragging

### ISSUE THREAD

**Issue by LierWier** [xyflow/xyflow#3721]
### Describe the Bug

![reactflow](https://github.com/xyflow/xyflow/assets/102370834/40da92fb-2a52-4fc7-b8b3-2154f331c9b5)

### Steps to Reproduce the Bug or Issue

as picture

### Expected behavior

as picture

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by bcakmakoglu** [comment]
No description when this happens at all?
Just a screenshot? :/ 

An issue should be descriptive enough to reproduce the issue, or better yet: provide a reproduction for the issue.

**Comment by moklick** [comment]
I don't think there is anything we can do about it. It's hard to reproduce and seems like a browser issue (I also saw it a few times).
