### ISSUE TITLE
Add onBeforeDelete handler to control deletions

### ISSUE THREAD

**Issue by moklick** [xyflow/xyflow#3722]

**Comment by jt6677** [comment]
I would love to have this. Currently, I want to prevent edges from being deletable. The only way I could find is to set edge property to be deletable:false.   Additionally, elementsSelectable={false}.  I would prefer to have nodeSeletable and edgeSelectable. Edge does not have a selectable property.

**Comment by jt6677** [comment]
Would you think onBeforeDelete would be a good place to handle any  orphan edge deletion?

**Comment by moklick** [comment]
@jt6677 that would be possible!
