### ISSUE TITLE
Controls Zoom In/Out button do not become disabled on max/min zoom

### ISSUE THREAD

**Issue by Dalimil** [xyflow/xyflow#3724]
### Describe the Bug

When zooming in and out using the <Controls> component, the plus/minus buttons should get disabled when max/min zoom is reached. That doesn't seem to be the case

### Steps to Reproduce the Bug or Issue

1. Create React Flow instance with <Controls> component inside
2. Click Plus until max zoom is reached

### Expected behavior

Plus button should get disabled

### Platform

- OS: macOS
- Browser: Chrome
- Version: 120.0

**Comment by moklick** [comment]
I can't reproduce this. The buttons get disabled when min/max is reached https://codesandbox.io/p/sandbox/modest-waterfall-9xphnf 

Please re-open with a codesandbox if the issue still occurs.
