### ISSUE TITLE
Overlapping two connection edges in version 11 

### ISSUE THREAD

**Issue by sudarsanarao995** [xyflow/xyflow#3734]
### Describe the Bug

There are overlaps of two streams connections numbers (1, 2)

### Steps to Reproduce the Bug or Issue

In Screenshot Mixsplit2 connected to  Mixsplit1 and again Mixsplit2 connected to Mixsplit3, then issue able to see the overlaps of two streams connections

### Expected behavior

Should not be Overlapping of  two connection edges (1 , 2)

### Screenshots or Videos

![image](https://github.com/xyflow/xyflow/assets/147405464/07be4e81-8bcd-453d-a7bc-34d0454090c2)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
This is not a bug or an issue. That's just how our edges work. If you need a custom layouting for edges, you need to implement a custom edge.
