### ISSUE TITLE
Proximity Connect is not working in Drag and Drop nodes 

### ISSUE THREAD

**Issue by sudarsanarao995** [xyflow/xyflow#3735]
### Describe the Bug

This is logic link we are using proximity connect  https://reactflow.dev/examples/nodes/proximity-connect 

below the codesandbox link integrated this proximity-connect in Drag and Drop code
https://codesandbox.io/p/sandbox/flamboyant-flower-trnj77?file=%2FApp.js

### Steps to Reproduce the Bug or Issue

https://reactflow.dev/examples/nodes/proximity-connect 

codesandbox link:
https://codesandbox.io/p/sandbox/flamboyant-flower-trnj77?file=%2FApp.js

### Expected behavior

Proximity Connection should work  in Drag and Drop nodes

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
This is not an issue or a bug. If you need to this feature, you need to implement it somehow. It's possible (https://twitter.com/ryanjhunter/status/1730166764913480061)

**Comment by sudarsanarao995** [comment]
can you please provide the source code for this , I unable to find the code this feature

**Comment by moklick** [comment]
I don't have implemented something like that yet
