### ISSUE TITLE
Facing Problem Proximity connect in Drag and Drop Nodes

### ISSUE THREAD

**Issue by sudarsanarao995** [xyflow/xyflow#3736]
### Please describe the feature that you want to propose

when we implementing Proximity connect in Drag and Drop Node , that proximity connect is not working getting some issue showing below.
here console.log("Store State", store.getState()); showing as empty 
```
 const getClosestEdge = useCallback((node) => {
    const { nodeInternals } = store.getState();
    console.log("Store State", store.getState());
    const storeNodes = Array.from(nodeInternals.values());

    const closestNode = storeNodes.reduce(
      (res, n) => {
        if (n.id !== node.id) {
          const dx = n.positionAbsolute.x - node.positionAbsolute.x;
          const dy = n.positionAbsolute.y - node.positionAbsolute.y;
          const d = Math.sqrt(dx * dx + dy * dy);

          if (d < res.distance && d < MIN_DISTANCE) {
            res.distance = d;
            res.node = n;
          }
        }

        return res;
      },
      {
        distance: Number.MAX_VALUE,
        node: null
      }
    );
```
 please look at below my codesandbox link code 
https://codesandbox.io/p/sandbox/flamboyant-flower-trnj77?file=%2FApp.js%3A41%2C2-65%2C7

**Comment by moklick** [comment]
As said before. This is not an issue with the library. If you dom nodes over the pane, it has nothing to do with React Flow nodes. `onDragOver`, `onDrop`, `onDragStart` and `draggable` from your codesandbox comes from the native HTML API https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API . If you want to measure stuff, you would need to do that inside `onDragOver`.
