### ISSUE TITLE
Svelte Flow: change background color with class name for Background component

### ISSUE THREAD

**Issue by moklick** [xyflow/xyflow#3744]
Since the last update it's not possible to change the background with a class name anymore.

**Comment by peterkogo** [comment]
This again 🙄

**Comment by peterkogo** [comment]
This actually works

**Comment by peterkogo** [comment]
Or it does not?

**Comment by peterkogo** [comment]
It actually works! Add to the theming guide that import order of css does effect if tailwind or svelteflow css comes first
