### ISSUE TITLE
Default node type with black border

### ISSUE THREAD

**Issue by rafaelsilva81** [xyflow/xyflow#3746]
### Describe the Bug

When using the custom node types feature, in scenarios where you need to fallback to the default node type some standard styles are applied, this ends up messing with some specific scenarios that rely on having unidentified node types but still need specific styling to match the rest of the flow.

### Your Example Website or App
https://codesandbox.io/p/sandbox/amazing-dew-9mrnt5

### Steps to Reproduce the Bug or Issue

1. Start a project with reactflow
2. Add custom node types
3. Specify an element for the default fallback on node types
4. You can use this same element for a node with specific types
5. Create a node with a specific node type and another one to fallback to the default node type
6. The node that fallbacks to default will have a standard black border applied to it, the other one will just render your custom component

### Expected behavior

No styles to be applied in this scenario

### Screenshots or Videos

![image](https://github.com/xyflow/xyflow/assets/57678093/d6e446a7-2fb0-4317-a76b-727b5e3e8adc)

### Platform

- OS: Windows 10
- Browser: Brave (Chromium based)
- Version: 11.10.1

**Comment by peterkogo** [comment]
You can always start of with the most minimal styles by importing `base.css` instead of `styles.css`. See here: https://reactflow.dev/learn/customization/theming

Otherwise you can always set the nodeType to a custom node in `onConnect`. The fallback nodeType does not have to be `default`.

Does this fix your problem?
