### ISSUE TITLE
Copy-Paste keeps the copied edges selected after pasting

### ISSUE THREAD

**Issue by Hiansdt** [xyflow/xyflow#3752]
### Describe the Bug

When using the drag select feature and copying the flow from the copy-paste example, the copied edges keep selected after pasting, so if you delete the pasted nodes and edges without deselecting anything, the edges from the initially copied flow will also  be deleted.

Can be fixed by changing the line 130 of the useCopyPaste.ts file of the example:

```
setEdges((edges) => [...edges, ...newEdges]);
```
To:
```
setEdges((edges) => [...edges.map((edge) => ({ ...edge, selected: false })), ...newEdges]);
```

Just like the line above the mentioned ones, where the same is done for the nodes already.

### Your Example Website or App

https://reactflow.dev/examples/interaction/copy-paste

### Steps to Reproduce the Bug or Issue

1. Go to the example
2. Use Shift+Click+Drag to select the initial nodes and edges
3. Use Copy
4. Use Paste
5. Press backspace without deselecting the pasted content

### Expected behavior

As a user, I expected only the pasted content to be deleted, but the edges from the initial flow are also deleted, even though the initial nodes aren't

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Thanks, we will check it!

**Comment by moklick** [comment]
fixed. Thanks @hayleigh-dot-dev 👍
