### ISSUE TITLE
How to achieve the example shown in react flow home page for edge intersection

### ISSUE THREAD

**Issue by azharakbar** [xyflow/xyflow#3753]
### Describe the Bug

Hi team

How to get this type of edge intersection,
<img width="1416" alt="image" src="https://github.com/xyflow/xyflow/assets/10185101/2f52e29b-af45-470e-9c5d-165088d2bfb1">

I tried by providing `type: "smoothstep",`
But didnt work

What i got is this
<img width="1537" alt="image" src="https://github.com/xyflow/xyflow/assets/10185101/210e281e-73df-48a6-9895-61cb57359f8f">

Can you help me with the props that are needed to pass so as to get the connection intersection style shown in the react flow homepage ?

### Steps to Reproduce the Bug or Issue

nil

### Expected behavior

nil

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by azharakbar** [comment]
Got the solution .. 
THe problem was that the 2nd layer of nodes were so close to the first layer ..

**Comment by belandrio** [comment]
@azharakbar I am facing the same issue. How did you adjust the distance between them?

**Comment by belandrio** [comment]
Ah, yes makes sense. I was doing auto layout, but changing the y fixed it. Thank you 👍🏻
