### ISSUE TITLE
Documentation on <ReactFlow>'s isValidConnection callback is incorrect

### ISSUE THREAD

**Issue by hydrusbeta** [xyflow/xyflow#3755]
### Describe the Bug

Documentation on \<ReactFlow\>'s isValidConnection callback is incorrect.

Hello, 

I just wanted to report that the documentation for the isValidConnection callback at https://reactflow.dev/api-reference/react-flow#is-valid-connection states that the callback's type is:
`(edge: Edge) => boolean`
However, it appears to actually be:
`(connection: Connection) => boolean`
At least, that's what my IDE (WebStorm) is telling me:
![image](https://github.com/xyflow/xyflow/assets/128447736/72aa5ea2-c192-441d-92a6-19aceab34f81)

And if I log the parameter of the callback, it looks like a Connection object to me:
```typescript
const isValidConnection = useCallback((edge : Edge) => {
    console.log(edge);
    return true
}, [])
```
![image](https://github.com/xyflow/xyflow/assets/128447736/7b62a7ec-0781-46e2-bbd0-645776ff4d7e)

In fact, a different documentation page (https://reactflow.dev/examples/interaction/validation) correctly uses a Connection object instead of an Edge object.

I am using ReactFlow version 11.10.1

### Steps to Reproduce the Bug or Issue

1. Create a callback with the signature `(edge : Edge) => boolean`.
2. Define a React component that uses a \<ReactFlow\> instance and set the ReactFlow's isValidConnection callback to the callback you defined in step 1.
3. Run ESLint or paste your code in WebStorm and observe the type error.

### Expected behavior

I believe the _code_ behavior is correct.
The _documentation_ should state that the isValidConnection callback has this signature:
`(connection: Connection) => boolean`

### Platform

- OS: Linux (Ubuntu 22.04.1)
- Browser: Chromium

### Additional context

Just thought I'd mention that this is my first time using ReactFlow and I'm loving it so far. Keep up the great work!

**Comment by peterkogo** [comment]
Thanks for pointing this out, should be fixed on next deployment.
