### ISSUE TITLE
NodeResizer - SvelteFlow

### ISSUE THREAD

**Issue by ahornbeck** [xyflow/xyflow#3756]
### Please describe the feature that you want to propose

Please provide a NodeResizer in SvelteFlow like ReactFlow.

**Comment by moklick** [comment]
Hey @ahornbeck, we will add it :)

**Comment by ahornbeck** [comment]
@moklick Thank you and team!  Just for my planning purposes, rough ETA? (days, weeks, months)

**Comment by peterkogo** [comment]
@ahornbeck Working on it now. Release probably next week.

**Comment by moklick** [comment]
published in 0.0.32 https://svelteflow.dev/examples/nodes/node-resizer
