### ISSUE TITLE
selectHandle

### ISSUE THREAD

**Issue by 0p3r4t0r** [xyflow/xyflow#3757]
### Please describe the feature that you want to propose

We can use the [dragHandle](https://reactflow.dev/api-reference/types/node-props#drag-handle) prop to specify a specific area by which we can drag a node. I was wondering if it would be possible to create something analogous for node selection?

My use-case is that I would like to able to "click-through" certain nodes when they overlap, I've found that I can do this my setting [selectable](https://reactflow.dev/api-reference/types/node#selectable) to `false` and specifying a drag handle, which still allows be to drag the node. However, I cannot delete the node, because that seems to require selection.

**Comment by moklick** [comment]
You can use the new helpers to to change the selection of a node easily:

```js
const onClick = () => {
  updateNode(id, { selected: false });
};
```

This could be the `onClick` for a button or any other area inside a custom node.
