### ISSUE TITLE
Example to have multiple edges on the same node with auto spacing between edges.

### ISSUE THREAD

**Issue by vseverestek** [xyflow/xyflow#3758]
<img width="571" alt="image" src="https://github.com/xyflow/xyflow/assets/71376893/f566b6b1-b6fa-4ec2-95df-21762e8fdec4">

# To build something likes This can you share examples or referneces please.

I am trying to add multiple edges on the same nodes

**Comment by moklick** [comment]
This is possible with a custom edge implementation. You could render a different path if there is already an edge. We are doing something like that for the bi-directional edge here: https://reactflow.dev/examples/edges/custom-edges
