### ISSUE TITLE
The connection arrow jumps off the node on connect

### ISSUE THREAD

**Issue by Ankoge** [xyflow/xyflow#3765]
### Describe the Bug

The bug is came with the 11.10.1 update. Its only a performance bug, it don't affect the functionality. Its easier to show:
[arrow-bug.webm](https://github.com/xyflow/xyflow/assets/91005914/d398724c-ecbb-4a83-acb8-f1741afb5ad2)
As i sad the connection itself is working, but the arrow point to a unexpected point.

### Steps to Reproduce the Bug or Issue

Move the connection arrow above the node.

### Expected behavior

It worked well in the 11.9.4
[expected-arrow-behavior.webm](https://github.com/xyflow/xyflow/assets/91005914/d306d1ea-df3d-42b6-8288-881f28cf4e8c)

### Platform

- OS: Linux
- Browser: Chrome
- Version: 11.10.1

### Additional context

Thank you for the helping, I'm happy to using your product. :)

**Comment by moklick** [comment]
could you create a codesandbox for this? https://new.reactflow.dev

**Comment by Ankoge** [comment]
> could you create a codesandbox for this? https://new.reactflow.dev

Tried to reproduce the issue in sandbox but it was beyond my skills. Also my collage find the source of the problem. We maybe used the custom node in a wrong way:
```javascript
<Box className="node">
      <Handle
        isConnectable={isConnectable}
        position={Position.Top}
        style={{
          ...handleStyle,
          //display: source !== id && source ? undefined : 'none',
          position: 'absolute',
        }}
        type="target"
      />
      <Handle
        isConnectable={isConnectable}
        position={Position.Bottom}
        style={{
          ...handleStyle,
          position: 'absolute',
          display: source ? 'none' : undefined,
        }}
        type="source"
      />
    </Box>
```
The commented line was the problem, it interfered with the new version. Now its work properly.

**Comment by moklick** [comment]
I am glad you could fix it :)
