### ISSUE TITLE
Dnd kit problem with component dragging and positioning

### ISSUE THREAD

**Issue by adevadev** [xyflow/xyflow#3768]
### Describe the Bug

Hey everyone!

Thank you for building React Flow! I have just started using it and I like it very much, I have to say!
Additionaly I'm using [dnd kit](https://dndkit.com) in order to create a sortable list within a custom node of a react flow. So basically I would like to drag and drop, and to reorder the content inside of the React Flow node.

However, when I start dragging the components, the dragging occurs below the node. You have to drag the mouse pointer in the far top left corner of the canvas in order to see the currently dragged element and to be able to release it. Something's not right with the coordinates. 

See this screenshot for reference:
![20240105-224205Part](https://github.com/xyflow/xyflow/assets/151959615/5f2628f5-41b7-458a-95e8-0ce3c5e1c673)

I believe that [issue 3553](https://github.com/xyflow/xyflow/issues/3553) is facing a similar problem, using another library. In the other issue @moklick asked for an example, so I have created [a codesandbox](https://codesandbox.io/p/sandbox/react-flow-drag-and-drop-3qrygt) for that.

Do you have any suggestions on how to fix that?

Greetings

adevadev

### Your Example Website or App

https://codesandbox.io/p/sandbox/react-flow-drag-and-drop-3qrygt

### Steps to Reproduce the Bug or Issue

Follow the codesandbox example, please.

### Expected behavior

As a user I would like to drag and drop the elements of the node without any mouse pointer issues.

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [120.0.6099.200]

**Comment by moklick** [comment]
This is not really an issue with React Flow but about the usage of dnd-kit. I haven't used the library, but I could find an issue about [using dnd kit in a transformed container](https://github.com/clauderic/dnd-kit/issues/464#issuecomment-1008316262), that recommended to render the DragOverlay outside of the transformed parent container, like this:

```js 
<>
...
  {createPortal(
     <DragOverlay>
       {activeId ? <Item id={activeId} /> : null}
     </DragOverlay>,
     document.body
  )}
<>
```

**Comment by adevadev** [comment]
Ok, thank you for your quick answer. This was very helpful indeed! I think I would not have figured that out on my own.
It's working much better now.

The only thing that's not working well is the size of the element that I am dragging, it's a little too small, see:
![20240108-225445-Part](https://github.com/xyflow/xyflow/assets/151959615/7859aeba-cf71-471e-8a57-1eead1f80f83)

It seems to be working at a different zoom level, though, see:
![20240108-225623-Part](https://github.com/xyflow/xyflow/assets/151959615/73e4de34-7698-4a8a-aec2-4585828bcc31)

Would you say that the approach https://reactflow.dev/examples/interaction/contextual-zoom is promising? Is that how I can track the current zoom factor for a node respectively the ReactFlow component? I would need to figure out a way to pass the current zoom level to the drag container of the library dnd kit, of course. Could you point me in the right direction to solve that, please?


Greetings

adevadev

**Comment by moklick** [comment]
I would try to solve this with the help of people who use dnd kit. Maybe you can try to re-activate this issue: https://github.com/clauderic/dnd-kit/issues/50
