### ISSUE TITLE
<Control/> doesn't propogate aria-label

### ISSUE THREAD

**Issue by marchingband** [xyflow/xyflow#3775]
### Describe the Bug

docs state "Additionally, the <Controls /> component accepts any prop valid on a div element."
But aria-label does not end up in the DOM

### Steps to Reproduce the Bug or Issue

...

### Expected behavior

...

### Platform

...

**Comment by moklick** [comment]
Thanks for the report. I think the docs are wrong here. We will check it.

Why would you want to pass an aria-label to the controls? The whole space is taken by buttons and you can pass aria-labels to those elements.

**Comment by marchingband** [comment]
aria-label is required on toolbars when there is more then one on the page, to distinguish them.

**Comment by marchingband** [comment]
I also wrapped the buttons in react-aria toolbar to provide keypress requirements, mentioning as you might consider integrating it, it's a fantastic project from adobe.

**Comment by marchingband** [comment]
No problem! Thanks so much.

**Comment by moklick** [comment]
This is supported since React Flow 12!

If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12
