### ISSUE TITLE
v12: Edge Always Connects to First of Multiple Target Handles

### ISSUE THREAD

**Issue by clarkmcc** [xyflow/xyflow#3787]
### Describe the Bug

I upgraded my app from v11 to v12 and edges started always connected to the first handle on the same side, even though the IDs and everything were correct. After reverting back to v11, my edges were connecting to the correct handles again. I inspected the edge data in both cases, and the target/source targetHandle/sourceHandle were all the expected values so this appears to be a bug.

I do not have a reproduction, but would be happy to make one if needed. If the bug is an obvious one, I didn't want to take the time to build out a reproduction. Just let me know!

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

Create two nodes, one with multiple unique handles. Create an edge connecting the first node, to the second node's second handle. The edge will draw to the first handle. This works with any number of handles. If I have 10 handles, and create an edge to the last one, it always goes to the first one.

### Expected behavior

I would expect the edges to connect to the correct handles as defined in the EdgeParams

### Platform

- OS: macOS
- Browser: Chrome
- Version: 120.0.6099.199

**Comment by moklick** [comment]
Hey! Thanks for checking v12 :) 

I can't reproduce your issue. Does this example help: https://codesandbox.io/p/sandbox/reactflow-dark-mode-forked-2yhyrp?file=/src/Flow.tsx:69,5 ?

**Comment by clarkmcc** [comment]
Thanks for investigating! I'll work on a reproduction then. 

If it makes a difference, my edges define both a sourceHandle and a targetHandle since there could be multiple source handles as well.

Any ideas what could cause the same application code to work on v11 and not work on v12? I read through the migration guide but didn't see anything about creating edges differently.

**Comment by moklick** [comment]
There shouldn't be any edge creation changes, so you might found a bug here. Are you using the latest version 12.0.0-next.6? (We are not using the npm "next" tag anymore, since there are no versions below 12 next).

**Comment by jbownzino** [comment]
@clarkmcc How did you upgrade to v12 without it being published? I want to try it out and see some of the new functionality.

**Comment by clarkmcc** [comment]
I followed the guide here https://github.com/xyflow/xyflow/discussions/3764

Which has you install a different library name basically.

**Comment by jbownzino** [comment]
Thank you so much @clarkmcc!

**Comment by clarkmcc** [comment]
I ended up rewriting large portions of my application and I don't have this issue anymore. Must have been something on my side.
