### ISSUE TITLE
How to get Reactflow bounding co-ordinates based on zooming or onPaneMove.

### ISSUE THREAD

**Issue by ajaysanthoshb** [xyflow/xyflow#3801]
**Requirement:**
If we get Bounding points of `reactflow canvas` then we can selectively display `visible nodes and edges` by checking each node to determine if it lies within the specified bounding region based on the node's position. It can enhance UI perf when it comes to rendering 1000s of `custom nodes`.

<img width="1553" alt="Screenshot 2024-01-16 at 10 54 37 PM" src="https://github.com/xyflow/xyflow/assets/63867660/3b547b22-5a9b-44ae-94b8-c2d8c9df0256">

**Comment by moklick** [comment]
You could use the prop `onlyRenderVisibleElements` or if you want to find out by yourself:

```js
const width = useStore(s => s.width);
const height = useStore(s => s.height); 
const isNodeWithinViewport = isNodeIntersecting({ id: 'node-id' }, { x: 0, y: 0, width, height })
```

https://reactflow.dev/api-reference/types/react-flow-instance#is-node-intersecting
