### ISSUE TITLE
disableKeyboardA11y property of <ReactFlow /> is different in Docs

### ISSUE THREAD

**Issue by andyflight** [xyflow/xyflow#3802]
### Describe the Bug

I needed `disableKeyboardA11y` in my project, but when I looked at all the properties in the [< ReactFlow/> Keyboard props](https://reactflow.dev/api-reference/react-flow#disabled-keyboard-a11y) documentation, it was listed as `disabledKeyboardA11y`. Difference in the letter 'd'. This issue is minor, but I had to think a little about why I could not use disabledKeyboardA11y

### Steps to Reproduce the Bug or Issue

1. Go to the [docs](https://reactflow.dev/api-reference/react-flow#disabled-keyboard-a11y),
2. Try to use that property
3. See that property does not exist

### Expected behavior

Please fix that, cause it a little bit weird :(

### Screenshots or Videos

![image](https://github.com/xyflow/xyflow/assets/53275456/cb7fed8b-cbdf-4836-adf5-7e990cc3ef7a)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
good catch, thanks!
