### ISSUE TITLE
The property 'focusable' of Node type doesn't exist

### ISSUE THREAD

**Issue by stephane** [xyflow/xyflow#3813]
### Describe the Bug

The template of issue tracker mentions v11 and react-flow so I hope it's the proper place to report issue with @xyflow/svelte.

The documentation https://svelteflow.dev/api-reference/types/node contains a 'focusable' property but it is not present in the Fields section of the same page.

The property is not declared in the `svelte/src/lib/components/NodeWrapper/types.ts` and TS raises an error if I try to use it.

### Steps to Reproduce the Bug or Issue

The Node type of '@xyflow/svelte' doesn't accept the 'focusable' attribute.

```typescript
export type AssessmentLane = {
	label: string;
	name: string;
	// Y position (top)
	y: number;
	// Distance with spacer
	height: number;
};
export type MtdsLane = Node<AssessmentLane>;

export function getMtdsLane(assessment: Assessment, assessmentLane: AssessmentLane): MtdsLane {
	const node: MtdsLane = {
		id: assessmentLane.name,
		type: 'group',
		data: assessmentLane,
		position: { x: assessment.x, y: assessmentLane.y },
		style: `width: ${assessment.width}px; height: ${assessmentLane.height}px;`,
		draggable: false,
		selectable: false,
		connectable: false,
		deletable: false,
		focusable: false, // VSCode underlines in red
		zIndex: -1000
	};
	return node;
}
```

### Expected behavior

The attribute should be exposed.

### Platform

"@xyflow/svelte": "0.0.33",

**Comment by moklick** [comment]
Thanks! I updated the docs. `focusable` is not part of the Node type yet.
