### ISSUE TITLE
Edges not rendered when persisting state and onlyRenderVisibleElements

### ISSUE THREAD

**Issue by cfrog1** [xyflow/xyflow#3816]
### Describe the Bug

Hi there!

I'm using zustand for state management, and zustand's `persist` to store the state in `sessionStorage`. 

I also have `onlyRenderVisibleElements` set in ReactFlow.

After a refresh, if a visible node has an edge connected to a node that is offscreen, then the edge will not render.

This fixes itself once I pan or zoom to include the offscreen node. 

I've added a CodeSandbox based on the example shown here: https://reactflow.dev/learn/advanced-use/state-management#create-a-store

The only changes I made were to move the nodes further to the left and right, add `onlyRenderVisibleElements`, and enable `persist` in the zustand store. 

Thanks!

### Your Example Website or App

https://codesandbox.io/p/sandbox/epic-dust-f8zwhs?file=%2Fstore.ts

### Steps to Reproduce the Bug or Issue

1. Go to https://codesandbox.io/p/sandbox/epic-dust-f8zwhs?file=%2Fstore.ts
2. Refresh 

### Expected behavior

I expect to see the edges connecting to offscreen nodes. The edges are visible with `persist` enabled and `onlyRenderVisibleElements` disabled, with `persist` disabled and `onlyRenderVisibleElements` enabled, but not with both enabled. 

### Screenshots or Videos

Initial render:

![image](https://github.com/xyflow/xyflow/assets/52989588/5bafa25e-c3f6-4827-8161-1899592ce852)

After zooming out:

![image](https://github.com/xyflow/xyflow/assets/52989588/23ab1a45-dc39-4e74-b28d-6bbd0f470fb1)

### Platform

All

**Comment by moklick** [comment]
The issue occurs, because the nodes `width` and `height` attributes are stored too. You can solve it by passing a [`reviver` function](https://docs.pmnd.rs/zustand/integrations/persisting-store-data#createjsonstorage) to filter them:  https://codesandbox.io/p/sandbox/inspiring-monad-46jhr3?file=/store.ts:50,4-59,6



I will check if we can solve this on library side in v12.

**Comment by cfrog1** [comment]
Sorry yes it did!! Thank you so much for figuring that one out! Performance is now amazing!
