### ISSUE TITLE
Delete edge

### ISSUE THREAD

**Issue by infu** [xyflow/xyflow#3831]
### Describe the Bug

It's weird that most examples don't include delete edge when it's supposed to be one of the most basic actions in this setting.
Even this dedicated to edge deleting page doesn't work: https://reactflow.dev/examples/edges/delete-edge-on-drop

### Steps to Reproduce the Bug or Issue

go to the main site
can't find edge deletion

### Expected behavior

to delete the edge

### Platform

any

**Comment by infu** [comment]
Actually right after posting I managed to delete the edge. There are 5 pixels where the edge move handle is and when someone manages to see that, they can delete it. This needs some improvement

**Comment by moklick** [comment]
Edge deletion is built in. You need to select an edge (or a node with a connected edge), and press Backspace (`deleteKeyCode`) to delete one or multiple edges. 

You can also add functionality on top like the example above ([delete on edge drop](https://reactflow.dev/examples/edges/delete-edge-on-drop)) or add a button for deleting an edge as seen in the [custom edges example](https://reactflow.dev/examples/edges/custom-edges).

**Comment by infu** [comment]
Thanks, backspace makes sense. I feel dumb for not trying it out and hitting "del" key instead. But I imagine some users won't be able to do it too. Is there any way I can add 'Del' key to do the same ?

**Comment by moklick** [comment]
You can pass a `deleteKeyCode` prop to the `<ReactFlow />` component https://reactflow.dev/api-reference/react-flow#delete-key-code
