### ISSUE TITLE
Error: Cannot find module 'node-sass'

### ISSUE THREAD

**Issue by shubhanshusingh** [xyflow/xyflow#3832]
### Describe the Bug

```
ERROR in ../../../reactflow/dist/style.css
Module build failed (from ../../../mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../../sass-loader/dist/cjs.js):
Error: Cannot find module 'node-sass'
```

how to fix above error for react project!

### Steps to Reproduce the Bug or Issue

```
<ReactFlow
                                        nodes={initialNodes}
                                        edges={initialEdges}
                                    />
```

### Expected behavior

I installed reactflow with my react (18.0.0), unable to display reactflow as per node-sass not found error

### Platform

- OS: MacOS
- Browser: Chrome

**Comment by moklick** [comment]
This doesn't look like a React Flow issue. We are just serving plain CSS. Did you try to install node-sass?
