### ISSUE TITLE
Clicking on a node triggers onNodesChange unnecessarily, resulting in unwanted `nodes` array recreation

### ISSUE THREAD

**Issue by stanislav-grin** [xyflow/xyflow#3833]
### Describe the Bug

I've observed an issue where clicking any node (without dragging it) triggers the onNodesChange callback from useNodesState. The callback provides the following argument:
```js
[
  {
    "id": "2",
    "type": "position",
    "dragging": false
  }
]
```

This behavior leads to the recreation of the nodes array within useNodesState, causing unintended side effects. For instance, in my scenario, it results in unnecessary server calls to save the entire flow due to the tracking mechanism that detects changes in the nodes list.

The problem arises when various scenarios involve clicking a node, such as opening its configuration or interacting with control icons. These clicks should not trigger changes in the nodes array. Currently, any click event on a node results in the recreation of the nodes array.

### Your Example Website or App

https://codesandbox.io/p/sandbox/eager-morse-gpw2mn?file=%2FApp.js%3A34%2C24

### Steps to Reproduce the Bug or Issue

I've reproduced this issue in the "Feature Overview" sample by modifying the code as follows:

```js
  const [nodes, setNodes, onNodesChange2] = useNodesState(initialNodes);
  ...

  const onNodesChange = useCallback((changes) => {
    console.log('onNodesChange: ', changes)

    onNodesChange2(changes)
  }, [onNodesChange2])

  useEffect(() => {
    console.log('nodes changed')
  }, [nodes])
```

STR:
- Open the example.
- Open the browser's console to view logs.
- Click any node (without dragging it).

ACR:
- see `console.log('onNodesChange: ', changes)` fired, after this `nodes` changed and `useEffect` triggered.

### Expected behavior

Clicking on a node should not trigger the onNodesChange callback unless it directly causes a change in node selection. Currently, onNodesChange incorrectly indicates that the node's position has been changed.

### Platform

- `reactflow` version: v11.9.2

**Comment by moklick** [comment]
Easiest way to fix this is to set `nodeDragThreshold={1}` https://reactflow.dev/api-reference/react-flow#node-drag-threshold (this is also the new default in the next major release).

**Comment by stanislav-grin** [comment]
Thank you very much for the prompt response!

Your suggestion was very helpful. Following your advice, I encountered a new challenge where it became impossible to select a node by clicking on it (as `onSelectionChanged` was triggered only during node dragging). However, I managed to resolve this by implementing custom logic for handling node selection. I now listen to `onNodeClick`, maintain the selected node's ID, and reset it when clicking on the pane or pressing ESC.

This is just for informational purposes, but I want to confirm that my initial issue has been successfully resolved. Thank you for your assistance!

**Comment by moklick** [comment]
I can't reproduce your issue. Everything looks good here https://codesandbox.io/p/sandbox/loving-cherry-mn9rmj?file=/App.js:77,1-79,1 - nodeDragThreshold = 1 and selection events are fired / handlers are called.

**Comment by moklick** [comment]
please re-open if the issue persists.

**Comment by bilal-uforia** [comment]
> Easiest way to fix this is to set `nodeDragThreshold={1}` https://reactflow.dev/api-reference/react-flow#node-drag-threshold (this is also the new default in the next major release).

Not working @moklick the example also logg on node change when we click on the node

**Comment by bcakmakoglu** [comment]
@bilal-uforia That is because clicking a node selects it and a selection *is a change*.
A position change won't happen unless you drag a node more than 1px (which was the problem in OPs post).

**Comment by bilal-uforia** [comment]
> @bilal-uforia That is because clicking a node selects it and a selection _is a change_. A position change won't happen unless you drag a node more than 1px (which was the problem in OPs post).

Is it possible to not make fire selection change when node is clicked ?

**Comment by bcakmakoglu** [comment]
There's no prop to disable that but you can hook into `onNodesChange` yourself and drop selection changes you don't wanna apply.

**Comment by bilal-uforia** [comment]
@bcakmakoglu  onNodeChange , when I add the object I dont get the add  change instead I get the dimension change ?

**Comment by bcakmakoglu** [comment]
`add` changes are only triggered if you use the [`addNodes` ](https://reactflow.dev/api-reference/types/react-flow-instance#add-nodes) helper. If you just add a node with a setter of `useState` or something (which `useNodesState` uses internally as well) it won't get triggered.
`dimensions` are always pushed when a node is rendered initially.

**Comment by bilal-uforia** [comment]
Oh Ok Thankyou,  I have  one more question doing this : 
const customInputUpdate = (input, input_html) => {
        let currentNode = getNode(id);
        let {inputs = {}} = currentNode?.data;
        updateNodeData(id, {
            inputs: {
                ...inputs,
                [layer?.id]: {input, input_html}
            }
        })

    }
the change I get is "replace" not update why ?
