### ISSUE TITLE
Preview connection of FloatingEdge bug

### ISSUE THREAD

**Issue by jnoerm19** [xyflow/xyflow#3843]
### Describe the Bug

I have this bug when I want to connect two nodes. The preview of the edge is correct until a targetNode is hovered. So basically, when a possible targetNode is hovered when a connection is in progress, the target position of the edge (ONLY in the preview) is incorrect.

I am using reactflow v. 11.10.3

Please see this video as an example of the bug. The FloatingEdge is taken from your example.

https://github.com/xyflow/xyflow/assets/60742511/207fe346-d93e-4b30-bb34-6df3f56e0207

### Steps to Reproduce the Bug or Issue

*

### Expected behavior

*

### Platform

- OS: [Windows]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by jnoerm19** [comment]
NOTE: The issue is not present in v. 11.8.3. The issue began after upgrading to version 11.10.3 from 11.8.3

**Comment by moklick** [comment]
thanks, we will check it.

**Comment by moklick** [comment]
Can you create a codesandbox or repo so that we can reproduce it?

**Comment by jnoerm19** [comment]
https://codesandbox.io/p/sandbox/connect-floating-edge-bug-hknj23?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsiopl7n0006356gqjwxna7d%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsiopl7n0002356glhhqna6i%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsiopl7n0003356ghphiq9dg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsiopl7n0005356geuzsvzl4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsiopl7n0002356glhhqna6i%2522%253A%257B%2522id%2522%253A%2522clsiopl7n0002356glhhqna6i%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsiq0egb0002356gagv6drmx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A9%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fnode%252FCustomNode.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsiq0egb0002356gagv6drmx%2522%257D%252C%2522clsiopl7n0005356geuzsvzl4%2522%253A%257B%2522id%2522%253A%2522clsiopl7n0005356geuzsvzl4%2522%252C%2522activeTabId%2522%253A%2522clsiq9w0k001m356gr3kuqglc%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clsiq5r0w00cn356gcgjow3ka%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clsiq9w0k001m356gr3kuqglc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clsiopl7n0003356ghphiq9dg%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsiopl7n0003356ghphiq9dg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by jnoerm19** [comment]
I noticed an issue with my custom node, setting the display: none property of the target handle, which I can see has been deemed wrong in the later versions of reactflow, so all good now :)
