### ISSUE TITLE
Accessibility- 'title' tooltip does not show for tab nav users on ControlButton component

### ISSUE THREAD

**Issue by DanielleCogs** [xyflow/xyflow#3847]
### Describe the Bug

Button description does not show on the Controls bar ControlButtons when using tab navigation (only shows on mouse hover). Looked through the [code](https://github.com/xyflow/xyflow/blob/v11/packages/controls/src/Controls.tsx) and looks like with the built-in buttons, the button description is passed as a 'title', but this doesn't show the tooltip with tab nav. See here https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#accessibility_concerns .

### Steps to Reproduce the Bug or Issue

1. Hover over Control component and see tooltip for buttons
2. Tab navigate through the Control buttons and see tooltip does not show

### Expected behavior

Could we create a tooltip to show the description with tab navigation?

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

Bug filed by our accessibilty assessment team here https://github.com/Azure/LogicAppsUX/issues/4043

**Comment by moklick** [comment]
Hey @DanielleCogs thanks for bringing this up. Better a11y defaults are important for us and we will check how/if we can support this. We don't want to provide too much UI stuff, but maybe there is a way to integrate a lightweight tooltip for the controls.

**Comment by DanielleCogs** [comment]
Thank you @moklick! Will be following to see what we can do on this!

**Comment by moklick** [comment]
The title attribute was added for screenreaders. If you want to display a tooltip for focused controls, you would need to implement your own controls.
