### ISSUE TITLE
Controlled Zoom

### ISSUE THREAD

**Issue by nartydev** [xyflow/xyflow#3854]
### Please describe the feature that you want to propose

Hello,
I would like to be able to outsource reactflow zoom, all the functions that concern zoom are great, but with the getZoom() function we have no reactive effect

It's possible to make a props "onZoomChange" to always be up to date with the internal state

Thanks,

**Comment by bcakmakoglu** [comment]
You might wanna take a look at [`useOnViewportChange`](https://reactflow.dev/api-reference/hooks/use-on-viewport-change)

```ts
import { useCallback } from 'react';
import { useOnViewportChange } from 'reactflow';

/* This is the shape of the Viewport type
type Viewport = {
  x: number;
  y: number;
  zoom: number;
};
*/

function ViewportChangeLogger() {
  useOnViewportChange({
    onStart: (viewport: Viewport) => console.log('start', viewport),
    onChange: (viewport: Viewport) => console.log('change', viewport),
    onEnd: (viewport: Viewport) => console.log('end', viewport),
  });
 
  return null;
}
```

**Comment by moklick** [comment]
you could also subscribe to the current zoom level by using the `useStore` hook:

```js
const zoom = useStore(s => s.transform[2]);
```
