### ISSUE TITLE
ResizerObserver loop completed with undelivered notifications when resizing nodes

### ISSUE THREAD

**Issue by osama095** [xyflow/xyflow#3857]
### Describe the Bug

When resizing a group node, on resize we see lots of errors on the console saying "ResizerObserver loop completed with undelivered notifications." We have a onNodesChange callback that sets the node changes into YJS because we're using collaborative editing.

### Steps to Reproduce the Bug or Issue

1. Create a Resizable node with a line style set such that there's a think border for the line.
2. Resize the node
3. Observe the logs in the console

### Expected behavior

As a user, I expected the node to resize without warnings.

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/141874706/09efcae7-ee4f-4ce1-b36f-8d40d47b9e68

### Platform

- OS: macOS
- Browser: Brave
- Version: 1.62.153

**Comment by moklick** [comment]
could you create a codesandbox or send a repo that reproduces this issue? Is it possible, that is has something to do with "react-beautiful-dnd"?

**Comment by osama095** [comment]
Hi @moklick. Thank you so much! I took out the component that was using react-beauitful-dnd and it seems that fixes the issue. Any ideas why reactflow could be interfering with this library? We are not re-rendering the component that uses dnd.

**Comment by moklick** [comment]
That's hard to tell, because I don't know the implementation details here. I would try to restructure the custom node so that the react-beautiful-dnd stuff won't get re-rendered when the node gets resized. For that you would put it in another memoized component. Does it help?

**Comment by osama095** [comment]
@moklick Thank you. We can close this issue as it seems the error is not related to reactflow. Thank you for your support!

**Comment by DavdGao** [comment]
> @moklick Thank you. We can close this issue as it seems the error is not related to reactflow. Thank you for your support!

@ghostdevv The same error happens to me. Have you any suggestions or solutions? thanks
