### ISSUE TITLE
Can't click on an edge if parallel/close edges border it on both sides.

### ISSUE THREAD

**Issue by tamszod** [xyflow/xyflow#3860]
### Describe the Bug

I have a feature where if you click on an edge an action is triggered. My problem is that if 3 edges are close to each other the middle one can not be clicked, because it detects the top or bottom one. Is there a way to reduce an edge click detection area so the onClick event can be used in such cases? 

### Steps to Reproduce the Bug or Issue

1. Create 2 nodes with 3-3 target and source handles close to each other.
2. Create 3 edges connecting the nodes.

### Expected behavior

Clicking the middle edge should be impossible because you are either clicking the top or the bottom one.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
You can set the clickable edge width with the `interactionWidth` edge option: https://reactflow.dev/api-reference/types/edge#interaction-width

```js
const defaultEdgeOptions = {
  interactionWidth: 4
};
```
