### ISSUE TITLE
Feature request: option to position handle at `LeftTop`、`LeftButton`、`RightTop`、`RightButton`

### ISSUE THREAD

**Issue by li-jia-nan** [xyflow/xyflow#3862]
### Please describe the feature that you want to propose

![image](https://github.com/xyflow/xyflow/assets/49217418/3ffd3e47-198f-4ea7-a78a-599f5291975c)

api:

```ts
export enum Position {
  // old values
  Left = "left",
  Top = "top",
  Right = "right",
  Bottom = "bottom",

  // new values
  LeftTop = "left-top",
  RightTop = "right-top",
  LeftBottom = "left-bottom",
  RightBottom = "right-bottom"
}
```

**Comment by mtrucc** [comment]
This is a really cool idea, you can submit a PR

**Comment by bcakmakoglu** [comment]
I'm not sure what this is solving though - this is already possible with very minor CSS tweaks on the user-side and imo doesn't require an additional option from the library to solve.

All you need to do is overwrite `top` `left` `right` `bottom` if necessary.

```cs
.react-flow__handle {
	// your styles
}
```

The `Position` is mainly used to determine at what angle an edge goes to a handle - a `LeftTop` position would just make this more confusing as it would imply the edge goes to the *left* and *top* when in reality in can only align to *one* side and not multiple - which side do we choose here now? Top? Left?

Imo, this would just be overcomplicating things.

**Comment by li-jia-nan** [comment]
Yes, I have implemented it this way, but I want these options to be preset in reactflow, If you think this is not necessary, then I implement it myself.

**Comment by Himeshqik** [comment]
left bottom is not working
