### ISSUE TITLE
Feature request: export `onToggleInteractivity` helper function from `useReactFlow` hook

### ISSUE THREAD

**Issue by li-jia-nan** [xyflow/xyflow#3863]
### Please describe the feature that you want to propose

expected api：

```ts
const { setViewport, zoomIn, zoomOut, ..., onToggleInteractivity } = useReactFlow();
```

**Comment by moklick** [comment]
There is a `onInteractiveChange` callback for the `Controls` component https://reactflow.dev/api-reference/components/controls. Does that help?

**Comment by li-jia-nan** [comment]
Thanks for your reply, I want to customise the style of the `Controls`, I'm afraid this callback doesn't help me, I need a click event.

<img width="442" alt="image" src="https://github.com/xyflow/xyflow/assets/49217418/0821d94a-ea58-4fcc-84ae-71609895ae0d">

**Comment by moklick** [comment]
What exactly do you need? `onInteractiveChange` gets called when a user clicks the button with the lock.

**Comment by li-jia-nan** [comment]
Sorry I'm not good at English, There's an internal method `onToggleInteractivity` in `<Controls />` that can actually do the `setState` things. If it's exported by `useReactFlow`, I can call this function to control the state of the lock button. ...we may rename it to `toggleInteractivity` when exporting to satisfy the naming convention.

**Comment by moklick** [comment]
ah, now I get it :) The interactivity control is a bit random and I am not sure if we should consolidate this feature any further. Currently the interactivity button is unlocked when `nodesDraggable || nodesConnectable || elementsSelectable`. This means that you could add those props to your store (or local component state) to control the button state:

```js 
const [flowInteractive, setFlowInteractive] = useState(false);


<ReactFlow
  nodesDraggable={flowInteractive}
  nodesConnectable={flowInteractive}
  elementsSelectable={flowInteractive}
 ...
```

Does this help?

**Comment by li-jia-nan** [comment]
Yes I have solved it, thank you for your answer
