### ISSUE TITLE
Svelte - Minimap - Background Color

### ISSUE THREAD

**Issue by Uhrendoktor** [xyflow/xyflow#3864]
### Describe the Bug

Svelte Flow's Minimap Plugin currently ignores its prop `bgColor`. The component sets the user defined color as `--xy-minimap-background-color-props={bgColor}` css variable on the child element of the minimap's background. The parent div has the class `svelte-flow__minimap`, which correctly uses `--xy-minimap-background-color-props` for it's background color. But because of css variables scoping properties the parent element is unable to access the variable.

Either the class tag or the css variable could be moved to correct this issue, though I am unsure which approach aligns better with React's implementation.

### Steps to Reproduce the Bug or Issue

```typescript
<MiniMap
        bgColor={"#ff0000"}
/>
```

### Expected behavior

as described above

### Platform

all

**Comment by peterkogo** [comment]
Thanks for the report, this should be fixed in the upcoming update
