### ISSUE TITLE
Selecting multiple nodes with box selector does not trigger callback registered in useOnSelectionChange 

### ISSUE THREAD

**Issue by Kallekro** [xyflow/xyflow#3870]
### Describe the Bug

The callback registered as onChange in the hook useOnSelectionChange is not called when multiple nodes are selected with the box selector. 
It works as expected when selecting individual nodes by clicking. It is also called when unselecting the nodes selected by the box selector.

The workaround is to not use the hook and instead implement the onSelectionChange function for the ReactFlow object. 

### Steps to Reproduce the Bug or Issue

1. Register a callback with the useOnSelectionChange.
2. Set breakpoint in callback function.
3. Use box selector to select multiple nodes, and see that the execution is not stopped at the breakpoint.

### Expected behavior

I expected that the function would be called with all the selected nodes and edges selected in the box selection.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 11.10.1

**Comment by moklick** [comment]
Hey @Kallekro 

I can't reproduce this. Could you create a repo or codesandbox?

**Comment by goliney** [comment]
I was able to reproduce the issue with the example @terheide provided.

**Comment by moklick** [comment]
You need to wrap the passed onChange function with `useCallback` (or define it as a store action or outside the render function). Otherwise, you will add a new handler on every render which breaks the expected behaviour. 

Fixed example: https://codesandbox.io/p/sandbox/node-and-edges-selection-forked-69xk39?file=/App.tsx:13,22

**Comment by terheide** [comment]
Thanks @moklick.
