### ISSUE TITLE
Is there any Feature like when two edges are intersect each other then intersection point should be shown as broken lines or semicircles in version 11

### ISSUE THREAD

**Issue by sudarsanarao995** [xyflow/xyflow#3880]
### Please describe the feature that you want to propose

that intersection point is not looking good in flow , so is it possible that intersection point should be shown as broken lines or semicircles ?
![image](https://github.com/xyflow/xyflow/assets/147405464/c26518a3-bb41-47e2-a2c5-071b367db80e)

**Comment by moklick** [comment]
not a built-in feature and not planned - duplicate of #3859

**Comment by sudarsanarao995** [comment]
@moklick  Is there any Planned to built this feature in version 12 ?

**Comment by moklick** [comment]
no, this is not planned.
