### ISSUE TITLE
`@default` JSDocs values for `minZoom` and `maxZoom` are outdated

### ISSUE THREAD

**Issue by snelsi** [xyflow/xyflow#3881]
### Describe the Bug

I'm using `@xyflow/react` version `12.0.0-next.8`.
In `ReactFlowProps` interface declaration:

```tsx
  /** Minimum zoom level
   * @default 0.1
   */
  minZoom?: number;
  /** Maximum zoom level
   * @default 1
   */
  maxZoom?: number;
 ```
 
 But actual default values in `ReactFlow` component are different:
![image](https://github.com/xyflow/xyflow/assets/15171036/4c3b5b50-bdb6-4321-947c-3f38d86ef079)

It's a bit confusing when you try to adjust the 'default' value slightly, but get a completely different result.

### Expected behavior

JSDocs values are out of date. Update them to show latest values

**Comment by moklick** [comment]
Thanks! will be fixed in the next release.
