### ISSUE TITLE
[Beta] Version 12 beta 8 regression from beta 7

### ISSUE THREAD

**Issue by sroussey** [xyflow/xyflow#3884]
### Describe the Bug

Edge thinks it exists, but doesn't show. Shows in v12beta 7 as expected, just not in beta 8

### Steps to Reproduce the Bug or Issue

```
clone https://github.com/sroussey/ngraph.git
cd ngraph
npm i
npm run build-storybook
npm run storybook
```

### Expected behavior

Go to http://localhost:6006/?path=/story/node-graph-editor--input-groups (choosing the story InputGroups)
Note the edge I selected:

<img width="542" alt="image" src="https://github.com/xyflow/xyflow/assets/127349/2b4508b0-dae3-44d0-bc64-e005e479e8f1">

Now stop storybook (important not to use cached old version) and update xyflow/react to beta 8

```
npm i @xyflow/react@12.0.0-next.8
npm run storybook
```
Note that the edge is missing:

<img width="542" alt="image" src="https://github.com/xyflow/xyflow/assets/127349/613ab333-89d7-4dfd-86b1-74f2a69dfdd8">

This is what it looks like when there is no actual edge (I recreate and then delete it)

<img width="542" alt="image" src="https://github.com/xyflow/xyflow/assets/127349/7537e93a-e2a3-4d25-bc62-b53aab2c14e2">

### Platform

- OS: MacOS
- Browser: Chrome

newest stable of everything

**Comment by moklick** [comment]
Thanks we will check it!

**Comment by sroussey** [comment]
Ah, that makes sense. Will fix. You might even generate a warning in the console.

This is a fork of [clarkmcc/ngraph](https://github.com/clarkmcc/ngraph.git). I should have used his url, but i was tired. But I am the second largest contributor to it. Also the second smallest, since there are only two.
