### ISSUE TITLE
How to use ReactFlowJsonObject

### ISSUE THREAD

**Issue by ulysse0** [xyflow/xyflow#3891]
Hi,

I would like to read an example of how do I use [ReactFlowJsonObject](https://reactflow.dev/api-reference/types/react-flow-json-object) for saving and loading diagrams (locally at first and in DB later). Exporting to JSON and importing it should create the exact same diagram, including styles.

Thanks

**Comment by bcakmakoglu** [comment]
[There's an example for that in the docs.](https://reactflow.dev/examples/interaction/save-and-restore)
