### ISSUE TITLE
Control+Backspace shortcut causes node deletion in Sveltekit application

### ISSUE THREAD

**Issue by mcmxcdev** [xyflow/xyflow#3895]
### Describe the Bug

Identical issue to https://github.com/xyflow/xyflow/issues/3328

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

Text input gets cleared rather than whole node removed

### Platform

-

**Comment by moklick** [comment]
good catch. It seems that Svelte Flow and React Flow v12 are not up to date with the latest changes here.

**Comment by mcmxcdev** [comment]
All clear, thanks for the quick fix!

Any ETA on a new release to pull from? We have a product launch in a couple of days and I would consider this to be a pretty bad bug for users to experience.

**Comment by moklick** [comment]
We will do a release tomorrow.

**Comment by moklick** [comment]
released in 0.0.36.
