### ISSUE TITLE
SvelteFlow useStore() width, height, and domNode stores are not updated

### ISSUE THREAD

**Issue by Sahasrara** [xyflow/xyflow#3900]
### Describe the Bug

I'm seeing the following always return default store values:
```
get(useStore().width) === 500
get(useStore().width) === 500
get(useStore().domNode) === null
```

These values never seem to change, but I think they're supposed to update dynamically. Please feel free to close this if I'm mistaken.

### Steps to Reproduce the Bug or Issue

Container.svelte
```
<SvelteFlowProvider>
    <Test/>
</SvelteFlowProvider>
```

Test.svelte
```
<script lang="ts">
import { useStore } from '@xyflow/svelte';

const { domNode, width, height } = useStore();

function test() {
    console.log($domNode);
    console.log($width);
    console.log($height);
}
</script>

<button on:click={test}>Test</button>
<SvelteFlow>
    <Controls />
    <Background />
    <MiniMap />
</SvelteFlow>
```

### Expected behavior

I think domNode should be the root div for SvelteFlow, width should update dynamically, and so should height. At least that's how it looks in SvelteFlow.svelte.

### Platform

- OS: Windows
- Browser: Electron
- Version: ^28.1.1

**Comment by moklick** [comment]
I can't reproduce it: https://stackblitz.com/edit/svelte-flow-ts-bjp5ys?file=src/App.svelte,src/Flow/index.svelte

**Comment by peterkogo** [comment]
You need to make a reactive statement otherwise you just print out the initial value

**Comment by Sahasrara** [comment]
Thank you so much for taking a look. This was my mistake. For posterity: 

I accidentally double wrapped a SvelteFlow in nested SvelteFlowProvider's
```
<SvelteFlowProvider>
    <SvelteFlowProvider>
        <SvelteFlow />
    </SvelteFlowProvider>
</SvelteFlowProvider>
```

I'm not sure how I missed that.
