### ISSUE TITLE
how to use setViewPort Methode then show this error

### ISSUE THREAD

**Issue by nkwoyce** [xyflow/xyflow#3901]
### Describe the Bug

Error: [React Flow]: Seems like you have not used zustand provider as an ancestor.

### Steps to Reproduce the Bug or Issue

setViewPort Methode then show this error

### Expected behavior

Error: [React Flow]: Seems like you have not used zustand provider as an ancestor.
Next JS Version :- 14.0.4
Node Version:- 20.1
React Version:- 18

### Platform

- OS: Linux
- Browser: [ Chrome]
- Version: [e.g. 24.2]

**Comment by bcakmakoglu** [comment]
You haven't used `ReactFlowProvider`, please read this section of the docs: https://reactflow.dev/learn/troubleshooting#warning-seems-like-you-have-not-used-zustand-provider-as-an-ancestor
