### ISSUE TITLE
SvelteFlow - on:nodedragstop is called even when dragging is disabled

### ISSUE THREAD

**Issue by Sahasrara** [xyflow/xyflow#3911]
### Describe the Bug

I think this is probably a small bug if it's unintended behavior. I've found that on:nodedragstop is called even when a node isn't draggable.

### Steps to Reproduce the Bug or Issue

1. Create a function that logs to console whenever on:nodedragstop fires
2. Create a node
3. Disable dragging for that node
4. Try to drag that node
5. You'll see an unexpected log in the console

### Expected behavior

I would not expect to see drag events when dragging is disabled.

### Platform

- OS: Windows
- Browser: Electron
- Version: 0.35

**Comment by peterkogo** [comment]
Thanks for the reporting, this will be fixed in the next release

**Comment by moklick** [comment]
should be fixed in 0.0.36
