### ISSUE TITLE
Edges on Node Handles source->source not rendering (sibling connection)

### ISSUE THREAD

**Issue by pubmp** [xyflow/xyflow#3916]
### Describe the Bug

When trying to connect nodes in a similar fashion as this example https://reactflow.dev/examples/nodes/shapes the edges are not rendered.
I found out it has to do with `Handle` component `type` prop, that is `source | target`.
I have the `pro version` and all the Handles are of type `source` and it somehow renders, but this is obviously not working when I try to build with webpack and add some more functionality on top of it. I think it is related to: https://github.com/xyflow/xyflow/issues/2429 validation.

I could add Nodes for all combinations of handles I use but it is CRAZY, is there some way how to make this work?

### Steps to Reproduce the Bug or Issue

write the code, build with webpack

### Expected behavior

it edges are rendered

### Platform

- OS: [e.g. macOS]
- Browser: [e.g. Chrome]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Are you using `connectionMode="loose"`  https://reactflow.dev/api-reference/react-flow#connection-mode

**Comment by pubmp** [comment]
> Are you using `connectionMode="loose"` https://reactflow.dev/api-reference/react-flow#connection-mode

Yes I do, I did refresh and clean the cache just to be sure - the edges[] are in the JS and look ok but not rendered - isn't there something else that interferes with this?

**Comment by pubmp** [comment]
Also, I do the thing with the `forwardRef` in order pass some state etc, is that related?
