### ISSUE TITLE
`you've created a new nodeTypes or edgeTypes` - troubleshooting#002 - React Strict Mode

### ISSUE THREAD

**Issue by avloss** [xyflow/xyflow#3923]
### Please describe the feature that you want to propose

Perhaps it's worth mentioning on https://reactflow.dev/learn/troubleshooting#002 page, or perhaps even in the error itself that `reactStrictMode` will cause this regardless of any other settings.

Please note:
https://nextjs.org/docs/pages/api-reference/next-config-js/reactStrictMode
```
Good to know: Since Next.js 13.4, Strict Mode is true by default with app router, so the above configuration is only necessary for pages. You can still disable Strict Mode by setting
```

And given how popular Next.js is, it'll be only expected that people will encountering this problem quite often when trying to use your great React component.

**Comment by moklick** [comment]
Fixed in React Flow 12! If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12
