### ISSUE TITLE
Render loop after v11.10.3 to  v11.10.4

### ISSUE THREAD

**Issue by tim-field** [xyflow/xyflow#3925]
### Describe the Bug

React becomes unresponsive with a render loop on the react-flow component.  I'll do some more digging to work out the cause but wanted to raise this now as its not something we expected with a minor upgrade. 

### Steps to Reproduce the Bug or Issue

Load react flow in v11.10.4 - graph is quickly unresponsive - `onNodesChange` callback is repeatedly called 
Revert to v11.10.3 - graph is happy.

### Expected behavior

A minor package update to not impact a react-flow install 

### Platform

- OS: macOS
- Chrome, Safari, Firefox
- latest 

### Additional context

We are pro users in a proprietary production context so will take me a while to get a reproduction

**Comment by moklick** [comment]
How can we reproduce this?

**Comment by noams-unbiased** [comment]
I am also experiencing the same issue. Endless loop caused in my case because the onNodesChange is called when it previously did not. This triggers a render of the graph in my code, which triggers the onNodesChange again.

**Comment by moklick** [comment]
Are you working with a custom `applyNodeChanges` function? Could you provide an example @noams-unbiased ?

**Comment by noams-unbiased** [comment]
My application is fairly large and proprietary so i cannot provide the actual code. However i can describe the issue with more detail:

On every [relevant] user interaction with the graph, i'm re-creating the nodes array. I've tried using the same array object and changing only some nodes, but then the graph does not re-render.

This means that if a node object is changed inside react-flow (i'm guessing this happens in your new sync code), the changes are not propagated to my nodes. 

When i get an 'onNodeChange' callback for a specific node type - i trigger a re-render which creates the re-creation of the node.

this is my simple onNodeChange function:
```
onNodesChange={(changes) => {
                changes.forEach((c) => c.type === 'position' && dragAnnotation(c));
                redrawAnnotations();
            }}
```
The `dragAnnotation` function simply changes the position of my internal annotation object.
The `redrawAnnotations` causes the graph to be re-rendered, with the new nodes array.

It seems like since version 10.4.0 the onNodeChange callback is called on the initial render of every node, which causes an endless loop.

**Comment by moklick** [comment]
Are you working with an uncontrolled flow or did you remove the other parts of the `onNodesChange` function? Which React version and which browser are you using?

**Comment by noams-unbiased** [comment]
i'm using react version 18 (though it functions as 17.. we are just beginning the transition to 18) 
running on latest chrome.

i'm not sure what you mean by 'removed the other parts of the onNodesChange function'? 
here's a simplified version of my code:
```
import ReactFlow from 'reactflow';

function RenderGraph() {
   const [nodes, setNodes] = useState([])

   const { aNodes, dragAnnotation, redrawAnnotations } = useAnnotations();

    const [currNodes, edges] = useGraphTransformer({ ... some state ... });

    useEffect(() => {
        setNodes([...currNodes, ...aNodes]);
    }, [currNodes, aNodes]);

   return <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={(changes) => {
                changes.forEach((c) => c.type === 'position' && dragAnnotation(c));
                redrawAnnotations();
      }}
   />
}
```
Is this considered an uncontrolled flow?
I hope this answers your question...

**Comment by moklick** [comment]
The issue is that you are not adding `width` and `height` to your nodes which means that they are not initialized for React Flow. In the previous version this worked but it was a bug that led to other issues, because the user nodes state and the internal one were out of sync. 

You somehow need to add `width` and `height` to your nodes. You could do it by using `setNodes` like this:
 
```js
const onNodesChange = useCallback((changes) => {
  const dimensionChanges = changes.filter(c => c.type === 'dimensions');
  
  setNodes(nds => applyChanges(dimensionChanges, nds));
   
  changes.forEach((c) => c.type === 'position' && dragAnnotation(c));
  redrawAnnotations();
}, []);
```

or better by adding an initializer to your `useAnnotations` hook:

```js
const onNodesChange = useCallback((changes) => {
  changes.forEach((c) => {
    if (c.type === 'position') {
      dragAnnotation(c);
    }

     if (c.type === 'dimensions') {
      initAnnotation(c);
    }
  });

  redrawAnnotations();
}, []);
```

Does it help?

**Comment by noams-unbiased** [comment]
Indeed it does. Thanks!

**Comment by moklick** [comment]
I am glad you could solve this @noams-unbiased. 

Let me know if you have any further information here @tim-field. I hope we can fix it for your use case too!

**Comment by tim-field** [comment]
We are still having issues here.

We render the graph as follows ( I've just included relevant code below )

```TS
type Position = {x: number; y: number}
type PositionMap = {[id: string]: Position}

/**
* Our graph component, this augments our nodes with attributes specific to react-flow  
**/
const Graph({
  nodes,
  // ...
  
  const [localPositions, setLocalPositions] = useState<PositionMap>({})
  const positionedNodes = useMemo(
    () =>
      nodes.map(node => {
        const position: Position | undefined = localPositions?.[node.id]
        // hide until we have a position, useAutoLayout will set this for us
        const style = position ? undefined : {opacity: 0}
        return {
          ...node,
          position: position ?? {x: 0, y: 0},
          style
        }
      }),
    [localPositions, nodes]
  )
  
  useAutoLayout()

  // stores the position changes for nodes that have been moved
  // this will be called after the auto-layout has run with change.type === 'reset'
  const onNodesChange: OnNodesChange = useCallback(
    (changes: NodeChange[]) => {
      const positionChanges = changes.reduce<PositionMap>((acc, change) => {
        if (change.type === 'position' && !!change.position) {
          acc[change.id] = change.position
        } else if (change.type === 'reset') {
          // useAutoLayout sends a reset event with the new positions
          acc[change.item.id] = change.item.position
        }
        return acc
      }, {})

      if (Object.keys(positionChanges).length) {
        setLocalPositions(current => ({
          ...current,
          ...positionChanges
        }))
      }
      },
     [setLocalPositions]
  )



   return (
    <ReactFlowStyled
      nodes={positionedNodes}
     // ...

```

I even tried switching to storing all nodes in state and updating them with [apply-node-changes](https://reactflow.dev/api-reference/utils/apply-node-changes) but this resulted in serious render glitches as well, We'd have a flurry of calls to onNodesChange whenever we interacted with the graph.

**Comment by tim-field** [comment]
@moklick I'm also happy to jump on a call about this and walk you though what I'm seeing here

**Comment by tim-field** [comment]
Ok I got this working with the following updates.

We now store all the nodes in state

```TS
const [graphNodes, setGraphNodes] = useState<PositionedNode[]>(() =>
    nodes.map(n => ({
      ...n,
      position: {x: 0, y: 0},
      style: {opacity: 0}
    }))
  )
  ```
  
  
  With a `useEffect` to ensure changes to the `nodes` param is reflected on the graph 
  
  ```TS
  useEffect(() => {
    setGraphNodes(gphNodes =>
      nodes.map(node => {
        const existing = gphNodes.find(n => n.id === node.id)
        return {
          position: {x: 0, y: 0},
          ...existing,
          style: {opacity: 0, ...existing?.style},
          ...node
        }
      })
    )
  }, [nodes])
  ```
  
  Our `onNodesChange` callback has been updated to the following 
  
  ```TS
  const onNodesChange: OnNodesChange = useCallback(
    (changes: NodeChange[]) => {
      const positionChanges = changes.filter(
        c =>
          c.type === 'position' || c.type === 'reset' || c.type === 'dimensions'
      )

      if (positionChanges.length > 0) {
        setGraphNodes(
          nds => applyNodeChanges(positionChanges, nds) as PositionedNode[]
        )
      }

      // ...
    },
    [setGraphNodes]
  )
  ```

**Comment by moklick** [comment]
@tim-field the issue is, that you are working with a controlled flow but don't apply the changes correctly. It would be better, if you could always apply the changes (this will also make a migration to the next major version easier). I would apply the changes and then do the custom stuff:

```js
const onNodesChange: OnNodesChange = useCallback(
  (changes: NodeChange[]) => {
      setGraphNodes(nds => applyNodeChanges(positionChanges, nds) as PositionedNode[])
      
      // ...
  },
  [setGraphNodes]
);
```

**Comment by rolint** [comment]
not sure if this is the best place for this comment, but I can confirm that setting width and height properties of nodes before rendering prevents "flickering" while dragging. In my case, the flickering wasn't terrible, but annoying  (the cursor was flickering between "grab" and "grabbed" while dragging). Note: I am updating from v9 to v11.

**Comment by moklick** [comment]
@rolint there shouldn't be any flickering. Please check if you applied changes correctly via `applyNodeChanges`. If the issue persists, please open a new issue for this.
