### ISSUE TITLE
`useNodesData`: return `type` and `id` besides data object

### ISSUE THREAD

**Issue by moklick** [xyflow/xyflow#3927]
Currently we only return the actual data object. It would be helpful to return the node id and the type, too.

**Comment by bogris** [comment]
I don't think it's bad, as I have this implemented in my custom hooks, 

but if we go this way, I think you overlap a lot with getNode from useReactFlow.

**Comment by moklick** [comment]
This was released in Svelte Flow 0.0.37 and React Flow 12.0.0-next.10


@bogris  `useNodes` returns all nodes. This means that the component that uses it, re-renders multiple times when a node is being dragged. This isn't the case for `useNodesData` and additionally you can pass an array of ids of the nodes data you want to receive.
