### ISSUE TITLE
[12.0.0-next.9] nodes can't he dragged after they are hidden/unhidden in  flow with parent nodes

### ISSUE THREAD

**Issue by bogris** [xyflow/xyflow#3931]
### Describe the Bug

I have the following sequence:
- a flow where I have parentNode defined in some nodes in my tree
- one or multiple nodes can be dragged.
- i hide/unhide a node/multiple nodes
- the nodes i toggled are not draggable anymore. 

I am running 12.0.0-next.9. _If I switch the imports to 11.10.4 it works as expected. 
there are no messages in the console._ 

here is the 

### Steps to Reproduce the Bug or Issue

1. render a flow with parent relations
2.using a button, hide / unhide a node
3. the node we toggled can't be dragged anymore

### Expected behavior

The node should be draggable after toggle hidden. 

### Platform

- OS: macOS 14.0
- Browser: Chrome (Version 121.0.6167.184 (Official Build) (arm64); or Safari
- Node: v18.17.1
- nextJS : "^13.5.6"

### here is the code to reproduce the issue. I gathered everything in one page:
```'use client';

import { BaseNodeData } from '@enchante/shared/types';
import { Button } from '@radix-ui/themes';
import {
  ReactFlowInstance,
  ReactFlow,
  Node,
  useEdgesState,
  useNodesState,
  DefaultEdge,
  Panel,
} from '@xyflow/react';
import { useEffect, useState } from 'react';
import 'reactflow/dist/base.css';

const mockInitialNodes: Node[] = [
  // one parent for "1", "2"
  {
    id: '0',
    data: {
      label: 'Test node 0',
    },
    position: { x: 0, y: 0 },
    // type: 'leaf-big',
  },
  {
    id: '1',
    parentNode: '0',
    data: {
      label: 'Test node 0-1',
    },
    position: { x: 50, y: 100 },
    // type: 'custom-one',
  },
  {
    id: '2',
    parentNode: '0',
    data: {
      label: 'Test node 0-2',
    },
    position: { x: 50, y: 200 },
    // type: 'custom-one',
  },
];

export default function Dashboard3Page() {
  const [nodes, setNodes, onNodesChange] = useNodesState<Node<BaseNodeData>>(
    [],
  );
  const [edges, setEdges, onEdgesChange] = useEdgesState<DefaultEdge>([]);
  const [rfInstance, setRfInstance] = useState<ReactFlowInstance | null>(null);

  const toggleHideNode = () => {
    console.log('nodes: ', nodes);
      rfInstance?.setNodes(ns => ns.map(n => ({ ...n, hidden: !n.hidden })));
  };

  useEffect(() => {
    if (rfInstance) {
      rfInstance.setNodes(mockInitialNodes);
    }
  }, [rfInstance]);

  return (
    <div className="fixed inset-0 top-[24px] bg-background">
      <div className="relative h-[calc(100vh_-_24px)] text-black">
        <div style={{ height: '100%' }}>
          <ReactFlow
            {...{
              edges,
              nodes,
              onNodesChange,
              onEdgesChange,
              onInit: setRfInstance,
            }}
          >
            <Panel className="flex gap-4 p-4">
              <Button onClick={toggleHideNode}>toggleHideNode</Button>
            </Panel>
          </ReactFlow>
        </div>
      </div>
    </div>
  );
}
```

**Comment by moklick** [comment]
Thanks for the report! Feedback about v12 is super helpful :) We will check out what is wrong here.

**Comment by bogris** [comment]
Glad I can help even a little bit.

To give you context: i have an beta app written in next 13 and reactflow 11

I am optimizing (rewriting) and adding new features to the flow logic. I
intend to do it on v12 so i hit prod on the latest version.

As a preliminary feeling, i like what you did with it. Bring more clarity!

I was working on collapsable nodes when i found this.

I will hold for a few days and maybe, just maybe you manage to fix this
little thing 🤭

After, i’ll try more funky stuff and let you know how it goes on v12.

If it is of interest to you, I managed to arrange children nodes in parents
based on html logic: you supply a classname string to the parent with a
tailwind like syntax, based on gap, paddings, margins, I am able to figure
out x/y for children, and the computed width/height of the parent. So
add/delete children in parents resizes everything automatically. So just
one data prop for each parent and no need for system params for arranging
them anymore.

Hey, great work with react flow!

I was looking for a project to use it for 2 years now :))

Sorin

**Comment by moklick** [comment]
Will be fixed with the next release!

**Comment by bogris** [comment]
thank you!

looking fw for next.10 👍

**Comment by bogris** [comment]
fixed!
