### ISSUE TITLE
Calling `useContext` inside a custom node causes controlled components like `<input>` to lose their state

### ISSUE THREAD

**Issue by oztune** [xyflow/xyflow#3937]
### Describe the Bug

It seems like calling `useContext()` inside a custom node causes that node to update out of sync with the rest of the react state. This causes several issues but a really obvious one is that it makes controlled components like text inputs get their cursor reset when the state changes. Please see my codesandbox link for a working reproduction.

Node that this only happens when the context provider's value changes due to the text input changing. But that shouldn't matter.

This issue happens with `reactflow 11.10.4` as well as `@xyflow/react` beta.

### Your Example Website or App

https://codesandbox.io/p/sandbox/divine-wood-wsl3xz

### Steps to Reproduce the Bug or Issue

1. Go to https://codesandbox.io/p/sandbox/divine-wood-wsl3xz
2. Type something in the box (eg: "123")
3. Move the text cursor to the start of the text field
4. Type anything else
5. Notice how the text cursor was jumped to the end of the text field

Note that if you remove the call to `useContext()` in `Flow.tsx` this issue disappears,.

### Expected behavior

I of course would expect the cursor to retain its position in the text area regardless whether or not the custom component depends on a context.

### Screenshots or Videos

![2024-02-21 22 02 51](https://github.com/xyflow/xyflow/assets/663175/9b076e1d-a330-4506-b2d2-61baa88a9608)

### Platform

- OS: macOS 14.3 (23D56)
- Browser: Chrome
- Version: 121.0.6167.184

**Comment by moklick** [comment]
I think the issue here is that you are creating a new nodes object on every render. Could you change that and see if it fixes the issue?

**Comment by oztune** [comment]
Hey @moklick thanks for taking a look.

Here's the thing: shouldn't nodes be allowed to change on ever render though? In this example my node's `data` needs to be recalculated when the `string` state changes. Per your request I added a `useMemo` to [the example](https://codesandbox.io/p/sandbox/divine-wood-wsl3xz?file=%2Fsrc%2FFlow.tsx) so it only creates new nodes when the state actually changes, but the original issue still remains.

I haven't dug into the source, but is it possible that the library does some sort of debouncing on the rendering logic for performance, and it causes React to re-render with stale state?

**Comment by peterkogo** [comment]
Sorry for the late reply, but there are a couple of things off with your example. You are using `Math.random()` on the ContextProvider, you put the setter of the local state into the data object. It won't work this way.

Take a look at our example which covers input fields and updating node data objects accordingly. https://reactflow.dev/examples/interaction/computing-flows 

If you have more questions feel free to hit us up on our [Discord](https://discord.gg/RVmnytFmGW)!
