### ISSUE TITLE
Edge connecting the nodes gets removed on pressing backspace when the node is selected

### ISSUE THREAD

**Issue by 777ahesh** [xyflow/xyflow#3938]
### Describe the Bug

I was trying to create a node structure using the dagree tree, but when I clicked a edge and pressed backspace it gets removed.

### Steps to Reproduce the Bug or Issue

1. Click on edge
2. press backspace
3. edge gets removed

### Expected behavior

As a user, I should not be able to remove fixed edges between nodes in dagree tree structure as it breaks the flow.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by bcakmakoglu** [comment]
This is not a bug, this is literally a feature.
You can disable the delete key by setting `deleteKeyCode={null}` (or any other key you want to use as the delete key code) or setting `edge.deletable = false` (this can be done *per edge* or set as the default using `defaultEdgeOptions={{ deletable: false }}`
