### ISSUE TITLE
Hitting backspace for deleting a node doesn't check for the correct event target

### ISSUE THREAD

**Issue by mcmxcdev** [xyflow/xyflow#3939]
### Describe the Bug

As can be seen in the video below, we use a node which opens a full screen modal on top of it.

Whenever hitting the Backspace button inside that modal, both the modal and the node itself are getting deleted.

This is unexpected and leads to us having to disable the delete functionality completely.

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

The delete functionality should only kick in when the event target where the delete key was invoked is an actual svelte-flow node.

### Screenshots or Videos

[Screencast from 2024-02-22 08-21-01.webm](https://github.com/xyflow/xyflow/assets/16797721/fde2e24f-605c-42c7-9a37-877d82ceb8ee)

### Platform

- OS: Ubuntu 23.10
- Browser: Brave
- Version: [Version 1.62.165 Chromium: 121.0.6167.184 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by moklick** [comment]
can you try to add the class name "nokey" to the modal as a workaround?

**Comment by mcmxcdev** [comment]
> can you try to add the class name "nokey" to the modal as a workaround?

I added it to the outmost container for the modal, but the node including modal still gets removed with `.onkey` set.

**Comment by dorlevi** [comment]
bumping this as we had some user feedback on our node deletion experience which is blocked on this

**Comment by moklick** [comment]
Hey @dorlevi, our idea is to bind the event handlers to the svelte flow container. We will give you an update next week!

**Comment by peterkogo** [comment]
@dorlevi we investigated this and we need some feedback from you.

Essentially, it would absolutely be possible for us to attach the key listeners to the Svelte Flow container, however this would mean you'd have to always manage focus by hand. This means, after closing the modal you'd have to manually give focus back to Svelte Flow. Actually, any flow would have to be focused first to receive key events.

There a multiple options I suggest you try first:

1. We check if any element between the target of an event & the document root has `.nokey` as a class. You mentioned you already tried to do this. If you focus your modal right after it appears (I recommend you do this anyway), the delete key should be ignored by Svelte Flow. If this does not work and you are sure your modal or anything inside the modal is focused than this is bug and we'll investigate.

2. You can also do `e.stopPropagation()` on the events coming from your modal. Those events will never reach Svelte Flow.

3. Set the relevant key interaction props on the Svelte Flow component to `null` as long as the modal is open. You could even extend this to a couple of other interactivity props.

I'd argue that all of the above options are easier than going through the pain of managing focus by hand.

What are your thoughts? Is this a reasonable path for your application?

**Comment by mcmxcdev** [comment]
Thanks for the detailed response! I am part of Dor's team and looked into it again. I was not aware that `.nokey` only works when an element is focused, so I was able to make this work now!

It's tricky since our modal is not fullscreen. Our users could end up clicking above it, leading to deselection and then hitting backspace which leads to the problem initially reported, but that should be quite edge case which I am not too worried about.

Option nr3 could be something we look into if we are not satisfied with Option nr1.

**Comment by peterkogo** [comment]
Great! I'll close this issue for now, feel free to reopen or report any further observations/ideas here.
