### ISSUE TITLE
Testing creation of edge connections in v12 beta

### ISSUE THREAD

**Issue by vonazt** [xyflow/xyflow#3948]
### Describe the Bug

When using `react-testing-library` in v11, we were able to test the creation of edge connections between nodes using this code:
```
       await waitFor(() => {
          fireEvent.click(sourceHandle);
          fireEvent.click(targetHandle);
        });

```
When we try this in v12, we get `TypeError: s.elementFromPoint is not a function` when trying to click on the target handle. Has there been some change in how edge connections are created when clicking on handles?

### Steps to Reproduce the Bug or Issue

1. Create one node with a source handle and another with a target handle
2. Assign each a `data-testid`
3. Using `react-testing-library`, get the `sourceHandle` and the `targetHandle`, e.g. `const sourceHandle = screen.getByTestId('<some-data-testid');`
4. Click on the `sourceHandle` and then the `targetHandle`, e,g:
```
await waitFor(() =>
  fireEvent.click(sourceHandle);
  fireEvent.click()
});
```

### Expected behavior

As a user, I expected for an edge connection to be created and for the test to pass. 

### Screenshots or Videos

![Screenshot 2024-02-26 at 15 06 49](https://github.com/xyflow/xyflow/assets/34370364/3625d5d8-eca0-4939-bc40-5ab2499a5601)

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Testing library: `@testing-library/react v14.1.2`
- Version: [12.0.0-next.9]

**Comment by moklick** [comment]
how could you solve this?
