### ISSUE TITLE
getSmoothStepPath center position is ignored if it is zero

### ISSUE THREAD

**Issue by RickeyWard** [xyflow/xyflow#3950]
### Describe the Bug

When using a getSmoothStepPath and passing in a center, if the center happens to be zero the default center is used because zero is a falsy value.

https://github.com/xyflow/xyflow/blob/13897512d3c57e72c2e27b14ffa129412289d948/packages/system/src/utils/edges/smoothstep-edge.ts#L84

SmoothStep-Edge.ts
```javascript
 if (sourceDir[dirAccessor] * targetDir[dirAccessor] === -1) {
    centerX = center.x || defaultCenterX; // if center.x is zero, defaultCenterX is used
    centerY = center.y || defaultCenterY; // if center.y is zero, defaultCenterY is used
 }
```
current work around is either make sure if you're going to pass zero to instead pass some other arbitrary small number like 0.00001, or to create a duplicate of all the non exported functions and modify these two lines to respect zero.

### Steps to Reproduce the Bug or Issue

pass zero as center.x or center.y to getSmoothStepPath and see that the defaults are used.

### Expected behavior

The passed value is retained

### Platform

- Browser: chrome
- Version: code issue is present in current main branch,

**Comment by peterkogo** [comment]
Thanks for reporting this, should be fixed in the next version.

**Comment by moklick** [comment]
Thanks! This is fixed in the latest release.
