### ISSUE TITLE
Show edge label renderer only on hover

### ISSUE THREAD

**Issue by noah-jun-521** [xyflow/xyflow#3951]
### Please describe the feature that you want to propose

I probably don't know if this is somehow possible but I would love to show the edge label renderer only when user hovers on the edge. (or by selecting the edge)

**Comment by moklick** [comment]
You could add `onMouseEnter` and `onMouseLeave` handler to a wrapping `<g>` element (for handling hover) and use the passed `selected` flag. Example: https://codesandbox.io/p/sandbox/solitary-forest-2jqf7q?file=/CustomEdge.tsx:33,48

**Comment by noah-jun-521** [comment]
@moklick Thanks for the quick response! That was exactly what I needed. 
By the way, from the above sandbox, can you teach me if I can style edge(for example stroke color or width) or edge label hover?
