### ISSUE TITLE
Updating parentNode property in Subflow causes positioning issues with node 

### ISSUE THREAD

**Issue by ritesh-nahar** [xyflow/xyflow#3965]
### Describe the Bug

I'm using Subflows in my app. When I am moving a node from one group to another and updating it's parentNode property then node is not getting positioned correctly it's placed randomly outside of the group. if I don't update parentNode then it works fine.

### Your Example Website or App

https://codesandbox.io/p/sandbox/mystifying-bird-wqrxy5

### Steps to Reproduce the Bug or Issue

Open [codesandbox](https://codesandbox.io/p/sandbox/subflow-drag-drop-wqrxy5?file=%2FApp.js)
Move "Node A.1" from Group A to Group B
See the output

### Expected behavior

Ideally, the node should be placed inside the dropped group.

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [e.g. 122.0]

**Comment by moklick** [comment]
it seems that the codesandbox is private

**Comment by ritesh-nahar** [comment]
Sorry, I have made it public.

**Comment by moklick** [comment]
I got it now. The behaviour is correct. When you drag a node out of its parent and add it to a new parent, you need to adjust the position based on the pointer position and the new parent position. 

pseudo code: 

nodePosition = screenToFlowPosition(event) - newParentNodePosition
