### ISSUE TITLE
[12.next10] strange node reorder after setNode

### ISSUE THREAD

**Issue by bogris** [xyflow/xyflow#3967]
### Describe the Bug

I have a bug (i think) related to nodes ordering. 

my plan is to add a new node to existing ones. I am using parenst extensivly. In order to respect logic, I need my children to be after the parents in the nodes array. In order to assure this I always add to the end of the array, As I to an existing parent. 

The issue I encountered is that I supply the array of nodes to setNodes with the new node last, but after the function is executed, getNodes gives me the node at the begining of the array. 

I created this test scenario, an will paste the code and the console log and the nodes object. 

`
....
  const { getNodes, setNodes, getNode } = useReactFlow();
...
    const nodes = getNodes();
    console.log('onAddNodeX: before enyhting. nodes: ', nodes); // <<<<< INITIAL

    const nodeToAdd = {
      ...newNode,
      parentNode: parentId,
      extent: 'parent',
      // zIndex: 10,
    } as Node<BaseNodeData>;
    if (!newNode.id) nodeToAdd.id = Math.random().toString(36).substring(7);

    const allNodes = [...nodes, nodeToAdd];
    const updatedNodes = await updateParentNodesRecursively(allNodes, parentId);

    console.log('onAddNodeX: finalUpdatedNodes: ', updatedNodes); // <<<<< AFTER MY PROCESSING
    setNodes(updatedNodes);
    await new Promise((resolve) => setTimeout(resolve, 1000)); // give it some time... 
    console.log('onAddNodeX: afterSetNodes: nodes: ', getNodes()); // <<<< RESULT. 
`

the console log is as a picture to be more clear
<img width="557" alt="Screenshot 2024-03-01 at 12 33 45" src="https://github.com/xyflow/xyflow/assets/10676067/acc9071a-5b10-4da9-bd98-b48be6ec75d1">

the nodes object is:

`
[
    {
        "id": "9ha0yc",
        "extent": "parent",
        "data": {
            "className": "min-h-16"
        },
        "position": {
            "x": 12,
            "y": 64
        },
        "type": "leaf",
        "parentNode": "2",
        "computed": {
            "positionAbsolute": {
                "x": 278,
                "y": 228
            },
            "width": 153,
            "height": 60
        }
    },
    {
        "id": "0",
        "data": {
            "className": "flex flex-col p-4 pt-16 gap-5",
            "height": 292,
            "width": 181
        },
        "position": {
            "x": 250,
            "y": 100
        },
        "type": "custom-one",
        "computed": {
            "positionAbsolute": {
                "x": 250,
                "y": 100
            },
            "width": 181,
            "height": 292
        }
    },
    {
        "id": "2",
        "parentNode": "0",
        "extent": "parent",
        "data": {
            "className": "flex flex-col p-3 pt-16 gap-3",
            "height": 212,
            "width": 149
        },
        "position": {
            "x": 16,
            "y": 64
        },
        "type": "custom-one",
        "computed": {
            "positionAbsolute": {
                "x": 266,
                "y": 164
            },
            "width": 149,
            "height": 212
        }
    },
    {
        "id": "2-3",
        "parentNode": "2",
        "extent": "parent",
        "data": {},
        "position": {
            "x": 12,
            "y": 140
        },
        "type": "leaf",
        "computed": {
            "positionAbsolute": {
                "x": 278,
                "y": 304
            },
            "width": 125,
            "height": 60
        }
    }
]
`

### Steps to Reproduce the Bug or Issue

1. const nodes = getNodes()
2. const newNodes = [...nodes, newNode]
3. setNodes(newNodes)
4. delay 1s
5. getNodes() >> newNode is first

### Expected behavior

newNode to be last, as I supplied it

### Platform

- OS: [macOS,]
- Browser: [Chrome]
- nextJs 14.1
- reactflow 12.next10

**Comment by moklick** [comment]
I can't reproduce this. Are you sure that you are not mutating the `updatedNodes` somewhere?

**Comment by moklick** [comment]
any update on this @bogris ?

**Comment by bogris** [comment]
sorry for the delay. 
This is part of a convoluted function that does node positioning while dragging and on drag stop. 

at first I hoped for a miracle from your side before me digging into it again. 

In the mean time I got sidetracked and did not got to this one. 

I think it's better to close this, and I'll get back with some feedback after I fugure it out.

**Comment by bogris** [comment]
hi @moklick 

This one was really bugging me for leaving it "in the air"... 

I managed to isolate the behaiviour in the code below. 

after adding the node it will be moved back to position 0, before the parent, so if the parent as BG, the child will be "behind"
In order to easly "work" with this, the custom node has transparent bg by default, but it is solid on selection so you can observe the problem. 

I also logged the array of node in the .setNodes, and after the change is processed by rfInstance. 

`'use client';

import { Button } from '@radix-ui/themes';
import {
  ReactFlowInstance,
  ReactFlow,
  Node,
  useEdgesState,
  useNodesState,
  Panel,
  NodeProps,
  Background,
} from '@xyflow/react';
import { clsx, ClassValue } from 'clsx';
import { FC, useEffect, useState } from 'react';
import 'reactflow/dist/base.css';
import { twMerge } from 'tailwind-merge';

export const cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));

export const CustomNodeOne: FC<NodeProps<any>> = (props) => {
  const { id, selected, width, height, data } = props;

  return (
    <>
      {/* <NodeResizer/> */}
      <div
        className={cn('flex flex-col  rounded border border-gray-600 p-4', {
          'bg-yellow-100': selected,
        })}
        style={{
          height: data.height,
          width: data.width,
        }}
      >
        <h1 className="text-lg font-bold">{data.label}</h1>
        <h1 className="text-xs text-gray-400">{id}</h1>
        <p className="text-gray-899 text-xs">
          H: {height || 'null'} W: {width || 'null'}
        </p>
      </div>
    </>
  );
};

const nodeTypes = {
  'custom-one': CustomNodeOne,
} as const;

const mockInitialNodes: Node[] = [
  // one parent for "1", "2"
  {
    id: '0',
    data: {
      label: 'Test node 0',
      width: 500,
      height: 500,
    },
    position: { x: 200, y: 200 },
    type: 'custom-one',
    // type: 'leaf-big',
  },
  {
    id: '1',
    parentNode: '0',
    data: {
      label: 'Test node 0-1',
      with: 200,
      height: 100,
    },
    position: { x: 50, y: 100 },
    type: 'custom-one',
  },
];

export default function Dashboard3Page() {
  const [nodes, setNodes, onNodesChange] = useNodesState<Node<any>>([]);
  const [edges, setEdges, onEdgesChange] = useEdgesState<any>([]);
  const [rfInstance, setRfInstance] = useState<ReactFlowInstance | null>(null);

  const addChildNode = async () => {
    console.log('nodes: ', nodes);
    const newNode: Node<any> = {
      id: Math.random().toString(36).substring(7),
      data: {
        label: 'Test node 0-2',
        with: 200,
        height: 100,
      },
      parentNode: '0',
      extent: 'parent',
      position: { x: 350, y: 100 },
      type: 'custom-one',
    };
    rfInstance?.setNodes((ns) => {
      const newNodes = [...ns, newNode];
      //log nodes before:
      console.log('addChildNode: newNodes before: ', newNodes);
      return newNodes;
    });
    //delay
    await new Promise((resolve) => setTimeout(resolve, 1000));
    //log nodes after:
    console.log('addChildNode: nodes after: ', rfInstance?.getNodes());
  };

  useEffect(() => {
    if (rfInstance) {
      rfInstance.setNodes(mockInitialNodes);
    }
  }, [rfInstance]);

  return (
    <div className="fixed inset-0 top-[24px] bg-background">
      <div className="relative h-[calc(100vh_-_24px)] text-black">
        <div style={{ height: '100%' }}>
          <ReactFlow
            {...{
              edges,
              nodes,
              onNodesChange,
              onEdgesChange,
              onInit: setRfInstance,
              nodeTypes,
            }}
          >
            <Panel className="flex gap-4 p-4">
              <Button onClick={addChildNode}>add child</Button>
            </Panel>
            <Background />
          </ReactFlow>
        </div>
      </div>
    </div>
  );
}
`

I am using the app directory in nextJs. 

the relevant package versions are:
`
    "@xyflow/react": "^12.0.0-next.12",
    "next": "14.0.4",
    "@radix-ui/themes": "^2.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
`

I hope is a better report this time :D

**Comment by bogris** [comment]
Qwick update: 

I relaceed ```
  // useEdgesState,
  // useNodesState,
```
with a zustand implementation and it works as expected: 

```
import { create } from 'zustand';
import {
  Connection,
  Edge,
  EdgeChange,
  Node,
  NodeChange,
  addEdge,
  OnNodesChange,
  OnEdgesChange,
  OnConnect,
  applyNodeChanges,
  applyEdgeChanges,
} from "@xyflow/react";

// import initialNodes from './nodes';
// import initialEdges from './edges';

export type RFState = {
  nodes: Node[];
  edges: Edge[];
  onNodesChange: OnNodesChange;
  onEdgesChange: OnEdgesChange;
  onConnect: OnConnect;
  setNodes: (nodes: Node[]) => void;
  setEdges: (edges: Edge[]) => void;
  addNode: (node: Node) => void;
};


const mockInitialNodes: Node[] = [
  // one parent for "1", "2"
  {
    id: "0",
    data: {
      label: "Test node 0",
      width: 500,
      height: 500,
    },
    position: { x: 200, y: 200 },
    type: "custom-one",
    // type: "leaf-big",
  },
  {
    id: "1",
    parentNode: "0",
    data: {
      label: "Test node 0-1",
      with: 200,
      height: 100,
    },
    position: { x: 50, y: 100 },
    type: "custom-one",
  },
];

// this is our useStore hook that we can use in our components to get parts of the store and call actions
export const useFlowStore = create<RFState>((set, get) => ({
  nodes: mockInitialNodes,
  edges: [],
  onNodesChange: (changes: NodeChange[]) => {
    set({
      nodes: applyNodeChanges(changes, get().nodes),
    });
  },
  onEdgesChange: (changes: EdgeChange[]) => {
    set({
      edges: applyEdgeChanges(changes, get().edges),
    });
  },
  onConnect: (connection: Connection) => {
    set({
      edges: addEdge(connection, get().edges),
    });
  },
  setNodes: (nodes: Node[]) => {
    set({ nodes });
  },
  setEdges: (edges: Edge[]) => {
    set({ edges });
  },
  addNode: (node: Node) => {
    set((state) => ({ nodes: [...state.nodes, node] }));
  }
}));


```

export default function Dashboard3Page() {
  const { nodes, edges, onNodesChange, onEdgesChange, onConnect, addNode } = useFlowStore(selector, shallow);

  const [rfInstance, setRfInstance] = useState<ReactFlowInstance | null>(null);

  const addChildNode = async () => {
    console.log("nodes: ", nodes);
    const newNode: Node<any> = {
      id: Math.random().toString(36).substring(7),
      data: {
        label: "Test node 0-2",
        with: 200,
        height: 100,
      },
      parentNode: "0",
      extent: "parent",
      position: { x: 350, y: 100 },
      type: "custom-one",
    };
    addNode(newNode);
    // rfInstance?.setNodes((ns) => {
    //   const newNodes = [...ns, newNode];
    //   //log nodes before:
    //   console.log("addChildNode: newNodes before: ", newNodes);
    //   return newNodes;
    // });
    // //delay
    // await new Promise((resolve) => setTimeout(resolve, 1000));
    // //log nodes after:
    // console.log("addChildNode: nodes after: ", rfInstance?.getNodes());
  };


  return (
    <div className="fixed inset-0 top-[24px] bg-background">
      <div className="relative h-[calc(100vh_-_24px)] text-black">
        <div style={{ height: "100%" }}>
          <ReactFlow
            {...{
              edges,
              nodes,
              onNodesChange,
              onEdgesChange,
              onConnect,
              onInit: setRfInstance,
              nodeTypes,
            }}
          >
            <Panel className="flex gap-4 p-4">
              <Button onClick={addChildNode}>add child</Button>
            </Panel>
            <Background />
          </ReactFlow>
        </div>
      </div>
    </div>
  );
}```
this is the zustand implementation

**Comment by bogris** [comment]
i was working with collab functions and I got to this error again. 

It was caused now by using 
```
rfInstance.addNode(...)
```

in order to reproduce it, in the code above with zusand, replace the store provided addNode with rfInstance.addNode(...)

**Comment by bogris** [comment]
another update. 

Altough it seemed like a good workaround to manipulate the Zustand strore directly, this introduces a bug: 

By not using rFinstance.addNodes function, I don't generate the "add" change event and it breakes the layouting logic as I tried to build it around the changes that are fired.

**Comment by sroussey** [comment]
> By not using rFinstance.addNodes function, I don't generate the "add" change event and it breakes the layouting logic as I tried to build it around the changes that are fired.

we have the same issue in ngraph

**Comment by bcakmakoglu** [comment]
Why not use [`useNodesInitialized`](https://reactflow.dev/api-reference/hooks/use-nodes-initialized) for layouting?

**Comment by bogris** [comment]
Well... first, i was not aware of it :))
It would have saved me some hours last tear if I read the docs properly 😔 

In my implementation i also do stuff on drag, hide and delete. I have a simulated flex box behavior for children where i control the layout with tailwind like classnames key in data (gap-2 spaces children at 8px for example, p-3 spaces the children 12px from the sides of the parent, etc). So add is just a small part. 
I also start the updates as a tree from the node that changed through his parents. 

I ended up using onNodeChange to centralize the point where i apply the logic. 

I will say that today i got to a workaround as i am hooking on the dimension change event. Looks like a side-effect of the node measures. So maybe the mentioned hook would have also worked, but i try my best to keep logic in one place. 

To add to this, i also implemented collaboration, and that is also linked in onNodeChange.

**Comment by bogris** [comment]
this is not an issue anymore on next15

**Comment by youngjuning** [comment]
have the same issuese

**Comment by cobish** [comment]
have the samme issue on 12.0.4

**Comment by moklick** [comment]
@cobish please use the latest version. This was already fixed.
