### ISSUE TITLE
useUpdateNodeInternals doesn't update handle positions during active connection

### ISSUE THREAD

**Issue by DenizUgur** [xyflow/xyflow#3983]
### Describe the Bug

I'm using custom nodes in my graph component and these nodes collapse the handles when user is not near them. This is done with absolute position on handles and with animations. Now, I've managed to handle animation and position updates on the source node by calling `updateNodeInternals` on every `requestAnimationFrame` until animation is done.

However, if the user has initiated a connection then target nodes doesn't update their handle positions. I think internally they are being updated but no one told the connection about it :)

### Your Example Website or App

https://codesandbox.io/p/devbox/react-flow-edge-issue-dvgwvh

### Steps to Reproduce the Bug or Issue

This is a very crude example, especially `requestAnimationFrame` being called all the time but it's the same behaviour with optimized version anyway.

1. Try to connect the source to target
2. See that even though you are hovering over target the connection thinks handle position is on the left (as opposed to where you are seeing)

### Expected behavior

I expect that when `updateNodeInternals` is called the connection should also know where the target handles are.

### Platform

Browser: Chrome (122.0.6261.94)
React Flow version: 11.10.4

**Comment by DenizUgur** [comment]
I get what you're saying, I would also need to increase the hover trigger area to compensate for that delay then. All of it seems a bit hacky though. May I ask the reasoning behind this? As source handles behave correctly in this case.

If it's also a won't fix situation, could you tell me where is the related logic located so that I can fork or monkey patch it?

**Comment by DenizUgur** [comment]
Okay it appears that this comes from the following snippet. I get why you are using a lookup here but if there is a way to know when `updateNodeInternals` is called then this lookup should be invalidated. I've tested it and updating the lookup here solves this issue. I'll investigate the code a little more to see how I can get notified about this and open a PR about it.

https://github.com/xyflow/xyflow/blob/82f40b4a6792ac734859521024e756a8834e78c6/packages/system/src/xyhandle/XYHandle.ts#L151-L161

**Comment by psychedelicious** [comment]
This is still an issue on v11.11.3.

I see the PR #3988 was closed pretty quickly after it was opened - did it not address the issue in a satisfactory way?

**Comment by DenizUgur** [comment]
I think I closed the PR because I didn't get any feedback and my project requirements changed.

I'm willing to work on it if I can get a review. Although, I have a feeling that this won't be fixed until v12 gets a stable release.

**Comment by psychedelicious** [comment]
Thanks @DenizUgur. I was thinking about how to be more efficient with this. I think it would need to be memoized as you said, but it's not immediately clear how to do that without adding substantial complexity. I agree it's probably best to wait for v12 to not put extra pressure on maintainers.

**Comment by peterkogo** [comment]
This should be possible with the changes proposed in #4548. If this lands in main you should be able to update your handles while a connection is in progress.

**Comment by andyfelder16** [comment]
I'm having the same exact problem. I need to update my handle positions when a connection is active so that fix would be really helpful!

**Comment by DenizUgur** [comment]
I suppose that PR would fix this issue without any changes from our side right?

**Comment by moklick** [comment]
yep @DenizUgur !

**Comment by DenizUgur** [comment]
That's perfect! Thank you @peterkogo @moklick
