### ISSUE TITLE
SvelteFlow on:selectionchange doesn't get called

### ISSUE THREAD

**Issue by Sahasrara** [xyflow/xyflow#3984]
### Describe the Bug

I just noticed that `on:selectionchange` is never called in SvelteFlow.

### Steps to Reproduce the Bug or Issue

Try assigning a handler to on:selectionchange
```
<SvelteFlow
    on:selectionchange={onSelectionChanged}
/>
```

The `onSelectionChanged` function is never called.

### Expected behavior

I would expect `onSelectionChanged` to be called when:

1. A node or edge is clicked that wasn't already selected
2. A selection rectangle is drawn

### Platform

- OS: Windows
- Browser: Electron
- Version: ^28.1.1

**Comment by moklick** [comment]
That handler doesn't exist. Where did you find it?

**Comment by Sahasrara** [comment]
Oh! I figured it existed based on my conversation with Peter here:
https://discord.com/channels/771389069270712320/1118204997671334019/1209083389286547467

But if that event doesn't exist, then I assume we're supposed to rely on `on:nodedragstop`, but I don't see that being called when you're dragging a selection.

**Comment by peterkogo** [comment]
@Sahasrara You can track the progress on [this here](https://github.com/xyflow/xyflow/pull/3998). If this pull request lands, you will receive `nodedragstop` events, when you drag the selection box, too.
