### ISSUE TITLE
RollupError: 'const' declarations must be initialized

### ISSUE THREAD

**Issue by khromov** [xyflow/xyflow#3985]
### Describe the Bug

I'm trying to install SvelteFlow in a SvelteKit 2 + Svelte 5 project. (I've overridden the peerDependencies in package.json)

I'm getting the following error:

```
21:44:12 [vite] Error when evaluating SSR module /node_modules/@xyflow/svelte/dist/lib/plugins/Minimap/index.js: failed to import "/node_modules/@xyflow/svelte/dist/lib/plugins/Minimap/Minimap.svelte"
|- RollupError: 'const' declarations must be initialized
```

### Your Example Website or App

https://www.sveltelab.dev/4fuf5vxv16tuo36

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

-

### Platform

-

**Comment by moklick** [comment]
Thanks for the hint, we will check it!

**Comment by peterkogo** [comment]
We will handle errors connected to Svelte 5 when its released - the list of bugs connected to the new update is still quite long. I hope you understand :)

**Comment by peterkogo** [comment]
I will close this for now, feel free to reopen if the error persists.
