### ISSUE TITLE
Rotatable parent node

### ISSUE THREAD

**Issue by MatheusRoichman** [xyflow/xyflow#3986]
### Describe the Bug

I'm trying to make a node rotatable, and when rotating it, making its child nodes rotate with it. But when I try to do it without changing the child nodes, it goes like this:

![image](https://github.com/xyflow/xyflow/assets/75812510/8c50f858-91d3-4680-9d48-0955a29aec22)

And if I try to apply the same rotation of the parent node to the child nodes (e.g. 90deg), it goes like this:

![image](https://github.com/xyflow/xyflow/assets/75812510/985669b0-a6b9-4570-9d5c-60d31b80edc2)

What am I doing wrong?

P.s.: the given website link is an edited sandbox of the [Resize and Rotate](https://reactflow.dev/examples/nodes/resize-rotate) official React Flow example. 

### Your Example Website or App

https://codesandbox.io/p/sandbox/optimistic-sunset-5h6g4k?file=%2FResizeRotateNode.js%3A57%2C20

### Steps to Reproduce the Bug or Issue

1. Rotate the parent element.

### Expected behavior

As a user, i expected the child nodes to resize accordingly to the parent.

![image](https://github.com/xyflow/xyflow/assets/75812510/e51f6310-3f41-459b-aacc-ac62d1b203d0)

### Platform

- OS: Windows 11
- Browser: Chrome, Brave
- Version: Chrome 109.0.5414.120 (64 bits), Brave 1.62.165 (64 bits)

**Comment by moklick** [comment]
Hey @MatheusRoichman 

rotation is not built in and if you rotate a parent, the coordinate system stays the same and you would have to do some maths, to position the child nodes correctly.

**Comment by MatheusRoichman** [comment]
> > What is the calculus that I need to do with the child nodes to position them correctly? I tried some, but I'm still not able to do it,
> 
> Have you tried rotating your node around the center of it's parent ?
> 
> You would use the formula x' = x * cos(angle) - y * sin(angle) y' = x * sin(angle) + y * cos(angle)
> 
> Applied to your case that would be: Because the parent node is 400x400, we can think of the relative position of your child node as x:-200; y:200 from the center (Y points UP)
> 
> The angle would be 90° or PI/2 radians
> 
> The new relative position would be x' = -200 * cos(PI/2) - 200 * sin(PI/2) = -200 y' = -200 * sin(PI/2) + 200 * cos(PI/2) = -200
> 
> You can then use this new relative position to place down your child node. IDK how your positioning system works in detail so i'll leave it here.
> 
> You will also need to rotate your child node in-place (as you are already doing) by the same angle

I tried it. Here's my implementation of this formula;

```ts
export const rotateNodeAroundParentCenter = (
  node: Node,
  angle: number,
  parentCenter: XYPosition
): XYPosition => {
  const x = parentCenter.x - node.position.x;
  const y = parentCenter.y - node.position.y;

  const angleCos = Math.cos(angle);
  const angleSin = Math.sin(angle);

  const newX = x * angleCos - y * angleSin;
  const newY = x * angleSin + y * angleCos;

  return {
    x: newX,
    y: newY,
  };
};

export const getNodeCenter = (node: Node): XYPosition => {
  const rect = getNodesBounds([node]);

  return {
    x: rect.width / 2,
    y: rect.height / 2,
  };
};
```

```ts
const handleRotate = useCallback(
  (e: DragEvent) => {
    if (!rotateControlRef.current || !resizerRef.current) return;

    e.dataTransfer.effectAllowed = "none";

    const rect = rotateControlRef.current.getBoundingClientRect();
    const centerX = rect.left + rect.width / 2;
    const centerY = rect.top + rect.height / 2;
    const dx = e.clientX - centerX;
    const dy = e.clientY - centerY;
    const rad = Math.atan2(dy, dx);
    const deg = (rad * 180) / Math.PI;

    const roundedDeg = parseInt(deg.toString());
    if (roundedDeg === roundedRotation) return;

    setNodes((nds) =>
      nds.map((node) => {
        if (
          !nodeOfThisElement ||
          (node.id !== element.id && node.parentNode !== element.id)
        )
          return node;

        const updatedNode = node as DesignElementNodeType;
        updatedNode.data.rotation = roundedDeg;

        if (updatedNode.parentNode === element.id) {
          const parentCenter = getNodeCenter(nodeOfThisElement);

          const childPosition = rotateNodeAroundParentCenter(
            updatedNode,
            roundedDeg,
            parentCenter
          );

          updatedNode.position = childPosition;
        }

        return updatedNode;
      })
    );

    setRotation(roundedDeg);
    updateNodeInternals(nodeId);
  },
  [
    element.id,
    nodeId,
    nodeOfThisElement,
    roundedRotation,
    setNodes,
    updateNodeInternals,
  ]
);
```

Didn't worked well.


https://github.com/xyflow/xyflow/assets/75812510/141a996e-c361-42cb-900c-6b1b2e7f44ec

**Comment by hocman2** [comment]
Your angle needs to be in radians and beware that the getNodeCenter() function does not return the global canvas center. For that it'd need to return x + width / 2 and y + height / 2. IDK If it's what you want though

Then I'd recommend logging x and y coordinates at different steps of the rotateAround function to see if the results are what you expect for offsetting the child. Depending on how coordinates work the implementations may differ so a simple stackoverflow copy paste might not be enough

**Comment by moklick** [comment]
We will not add rotation as a built-in feature for React Flow. If you need resizing and rotation, you would need to implement resizing in the custom node on your own since the built-in NodeResizer doesn't work with rotated nodes.

We will update the docs to make this more clear.
