### ISSUE TITLE
Resizing rotated node

### ISSUE THREAD

**Issue by MatheusRoichman** [xyflow/xyflow#3987]
### Describe the Bug

When I rotate a node more than 180 degrees, its resizing is not working as expected. Further details on the attached recording.

### Steps to Reproduce the Bug or Issue

1. Go into the [Resize and Rotate](url) official React Flow example;
2. Clear the first node and the edge, leaving only the second node;
3. Make the second node resizable AND rotatable;
4. Rotate the node 180 degrees;
5. Try to resize with the bottom-right corner.

### Expected behavior

As a user, I wanted it to increase the size of the node, but it decreased.

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/75812510/09646699-37aa-42a7-9612-779fa1cf3d9b

### Platform

- OS: Windows 11
- Browser: Chrome, Brave
- Version: Chrome 109.0.5414.120 (64 bits), Brave 1.62.165 (64 bits)

**Comment by moklick** [comment]
Since rotation is not built-in, it breaks a lot of things. Unfortunately I am not sure, if we are going to address this.

**Comment by MatheusRoichman** [comment]
> Since rotation is not built-in, it breaks a lot of things. Unfortunately I am not sure, if we are going to address this.

Please make rotation built-in on some next version 🥲 I'm constantly having problems with the implementation I made

**Comment by 26KantaHasegawa** [comment]
@MatheusRoichman 

I forked the project and made some custom changes to resolve this issue. It seems to be working fine so far, but please incorporate it at your own risk as it might affect other features.

Changes:
I added logic to detect the rotation angle in `XYResizer.ts`. When the angle is passed through props, it adjusts the mouse pointer coordinates according to the angle.

https://github.com/KantaHasegawa/rotate-xyflow/pull/1/files

**Comment by moklick** [comment]
We will not add rotation as a built-in feature for React Flow. If you need resizing and rotation, you would need to implement resizing in the custom node on your own since the built-in NodeResizer doesn't work with rotated nodes.

We will update the docs to make this more clear (maybe we can create an example with a simple custom node resizer).
