### ISSUE TITLE
SvelteFlow `on:nodedrag`, `on:nodedragstart`, and `on:nodedragstop` not emitted when multiple nodes selected 

### ISSUE THREAD

**Issue by ahornbeck** [xyflow/xyflow#3997]
### Describe the Bug

In SvelteFlow, `on:nodedrag`, `on:nodedragstart`, and `on:nodedragstop` are not emitted when multiple nodes selected and dragged.  They *are* emitted when only a single node is selected and dragged.

### Steps to Reproduce the Bug or Issue

Setup a `SvelteFlow` with 2 nodes.  Select 2 notes. Drag.

```
        <SvelteFlow
            id={flowId}
            {nodes}
            {edges}
            {nodeTypes}
            {proOptions}
            selectionMode={SelectionMode.Partial}
            selectionOnDrag
            panOnScroll
            {panOnDrag}
            fitView
            minZoom={0.1}
            maxZoom={5}
            on:nodedrag={(event) => {
                console.log('on node drag', event);
            }}
            on:nodedragstart={(event) => {
                console.log('on node drag start', event);
            }}
            on:nodedragstop={(event) => {
                console.log('on node drag stop', event);
            }}
            colorMode={'dark'}
        >
            <Controls />
            <Background id={backgroundId} />
            <MiniMap nodeColor={getMiniMapNodeColor} />
        </SvelteFlow>

```

### Expected behavior

I expect the 3 events to fire for start, drag, and end when multiple nodes are selected and dragged.  However, none of these events are fired with multiple nodes are selected and dragged.  However, they do fire when a single node is selected and dragged.  Note: the `nodes` array in the `CustomEvent` does contain a single item, as expected, when a single node is dragged.

### Platform

- OS: macOS
- Browser: Tauri 2.0-beta.8
- Version: 2.0-beta.8

**Comment by moklick** [comment]
Thanks, we will check it. Which version of Svelte Flow are you using?

**Comment by ahornbeck** [comment]
My apologies, I forgot to include that.

I saw this behavior in 0.0.36 and 0.0.38.  I did not try 0.0.37.

**Comment by moklick** [comment]
`on:nodedrag`, `on:nodedragstart`, and `on:nodedragstop` now also works for selections. For this we renamed the `node` param to `targetNode` and set it to `null` if users drags a selection.
