### ISSUE TITLE
[Svelte Flow] connectingto doesn't behave the same as connecting used to

### ISSUE THREAD

**Issue by lucascompython** [xyflow/xyflow#3999]
### Describe the Bug

In 0.0.37, connecting turned into "connectingfrom" and "connectingto" 
>status class names for Handle components are slightly different. It's now "connectingfrom" and "connectingto" instead of "connecting"  

But they don't have the same behavior has "connecting" used to.
For example, I was able to change the color of a handle to red if it wasn't a valid connection, didn't matter the handle. Now I can only do that with the connections that are specifically not valid trough IsValidConnetion, which doesn't fulfill all the cases.

### Steps to Reproduce the Bug or Issue

Update to 0.0.37

### Expected behavior

Being able to apply css styles to handles that are not valid connections like we could before 0.0.37

### Platform

- OS: [Linux]
- Browser: [Brave, Epiphany]
- Version: [Brave: 1.63.169 Chromium: 122.0.6261.111, Epiphany 45.3]

**Comment by moklick** [comment]
Thanks! We will check that.

**Comment by peterkogo** [comment]
@lucascompython We have adjusted the behavior of the classes that get applied to handles depending on their connectability.
- `connectingfrom` gets added if you start a new connection line from a handle
- `conntenctingto` gets added if you are trying to end a connection line at a handle (but have not released the mouse button yet)
- `connectionindicator` gets added to all handles where a connection can be started from OR if you have started a new connection: to all handles that the connection can end at (respecting `connectionMode` and your handle types)

If you would want to add additional checking through the `isValidConnetion` function, you can subscribe to the current connection from the store inside a customNode, call `isValidConnetion` and apply an additional class to the handles depending on that.

Can you achieve what you are trying to implement with these changes?

**Comment by lucascompython** [comment]
Hi!
Thanks for the reply.
Could you elaborate on the last part? I'm new to svelte.
>If you would want to add additional checking through the isValidConnetion function, you can subscribe to the current connection from the store inside a customNode, call isValidConnetion and apply an additional class to the handles depending on that.  

The behavior, I want, is exactly the same as the one you have on the [validation example](https://svelteflow.dev/examples/interaction/validation) on your website. If you go to the [stackblitz of that example](https://stackblitz.com/run?file=src%2Fexample%2FApp.svelte), it is already using xyflow/svelte v0.0.38, and the intented behaviour doesn't work.

**Comment by peterkogo** [comment]
Thanks for pointing this out! I updated the validation example. You can use `connectingto` instead of `connecting` to achieve the same thing.

What I was referring to earlier was a way to already check all possible connections when you start a connection - not only by hovering over the end handle. You could do that in all you custom nodes when a new connection is started.

**Comment by lucascompython** [comment]
Hi there!
I am reopening as I don't feel that the solution works.

Source to Source or Target to Target connections by default are not valid, but there aren't any classes that get applied when I try to connect them. 

Right now, the `connectingto` class only gets applied with the condition that `isValidConnetion` defines.
Let's say the user starts a connection in a source handle, if he then hovers another source handle, the connection is not valid, but the class doesn't get applied as it used to be.
