### ISSUE TITLE
Multi Select functionality using shift key not working properly

### ISSUE THREAD

**Issue by ishitaka-boe** [xyflow/xyflow#4005]
### Describe the Bug

In case of Dynamic grouping where we have groups and child nodes, the in-built multiselect functionality to hold the shift button down and drag the cursor (with left click of mouse) to capture the area and select nodes is broken. The blue highlighted area is not shown correctly. It changes it's size and position sporadically

### Your Example Website or App

https://reactflow.dev/examples/nodes/dynamic-grouping

### Steps to Reproduce the Bug or Issue

1.  Open the Dynamic grouping preview from the examples mentioned in the react flow website
2.  Add some more groups and nodes (refer to the image for sample data)
3.  Hold down the shift key, and left click your mouse to select the starting point of the area you want to cover
4.  While holding down the shift key, drag the mouse to expand the selection area as needed 
5. Release the mouse button first and then the shift key to get the desired selected area

 
![dynamicGrouping](https://github.com/xyflow/xyflow/assets/84437680/d2130b23-fe9e-4d1b-8e97-7eb64328b07c)

### Expected behavior

As a user, I expected the selected area (selected by the user) to match the highlighted area but the highlighted area (blue box) changes the size and position sporadically

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/84437680/7abb302d-349e-466d-9cd7-d475630eb226

### Platform

OS: Windows
Browser: Chrome, Firefox, Edge
Version: 120.0.6099.110, 120.0.1, 120.0.2210.77

**Comment by peterkogo** [comment]
@ishitaka-boe I can't reproduce this issue anymore - I think it was fixed some time ago. Please don't hesitate to reopen if it still persists.
