### ISSUE TITLE
Adjust graph edges and nodes by changing one node height or width dynamically

### ISSUE THREAD

**Issue by LiorLivyatan** [xyflow/xyflow#4007]
### Describe the Bug

Hello everyone!

I'm encountering a challenge with dynamically adjusting the layout of my graph when the size of a node changes upon interaction.
I have a node that expands to display a larger image when clicked.
The expected behavior is for the rest of the graph to adjust dynamically to accommodate the expanded node's new dimensions.
However, the expanded node ends up overlapping and hiding other nodes and edges instead of "pushing" them away to make space.

Is there a recommended approach to trigger a re-layout of the graph when a node changes its size?

Thank you very much in advance for your help!

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

.

### Platform

- OS:macOS
- Browser: Chrome

**Comment by moklick** [comment]
You could use `onNodesChange` for this. Whenever nodes change their dimensions, a change of type "dimensions" gets fired:

```js
const onNodesChange = useCallback((changes) => {
  setNodes((nds) => {
    const nextNodes = applyNodeChanges(changes, nds);
    
    if (changes.some((change) => change.type === 'dimension')) {
      // layout nodes
    }

    return nextNodes;
  });
}, []);
```

**Comment by LiorLivyatan** [comment]
Thank you for the super fast answer!

Unfortunately the div inside the node is being changed, but I do not get any changes (except for selected change).
I also do not understand how to trigger the layout change.

Thanks again!

**Comment by moklick** [comment]
You don't have to do anything. React Flow adds a resize observer to every node and should send the changes automatically. It's fine to resize an inner div, but it's important that the outer node doesn't have a fixed width or height and also changes it's size based on the content. 

Are you using v11 or v12? Could you send a codesandbox or repo we could check out?

**Comment by LiorLivyatan** [comment]
Thank you, I think I understand what is happening.

I am using dagre to position the nodes and edges, and this indeed has a fixed height and width as per the example from the docs:

const dagreGraph = new dagre.graphlib.Graph()
dagreGraph.setDefaultEdgeLabel(() => ({}))

const nodeWidth = 250
const nodeHeight = 60

const getLayoutedElements = (nodes: any, edges: any, direction = 'TB') => {
  dagreGraph.setGraph({ rankdir: direction })

  nodes.forEach((node: any) => {
    dagreGraph.setNode(node.id, { width: nodeWidth, height: nodeHeight })
  })

  edges.forEach((edge: any) => {
    dagreGraph.setEdge(edge.source, edge.target)
  })

  dagre.layout(dagreGraph)

  nodes.forEach((node: any) => {
    const nodeWithPosition = dagreGraph.node(node.id)
    node.targetPosition = 'top'
    node.sourcePosition = 'bottom'

    node.position = {
      x: nodeWithPosition.x - nodeWidth / 2,
      y: nodeWithPosition.y - nodeHeight / 2,
    }

    return node
  })

  return { nodes, edges }
}


Is it possible to let dagre "decide" about the height and width of the nodes instead of hardcoding them?

Thanks! :)

**Comment by goliney** [comment]
@moklick 
> Are you using v11 or v12? 

I didn't know v12 was available. How do I check it out?

**Comment by moklick** [comment]
@goliney all info about 12 can be found in this discussion: https://github.com/xyflow/xyflow/discussions/3764
