### ISSUE TITLE
Reactflow holding Shift key acts werid and doesn't get released when we open context menu(browser's)

### ISSUE THREAD

**Issue by avtblspd** [xyflow/xyflow#4021]
### Describe the Bug

So i see this bug particularly when I hold Shift key from keyboard in reactflow canvas and drag and select multiple nodes and i haven't released the Shift Key and right click anywhere in canvas which opens the browser's context menu and after that release the Shift key and click anywhere in canvas, so it seems like the Shift button feels its still active since i don't see the hand cursor in react flow to pan the canvas and rather it seems the drag and selection event is still active

Please see the gif image which in the following 
Step 1 : Drag and Selecting holding Shift Key
Step 2 : Once its selected(keep holding the Shift Key) and just right click so it opens the context menu(of browsers)
Step 3: Release the Shift Key
Step 4: Click anywhere and try to pan the canvas

You'll see that, you can't pan the canvas but rather the dragging and selecting action is active, so inorder make it go away i have to Press Shift Key and release it, so then after that i can pan the canvas, it seems like the once i open the context menu and release the Shift Key the reactflow canvas may be doesn't senses the up key event, please correct my understanding i may be wrong.

but is there a way to fix it, i could really have an external workaround to keep tracking of the key event and probably refire programmatically the shift key so it can be fixed but i was hoping if this needs to be fixed as part of reactflow idk ? 

![react flow issue](https://github.com/xyflow/xyflow/assets/72560398/547f6dfb-4aa1-4604-9461-40789e8a26ee)

### Your Example Website or App

https://reactflow.dev/examples/nodes/easy-connect

### Steps to Reproduce the Bug or Issue

Please see the gif image which in the following 
Step 1 : Drag and Selecting holding Shift Key
Step 2 : Once its selected(keep holding the Shift Key) and just right click so it opens the context menu(of browsers)
Step 3: Release the Shift Key
Step 4: Click anywhere and try to pan the canvas

You'll see that, you can't pan the canvas but rather the dragging and selecting action is active, so inorder make it go away i have to Press Shift Key and release it, so then after that i can pan the canvas, it seems like the once i open the context menu and release the Shift Key the reactflow canvas may be doesn't senses the up key event, please correct my understanding i may be wrong.

### Expected behavior

once the Shift key is been release reactflow canvas should be able to pan the canvas rather than having the drag and selection event in action

### Screenshots or Videos

![react flow issue](https://github.com/xyflow/xyflow/assets/72560398/cfeff791-f981-4117-90f9-acf069ab96d0)

### Platform

- OS: [Windows]
- Browser: [Chrome, Safari, Firefox]
- Version: [Latest]

**Comment by avishwakarmaplex** [comment]
@moklick any suggestions ?

**Comment by moklick** [comment]
Fixed in React Flow 12! If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12
