### ISSUE TITLE
Support JSON Canvas

### ISSUE THREAD

**Issue by NiluK** [xyflow/xyflow#4022]
### Please describe the feature that you want to propose

1. Look at JSON Canvas and the obsidian spec

https://jsoncanvas.org/

2. Join the Open Canvas Working Group:

https://twitter.com/OrionReedOne/status/1768292314802201087

3. Implement JSON Canvas Functionality into Reactflow

This will probably mean modfiying node / edge properties but it shouldn't be a massive lift to support this

**Comment by moklick** [comment]
We will keep an eye on OCWG but it's way too early to make any changes now.
