### ISSUE TITLE
Node height dynamic

### ISSUE THREAD

**Issue by SmackdabDevOps** [xyflow/xyflow#4026]
### Describe the Bug

 https://screenrec.com/share/YwpvihgOxm

### Steps to Reproduce the Bug or Issue

1 https://screenrec.com/share/OfdZ45Lw3c  - workflow-builder-pro-example (Working fine)
2 https://screenrec.com/share/YwpvihgOxm - if content is more then generate issue 

### Expected behavior

https://screenrec.com/share/jby6G31M7m 

i required this type nodes height and width dynamicaly if i add new node but its content is more then adjust its height dynamicaly so 

### Screenshots or Videos

![image](https://github.com/xyflow/xyflow/assets/140397043/a02eb753-e146-4136-8107-0e5bdd1d0209)
![image](https://github.com/xyflow/xyflow/assets/140397043/a921814b-0675-4f8b-beb4-d7dcab897ae7)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

1 https://screenrec.com/share/OfdZ45Lw3c  - workflow-builder-pro-example (Working fine)
2 https://screenrec.com/share/YwpvihgOxm - if content is more then generate issue 

https://screenrec.com/share/jby6G31M7m   - my need is this type of feature so is this possible so suggest me or small example of this type of feature, in this dynamic height if content is more then i required different different height nodes

**Comment by moklick** [comment]
Hey! This is not an issue with React Flow but a general question. If you are a pro subscriber, please write us an email or reach out via Discord or GH discussions.

**Comment by SmackdabDevOps** [comment]
okay thannks
