### ISSUE TITLE
Incorrect copy-paste example key handlers

### ISSUE THREAD

**Issue by Iaotle** [xyflow/xyflow#4039]
### Describe the Bug

The pro copy-paste example provides the following code:

`useCopyPaste.ts:138-140`:
```typescript
useShortcut(['Meta+x', 'Ctrl+x'], cut);
useShortcut(['Meta+c', 'Ctrl+c'], copy);
useShortcut(['Meta+v', 'Ctrl+v'], paste);
```

Currently this doesn't work, since the appropriate key event is `Control`, not `Ctrl`

### Your Example Website or App

https://pro.reactflow.dev/examples/react/copy-paste

### Steps to Reproduce the Bug or Issue

self-explanatory

### Expected behavior

I expect the key handlers to work OOB.

### Platform

- OS: Windows, Linux
- Browser: any

**Comment by moklick** [comment]
fixed, thanks!
