### ISSUE TITLE
[SvelteFlow] update intersections example nodedrag handler with targetNode

### ISSUE THREAD

**Issue by bluecorridor** [xyflow/xyflow#4042]
### Describe the Bug

Was looking at the example, and noticed it wasn’t working since the last time I looked at it. 

### Steps to Reproduce the Bug or Issue

1. Go to svelteflow.dev/examples/nodes/intersections
2. Tried to intersect nodes, no highlighting observed 
3. Looked at “What’s new” for latest changes, and made the connection to 0.0.39 node drags events. 
4. Opened example in stackblitz to try the change out, and seemed to work. 

### Expected behavior

Node should highlight upon intersection. 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

Appreciate all the cool stuff you’re bringing to svelte!

**Comment by peterkogo** [comment]
Thanks for bringing this up!
