### ISSUE TITLE
Expose dHeight & dWidth in NodeDimensionChange in ReactFlow

### ISSUE THREAD

**Issue by tristanls** [xyflow/xyflow#4046]
### Please describe the feature that you want to propose

First, apologies for me being poorly organized and not bundling this together with #4045 . The motivation is the same as in #4045.

**Feature**: expose `dHeight` & `dWidth`(change in dimensions `height` & change in dimensions `width`) in `NodeDimensionChange` event in ReactFlow.

**Motivation**: Similarly to #4045 , when xyflow is used with multiplayer technology, when resizing a node, sending resize intent (i.e. changes, like dHeight & dWidth) is recommended over sending final dimensions. This allows for dealing with cases where two people attempt to resize the same node.

And just as in #4045, reconstructing `dHeight` & `dWidth` from `NodeDimensionChange` is straightforward when only scaling comes from xyflow zoom, but becomes problematic when there are scaling parameters inside nodes that are separate from xyflow zoom, as the multiplication gets out of hand once scaling parameters reach certain values.

**Comment by peterkogo** [comment]
I replied in #4045. Let's continue the discussion there.
