### ISSUE TITLE
Include `endHandle` on invalid connection

### ISSUE THREAD

**Issue by tinybitsofcode** [xyflow/xyflow#4048]
### Please describe the feature that you want to propose

I'm using the new `useConnection` hook which is great for finding the start and end handles.

I see when the status is `invalid` the endHandle is not populated, although internally it would be very easy to do so, given we actually find it and check if it's valid.

This removes the need of having to create a simlar logic `getClosestHandle` which is quite elaborate to replicate.

**Comment by moklick** [comment]
I agree! We will check it :)

**Comment by peterkogo** [comment]
This will be added to next release of v12. You can track the status here #4382

**Comment by moklick** [comment]
Added in React Flow 12! If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12
