### ISSUE TITLE
Docs are confusing regarding update of nodes

### ISSUE THREAD

**Issue by korroktheslavemaster** [xyflow/xyflow#4049]
### Describe the Bug

Writing here after spending way too much time trying to debug why my node wasn't rerendering after I updated the `nodes` prop, especially since afaict I followed the instructions here https://reactflow.dev/examples/nodes/update-node (i.e. passing a newly created `nodes` array to `ReactFlow`). Turns out I also need to create a new `data` object on each node (instead of merely updating the data object) to let `ReactFlow` know about the change (as mentioned here in the older docs https://v9.reactflow.dev/examples/update-node/#:~:text=to%20create%20a-,new%20data%20object,-and%20always%20pass but missing in the new docs).
I would suggest updating the new docs with this information explicitly (it's kind of there in the code example but I feel most people would miss it)

### Steps to Reproduce the Bug or Issue

- Render `<ReactFlow nodes={nodes}/>`
- Create a new `nodes` array but only update `node.data` instead of creating a new data object

### Expected behavior

should re-render the node with new data. however it only does that after i move some things around in the ui.

### Platform

- reactflow 11.10

**Comment by peterkogo** [comment]
Thanks for raising this issue. There are comments in the code mentioning it, but you are right, we have to make this more prominent in the description of the example.
