### ISSUE TITLE
 how do we show position or placeholder to drop items while dragging an item as shown in the shared attachment?

### ISSUE THREAD

**Issue by ATMECS-IT** [xyflow/xyflow#4053]
### Please describe the feature that you want to propose

 how do we show position or placeholder to drop items while dragging an item as shown in the shared attachment?

https://github.com/xyflow/xyflow/assets/45692522/66cab1f8-deac-4535-a351-fa29c56b89f6

**Comment by peterkogo** [comment]
There is no built-in feature for this, but you can definitely make this work. Feel free to join our [discord server](https://discord.gg/RVmnytFmGW) to get some help and guidance on questions like this.
