### ISSUE TITLE
[DOCS] Zustand create implementation marked as deprecated

### ISSUE THREAD

**Issue by bogris** [xyflow/xyflow#4055]
### Describe the Bug

https://reactflow.dev/learn/advanced-use/state-management

the zustand store init is marked as deprecated. 

https://github.com/pmndrs/zustand/discussions/1937

for me the zustand docs worked as expected:
```
import { createWithEqualityFn } from 'zustand/traditional'
import { shallow } from 'zustand/shallow';
...
export const useFlowStore = createWithEqualityFn<RFState>((set, get) => ({
...
}), shallow);
```

### Steps to Reproduce the Bug or Issue

used the docs to create a zustand backed RF instance

### Expected behavior

no deprecation warning on the store function

### Platform

- OS: macOs
- Browser: Chrome

**Comment by moklick** [comment]
thanks! For stuff like this you can also use the https://github.com/xyflow/web repo

**Comment by moklick** [comment]
The guide now uses the latest API.
