### ISSUE TITLE
[v12] z-index Grouping for SubFlows

### ISSUE THREAD

**Issue by sroussey** [xyflow/xyflow#4060]
### Please describe the feature that you want to propose

It would be great if (at least optionally) we could set the z-index of nodes that are contained in a parent to be on the same plane.

Nodes move around with their parent as a group, so they should move backward and forward as group as well. 

In almost any diagram program that allows the user to group items, those items act as one in the z plane. You don't group things in Illustrator and then have parts of the group on the top of all other items in the document when you "send to back", etc.

**Comment by sroussey** [comment]
<img width="1095" alt="image" src="https://github.com/xyflow/xyflow/assets/127349/1ccf1569-8e77-4e7b-936e-412ed5c486f5">

Drag and looks ok:

<img width="1095" alt="image" src="https://github.com/xyflow/xyflow/assets/127349/9ca5935e-82b0-4e34-bc0b-add215ade58c">

Click on item behind it:

<img width="1095" alt="image" src="https://github.com/xyflow/xyflow/assets/127349/c45b3eee-2903-434e-8a6e-a98d139aff4b">

Try dragging it:

<img width="1095" alt="image" src="https://github.com/xyflow/xyflow/assets/127349/6339eb8d-2c94-4cd2-8111-f2186bc72129">

Now dragging the first one again:

<img width="1095" alt="image" src="https://github.com/xyflow/xyflow/assets/127349/c01fb3ed-4666-4836-9436-924e14ce2986">

**Comment by sroussey** [comment]
At the moment, the only way I can think of to fix this is to not use sub flows and instead create a new xf flow for every child group.

**Comment by sroussey** [comment]
If you want to test for yourself:
```
git clone: https://github.com/sroussey/ellmers.git
git checkout turbo-runner-graph
bun install
bun run build
cd packages/web
bun run dev
```

**Comment by sroussey** [comment]
(BTW: in this particular use case, I can disable dragging of anything, but I want to be able to do grouping in [ngraph](https://github.com/sroussey/ngraph) )

**Comment by peterkogo** [comment]
Subflows are grouped by zIndex. Children will always have the parent zIndex + 1. But if you don't set any zIndex on the parent nodes, the flow will be drawn in order of the nodes array. Try setting different z indices for you parent nodes.

**Comment by sroussey** [comment]
Everything has a zIndex of zero. 

<img width="608" alt="image" src="https://github.com/xyflow/xyflow/assets/127349/2346d7cb-3f77-4e33-a0ce-e715da9029c5">

**Comment by moklick** [comment]
by default all nodes have zIndex = 0. It's important that your parent nodes are always in front of the child nodes in your nodes array, so that child are rendered on top. If you select or drag a parent node, the zIndex of that node and all child node z indices get adjusted.

**Comment by peterkogo** [comment]
Are you sure that the parents are coming first and then the children? Do the parents have different z-indices? 
I can't replicate it, unfortunately. Do you have a codesandbox with a replication by any chance?

**Comment by sroussey** [comment]
So, I added something that sorts nodes any time there is a change (adding / deleting a node). 

There is improvement on the first drag of any parent over any other parent.

However, the process of selection seems to alter things such that if i select various things, then go back and drag a parent over another parent, everything is messed up again.

**Comment by sroussey** [comment]
Oh, i see what is happening.

When i select, all @moklick says, the parent and its children get a higher zIndex.

However, when i select another parent, while the first parent gets zIndex lower, its children do not. The the children are left with zIndex of 1000 while the parent goes back to 0. Then when selecting/dragging on something new, the parent and children go to 1000 and then collide with the child that was left behind.

<img width="1199" alt="image" src="https://github.com/xyflow/xyflow/assets/127349/d0a902ad-0122-4893-82bc-acadb02498b1">

Here you can see the node on top has z-index of 1000 even though it belongs to the parent way underneath.

**Comment by moklick** [comment]
Is this about v11 or v12?

**Comment by sroussey** [comment]
> Is this about v11 or v12?

v12

**Comment by sroussey** [comment]
I am looking at catching when a node de-selects, and then clean up myself by looking at the children and be sure they have zIndex of 0. But how do i set that?

**Comment by peterkogo** [comment]
Thanks for investigating this! I just double checked whats happening here and you are indeed correct. Once the internal zIndex was changed on select of the parent node, it never returns to its supposed zIndex. Thanks for the pull request!
