### ISSUE TITLE
svelte-flow "reactive flow" example is not working

### ISSUE THREAD

**Issue by tsdexter** [xyflow/xyflow#4063]
### Describe the Bug

The example Reactive Flow is not working for svelte: https://svelteflow.dev/examples/interaction/reactive-flow

<img width="541" alt="image" src="https://github.com/xyflow/xyflow/assets/4126987/0f130b7b-3e77-4533-bee3-8de77666a02b">

### Your Example Website or App

https://stackblitz.com/run?file=src%2Fexample%2FApp.svelte

### Steps to Reproduce the Bug or Issue

See `undefined` texts in example

### Expected behavior

Texts should be 

```
HELLO
world
```

### Platform

svelte-flow

**Comment by peterkogo** [comment]
Thanks for bringing this up! Should be fixed now.
