### ISSUE TITLE
Ability to auto save the flow on every user interaction

### ISSUE THREAD

**Issue by pdubey84** [xyflow/xyflow#4068]
### Please describe the feature that you want to propose

Wondering is this is already possible. Whenever user 
- adds node
- adds edges/connection
- moces nodes around
- any interaction that changes the flow

We can call an auto save fn to save the state of the canvas

I tried using `rfInstance` from this example  https://reactflow.dev/examples/interaction/save-and-restore but its always 1 step behind, meaning if I add 3 nodes the rfInstance only shows & saves 2 nodes

Has anyone solved this?

**Comment by moklick** [comment]
I can't reproduce this. The example works as expected. If it's not working, please provide a codesandbox.

If you want to implement auto save, you could use `onNodesChange` and `onEdgesChange` in combination with `onMoveEnd`. 

If the issue persists, please re-open with a repo or codesandbox.
