### ISSUE TITLE
Support `orientation` prop for `Controls`

### ISSUE THREAD

**Issue by mcmxcdev** [xyflow/xyflow#4069]
### Please describe the feature that you want to propose

We have a design requirement to display the `Controls` component horizontally rather than vertically.

Looking at https://svelteflow.dev/api-reference/components/controls, this doesn't seem to be supported currently, so it would be great to have as a feature!

**Comment by peterkogo** [comment]
You can pass `style={{ flexDirection: 'row', display: 'flex' }}` to `<Controls />` to change the orientation. You can change ordering with `row-reverse` and `column-reverse`.
Because this is solvable with css-only, we wont be adding an additional orientation prop.

**Comment by peterkogo** [comment]
Reopen, because it might actually be useful to have shortcut on this.

**Comment by mcmxcdev** [comment]
I would like to simply modify it with CSS but encountering `Object literal may only specify known properties, and '"style"' does not exist in type 'ControlsProps'.` in Svelteflow.

**Comment by peterkogo** [comment]
Sorry, did not realize this is a Svelte Flow issue. We will add style & class to the `<Controls />`

**Comment by moklick** [comment]
added in 0.0.40 https://svelteflow.dev/api-reference/components/controls#orientation

**Comment by mcmxcdev** [comment]
We have modified it with global CSS for now:

```
:global(.svelte-flow__controls) {
  @apply flex;
}
```

But then we can switch to `orientation` prop, thank you!
