### ISSUE TITLE
Copied node drag exception

### ISSUE THREAD

**Issue by coderlzw-cn** [xyflow/xyflow#4076]
### Describe the Bug

After copying, you need to click elsewhere on the canvas to drag normally.

### Steps to Reproduce the Bug or Issue

none

### Expected behavior

After copying the node, drag it immediately without affecting the position of the source node.

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/55791848/1c3e2a8b-a64c-446c-9c0a-8dbd6027b498

### Platform

Chrome

**Comment by moklick** [comment]
probably just an issue with the example. I will check it.

**Comment by moklick** [comment]
The example could be fixed by resetting the selected flag after duplication.
