### ISSUE TITLE
[Svelte Flow] Minimap dragging doesn't work on older versions of Webkit2Gtk

### ISSUE THREAD

**Issue by lucascompython** [xyflow/xyflow#4080]
### Describe the Bug

When trying to move around using the minimap using webkit2gtk-4.1, it "teleports" very, very far away.
From my testing, this does not happen in webkitgtk-6.0 (what Epiphany is currently using).

### Your Example Website or App

you can see the bug happening here: https://svelteflow.dev/examples/nodes/custom-node

### Steps to Reproduce the Bug or Issue

Using webkit2gtk-4.1 try to move with the minimap

### Expected behavior

As a user, I except the same behavior that I have in any other browser/webview.

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/77930083/151bad4e-2971-4648-8f6d-1614ab3e8ba9

### Platform

- OS: [Linux]
- Browser: [webkit2gtk-4.1]
- Version: [2.44.0]

### Additional context

I am building a [Tauri V2](https://beta.tauri.app/) app.

**Comment by wyhaya** [comment]
I'm experiencing the same error.
webkit2gtk is quite common on Linux, it is similar to WebKit but lags behind by a few versions. For those using [Tauri](https://github.com/tauri-apps/tauri), this should be the only choice.

**Comment by moklick** [comment]
This should be fixed in 0.1.0 - can anyone here confirm?

**Comment by wyhaya** [comment]
@moklick  I think the bug has been fixed!

```diff
- "reactflow": "^11.11.3",
+ "@xyflow/react": "12.0.0-next.17",
```

**Comment by wyhaya** [comment]
@moklick I just retested it, and in my opinion, this bug has indeed been fixed!

```
# Svelte
❌ "@xyflow/svelte": "^0.0.41"
✅ "@xyflow/svelte": "^0.1.3"

# React
❌ "reactflow": "^11.11.3",
✅ "@xyflow/react": "12.0.0-next.17",
```

### @xyflow/svelte 0.0.41 ❌
https://github.com/xyflow/xyflow/assets/23690145/b7309481-78f4-4132-80c5-26a3c85e2b13

### @xyflow/svelte 0.1.3 ✅
https://github.com/xyflow/xyflow/assets/23690145/2e6bd420-7ffd-4637-9de6-11eb720bb5ce

**Comment by moklick** [comment]
Awesome! Thanks for checking Svelte Flow as well :)
