### ISSUE TITLE
Atomic updates of both nodes and edges.

### ISSUE THREAD

**Issue by amirrezapanahi** [xyflow/xyflow#4089]
### Please describe the feature that you want to propose

Is there a way to batch update nodes and edges together so that you wont have any out of date data come through to any useEffects that are listening to the 'setNodes', 'setEdges' etc...

currently im doing: 
```jsx
  useEffect(() => {
    setNodes(newNodes)
    setEdges(newEdges)
  }, [mindmap])

```

I think one way is to do your own state management with Reactflow instead of using the built in one but I feel that it would be good to have this action in place already within the built in useReactflow()

**Comment by pot-code** [comment]
+1, to set data to one node, i have to pass all node data to `setNodes`, it's hard to manage the data changes and will introduce unnecessary renders

**Comment by moklick** [comment]
That's not possible with the built-in functions. As you suggested @amirrezapanahi you can optimize this by using your own state management with your own `setNodes` / `setEdges` helpers.
