### ISSUE TITLE
New node with selected property set to True is not being updated

### ISSUE THREAD

**Issue by prabak** [xyflow/xyflow#4090]
### Describe the Bug

I am using zustand to store the nodes and edges. I have added the feature to create a new node on edge drop. When adding the new node, I set the selected property of the node to `true`. After the store is updated, when the component renders the selected property is set to false. 

I can see that there is a `onNodesChange` triggered to set the selected property to false for the new node that was just added. i.e. `{ "id": "Node_1", "type": "select", "selected": false}`.

I am also seeing that if I have 2 nodes already in the flow that are selected and adding a third one also triggers the `onNodesChange` with selected property to false for all nodes. I.e. there will be 3 elements in the changes array parameter for the the onNodesChange call that are setting the selected property to `false`.

I am not sure if I am missing something from the documentation or if this is a bug.

### Steps to Reproduce the Bug or Issue

1. Use the controlled flow with zustand to store the nodes and edges
2. Add the on edge drop feature that adds a new node with selected property set to true.

### Expected behavior

I expected the newly added node to have the selected property set to true.

### Platform

- OS: [e.g. Windows]
- Browser: [e.g. Chrome]
- Version: [e.g. 91.1]

**Comment by prabak** [comment]
Here you go:

https://codesandbox.io/p/sandbox/brave-sky-qgng4k

thank you

**Comment by dice-pickle** [comment]
I assume this is because of `resetSelectedElements` call for the default `onMouseDown` event, a cheap trick would be to postpone adding node for few ms, I wonder what a good solution for this would look like.

**Comment by moklick** [comment]
Yep, that's the issue. You can fix it by adding the node after the reset:

```js
 requestAnimationFrame(() => addNewNode(position));
```
