### ISSUE TITLE
Viewport Resetting Issue When Zooming Nodes and Clicking on Another Node

### ISSUE THREAD

**Issue by imam2nd** [xyflow/xyflow#4092]
### Describe the Bug

Upon adding a new node, I'm utilizing `fitView()` to appropriately adjust the nodes within the viewport. However, I've observed that if I perform a zoom in or zoom out action on any node and subsequently click on another node, the viewport resets.

### Steps to Reproduce the Bug or Issue

1. Add nodes to the flow diagram.
2. Utilize the Zoom In or Zoom Out functionality on the graph.
3. Click on any node within the diagram.

### Expected behavior

Clicking on a node should retain the current viewport zoom level, maintaining the user's chosen zoom setting.

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/18742807/fdc5a6f9-a6e7-432c-8c30-6cff06f136ae

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]

### Additional context

Here is how I am using the `fitView()` function:

> React.useEffect(() => {
>   fitView({ padding: 1, minZoom: 0.75 });
> }, [nodes, fitView]);

**Comment by moklick** [comment]
Hey @imam2nd 

as soon as you click a node, the `nodes` array changes and the `fitView` inside your `useEffect` gets called. You need to find another solution when you want to call `fitView`. There are different options for this:

1. onNodeDragStop
2. useNodesInitialized
3. on button click

Does it help?

**Comment by imam2nd** [comment]
@moklick, I attempted the methods that you've mentioned above, yet none appear to suit my particular scenario. Nonetheless, I've found that I can handle them using internal business logic.

Thanks for your response regardless.
