### ISSUE TITLE
Node positions are off when using RTL text direction

### ISSUE THREAD

**Issue by devnull69** [xyflow/xyflow#4093]
### Describe the Bug

I've located the following (closed) issue: https://github.com/xyflow/xyflow/issues/3116

It describes that it is necessary to put `dir="rtl"` on the `.react-flow` element in order to make graphs work in RTL text direction mode. But this doesn't work. The edges seem to be positioned correctly, but the node positions are off, so they don't connect to the edges any more.

Please view it on [stackblitz](https://stackblitz.com/edit/vitejs-vite-vksa9f)

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-vksa9f

### Steps to Reproduce the Bug or Issue

Put `dir="rtl"` on the body of your HTML document. Suddenly the graphs on React Flow will no longer look correct. It seems like the edges are positioned correctly but the nodes are off.

### Expected behavior

Graph should still look correct on RTL text direction mode

### Platform

- OS: Windows
- Browser: Firefox
- Version: 124

**Comment by moklick** [comment]
The solution is to set `dir="ltr"` for `<ReactFlow />`. You can then switch back to rtl inside your custom nodes. I will check if we should fix this on library side.

**Comment by moklick** [comment]
This is fixed in 11.11.1

**Comment by devnull69** [comment]
Thank you, it works now
