### ISSUE TITLE
Customize minimum zoom level to interact with nodes

### ISSUE THREAD

**Issue by kevinschaich** [xyflow/xyflow#4094]
### Please describe the feature that you want to propose

From my usage it seems like there is a minimum zoom level required to interact with individual nodes, otherwise it just pans the whole canvas (see below).

![reactflow-zoom](https://github.com/xyflow/xyflow/assets/9244728/5a6188d9-401b-4581-9ab9-fded0ad277d1)

How can we adjust this threshold?

**Comment by moklick** [comment]
This shouldn't be the case 🤔 Can you create a codesandbox for this? https://new.reactflow.dev

**Comment by kevinschaich** [comment]
I tried to repro today (admittedly a lot of changes in our codebase) and it's working as expected 🤷🏻 

Thanks!
