### ISSUE TITLE
Handle drop radius different from handle drag radius

### ISSUE THREAD

**Issue by patatoes1235** [xyflow/xyflow#4097]
### Describe the Bug

Starting a drag can happen on any part of the source handle, but in order for a connection to be formed, the edge must be dragged to within connectionRadius of the **center** of the target handle. 

### Your Example Website or App

https://reactflow.dev/examples/nodes/easy-connect

### Steps to Reproduce the Bug or Issue

1. From the easyconnect example, drag from any node
2. Drop the edge onto another node, somewhere away from the middle
3. No connection is formed

### Expected behavior

Expected to see a valid connection to be formed when an edge is dropped anywhere inside the <Handle /> element, but an edge is only created when you drag to the center of the handle. 

### Screenshots or Videos

![image](https://github.com/xyflow/xyflow/assets/60528673/e79d51d6-f822-4b95-944b-f2b1e0758263)
This does not create a valid connection, or cause the edge to snap to the middle of the handle

### Platform

- OS: [Windows]
- Browser: [Chrome]

**Comment by peterkogo** [comment]
This is fixed in v12

**Comment by DONGNEZHA** [comment]
> This is fixed in v12

Hello, may I ask where the V12 is? I see that the latest version in the release is 11.11.4.
