### ISSUE TITLE
[Svelteflow] Support width and height alignment of nodes based on snap-to-grid

### ISSUE THREAD

**Issue by mmailaender** [xyflow/xyflow#4098]
### Please describe the feature that you want to propose

If snap-to-grid is active, resizing a node will be aligned with the grid size. So, if the grid is 20px, the resizing also happens in 20px steps. But if a node's width and height are not a multiple of 20, the node is not aligned with the grid. It would be great if there were an option that rounds the width and height of a node up to the next multiple of 20 (Or whatever the grid size is).

**Comment by peterkogo** [comment]
This is something we actually cannot provide with our current philosophy. Svelte Flows ergonomics arise mostly from the fact that you can style any node with css and have variable content dimensions, which we measure and apply to our internal calculations. There is no way of setting the width and height on library side without interfering with this principle.

You have 2 options:
1. You can reason about the dimensions of your content and set clamped width & height values
2. You create child div that overflows from the parent div, keep track of its size through a resizeObserver and resize the parent container with clamped with & height values
