### ISSUE TITLE
zoomOnPinch not working when preventScrolling is false

### ISSUE THREAD

**Issue by PhoenixEmbers** [xyflow/xyflow#4101]
### Describe the Bug

once preventScrolling is set to false, zoomOnPinch doesnt work even when its set to true

### Your Example Website or App

https://codesandbox.io/p/sandbox/reactflow-scroll-pinch-xy7kyn?file=%2FApp.js

### Steps to Reproduce the Bug or Issue

1. Add `preventScrolling={false}` and `zoomOnPinch={true}` props together

### Expected behavior

i expect page scroll is maintained with zoomOnPinch working

### Platform

- OS: macOS
- Browser: Chrome
- Version: 123

**Comment by moklick** [comment]
Hey @PhoenixEmbers 

I haven't thought about this, but I see your point. 

`preventScrolling` removes all wheel listeners. A pinch is a wheel event, so those are not coming through anymore. I will check if we can solve it.

**Comment by moklick** [comment]
this is fixed in 11.11.1
