### ISSUE TITLE
Node creation by click and draw / drag

### ISSUE THREAD

**Issue by Nick-Lucas** [xyflow/xyflow#4119]
### Please describe the feature that you want to propose

I have a use case in my project where the desired UX is via a simple drawing mechanism:

1. click and hold on the canvas
2. drag out a node's shape
3. on release the node is created with the dragged dimensions

This seems impossible to achieve in user-land currently, both due to the canvas having a selector click-and-drag mechanism and needing to essentially hijack the canvas to achieve it.

I'm imagining some API like the following would be needed:

```tsx
<ReactFlow
  // existing selection API but shouldn't be enabled simultaneously
  selectionOnDrag={false}

  // a new flag to enable the feature conditionally - maybe needs combining with the above to avoid both being set at once?
  creationOnDrag={true} // enable creation
  
  // A way to render a custom node with correct position and dimensions
  renderCreationOnDrag={(opts) => ReactNode}

  // Final creation can work through existing APIs
  onNodesChange
/>
```

Some keyboard shortcuts to consider too like pressing Escape while dragging to cancel, and maybe a modifier to start dragging if creationOnDrag is disabled? Similar to Shift+Click when selectionOnDrag is disable?

I would be happy to try and contribute this if it's accepted and viable

**Comment by peterkogo** [comment]
Why is this currently not achievable in user-land? 
If you set `panOnDrag` to false whenever your node creation is happening and start listening to pointerdown & pointermove events on the React Flow dom node you should be able to achieve this

**Comment by Nick-Lucas** [comment]
Interesting, how would we go about rendering the node on the canvas like this while cursor down? Just concat into the nodes list?

Seems potentially quite render intensive to have reactflow re-render the entire list of nodes for every frame of the drag?

I will definitely have a try and report back here, just couldn't find any references to a solution to this so best case we just document a solution in this issue!

**Comment by Nick-Lucas** [comment]
Okay yep you're right @peterkogo this is possible in userland, key gubbins from my prototyping:

```ts
const reactFlowInstance = useReactFlow() // obviously need to wrap the component in ReactFlowProvider to hoist this value upward
const [drawing, setDrawing] = useState<false | { x: number; y: number }>(
  false,
)
const [drawingPosition, setDrawingPosition] = useState<
  false | { x: number; y: number }
>(false)

return <ReactFlow
  nodes={
    drawing && drawingPosition
      ? nodes.concat({
          id: 'DRAWING',
          type: 'box',
          position: {
            x: Math.min(drawingPosition.x, drawing.x),
            y: Math.min(drawingPosition.y, drawing.y),
          },
          data: { },
          style: {
            width: Math.abs(drawingPosition.x - drawing.x),
            height: Math.abs(drawingPosition.y - drawing.y),
          },
        })
      : nodes
  }
  selectionOnDrag={false}
  onPointerDown={(e) => {
    const element = e.target as HTMLElement | undefined
    if (element?.className.includes('react-flow__pane')) {
      const x = e.clientX
      const y = e.clientY

      const position = reactFlowInstance.screenToFlowPosition({
        x,
        y,
      })

      setDrawing(position)
      setDrawingPosition(position)

      console.log('DOWN', e.target, e.clientX, e.clientY)
    }
  }}
  onPointerLeave={() => {
    setDrawing(false)
    setDrawingPosition(false)
  }}
  onPointerMove={(e) => {
    if (drawing) {
      const x = e.clientX
      const y = e.clientY

      const position = reactFlowInstance.screenToFlowPosition({
        x,
        y,
      })

      setDrawingPosition(position)
    }
  }}
  onPointerUp={(e) => {
    console.log('UP', e.target, e.clientX, e.clientY)
    setDrawing(false)
    setDrawingPosition(false)
  }}
/>
```

there are some weird visual glitches, not sure what that's about but seemingly canvas related?

![Apr-10-2024 22-16-51](https://github.com/xyflow/xyflow/assets/8896153/d31dd5c0-f145-4cf6-b17c-244abd64e56a)

Not sure how well it would respond to a more expensive nodes list given this may force ReactFlow to do quite a bit of rendering internally, but it definitely works :)

**Comment by peterkogo** [comment]
As an addition you can also just add a CustomNode onPointerDown, and have an absolutely positioned child of the CustomNode that you resize. This should not trigger dimension updates inside ReactFlow and might be a bit more efficient.

You can also render a custom component inside the viewport through the <EdgeLabelRenderer> portal. (there is an extra ViewportPortal you can use in v12 for this, but it is essentially the same thing)
With this approach you can bail out of react flows logic while resizing.

**Comment by Nick-Lucas** [comment]
Thanks for the extra details! Those do both sound like better options. Looking forward to v12 as there are so many great improvements there! 🙂
