### ISSUE TITLE
Copy & Paste issue

### ISSUE THREAD

**Issue by zakaria-imzilen** [xyflow/xyflow#4125]
### Describe the Bug

While using copy & paste feature and the focus in on an input,
I noticed that when copying a string from that input and pasting in another one, 
it creates a new node and push to the Workflow

### Your Example Website or App

https://flowsit.ai

### Steps to Reproduce the Bug or Issue

Login:
- Email: test@gmail.com
- Password: Faruar05

Steps
1- Click on Start Here
2- Click on First Process
3- Click on the Node
4- Click on the Info Icon from the Toolbar (first one)
5- Click on "Documentation" Tab
6- Open "Requirements" Accordion
7- Write something in any input & copy it
8- Try to paste it in another input
9- Voila, now you end up with a new node!

### Expected behavior

It should simply paste my clipboard string correctly

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
You can pass a target to `useKeyPress('Meta+c', { target: document.querySelector('.react-flow') })` to bind the event to the React Flow container instead of the window.

**Comment by zakaria-imzilen** [comment]
It worked, thank you sir
