### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by maxembregts** [xyflow/xyflow#4127]
### Describe the Bug

```
nodes.push({
   key: `${key}-${task.key}`,
   id: task.key,
   data: { label, name: task.name, status },
   sourcePosition: 'left',
   targetPosition: 'right',
   position: { x: (Number(key) + 1) * 200, y: (initialLaneIndex + index) * 100 },
});

edges.push({
  key: `${key}-${task.key}`,
  source: task.key,
  target: parent,
});
                                         
 return (
        <div className="flow">
            <ReactFlow nodes={nodes} edges={edges} zoomOnDoubleClick={true} />
        </div>
    );
```
        
I get this warning in the console: Warning: Each child in a list should have a unique "key" prop.

I pass a key to both the nodes and the edges, why do I still get this warning?

### Steps to Reproduce the Bug or Issue

See code.

### Expected behavior

I expect no warning in the console.

### Platform

- OS: macOS
- Browser: Chrome
- Version: latest

**Comment by Khushboog24** [comment]
probably because your component is rendering multiple times but the key you're sending is the same. Also, give a key to <div className="flow">
