### ISSUE TITLE
`Handle` is supposed to accept `isValidConnection` prop but it is not supported

### ISSUE THREAD

**Issue by mcmxcdev** [xyflow/xyflow#4133]
### Describe the Bug

https://svelteflow.dev/api-reference/components/handle#custom-handle-with-validation mentions that `Handle` supports `isValidConnection` prop, but it doesn't.

I encounter `Object literal may only specify known properties, and '"isValidConnection"' does not exist in type 'HandleComponentProps'.ts(2353)` when trying to use it.

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

Be able to use `isValidConnection` on `Handle`, not just on `Flow`

Looking at alternative props, there is `onconnect` and `ondisconnect` on `Handle` but they probably trigger too late in the cycle when wanting to validate.

### Platform

- OS: Ubuntu 23.10
- Browser: Brave
- Version: [Version 1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by peterkogo** [comment]
Thanks for raising this issue, will be fixed with #4144

**Comment by moklick** [comment]
fixed in 0.1.3!
