### ISSUE TITLE
`Minimap` cannot be interacted with on a touch device

### ISSUE THREAD

**Issue by mcmxcdev** [xyflow/xyflow#4134]
### Describe the Bug

I was looking at some of the https://svelteflow.dev/examples on my iPhone (iOS 11) and noticed that the minimap cannot be interacted with. 

### Steps to Reproduce the Bug or Issue

1. Go to e.g. https://svelteflow.dev/examples on your phone (not sure if all touch devices are affected)
2. Try to interact with the `Minimap`
3. It doesn't do anything

### Expected behavior

I would expect to be able to tap the `Minimap` and swipe it and change the viewport position. Possibly also zooming in and out by pinching using two fingers.

### Platform

- OS: iOS 11
- Browser: Brave
- Version: v1.62.2

**Comment by peterkogo** [comment]
this will be fixed by #4143

**Comment by mcmxcdev** [comment]
Amazing, I appreciate the quick fix :rocket:

**Comment by peterkogo** [comment]
ETA for next Svelte Flow version is next week, just so you know

**Comment by bilogic** [comment]
The minimap in react-flow also cannot be interacted with on Windows Chrome

Check the `overview` example at https://react-flow-dev.netlify.app/

Should I open a new issue?

**Comment by bilogic** [comment]
@peterkogo I tested on `11.4.0-next.1` on my Android Chrome and it still doesn't seem to work

**Comment by moklick** [comment]
@bilogic please check out the latest version 11.11.2

**Comment by bilogic** [comment]
@moklick did that too and doesn't work, I tested `next` because I saw #4143 merged into `next`

**Comment by moklick** [comment]
fixed in 0.1.3!
