### ISSUE TITLE
onDrag node param has previous position with grid and snapToGrip enabled

### ISSUE THREAD

**Issue by aamalric-talend** [xyflow/xyflow#4138]
### Describe the Bug

Using the intersections code sandbox modified with a large grid and `snapToGrid` enabled, shows that the node received in `onDrag` callback has not the updated position but the old one.
This leads to a wrong intersection computation, see my sample here: [IntersectingNodesGrid](https://codesandbox.io/p/sandbox/intersectingnodesgrid-6cs927?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluuyvr1i0006356mqjch3vm8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluuyvr1i0002356mstnic1xo%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluuyvr1i0003356m7ejmddbf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluuyvr1i0005356mustjy388%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluuyvr1i0002356mstnic1xo%2522%253A%257B%2522id%2522%253A%2522cluuyvr1i0002356mstnic1xo%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cluuyvr1i0005356mustjy388%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluuyvr1i0004356mwsucwqeu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluuyvr1i0005356mustjy388%2522%252C%2522activeTabId%2522%253A%2522cluuyvr1i0004356mwsucwqeu%2522%257D%252C%2522cluuyvr1i0003356m7ejmddbf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluuyvr1i0003356m7ejmddbf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

![image](https://github.com/xyflow/xyflow/assets/119614409/42b2b0b2-fa1e-4804-9616-d8c9f1e502b9)

### Your Example Website or App

https://codesandbox.io/p/sandbox/intersectingnodesgrid-6cs927?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluuyvr1i0006356mqjch3vm8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluuyvr1i0002356mstnic1xo%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluuyvr1i0003356m7ejmddbf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluuyvr1i0005356mustjy388%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluuyvr1i0002356mstnic1xo%2522%253A%257B%2522id%2522%253A%2522cluuyvr1i0002356mstnic1xo%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cluuyvr1i0005356mustjy388%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluuyvr1i0004356mwsucwqeu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluuyvr1i0005356mustjy388%2522%252C%2522activeTabId%2522%253A%2522cluuyvr1i0004356mwsucwqeu%2522%257D%252C%2522cluuyvr1i0003356m7ejmddbf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluuyvr1i0003356m7ejmddbf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce the Bug or Issue

1. Move slowly the Node1 box to enter the Node3 box
2. Visually intersecting but no highlighting

### Expected behavior

The onDrag callback should receive the node with it's updated position.

### Platform

- OS:  macOS, Windows, Linux
- Browser: Chrome, Safari, Firefox
- Version: 11.10.4

**Comment by peterkogo** [comment]
Oh yes, this is definitely a bug. Great find!

**Comment by moklick** [comment]
Thanks @aamalric-talend ! Will be fixed with the next release.

**Comment by aamalric-talend** [comment]
@moklick Thanks for the fix
