### ISSUE TITLE
Unable to render all the nodes and edges

### ISSUE THREAD

**Issue by imvetri** [xyflow/xyflow#4145]
### Describe the Bug

I made this example to run react-flow without build system. 
I have two nodes and one edge, but it is rendering only one node.

Can you tell me how to fix it?

https://github.com/imvetri/ui-editor/pull/578/files#diff-6f8110e2658683b224e4ae04c5f8b95dbf34d4a45ca52b4f558134771b485e26R41

### Steps to Reproduce the Bug or Issue

1. Open https://github.com/imvetri/ui-editor/pull/578/files#diff-6f8110e2658683b224e4ae04c5f8b95dbf34d4a45ca52b4f558134771b485e26R41
2. Download the html file
3. Open in browser

### Expected behavior

It should render two nodes and one edge

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
The `node.id` needs to be a string. Replace this `id: 1` with `id: '1'` and it should work.
