### ISSUE TITLE
90% GPU utilization for animated edges

### ISSUE THREAD

**Issue by kevinschaich** [xyflow/xyflow#4149]
### Describe the Bug

My GPU and fans are going crazy when edges have `animated: true`.

I've set `onlyRenderVisibleElements={true}` and this helps a bit – if I scroll to a section of the canvas with no edges it idles around ~24%. But if I go to an area with even one animated node it's at like 95%.

### Steps to Reproduce the Bug or Issue

See gif below

### Expected behavior

Expect lower utilization when there's only a few nodes and one edge in view

### Screenshots or Videos

![Export-1712892236040](https://github.com/xyflow/xyflow/assets/9244728/62a6b2e4-8b70-4014-a886-c07ee095ec00)

### Platform

- OS: MacOS
- Browser: Arc
- Version: 1.38.0

**Comment by peterkogo** [comment]
Do you have a 120hz screen by any chance? What kind of hardware are you running it on?

Can you check the performance tab in the browser, how long does it take for your GPU to render a frame?

Can you turn off all the shadows on your nodes and see how GPU utilization behaves? Maybe the layer of the shadow is being invalidated each frame and needs to be redrawn which can be quite expensive.

All that being said, might there be a comparison we could make of something similar being achieved with less utilization?

**Comment by moklick** [comment]
Animating complex svg paths is expensive. Probably the only solution for this would be a canvas renderer for edges (but we don't have that). I will leave it open for now as a reminder that there is room for optimization regarding edge animations.

**Comment by kevinschaich** [comment]
I do have a 120hz screen on both my laptop and my monitor. The monitor is 4k 120hz.

<img width="249" alt="image" src="https://github.com/user-attachments/assets/866ddd83-96d5-4b4c-9d01-2b77faaab040">

We're in the progress of moving to the new version of ReactFlow so I'll try turning off shadows and just using the animated edges.

Not using opacity, fill opacity, or stroke opacity, they should all be at 100% / not modified.

(Heavy caveat: I don't have a great understanding of how RF does rendering) I do think it's strange that an animated line is causing 90% GPU utilization yet you can do crazy 3D stuff in Three / WebGL without breaking a sweat, and even more crazy things like ray-tracing in native apps which are orders of magnitude more complicated. Is the reason it's expensive because the SVG node is a part of the DOM?

**Comment by peterkogo** [comment]
This seems to come down to Chromiums slower SVG implementation. I can definitely replicate a moderate GPU utilization ([which is a terribly imprecise metric btw](https://trainy.ai/blog/gpu-utilization-misleading)) when an animated edge is on-screen but I get like 30% at 120Hz on a M3 Pro.

I had issues before in Arc with specific plugins before - @kevinschaich  can you replicate it on Chrome inside an incognito window with all plugins disabled?

**Comment by kevinschaich** [comment]
Hey guys - I think we can close this out. We upgraded to v12 recently and also refactored a ton of our app – so either your rendering logic got way better, or maybe our state management logic got way better – either way, everything is smooth creamy 4k @ 120fps. Same laptop as earlier this year. Beaut.

Thanks for checking it out with me.

https://github.com/user-attachments/assets/fa730a38-b236-4090-a7ba-67d5521932c5

**Comment by peterkogo** [comment]
@kevinschaich That is wonderful to hear. v12 indeed had quite significant performance improvements.
