### ISSUE TITLE
Edges not rendering with production build.

### ISSUE THREAD

**Issue by sankhlepawan** [xyflow/xyflow#4150]
### Describe the Bug

I am working with reactflow 11.10.4 everything working fine. until I create a production build using craco build.
once deploy edges are not rendering properly even logo css is not applying. please find below screenshot.

However, I tried it with version 10.3.17 and it is working as expected.

### Steps to Reproduce the Bug or Issue

use craco with provided config below. build using craco build and run.

### Expected behavior

use version 11.10.4 with craco with the below config provided. 
Build a production build using craco build and deploy.

### Screenshots or Videos

version: 11.10.4
![Screenshot 2024-04-12 at 9 33 10 PM](https://github.com/xyflow/xyflow/assets/46869561/b3a0ddb9-ea5b-4066-80ba-e5e0382d5eef)

version: 10.3.17
![Screenshot 2024-04-12 at 9 37 05 PM](https://github.com/xyflow/xyflow/assets/46869561/2c0aab17-f9b7-43c0-b3be-793cc3592fbe)

### Platform

- OS: macOS
- Browser: Chrome
- Version: all

### Additional context

craco config as below.

const path = require("path");

const glob = require("glob");
const { PurgeCSSPlugin } = require("purgecss-webpack-plugin");
const { CracoAliasPlugin } = require("react-app-alias");

module.exports = {
  babel: {
    presets: [],
    // For targeting nested components https://emotion.sh/docs/styled#targeting-another-emotion-component
    plugins: ["@emotion/babel-plugin"],
    loaderOptions: {},
  },
  plugins: [
    {
      plugin: CracoAliasPlugin,
      options: {},
    },
  ],
  jest: {
    configure: (jestConfig, { env, paths, resolve, rootDir }) => {
      return {
        ...jestConfig,
        restoreMocks: true,
        clearMocks: true,
        transformIgnorePatterns: [
          // Liquid components needs to be transpiled by Jest ( slows down tests a lot )
          "node_modules/(?!@emdgroup-liquid)/",
          "^.+\\.module\\.(css|sass|scss)$",
        ],
        collectCoverageFrom: [
          "src/components/**/*.{js,jsx,ts,tsx}",
          "src/features/**/*.{js,jsx,ts,tsx}",
          "src/hooks/**/*.{js,jsx,ts,tsx}",
          "src/layouts/**/*.{js,jsx,ts,tsx}",
          "src/pages/**/*.{js,jsx,ts,tsx}",
          "src/utils/**/*.{js,jsx,ts,tsx}",
          "!<rootDir>/node_modules/",
          "!<rootDir>/**/*.d.*",
          "!<rootDir>/**/types.ts",
          "!<rootDir>/**/index.{ts,tsx,js,jsx}",
        ],
        setupFilesAfterEnv: ["<rootDir>/src/tests/setupTests.tsx"],
        moduleDirectories: ["node_modules"],
        coverageThreshold: {
          "src/**/*": {
            branches: 85,
            functions: 85,
            lines: 85,
            statements: 85,
          },
          global: {
            branches: 85,
            functions: 85,
            lines: 85,
            statements: 85,
          },
        },
      };
    },
  },
  webpack: {
    plugins: {
      add: [
        // Clear up unused Liquid classes
        new PurgeCSSPlugin({
          paths: glob.sync(`${path.join(__dirname, "src")}/**/*`, {
            nodir: true,
          }),
          safelist: ["html", "body", /^token/, /^pre/, /^code/, /szh/],
        }),
      ],
      remove: [],
    },
    configure: {
      module: {
        rules: [
          {
            test: /\.m?js/,
            resolve: {
              // Allow import untranspiled Liquid modules
              fullySpecified: false,
            },
          },
        ],
      },
    },
  },
};

**Comment by bcakmakoglu** [comment]
Did you follow the v11 [migration guide](https://reactflow.dev/learn/troubleshooting/migrate-to-v11)?

It looks to me as if you're not importing the necessary styles, although from the little bit of code you gave us (not even sure what "craco" is supposed to be - a build tool? Never heard of that before tbh) it's not quite apparent what you're doing and why it's not working.

Best thing in these situations is to provide a sandbox repro for your issue 😄 

[You can find a template here.](https://new.reactflow.dev/react-ts)

**Comment by sankhlepawan** [comment]
Migration not required as we started with version 11.10.4 from scratch. and craco is Create React App Configuration Override tool. I just downgraded it to 10.3.17 when it was not working with 11.10.4. and it worked.

**Comment by bcakmakoglu** [comment]
Ah my bad should've been obvious that it's create react app 🤣 
Been using vite for so long I removed all other build tools from my brain


Okay that's interesting, I assumed you wanted to *upgrade* from 10 to 11.

Are the edges in the DOM? Can you check that?
What styles are applied on `react-flow__edges`?
Is `overflow: visible` possibly not enabled?

**Comment by bcakmakoglu** [comment]
Any chance that your prod build is simply not including react flow styles?
I see you're using PurgeCSS and I kinda suspect that the relevant styles for ReactFlow are removed by that.

It would explain why downgrading seemingly makes it work, since you wouldn't have to explicitly import the css anymore and it can't just be purged away.

**Comment by sankhlepawan** [comment]
You are great...as you explained...the culprit was PurgeCSS..its working fine now...

**Comment by moklick** [comment]
As @bcakmakoglu pointed out you need to import the styles as mentioned in the migration guide.
