### ISSUE TITLE
Get relative node position on Edge Drop for new node with parentNode

### ISSUE THREAD

**Issue by TrySpace** [xyflow/xyflow#4152]
### Please describe the feature that you want to propose

I'm trying to use the [Add Node On Edge Drop example](https://reactflow.dev/examples/nodes/add-node-on-edge-drop) and have the newNode add a `parentNode: connectingNodeId.current` prop so it will automatically belong to its parent.

But I can't figure out how to calculate the relative position because `event.clientX` is the absolute position which is not the one I need when it uses the parentNode's relative position.

I would like a way to get the relative position or to subtract the parentNode's x/y coords somehow? 
I saw this issue https://github.com/xyflow/xyflow/issues/3393 but I don't want to use absolute positioning for the grouped/parented nodes.

See [sandbox](https://codesandbox.io/p/sandbox/awesome-ritchie-yyjp82?file=%2FApp.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluyibyjc0007356ggblfqkif%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluyibyjc0003356g8xyg82cv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluyibyjc0004356gg7uq1ljb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluyibyjc0006356gdi1xngna%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluyibyjc0003356g8xyg82cv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluyibyjc0002356g4xysldkq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FApp.js%2522%257D%255D%252C%2522id%2522%253A%2522cluyibyjc0003356g8xyg82cv%2522%252C%2522activeTabId%2522%253A%2522cluyibyjc0002356g4xysldkq%2522%257D%252C%2522cluyibyjc0006356gdi1xngna%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluyibyjc0005356gkwpg5hw5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluyibyjc0006356gdi1xngna%2522%252C%2522activeTabId%2522%253A%2522cluyibyjc0005356gkwpg5hw5%2522%257D%252C%2522cluyibyjc0004356gg7uq1ljb%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluyibyjc0004356gg7uq1ljb%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 

It could be achieved if the `OnConnectEnd` event would have a `node` besides the `event` from which I could simply extract the `position` or 'absolutePosition` from. That node would be the node that I connect from.

/Update
I've tried to use `useRef` to store the origin node and calculate the position, but I can't get it to work right

**Comment by TrySpace** [comment]
What's working for me right now is this:

```ts
 const onConnectStart: OnConnectStart = useCallback((evt, node) => {
    const { nodeId } = node
    const pNode = nodeId ? getNode(nodeId) : {}
    // @ts-ignore
    parentNode.current = pNode
    connectingNodeId.current = nodeId
  }, [])

  const onConnectEnd: OnConnectEnd = useCallback(
    (event) => {
      if (!connectingNodeId.current) return

      const targetIsPane = (event.target as Element).classList.contains(
        'react-flow__pane'
      )

      if (targetIsPane) {
        // Get mouse position
        // @ts-ignore
        const clientX = (event?.clientX as number) || 0
        // @ts-ignore
        const clientY = (event?.clientY as number) || 0

        // Convert mouse coordinates to relative position
        const screenPos = screenToFlowPosition({
          x: clientX,
          y: clientY,
        })

        // Get the absolute position of the parent node (if any)
        const parentX = parentNode.current?.positionAbsolute?.x || 0
        const parentY = parentNode.current?.positionAbsolute?.y || 0

        // Subtract parent coords from relative screenPos
        const posX = screenPos.x - parentX
        const posY = screenPos.y - parentY

        const newId = getId()

        const newNode = NewNode({
          id: newId,
          position: { x: posX, y: posY },
          parentId: connectingNodeId.current,
        })

        setNodes((nds) => nds.concat(newNode))

        setEdges((eds) =>
          // @ts-ignore
          eds.concat({
            id: newId,
            source: connectingNodeId.current,
            target: newId,
          })
        )
      }
    },
    [screenToFlowPosition]
  )
```

This won't work anymore when I upgrade to v12 though...

**Comment by Fzlw** [comment]
Yes, I also encountered the same problem, is there any solution?

**Comment by peterkogo** [comment]
@TrySpace the solution you posted is the actual way you'd do it. The reason this does not translate 1:1 to RF 12 is because we moved `positionAbsolute` to the internals.

You can use `getInternalNode(parentId)` to get the InternalNode (node with all kinds of tracking information attached) and access `parentNode.internals.positionAbsolute`.

**Comment by peterkogo** [comment]
I will close this issue. Feel free to ask anything over at our [Discord](https://discord.gg/RVmnytFmGW).
