### ISSUE TITLE
It is not possible to call 'layout' with 'useNodesInitialized()' and controlled flow

### ISSUE THREAD

**Issue by uschen** [xyflow/xyflow#4153]
### Describe the Bug

Just start to learn react-flow. Awesome library!

I'm trying to trigger a custom layout of nodes after 'NodesInitialized'.

here is the outline of code:

```ts
const nodesInitialized = useNodesInitialized({ includeHiddenNodes: false });
const [nodes, setNodes] = useState<Node<any>[]>([]);
const [edges, setEdges] = useState<Edge<any>[]>([]);
const onNodesChange = useCallback((changes: NodeChange[]) => setNodes(nds => applyNodeChanges(changes, nds)), []);
const onEdgesChange = useCallback((changes: EdgeChange[]) => setEdges(eds => applyEdgeChanges(changes, eds)), []);

useEffect(() => {
    setNodes(initialNodesAndEdges.Nodes);
    setEdges(initialNodesAndEdges.Edges);
}, [initialNodesAndEdges]);

const onLayout = useCallback(() => {
    const nds = [...nodes];
    for (let index = 0; index < nds.length - 1; index++) {
        // doing layout
    }
    setNodes(nds);
    window.requestAnimationFrame(() => {
        fitView();
    });
}, [fitView, nodes]);

useEffect(() => {
    if (nodesInitialized) { onLayout() }
}, [nodesInitialized]);

```

so, the significant part is basically it is impossible for ` if (nodesInitialized) { onLayout() }` to depend on `onLayout` even if it should. Since the `onLayout` is depending on the *controlled* `nodes` and `nodesInitialized` is also depending on `nodes`, adding `nodes` to the `useEffect` will just trigger inf loop.

### Steps to Reproduce the Bug or Issue

See the example codes.

### Expected behavior

See the example codes.

### Platform

- Version: "reactflow": "^11.11.1"

**Comment by uschen** [comment]
a minor nitpicking about: https://reactflow.dev/api-reference/utils/apply-node-changes

```js

  const [nodes, setNodes] = useState([]);
  const [edges, setEdges] = useState([]);
  const onNodesChange = useCallback(
    (changes) => {
      setNodes((oldNodes) => applyNodeChanges(changes, oldNodes));
    },
    [setNodes],
  );

```

it is not necessary to add `setNodes` to the dependencies.

see: https://react.dev/reference/react/useCallback#updating-state-from-a-memoized-callback

**Comment by uschen** [comment]
seems to be related to https://github.com/xyflow/xyflow/issues/3946

**Comment by moklick** [comment]
You can use `getNodes` from `useReactFlow` inside your layout function to get the current nodes without passing `nodes` as a dependency. Does that help?
