### ISSUE TITLE
Select text inside node: chrome bug for transformed elements

### ISSUE THREAD

**Issue by Pronink** [xyflow/xyflow#4156]
### Describe the Bug

I detected a bad behaviour when you select text inside a text input inside a node. The text deselects when the mouse exit the node's body and reselects when you drag near top left of the canvas. 

I search for and I found that it's a chrome bug when selecting text of input with css tranform:
- Stackoverflow: https://stackoverflow.com/questions/38143005/transform-translatex-breaks-text-selection-in-inputs-in-chrome
- Chrome bug: https://issues.chromium.org/issues/41439320

Examples:
- https://jsfiddle.net/k42g91h1/1/
- https://codepen.io/siruppypancakes/pen/ZwJXax
- Video **using React-Flow** attatched below

**There is a workaround using css top and left properties instead of using transform**. I have created this issue to notify you of this problem so that you are aware and to see if some workaround could work well.

### Steps to Reproduce the Bug or Issue

Using a node with a text input:
- Write some text inside input
- Move the node at the center of the canvas
- Select the text from right to left dragging with the mouse and exit the node
- Move the mouse (keep dragging) to top left the canvas (imagining that there is a ghost node placed there)

Like the attatched video, you can select exactly the text you want from outside the node.

### Expected behavior

Chrome should follow the cursor taking into account the previous transformations and select taking into account the x position of the cursor.

### Screenshots or Videos

[2024-04-15 11-16-21.webm](https://github.com/xyflow/xyflow/assets/17512287/ae3ba936-ba5a-4124-9af8-65b7583484a0)

### Platform

- OS: Windows, Linux
- Browser: Chrome
- Version: 123

**Comment by peterkogo** [comment]
Using top, left coordinates has unmanageable implications for performance. This seems to be a browser problem we cannot mitigate on library side.

You can prevent this behavior by adding add a piece of css to the node while dragging the text selection (probably onpointerdown of the input node).

In you codepen this would be something like this: 
```css
#tanDiv::before {
  content: ' ';
  position: absolute;
  width: 5000px;
  height: 5000px;
  top: -2500px;
  left: -2500px;
}
```

This extends the node invisibly so the pointer never leaves the transformed div during selection.

**Comment by Pronink** [comment]
That's a good idea. I have implemented your idea using only css and it looks like it could work.
https://codepen.io/pronink/pen/ZEZjZvB

--------------------

I implemented your idea in my proyect and it works :smiley:  ¡¡thank you!!
```jss
// '&' being the node body root
'&:has(input:active)::after, &:has(textarea:active)::after': {
    content: '""',
    position: 'absolute',
    width: '10000px',
    height: '10000px',
    top: '-5000px',
    left: '-5000px',
    cursor: 'text',
}
```

But it is still a workaround for a chrome bug.

**Comment by peterkogo** [comment]
Happy to have helped!

**Comment by chr11115** [comment]
for me this solution did not suffice since it doesn't take the node order into consideration. If a node is higher in the DOM then hovering another node will still yield strange selection results...

Another workaround that seems to work for me is to capture the cursor when clicking on an input field.. e.g.

`function isInputDOMNode(target: HTMLElement): boolean {
  return ["INPUT", "SELECT", "TEXTAREA"].includes(target?.nodeName) ||
    target?.hasAttribute("contenteditable");
}

function handleMouseDownCapture(event: React.PointerEvent) {
  if (event.target instanceof HTMLElement && isInputDOMNode(event.target)) {
    // Workaround for Chrome bug where pointer location doesn't match translated div location when selecting text
    // https://issues.chromium.org/issues/41439320
    event.target.setPointerCapture(event.pointerId);
  }
}

function MyReactFlowComponent() {
[...]

return (
  <ReactFlow
    onPointerDownCapture{handleMouseDownCapture}
  ...
  />
)
}`
