### ISSUE TITLE
Setting connectionMode to loose prevents self-connections from handles rendered in the same CustomNode

### ISSUE THREAD

**Issue by jonlev1n** [xyflow/xyflow#4161]
### Describe the Bug

Using the [Easy Connect](https://reactflow.dev/examples/nodes/easy-connect) example, setting the `connectionMode` prop to "loose" somehow disables the ability for the source handle to connect to a target handle rendered in the same node. 

### Steps to Reproduce the Bug or Issue

1. Open [Easy Connect](https://reactflow.dev/examples/nodes/easy-connect) in the code sandbox
2. Set `connectionMode={ConnectionMode.Loose}`
3. Observe that the connection line no longer "snaps" when the source node and target node are the same 

### Expected behavior

As a user, I would expect that the `ConnectionMode.Loose` would not prevent self-connection

### Screenshots or Videos

With default strict settings:

https://github.com/xyflow/xyflow/assets/8312367/4c9c748a-cb22-4e0c-b770-f13a75c6d9fa

And with loose:

https://github.com/xyflow/xyflow/assets/8312367/a1f45f22-fcb1-46df-8959-86592419168d

### Platform

- OS: macOS 14.2.1 [arm64]
- Browser: Chrome 123.0.6312.122
- Reactflow: 11.11.1

**Comment by peterkogo** [comment]
You need to set handle ids if you want to use `ConnectionMode.Loose` because it ignores handle types and there is nothing left to distinguish the source and target handles on the same node.

However, this issue uncovered another bug, so thanks for raising it non-the-less!
