### ISSUE TITLE
Firefox: The selection is reset to none.

### ISSUE THREAD

**Issue by lwl5219** [xyflow/xyflow#4162]
### Describe the Bug

**Purpose** Users can select multiple nodes and edges when the React flow is working in the selection mode. I desire to switch the _selectionOnDrag_ mode to _panOnDrag_ mode while the selection ends.

**Mechanism**  I capture the `onSelectionEnd` event and set the `setSelectionOnDrag(false)`. This works well on Chrome and Edge. However, it is **failed on Firefox**.

### Your Example Website or App

https://codesandbox.io/p/sandbox/multipleselectiondemo-forked-4mq5xc

### Steps to Reproduce the Bug or Issue

1. Check the checkbox of _select_
2. Press down the left mouse key and drag it to select several nodes and edges
3. Lift the left mouse key

### Expected behavior

While the selection ends, the React flow is under the _panOnDrag_ mode instead of _selectionOnDrag_ mode and the selected nodes and edges are kept.

### Screenshots or Videos

The selection doesn't work on **Firefox**

![FailedInFirefox](https://github.com/xyflow/xyflow/assets/4666735/768b1404-f93d-4e8e-aa9c-df766fac820a)

The selection works well on Chrome or Edge

![WellInEdgeChrome](https://github.com/xyflow/xyflow/assets/4666735/b5dbd04f-b4b9-4b2f-91d5-786277a0c370)

### Platform

- OS: Windows 10 (64-bit)
- Browser: Firefox (v124.0.2), Edge (v123.0.2420.97), Chrome (v121.0.6167.140)

**Comment by peterkogo** [comment]
What version of React Flow are you using?

**Comment by moklick** [comment]
Seems to be a weird race condition 🤔 Easiest fix for now on user side is to wrap the setter with `requestAnimationFrame`:

```js
const onSelectionEnd = useCallback(() => 
  requestAnimationFrame(() => setSelectionOnDrag(false)),
  [setSelectionOnDrag]
);
```

**Comment by lwl5219** [comment]
Thanks @moklick. This workaround works well for me. 

The common usage of `requestAnimationFrame` is to perform an animation. I'm pretty curious why this function can bypass this issue on Firefox. I would appreciate it if you have time to give me a description of the reason.

**Comment by moklick** [comment]
It seems to be a race condition, where `onSelectionEnd ` is triggered too fast / at the same as `onSelectionChange` which leads to an outdated nodes state. With `requestAnimationFrame` we can wait until the next repaint (or actually just before the next repaint) to delay it a tiny bit.
