### ISSUE TITLE
Cannot pass component as a label.

### ISSUE THREAD

**Issue by leochoo** [xyflow/xyflow#4163]
### Describe the Bug

My project is using React and TypeScript.
I followed the example [here ](https://reactflow.dev/learn/concepts/core-concepts#connecting-nodes).

I copied the code files exactly.
I changed `js` extension to `ts`.

However, although it says `you can also pass a React component as a label`, I realized that in my project it breaks.

```js
  {
    id: "2",
    // you can also pass a React component as a label
    data: { label: <div>Default Node</div> },
    position: { x: 100, y: 125 },
  },
```

Error:
![CleanShot 2024-04-16 at 17 47 57@2x](https://github.com/xyflow/xyflow/assets/26427048/ab832286-8d17-46af-ab1b-1bd4132d9833)
![CleanShot 2024-04-16 at 17 47 40](https://github.com/xyflow/xyflow/assets/26427048/bfeb72fe-6ec5-474e-822e-c566fb31c78f)

## Reproduction of the bug
I cannot even reproduce this properly because it fails to recognize nodes and edges.ts on code sandbox somehow... but here is a good starting point.

(It seems like sandbox can sometimes reproduce, but not exactly)
![CleanShot 2024-04-16 at 17 49 45](https://github.com/xyflow/xyflow/assets/26427048/270c77d2-3293-4f0d-9067-3e293612e6dd)

https://codesandbox.io/p/sandbox/bug-react-flow-component-label-qvvfn3?file=%2Fsrc%2FApp.tsx%3A9%2C42

What else can i try to solve this issue?

### Steps to Reproduce the Bug or Issue

Go to sandbox

### Expected behavior

It should accept React component as a label for TypeScript.

### Platform

- OS: macOS
- Browser: Edge
- Version: 123.0.2420.97 (Official build) (arm64)

**Comment by bcakmakoglu** [comment]
Not sure where exactly you got that sandbox from but there's a couple things wrong with it.

1. Missing styles for the app wrapper so the flow wouldn't show up even if there wasn't an error as you describe
2. Trying to import from `edges.ts` when there's only a `edges.js` file
3. Mixing `tsx` and `js` files (not necessarily wrong but for this sandbox demo why mix?)
4. Putting the label into `""` double quotes will not render a jsx element but a literal string

Here's the sandbox corrected and no errors: https://codesandbox.io/p/sandbox/bug-react-flow-component-label-forked-fphfmn?file=%2Fsrc%2Fnodes.js%3A13%2C43

**Comment by bcakmakoglu** [comment]
Sandbox link is still the same one that I saw when I first opened it, so either you forgot to save changes or the link is wrong 😄

**Comment by leochoo** [comment]
@bcakmakoglu 
I updated the original question with updated screenshots!
I also made sure the link is correct! Sorry for the trouble.

**Comment by moklick** [comment]
This is not an issue with React Flow. If you want to write JSX, you should use ".tsx" as a file extension instead of ".ts".

**Comment by leochoo** [comment]
Changing it to `tsx` and adding `Node[]` type indeed fixed the issue. thanks.
