### ISSUE TITLE
`isValidConnection` prop on `SvelteFlow` doesn't trigger for attempted target to target or source to source handle connections  

### ISSUE THREAD

**Issue by mcmxcdev** [xyflow/xyflow#4171]
### Describe the Bug

As can be seen in the video below, the validation between handles using `isValidConnection` only kicks in for certain attempted connections.

We would also like to validate an attempted source to source or target to target connection and give the user information about why this is not allowed.

### Steps to Reproduce the Bug or Issue

- create a `SvelteFlow` using `isValidConnection` prop
- create two nodes each having a target and source handle
- try to connect source to source or target to target
- expect `isValidConnection` to not get triggered

### Expected behavior

I would expect any attempted connections between handles to trigger `isValidConnection`

### Screenshots or Videos

[Screencast from 2024-04-17 09-17-45.webm](https://github.com/xyflow/xyflow/assets/16797721/76c0b9cd-b4b6-4fc5-8c69-c8d56d6e0fa1)

### Platform

- OS: Ubuntu 23.10
- Browser: Brave
- Version: Version 1.64.122 Chromium: 123.0.6312.122 (Official Build) (64-bit)

**Comment by moklick** [comment]
Does it work for your @mcmxcdev ?

**Comment by mcmxcdev** [comment]
It ended up not being a high priority for us; an initial check worked fine, but I will test this out properly some other time! 

Closing the issue in the meantime
