### ISSUE TITLE
`MiniMap`'s mask doesn't cover the entire area

### ISSUE THREAD

**Issue by mavdryk** [xyflow/xyflow#4178]
### Describe the Bug

There is a line at the bottom of the MiniMap that isn't covered by the svg mask

### Your Example Website or App

https://vnphv5.csb.app/

### Steps to Reproduce the Bug or Issue

Go to the provided link
Check the bottom line of the MiniMap
It has the white line instead of the grey color of the mask

### Expected behavior

MiniMap shouldn't have the line at the bottom

### Screenshots or Videos

![image](https://github.com/xyflow/xyflow/assets/25711177/641bc040-ee8e-4736-b57a-24f23622c8e6)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Will be fixed with the next release. As a workaround you can do:

```css
.react-flow__minimap svg {
  display: block;
}
```

(It's already fixed in React Flow 12)

**Comment by moklick** [comment]
fixed in 11.11.3
