### ISSUE TITLE
Can't get "nodeLookup"  from useStoreApi() 

### ISSUE THREAD

**Issue by LehanChancetop** [xyflow/xyflow#4191]
### Describe the Bug

I want to get "nodeLookup" form useStoreApi() ,but it get undefined.
"getNodeRect", "getInternalNode"  have the same problem form useReactFlow()

### Your Example Website or App

https://codesandbox.io/p/sandbox/objective-brahmagupta-g4jd9q?file=%2FResizeRotateNode.js%3A48%2C46

### Steps to Reproduce the Bug or Issue

In the child component, call useStoreApi() and return the state.

### Expected behavior

I want use  "nodeLookup" form state

### Platform

- OS: macOS
- Browser: Chrome

**Comment by moklick** [comment]
`nodeLookup` (and `getInernalNode`) is only available in v12 (package name 'xyflow/react'). The example uses v11 (package name 'reactflow').
