### ISSUE TITLE
sketch marks when using Chrome and Edge with very small zoom

### ISSUE THREAD

**Issue by zhaoyu1999** [xyflow/xyflow#4200]
### Describe the Bug

When using Chrome and Edge, if you use a small zoom, there will be some sketch marks after dragging connected nodes. Firefox works fine.

### Your Example Website or App

https://codesandbox.io/p/sandbox/reactflow-marks-95dc6v

### Steps to Reproduce the Bug or Issue

- Set a small zoom
- Let an edge have a z-turn.
- Drag the node.

### Expected behavior

The sketch marks should not appear

### Screenshots or Videos

![marks](https://github.com/xyflow/xyflow/assets/1793554/5eee25d0-82be-45ef-926a-f2b004169cd8)

### Platform

- OS: Windows
- Browser: Edge
- Version: 123.0.2420.97

**Comment by moklick** [comment]
I don't think this is something we could fix, but we will check it.

**Comment by peterkogo** [comment]
You can potentially fix this by simply setting `outline: none` on the outer div of your custom node as per [this issue](https://github.com/xyflow/xyflow/issues/4886#issuecomment-2580113551).
