### ISSUE TITLE
FitViewOptions not working with Controls component

### ISSUE THREAD

**Issue by ChevalMonsieur** [xyflow/xyflow#4201]
### Describe the Bug

On svelteflow, when using the fitViewOptions for fitView, if you put fitViewOptions as a prop to the Controls component like this :
```js
<Controls {fitViewOptions} showLock={false}>
```
with a fitViewOptions that look like this : 
```js
const fitViewOptions = {
    duration: 400,
};
```
it doesn't do anything except throwing a warning ```<Controls> was created with unknown prop 'fitViewOptions'```

fitViewOptions works if I call it like this in fitView however : 
```js
fitView(fitViewOptions);
```
and the documentation looks like saying you can put fitViewOptions as a prop in Controls just as showLock
![image](https://github.com/xyflow/xyflow/assets/126174925/4a33882d-49f7-46d9-86a4-2c7f01882e9e)

### Steps to Reproduce the Bug or Issue

1. Create a <SvelteFlow> component in your svelte app
2. put a <Controls> component inside
3. create a fitViewParameter prop like I did earlier and put it inside the <Controls> component 
4. launch the app and see the warning

### Expected behavior

The options put in parameter of fitViewOptions should have been integrated to the fitView button on the Controls component and shouldn't throw a warning

### Platform

- OS: [Ubuntu]
- Browser: [Neutralino]
- Version: [^0.0.41]

**Comment by ChevalMonsieur** [comment]
A workaround for this : 

```svelte
        <Controls showFitView={false} showLock={false}>
            <ControlButton on:click={fitViewWithOptions}>SVG</ControlButton>
        </Controls>
```

with fitViewWithOptions being : 
```js
function fitViewWithOptions() {
    fitView(fitViewOptions);
}
```

**Comment by moklick** [comment]
I think the docs are wrong here. There are not fitViewOptions for the `Controls` component. However we will see if we can add it.
