### ISSUE TITLE
Node rendering inconsistent between Mac and Windows with Chrome

### ISSUE THREAD

**Issue by paulleonartcalvo** [xyflow/xyflow#4208]
### Describe the Bug

When using padding on a node with `width` === `height` and `borderRadius: '50%'`, subsequent concentric circles within the node are slightly off-center. It renders fine on Mac but not on Windows. I replicated the bug in the code sandbox and attacked screenshots showing how the element inspections show the circle is off center. It's very subtle but you can see its definitely there. The gap between the inner and outer radius is smaller at the 120 degree mark.

**I noticed that altering the actual browser window zoom level seems to exacerbate this effect, though all the screenshots I provided were at browser default 100% zoom level**

I am running reactflow@11.11.1

### Your Example Website or App

[Sanbox](https://codesandbox.io/p/sandbox/awesome-rgb-hx9v6h?file=%2FConcentricCircleNode.js%3A1%2C1-30%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvevyd040007356iul28ww7k%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvevyd040003356is16wer5g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvevyd040004356i615tipaf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvevyd040006356icmu77fzt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B48.28754873587499%252C51.71245126412501%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvevyd040003356is16wer5g%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvevyd040002356iz6zaqz5d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvevyzzt003j356ijt9jrn4t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A57%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A57%257D%255D%252C%2522filepath%2522%253A%2522%252FColorSelectorNode.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvew7sgz0002356idpgvu5de%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A30%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252FConcentricCircleNode.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvevyd040003356is16wer5g%2522%252C%2522activeTabId%2522%253A%2522clvew7sgz0002356idpgvu5de%2522%257D%252C%2522clvevyd040006356icmu77fzt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvevyd040005356i4ykjgx44%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvevyd040006356icmu77fzt%2522%252C%2522activeTabId%2522%253A%2522clvevyd040005356i4ykjgx44%2522%257D%252C%2522clvevyd040004356i615tipaf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvevyd040004356i615tipaf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to Reproduce the Bug or Issue

1) Create a Node with padding, equal sides, and a border radius of 50%

```
{
          id: n,
          type: data.type,
          data,
          position: {
            x: 0
            y: 0,
          },
          style: {
            height: 48,
            width: 48,
            padding: 2,
            outline: "3px solid yellow",
            borderRadius: "50%",
            color: "#fff",
          },
          connectable: false,
        }
```

2) Create the custom node being used which creates a circle of 100% parent width and height, with display flex and center its contents

```
function MyNode(...props) {
  return <div style={{ height: '100%', width: '100%', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center' background: 'red'}}> 
   {...}
  </div>
}

```

3) Add a smaller circle to the center of the previous circle

```
function MyNode(...props) {
  return <div style={{ height: '100%', width: '100%', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'red'}}> 
   <div style={{width: '75%', height: '75%', borderRadius: '50%', background: 'blue' }} />
  </div>
}

```

The inner circle is not centered depending on the viewing platform.

### Expected behavior

I expect that with the styling above, the circles are perfectly concentric and the distance between the inner radius and outer radius is consistent across every point along the circumferences.

## On Mac (good)
![Image 4-25-24 at 2 40 AM](https://github.com/xyflow/xyflow/assets/93534747/37a661c0-30fc-4fb8-a3e4-e3635dd2c554)

## On Windows (bad)
![image](https://github.com/xyflow/xyflow/assets/93534747/5072a2c0-cd01-49b5-8ad9-32a865d35b7a)

## Provided sandbox on Mac (good)
![Image 4-25-24 at 3 02 AM](https://github.com/xyflow/xyflow/assets/93534747/fefe53f0-73fc-45f2-b6ca-74e9113425ba)

## Provided sandbox on Windows (bad)
![image](https://github.com/xyflow/xyflow/assets/93534747/b3e1cf78-ff6c-4b05-86a6-a7098a96bb30)

## At 100% (default) browser zoom on Windows chrome
![image](https://github.com/xyflow/xyflow/assets/93534747/12e6f80f-412a-4225-ba33-a70da2c4724b)

## At 90% browser zoom on Windows chrome
![image](https://github.com/xyflow/xyflow/assets/93534747/70c8e46c-9c03-4180-879d-d652f48e40ff)

## At 75% browser zoom on Windows chrome
![image](https://github.com/xyflow/xyflow/assets/93534747/cf79ed31-6817-471e-a6d1-4fc11ba6fffa)

## At 67% browser zoom on Windows chrome
![image](https://github.com/xyflow/xyflow/assets/93534747/dea62729-83e9-4f36-9f48-ca5da597cb2e)

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [124.0.6367.78]

**Comment by moklick** [comment]
Not sure if we can do anything about it. Does this also happen when you are not using `fitView`?

**Comment by moklick** [comment]
I checked this again and it's not something we could solve on library side. It seems to be a sub pixel rendering issue that might be better if you would round the viewport and the node positions. You could do this by using a controlled `viewport` + `onViewportChange` in combination with rounding node positions in `onNodesChange`.
