### ISSUE TITLE
Add `avoidNodes` prop to getSmoothStepPath, getBezierPath and getSimpleBezierPath

### ISSUE THREAD

**Issue by DenisLantero** [xyflow/xyflow#4213]
### Please describe the feature that you want to propose

Add `avoidNodes` to the utils functions that calculate the path for the edges (`getSmoothStepPath`, `getBezierPath`, and `getSimpleBezierPath`), which will make the edge not intercept any nodes.

This is very similar to what this library does: https://github.com/tisoap/react-flow-smart-edge/, but without any speed limitations since it will have direct access to the nodes.

**Comment by moklick** [comment]
Hey!

It would be a super nice feature but it is not planned and we will probably never had a functionality like this to the core. 

All internals are accessible vie useStore so if anyone wants to create a third party package it's definitely possible.
