### ISSUE TITLE
Add "Reset zoom to 1" button as part of `Controls`

### ISSUE THREAD

**Issue by mcmxcdev** [xyflow/xyflow#4225]
### Please describe the feature that you want to propose

Currently when doing updates on a canvas, inspected elements show scaled dimensions based on zoom level rather than their intrinsic ones. Being able to reset the view quickly would be very helpful.

Browsers also allow zooming in and out and reset the zoom level with e.g. `Strg+0` keyboard shortcut.

This functionality could be easily added disabled by default and configurable same like e.g. `showFitView` is currently.

**Comment by moklick** [comment]
Hey @mcmxcdev 

we had a lot of question about additional buttons for the controls. We decided to keep it simple but export a `ControlButton` component and the possibility to add buttons to the existing controls via slots.
