### ISSUE TITLE
The edge style is wrong when dragging

### ISSUE THREAD

**Issue by da-du** [xyflow/xyflow#4227]
### Describe the Bug

I set the edge type to 'step', but when dragging, the edge is not of type 'step'
```
defaultEdgeOptions={{
      type: 'step',
      style: {
          stroke: theme.colors.pattern.text.secondary,
      },
      markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 20,
          height: 20,
      },
  }}
```
![image](https://github.com/xyflow/xyflow/assets/106589025/d10294f6-194a-4b36-bb53-03705119fc50)

### Steps to Reproduce the Bug or Issue

1.set defaultEdgeOptions， type: 'step',
2.Create new connections between nodes

### Expected behavior

The edge type is 'step'

### Platform

- OS: macOS
- Browser: Chrome
- Version: 123.0.6312.124

**Comment by bcakmakoglu** [comment]
An *edge* and a *connection line*  are two different things, hence why `defaultEdgeOptions` will **not** change the style/type of a connection line.
**Edges** are established connections between two nodes.
**Connection Lines** are lines that are drawn to establish a connection between two nodes (in other words, the connection has not yet been created).

[There's a separate set of props for connection lines (besides using your own custom connection line).](https://reactflow.dev/api-reference/react-flow#connection-line-props)

In your case you would want to use something like this

```tsx
<ReactFlow connectionLineType={ConnectionLineType.Step} connectionLineStyle={{ stroke: theme.colors.pattern.text.secondary, }} {...rest}>
```
