### ISSUE TITLE
Minimap's onNodeClick doesn't work when using a custom minimap node

### ISSUE THREAD

**Issue by mirisony** [xyflow/xyflow#4237]
### Describe the Bug

When using a custom minimap node, the onNodeClick of the minimap doesn't work.

### Steps to Reproduce the Bug or Issue

1. Configure basic minimap code to use a custom minimap node.
2. Add onNodeClick to the minimap, for example:
<MiniMap
        nodeComponent={MiniMapNode}
        onNodeClick={(_event, node) => {
            console.log(node);
        }}
/>
4. Click on a minimap node.

### Expected behavior

As a user, I expected my callback to be called

### Platform

- OS: macOS
- Browser: Chrome

**Comment by peterkogo** [comment]
The custom minimap node receives an onClick handler as a prop. Because you are in charge of the dom node you need to call the handler yourself.
```jsx
<element onClick={(event) => props.onClick(event, nodeId)} />
```

**Comment by mirisony** [comment]
Thank you @peterkogo  🙏
