### ISSUE TITLE
React flow fails when execute inside a Microfrontend with Module federation

### ISSUE THREAD

**Issue by OscarLijoBusto** [xyflow/xyflow#4244]
### Describe the Bug

React flow fails when execute inside a Microfrontend with Module federation

### Steps to Reproduce the Bug or Issue

Create a Shell and Host Microfrontend like this example:
https://github.com/originjs/vite-plugin-federation?tab=readme-ov-file#usage

When the remote app uses reactflow crash

### Expected behavior

I expected the application to behave normally even if I was inside the remote

### Platform

- OS: Windows,
- Browsers: Chrome, Edge, Firefox...
- Version: Latest

**Comment by Tiagoperes** [comment]
Hello @OscarLijoBusto. Have you solved this problem? How?

**Comment by Rashiq50** [comment]
@Tiagoperes  can you please share how exactly i can edit the package.json of Reactflow ?
