### ISSUE TITLE
getEdges return connections, not edges

### ISSUE THREAD

**Issue by maliyshock** [xyflow/xyflow#4246]
### Describe the Bug

```const { setNodes, getEdges } = useReactFlow();```
```console.log("getEdges", getEdges());```

**Current behavior:** you will get a list of connections
`with id, source, sourceHandle, target, type and targetHandle` fields
Which is shorten version of Edge, which is connect.

**Expected behavior**
You should receive Edge accordingly the documentation
https://reactflow.dev/api-reference/types/react-flow-instance#get-edges
https://reactflow.dev/api-reference/types/edge
```getEdges: () => Edge<U>[];```
Get edge should return array of Edges, not `Connection[]`

### Steps to Reproduce the Bug or Issue

connect any 2 nodes and see what would you get from getEdges() function.
You will get a list of connections (connection is shorten version of edge)

```const { setNodes, getEdges } = useReactFlow();```
```console.log("getEdges", getEdges());```

**Current behavior:** you will get a list of connections
`with id, source, sourceHandle, target, type and targetHandle` fields
Which is shorten version of Edge, which is connect.

### Expected behavior

You should receive Edge accordingly the documentation
https://reactflow.dev/api-reference/types/react-flow-instance#get-edges
https://reactflow.dev/api-reference/types/edge
```getEdges: () => Edge<U>[];```
Get edge should return array of Edges, not `Connection[]`

### Screenshots or Videos

![image](https://github.com/xyflow/xyflow/assets/7099817/902a8612-7d54-4c06-9649-e264343ea55f)
![image](https://github.com/xyflow/xyflow/assets/7099817/6db117e5-ca91-4663-be50-92e80aa9feb7)

### Platform

macOS
Chrome
"reactflow": "^11.11.2",

**Comment by moklick** [comment]
The `getEdges` function returns the store edges: https://github.com/xyflow/xyflow/blob/v11/packages/core/src/hooks/useReactFlow.ts#L37-L40 

It will return whatever you passed as edges to the `ReactFlow` component. It's not a `Connection` or a short form of an edge.

**Comment by moklick** [comment]
Hey @maliyshock,

`onConnect` gets called when you connect two nodes. As a parameter it gets a connection, because it's not an edge yet. In your case you are using the helper function `addEdge` (a simple helper that adds an id and checks if that edge already exists) to create an edge of the connection.
