### ISSUE TITLE
Marker and node do not touch

### ISSUE THREAD

**Issue by luca-workera** [xyflow/xyflow#4257]
### Describe the Bug

Hi,
thank you for the great job!

I am experiencing this issue: when adding a node, the marker does not touch the node. The issue happens "randomly", by that I mean: I can add a node and the marker does touch it as expected, remove that node, and add it again and the issue happens. Or to just add a node and get the issue. There is no way to get it consistently.

From my tests, the issue is introduced on this version: https://github.com/xyflow/xyflow/releases/tag/11.10.4
No issue until this version: https://github.com/xyflow/xyflow/releases/tag/reactflow-11.10.3.tgz

I wonder if what I am saying rings any bells, happy to add more info on request,
Thank you,
Luca

### Steps to Reproduce the Bug or Issue

On a tree, add nodes and edges until the issue happens.

### Expected behavior

I expect to see the marker touching the node consistently.

### Screenshots or Videos

<img width="224" alt="Screenshot 2024-05-07 at 11 31 09" src="https://github.com/xyflow/xyflow/assets/141356205/b295032a-1f30-444a-89ce-3325232fd93b">

### Platform

- OS: tested on macOS, Windows, and Linux
- Browser: tested on Chrome, Safari, and Firefox
- Version: issue since 11.10.4

**Comment by peterkogo** [comment]
I will close this issue for now. Feel free to ask any questions over on [Discord](https://discord.gg/RVmnytFmGW) or reopen this issue with a reproduction.
