### ISSUE TITLE
Regression Bug: onNodeMouseEnter and onNodeMouseLeave fire more than once since 11.10.0, but was okay in 11.9.4

### ISSUE THREAD

**Issue by simonharrer** [xyflow/xyflow#4265]
### Describe the Bug

Regression Bug: onNodeMouseEnter and onNodeMouseLeave fire more than once since 11.10.0, but was okay in 11.9.4

```
<ReactFlow
          onNodeMouseEnter={
            (event, node) => {
              console.log('onNodeMouseEnter', event, node);
            }
          }
          onNodeMouseLeave={
            (event, node) => {
              console.log('onNodeMouseLeave', event, node);
            }
          }
```

This should fire only once when hovering over a node. Since 11.10.0 it fires multiple times.

### Steps to Reproduce the Bug or Issue

1. Register onNodeMouseEnter listener.
2. Register onNodeMouseLeave listener.
3. Hover over it.
4. Should fire the enter/leave events as one would expect, but not more.

### Expected behavior

Fire event once.

### Platform

- OS: macOS
- Browser: Chrome

**Comment by bcakmakoglu** [comment]
Can you provide a repro for this issue?
Trying to reproduce this in a fresh sandbox and it seems to work fine:

https://github.com/xyflow/xyflow/assets/78412429/52802114-1f8e-4ee9-a9e8-dd120a61b955

**Comment by moklick** [comment]
I can't reproduce this either. Please re-open with a codesandbox if the issue persists: https://new.reactflow.dev
