### ISSUE TITLE
Multiple parent nodes for one child node.

### ISSUE THREAD

**Issue by SannanOfficial** [xyflow/xyflow#4267]
### Please describe the feature that you want to propose

Allow for there to be multiple parents to one child node. (Image not drawn by me)
![react-flow-multiple-parent-v0-d6csrs90aoxb1](https://github.com/xyflow/xyflow/assets/67487579/0eb6deef-70ea-417b-a4e0-45cf6e522e7f)

**Comment by moklick** [comment]
We use the term "parent" / "child" node when it's about sub flows / nested flows. Your image just shows regular connections. With React Flow it's possible to have multiple up- and downstream nodes as you can see in this example: https://reactflow.dev/examples/layout/dagre
