### ISSUE TITLE
Include 'deletable' property with EdgeProps and NodeProps

### ISSUE THREAD

**Issue by TimmyTango** [xyflow/xyflow#4269]
### Please describe the feature that you want to propose

The `deletable` property exists on Nodes and Edges, but isn't exposed to NodeProps and EdgeProps. This means you can't use the `deletable` property for conditional rendering for Node and Edge types.

In my specific case, I want to hide the delete icon I normally show on Edges in my EdgeType if `deletable` is false. I tried to access `deletable` anyway, hoping it was just at the type level, but it's always undefined.

As a workaround, I'm adding my own `deletable` property in my Edge's `data` property.

**Comment by moklick** [comment]
Fixed with React Flow 12! If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12
