### ISSUE TITLE
useOnSelectionChange on change must be memoized now

### ISSUE THREAD

**Issue by jroith** [xyflow/xyflow#4273]
### Describe the Bug

The on change callback must be memoized using useCallback now. Otherwise the event triggers only when deselecting a node.

### Steps to Reproduce the Bug or Issue

1. Pass an onChange function to useOnSelectionChange that has not been wrapped in useCallback.
2. Observe that the event only triggers when deselecting a node.

### Expected behavior

 This should be documented as a breaking change or fixed.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment]
Thanks. Documented!
