### ISSUE TITLE
Node Drag behaviour affected by chrome developer console - d3.Force layout

### ISSUE THREAD

**Issue by buchananwill** [xyflow/xyflow#4274]
### Describe the Bug

The bug is visible on the Layouting page of reactflow.dev:

[https://reactflow.dev/learn/layouting/layouting#d3-force](url)

When the simulation is running, dragging a node does not update its location correctly unless the node is dragged to the extremity of the viewport. HOWEVER, when the console is open, the behaviour is as expected: nodes can be dragged when the simulation is running or not.

I have tried a lot of approaches and workarounds to get this working on my own set up, the package.json for which is as below. Various combinations of useRef, curried functions, global scoped functions with different parameters, and other context/state update tools have been tried. None of them has succeeded in the desired behaviour manifesting without the console window (F12) being open in Chrome (version 124.0.6367.158). Needless to say that is not a production-grade workaround...

### Your Example Website or App

https://codesandbox.io/p/sandbox/jovial-shadow-8k4n88

### Steps to Reproduce the Bug or Issue

In the video, the console is popping out of view behind the main chrome screen, but I'm also manually closing it and opening it with F12. You can see that the behaviour changes depending on whether I've just opened the console manually, or closed it manually.

`{
  "name": "graph-tools-demo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@headlessui/react": "^1.7.19",
    "@heroicons/react": "^2.1.3",
    "@nextui-org/accordion": "^2.0.32",
    "@nextui-org/button": "^2.0.31",
    "@nextui-org/card": "^2.0.28",
    "@nextui-org/chip": "^2.0.28",
    "@nextui-org/input": "^2.1.21",
    "@nextui-org/modal": "^2.0.33",
    "@nextui-org/popover": "^2.1.21",
    "@nextui-org/react": "^2.3.6",
    "@nextui-org/slider": "^2.2.9",
    "@nextui-org/switch": "^2.0.28",
    "@nextui-org/system": "^2.1.2",
    "@nextui-org/tabs": "^2.0.29",
    "@nextui-org/theme": "^2.2.3",
    "@nextui-org/tooltip": "^2.0.33",
    "@types/d3": "^7.4.3",
    "d3": "^7.9.0",
    "framer-motion": "^11.1.8",
    "heroicons": "^2.1.3",
    "lodash": "^4.17.21",
    "next": "14.2.3",
    "react": "^18",
    "react-dom": "^18",
    "reactflow": "^11.11.3",
    "selective-context": "file:D:\\Coding\\selective-context"
  },
  "devDependencies": {
    "@types/lodash": "^4.17.1",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.3",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "type-fest": "^4.18.1",
    "typescript": "^5"
  }
}`

### Expected behavior

I would expect the node dragging behaviour to be independent of whether the developer console is open.

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/139961977/b3caab98-4919-482d-ab45-bea4a04bbf98

### Platform

- OS: Windows
- Browser: Chrome
- Version: 124.0.6367.158

**Comment by buchananwill** [comment]
Moments later, I found a solution! Using the dragging callbacks, I pass the currently drag-engaged node into a ref. In the tick() function, I directly copy the position properties _from this ref_ for the node with matching ID.

`
    const draggingNodeRef = useRef<Node | undefined>(undefined);
    const {dispatchWithoutListen} = useGlobalDispatch(draggingNodeKey);

    useEffect(() => {
        dispatchWithoutListen(draggingNodeRef)
    }, [draggingNodeRef, dispatchWithoutListen])

    const handleDragStart = useCallback(
        (event: ReactMouseEvent, node: Node, nodes: Node[]) => {


            draggingNodeRef.current = {...node}
    }, [draggingNodeRef])

    const handleDragStop = useCallback(
        (event: ReactMouseEvent, node: Node, nodes: Node[]) => {
        console.log(node, nodes)

            draggingNodeRef.current = undefined
    }, [draggingNodeRef])

    const handleDrag = useCallback(
        (event: ReactMouseEvent, node: Node, nodes: Node[]) => {
        console.log(node, nodes)
            draggingNodeRef.current = {...node}
    }, [draggingNodeRef])

    useEffect(() => {
        setNodes(initialNodes as FlowNode[])
        setEdges(initialEdges as FlowEdge[])
    }, [initialNodes, initialEdges, setEdges, setNodes])

    return (

        <ReactFlow
            nodes={nodes}
            edges={edges}
            onNodesChange={onNodesChange}
            onEdgesChange={onEdgesChange}
            fitView
            onNodeDragStart={handleDragStart}
            onNodeDrag={handleDrag}
            onNodeDragStop={handleDragStop}
        >{children}
`

`
            const scopedNodes = nodeListRef.current;

            let foundDrag = false
            for (let i = 0; i < scopedNodes.length; i++){
                const node = scopedNodes[i];

                const dragging = draggingNode?.current?.id === node?.id
                // Setting the fx/fy properties of a node tells the simulation to "fix"
                // the node at that position and ignore any forces that would normally
                // cause it to move.
                const scopedNode = scopedNodes[i];
                if (dragging) {
                    foundDrag = true
                    nodeIndex = i
                    // Copy the current position from the ref
                    scopedNode.fx = draggingNode?.current.position.x;
                    scopedNode.fy = draggingNode?.current.position.y;
                } else {
                   delete scopedNode.fx
                    delete scopedNode.fy
                }
            }

            if (!foundDrag) nodeIndex = NaN
`

**Comment by peterkogo** [comment]
Glad you solved your issue! Thanks for posting a solution for future travelers.
