### ISSUE TITLE
Mini Map preview disappeared in 12.0.0-next.18

### ISSUE THREAD

**Issue by dAN0n** [xyflow/xyflow#4279]
### Describe the Bug

Hi,
I suppose mini map preview was somehow broken after upgrade from 12.0.0-next.17 to 12.0.0-next.18. Zooming and dragging works but without any elements inside, just gray square with white viewport.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-2bl2pz?file=src%2FApp.jsx

### Steps to Reproduce the Bug or Issue

1. The bug is visible in example app
2. On xyflow/react 12.0.0-next.17 mini map works as intended.

### Expected behavior

Mini map has a graph preview.

### Screenshots or Videos

12.0.0-next.18
![puush-linux+(2024-05-15+at+02 27 08)](https://github.com/xyflow/xyflow/assets/12194419/23136f12-98b4-4488-947c-cadba13f7168)
12.0.0-next.17
![puush-linux+(2024-05-15+at+02 27 54)](https://github.com/xyflow/xyflow/assets/12194419/37c25524-7745-4828-bbc0-5fbd5dae2192)

### Platform

- OS: Ubuntu 20.04.4 LTS
- Browser: Firefox 125.0.3, Chrome 123.0.6312.86
- Version: 12.0.0-next.18

**Comment by peterkogo** [comment]
You forgot to add onNodesChange and onEdgesChange handler. Plus, the nesting you are doing is not recommended and will result in weird side effects. [Here is a corrected sanbox.](https://stackblitz.com/edit/vitejs-vite-oyyyvh?file=src%2FFlowContainer.jsx)
