### ISSUE TITLE
Large Data React-Window Virtualization

### ISSUE THREAD

**Issue by choiyounghun0712** [xyflow/xyflow#4291]
### Please describe the feature that you want to propose

I'm using ReactFlow customized, but if there are 500 pieces of data, the scroll is stuttering. 

In this case, I'm trying to optimize rendering using a react-window, are there any options or methods available?

https://github.com/xyflow/xyflow/assets/130032473/e8fcbb17-24b8-493a-a2da-c189ecde42bb

**Comment by moklick** [comment]
You can use the `onlyRenderVisibleElements` prop. 

We want to improve the virtualization. You can follow that status here: #4239

**Comment by choiyounghun0712** [comment]
Thank you for your quick response.
 I have an additional question, '[React Flow]: Couldn't create edge for source handle id: s-right;'<- I'm ignoring the warning and using the feature. I wonder if the warning has a big impact on rendering. Is it okay to ignore it if it's not a big problem?

**Comment by moklick** [comment]
Do you only get that warning while using `onlyRenderVisibleElements`?

**Comment by choiyounghun0712** [comment]
No, it was a warning that occurred in the past regardless of the use of onlyRenderVisibleElements.

The flow is well displayed, but I think there is a problem internally because the warning is happening. I would like to get some guidance on how to fix the problem

I used onlyRenderVisibleElements, but it doesn't seem to have much effect on the screen, so I thought it might be a warning problem

The code I'm working on is as follows

https://codesandbox.io/p/sandbox/reactflow-9h9mfz?file=%2Fsrc%2Fcomponents%2FCallFlow.tsx%3A276%2C30

**Comment by moklick** [comment]
I can't see the warning in your codesandbox. The warning happens if you want to connect to handles or nodes that don't exist. Sometimes it's a race condition, because nodes get rendered, before the new edge state is set. Could that be the case here?

**Comment by moklick** [comment]
If that's the case you can safely ignore the warning. Or delay the next edge state a bit
