### ISSUE TITLE
prevent outcoming edge from target handle

### ISSUE THREAD

**Issue by minaBemani** [xyflow/xyflow#4292]
### Describe the Bug

In svelte flow the source handles work great but the handles with type target have a bug that edge come out of them. I mean source handles should be capable of edge coming out of them and they work properly right now, but edge must not come out of target handles and this is the bug about target handles.  Thanks for your consideration

### Steps to Reproduce the Bug or Issue

this is a bug in the library, i have no source code to share

### Expected behavior

prevent outcoming edge from target handle

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by peterkogo** [comment]
It is possible to connect a target handle to a source handle the same way you can connect a source handle to a target handle. Why shouldn't it be?

**Comment by minaBemani** [comment]
> It is possible to connect a target handle to a source handle the same way you can connect a source handle to a target handle. Why shouldn't it be?

Thanks for your response, I want the whole node to be connectable and act as target handle, but in this situation the node is not draggable anymore and edge comes out of it. The target handle should not be like this.

**Comment by minaBemani** [comment]
> It is possible to connect a target handle to a source handle the same way you can connect a source handle to a target handle. Why shouldn't it be?

Thanks for your response, I want the whole node to be connectable and act as target handle, but in this situation the node is not draggable anymore and edge comes out of it. The target handle should not be like this.

**Comment by peterkogo** [comment]
We have [two handle props ](https://reactflow.dev/api-reference/components/handle#is-connectable-start)that are not implemented yet in SvelteFlow that would achieve something like this.

In the meantime, I feel like there is a better solution to what you want to achieve. You can subscribe to the [connection](https://svelteflow.dev/api-reference/types/svelte-flow-store#connection) that is currently in progress through the store and apply `pointer-event: none;` to the target handles if there is currently no connection happening.

**Comment by minaBemani** [comment]
pointer-event: none; does not solve the issue and still edge comes out of target handle.

**Comment by peterkogo** [comment]
Take a look at our [easy-connect example](https://svelteflow.dev/examples/nodes/easy-connect). You can also conditionally render the handles. 

`pointer-events: none` works for me flawlessly.
```svelte
<Handle style="pointer-events: none;" {...} />
```
