### ISSUE TITLE
Edge marker is not dynamically updated

### ISSUE THREAD

**Issue by ysds** [xyflow/xyflow#4293]
### Describe the Bug

Changing `markerStart` and `markerEnd` of an Edge dynamically but the marker is not updated.

### Your Example Website or App

https://codesandbox.io/p/sandbox/hopeful-scott-xwsysm?file=%2FApp.js

### Steps to Reproduce the Bug or Issue

1. Go to the https://codesandbox.io/p/sandbox/hopeful-scott-xwsysm?file=%2Fpackage.json
2. Click the "Arrow" checkbox
3. **Marker is not rendered**
4. Drag a node
5. A marker appears

### Expected behavior

Markers should be updated immediately.

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/4065765/22e4b829-672e-43fe-9623-a23cbcd8743d

### Platform

- OS: Mac
- Browser: Chrome
- Version: 125.0.6422.61

**Comment by bcakmakoglu** [comment]
Don't mutate objects in your setter function, that's where the issue comes from.
Replace this
```ts
if (edge.id === "e1-2") {
  edge.markerStart = markerStart;
}
```

with this
```ts
if (edge.id === "e1-2") {
  return {
    ...edge,
    markerStart,
  };
}
```

[Here's your sandbox corrected.](https://codesandbox.io/p/sandbox/misty-wave-6yl8t3?file=%2FApp.js%3A31%2C9-36%2C10)

**Comment by ysds** [comment]
Thanks, but that Sandbox still doesn't seem to work correctly.

**Comment by bcakmakoglu** [comment]
The sandbox I linked seems to work completely fine. I open the sandbox, click the checkbox and see a red marker appearing without having to click/drag or do anything at all.

**Comment by ysds** [comment]
Is it possible that this is environmentally dependent? I am having problems in my environment described in the ticket.

https://github.com/xyflow/xyflow/assets/4065765/fa246ea7-722b-485b-b544-f708265ce491

**Comment by bcakmakoglu** [comment]
Mh... what browser is that? Chrome?

**Comment by bcakmakoglu** [comment]
Interesting, in Chrome it doesn't work but in FF it does 😄 
Seems to be a bug somewhere, that's strange

**Comment by ysds** [comment]
Dynamically instantiated SVG elements don't work: https://issues.chromium.org/issues/40656725
svg may needs an appropriate namespace.

https://github.com/xyflow/xyflow/blob/467223b9a321f6af4555244de0990ea2b766cd0c/packages/react/src/container/EdgeRenderer/MarkerDefinitions.tsx#L68
It is worth trying this:
```diff
- <svg className="react-flow__marker"> 
+ <svg xmlns="http://www.w3.org/2000/svg" className="react-flow__marker">
```
There seem to be other svg's in the codebase with no namespace defined.

**Comment by peterkogo** [comment]
Interesting find!

**Comment by ysds** [comment]
I found a workaround. This works fine in Chrome:
https://codesandbox.io/p/sandbox/focused-morse-8wm7s5

Add a custom edge marker, and set it in the`defaultEdgeOptions`:
```tsx
<svg style={{ position: `absolute`, width: 0, height: 0 }}>
  <defs>
    <marker
      id="default-edge-marker"
      viewBox="0 0 0 0"
      markerHeight={0}
      markerWidth={0}
    ></marker>
  </defs>
</svg>
<ReactFlow
  defaultEdgeOptions={{
    markerStart: `default-edge-marker`,
    markerEnd: `default-edge-marker`,
  }}
/>
```

**Comment by MMMMoriaty** [comment]
Awesome. How do you find this way out?

**Comment by moklick** [comment]
This is fixed in v12 and we won't fix it for v11. The namespace doesn't solve it unfortunately.

**Comment by moklick** [comment]
Fixed with React Flow 12! If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12

**Comment by bakl** [comment]
Same problem appears in safari ("@xyflow/react": "^12.9.3")
but the reason is different (some related info here: https://github.com/facebook/react/issues/29849)

The only workaround for now is to use a key for whole edge like:

`key={id+(hasMarkerStart ? '-start' : '')+(hasMarkerEnd ? '-end' : '')}`

it will trigger whole re-render of the edge when marker changed

@moklick can we reopen or create new issue?
