### ISSUE TITLE
Extra Objects needed

### ISSUE THREAD

**Issue by Muhammad1Siddique** [xyflow/xyflow#4296]
### Please describe the feature that you want to propose

let nodeData: NodeType[] = [{
        id: item.uuid,
        data: { 
          label: (
            <KubernetesIcon
              name={item?.name}
              type={item?.type}
              contextName={item?.contextName}
              namespace={item?.namespace}
              replicas={item?.replicas}
              phase={item?.phase}
              restartPolicy={item?.restartPolicy}
              serviceAccount={item?.serviceAccount}
              image={item?.image}
              podname={item?.podname}
              containername={item?.containername}
              readOnly={item?.readOnly}
              automountServiceAccountToken={item?.automountServiceAccountToken}
              creationTimestamp={item?.creationTimestamp}
            />
          ),
          expanded: true,
          title: item.name
        }, 
        position: { x: 0, y: 0 },
      }]
      
![Screenshot from 2024-05-21 18-00-49](https://github.com/xyflow/xyflow/assets/48084054/6c4dd9a4-034f-4d7c-b872-8dff7e87fcd8)

When I hovered over the label component, I encountered a bug where the hovercard appeared behind the node. I need assistance with the z-index sequence to ensure the hovercard displays correctly in front.

I need to add a title object to the customNode component to display a title at the location of the "Add Node" button.

**Comment by bcakmakoglu** [comment]
1. This isn't a feature request - there is a Discussion Board that can be used for questions like these ^^

2. Can you provide a minimal repro of your issue? That way it'd be easier to help you. The small bits and pieces of code you provide don't tell us anything about your setup etc.
[You can find a template here.](https://new.reactflow.dev/react-ts)
