### ISSUE TITLE
defining a fixed markerEnd (or Start) in custom Edge doesn't work?

### ISSUE THREAD

**Issue by wowtah** [xyflow/xyflow#4299]
### Describe the Bug

I have implemented a custom edge with a BaseEdge and an EdgeLabelRenderer, based on the example on: https://reactflow.dev/examples/edges/custom-edges (buttonEdge.tsx). 

I want to always show a predefined markerEnd when this edge type is used. So, on the BaseEdge I set the markerEnd:

` <BaseEdge path={edgePath} markerEnd={MarkerType.ArrowClosed} style={style} />`

But the arrow doesn't show. 

After some digging I found out that in the edges collection, the markerEnd property is of type
`(property) markerEnd?: EdgeMarkerType | undefined`

But when the property comes in through the EdgeProps it now is a:
`(parameter) markerEnd: string | undefined`

Curious as I was, I went to check what the string value would become:
`url('#1__color=#FF0072&height=20&type=arrowclosed&width=20')`

Then I thought, okay, it is a bit hacky, but if I define my own string in this format and pass it onto the markerEnd property of BaseEdge I could style it. But then the whole marker just disappears. 

**So how to achieve this? Am I doing something wrong? Or is this just unsupported or a bug?**

Apologies if this is more of a question than a bug maybe. 

My full code:

```
import React from "react";
import { BaseEdge, EdgeLabelRenderer, EdgeProps, getBezierPath, MarkerType } from "reactflow";

export default function CustomEdge({ id, sourceX, sourceY, targetX, targetY, sourcePosition, targetPosition, style = {} }: EdgeProps) {
  const [edgePath, labelX, labelY] = getBezierPath({
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition,
  });

  return (
    <>
      <BaseEdge path={edgePath} markerEnd={MarkerType.ArrowClosed} style={style} />
      <EdgeLabelRenderer>
        <div
          style={{
            position: "absolute",
            transform: `translate(-50%, -50%) translate(${labelX}px,${labelY}px)`,
            fontSize: 12,
            pointerEvents: "all",
          }}
          className="nodrag nopan"
        >
          My custom label renderer
        </div>
      </EdgeLabelRenderer>
    </>
  );
}
```

Any help would be appreciated. 

### Steps to Reproduce the Bug or Issue

1. Copy the code from the description. 
2. Arrow doesn't show

### Expected behavior

I would expect the marker arrow to show when I do:

`<BaseEdge path={edgePath} markerEnd={MarkerType.ArrowClosed} style={style} />`

Or, I would expect some way of implementing a fixed marker that comes with the custom Edge. 

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version:  "reactflow": "^11.11.3",

**Comment by bcakmakoglu** [comment]
You can just pass the marker definition when you create an edge, there's not much else to it.
As you noticed yourself, the definition you pass to an edge is not the same thing as the *marker id* you receive as a prop for Custom Edges and it's not gonna work passing `MarkerType.Arrow` to `BaseEdge` (and I doubt that's something that's gonna change anytime soon).

> Then I thought, okay, it is a bit hacky, but if I define my own string in this format and pass it onto the markerEnd property of BaseEdge I could style it. But then the whole marker just disappears.

That is because markers are created based on the definitions that are found in edges.
If no edge uses a markerEnd then *no marker will be created*.
So just copy+pasting the marker id and skipping the marker definition will *not* work as you experienced already.

So you will have to do this

```ts
{
	id: 'e1->2,
	source: '1',
	target: '2',
	type: 'custom',
	markerEnd: /* your marker def */
}
```

You can add the same thing for `onConnect` callbacks and check what type of edge you want to create and add the marker definition

```ts
const onConnect = (params: Edge | Connection) => {
	setEdges(edges => addEdge({ ...params, type: 'custom', markerEnd: /* your marker def */ }, edges)
}
```

**Comment by wowtah** [comment]
Thanks for the quick reply. 

It would have been nice if I could have put all of this behaviour inside the custom Edge component, then all the behaviour/styling related to the edge type would be in the same place.

 But I'll implement it in the edge collection for now.  Thanks!
