### ISSUE TITLE
I face a bug to align center expand and collapse flow

### ISSUE THREAD

**Issue by Muhammad1Siddique** [xyflow/xyflow#4302]
### Describe the Bug

I want to display react-flow in the center top to bottom but not able to do this at this time.

<section id='proflow'>
      <div className={FlowStyle.node}>
        <div className={FlowStyle.label} style={{ zIndex }}>{data.label}</div>
        <Handle position={Position.Top} type="target" />
        <Handle position={Position.Bottom} type="source" />
        <div className={FlowStyle.button}>
          {displayedText(data.title, 23, "...")}
        </div>
      </div>
    </section>

### Steps to Reproduce the Bug or Issue

display react-flow center

### Expected behavior

tree display top to bottom in the left side

### Screenshots or Videos

![Screenshot from 2024-05-23 18-06-48](https://github.com/xyflow/xyflow/assets/48084054/8ee2df1a-efbf-444d-bf46-368dfa751916)

### Platform

- OS: [ Linux]
- Browser: [ Chrome]
- Version: [22.04]

**Comment by peterkogo** [comment]
https://reactflow.dev/api-reference/types/react-flow-instance#fit-view

Please stop creating bug reports if you need help. 
We have a very active Discord where these things get answered. https://discord.gg/RVmnytFmGW
