### ISSUE TITLE
Export type definitions for individual methods and variables of `useSvelteFlow` functionality

### ISSUE THREAD

**Issue by mcmxcdev** [xyflow/xyflow#4304]
### Please describe the feature that you want to propose

We moved out `deleteEdge` functionality for reusabiity into a `.ts` file which looks like this:

`export const deleteEdge = (id: string, deleteElements: DeleteElements) => {`

Ideally, we would like to reuse svelteflow type definitions for `deleteElements` here, but we have to redefine them completely because there is no type/interface to import for it, they only exist as part of `useSvelteFlow()`

Just for reference, this is the verbose type definitions that we set up ourselves for now:

```
type DeleteElementsParams = {
  nodes?: (Node | { id: string })[] | undefined
  edges?: (Edge | { id: string })[] | undefined
}

type DeleteElementsResult = {
  deletedNodes: Node[]
  deletedEdges: Edge[]
}

type DeleteElements = (params: DeleteElementsParams) => Promise<DeleteElementsResult>
```

**Comment by bcakmakoglu** [comment]
Probably a good idea to have some of these types exported but for the time being you could also do this:

```ts
type DeleteElementsFn =  ReturnType<typeof useSvelteFlow>['deleteElements']
```

That way you at least don't have to copy+paste all the params ^^

**Comment by mcmxcdev** [comment]
Oh very cool, I was trying out `typeof useSvelteFlow` but didn't realize I could import `useSvelteFlow` as type only import. Thanks!

**Comment by moklick** [comment]
Thanks for the workaround @bcakmakoglu . We will add those missing types!

**Comment by peterkogo** [comment]
The approach suggested by @bcakmakoglu is the way to go here. There are no specific types we are able to export, because they are implicitly defined by `useSvelteFlow`.
