### ISSUE TITLE
lavaProps useControl

### ISSUE THREAD

**Issue by Muhammad1Siddique** [xyflow/xyflow#4308]
### Describe the Bug

When I load two components with different lavaProps, I face a bug when using control to hold the props value. When I load another ReactFlow component on a different page, I suspect that use control is defaulting to holding the value of the first component props. Is this a bug, or am I doing anything that is causing this issue? 
  ````
  
function MainFlowWrapper() {

  const levaProps = useControls({
    treeWidth: {
      value: 230,
      min: 0,
      max: 440,
    },
    treeHeight: {
      value: 100,
      min: 0,
      max: 200,
    },
    animationDuration: {
      value: 300,
      min: 0,
      max: 600,
    },
  });

  return (
    <div className='mainReactFlow react-flow-wrapper'>
        <ReactFlowPro {...levaProps} />
    </div>
    
  );
}
  ````
  
![screencapture-localhost-3000-workloads-nodes-2024-05-28-16_09_14](https://github.com/xyflow/xyflow/assets/48084054/707f742a-a1a7-4c04-b245-2cd744f15016)
![Screenshot from 2024-05-28 16-13-24](https://github.com/xyflow/xyflow/assets/48084054/5f3d1673-0453-40db-8045-d49a1ed9642e)

### Steps to Reproduce the Bug or Issue

1. when I load react flow it is ok with this use control configurations but when I load after this another component that creates impact first loading configuration

### Expected behavior

when i load the second component to display flow they display his own useControl congregation not first loaded configurations

### Screenshots or Videos

![Screenshot from 2024-05-28 16-13-24](https://github.com/xyflow/xyflow/assets/48084054/8b0e6468-1f45-4c4d-a870-b8a3faa5771a)
![screencapture-localhost-3000-workloads-nodes-2024-05-28-16_09_14](https://github.com/xyflow/xyflow/assets/48084054/faf3538d-8442-4f92-bc9f-68fcd78e171e)

### Platform

- OS: [Linux]
- Browser: [Chrome]

**Comment by Muhammad1Siddique** [comment]
any update about this bug

**Comment by moklick** [comment]
Could you create a codesandbox with a simplified example for this issue? https://new.reactflow.dev

**Comment by Muhammad1Siddique** [comment]
yes, I'm working on it and update you

**Comment by Muhammad1Siddique** [comment]
https://codesandbox.io/p/devbox/stoic-thunder-r2r9qv-forked-ztzfjg

This example code uses useControl to set the default height and width for both React Flow components. I display them using buttons, but when I click one button and then another, the default values do not update. This issue seems to occur when loading multiple components with different lavaProps, as useControl appears to hold the props value of the first component even when switching pages. I've created this example to demonstrate the bug for better understanding.

**Comment by moklick** [comment]
This has nothing to do with React Flow but with leva.

The easiest solution for this would be to name the controls like this:

In FirstFlow.tsx:

```js
 const levaProps = useControls("first-flow", {
    treeWidth: {
      value: 160,
...
```

SecondFlow.tsx:

```js
 const levaProps = useControls("second-flow", {
    treeWidth: {
      value: 160,
...
```

This way leva is able to distinguish between the different controls.
