### ISSUE TITLE
Removing extent attribute onNodeDragStart doesn't allows for free roam until after onNodeDragStop

### ISSUE THREAD

**Issue by dariovillalta** [xyflow/xyflow#4310]
### Describe the Bug

Hello everyone,

I am experiencing what I describe as a bug since I am updating the node state object onNodeDragStart and I see the changes being made in the console, but the funcionality that restricts a node inside the the parentNode because of the attribute extent: 'parent' stays in place, thinking It's some logic in the library but I think it should work the way I would expect it to.

Here's some code to recreate the issue:

`
import React, { useCallback, useEffect } from 'react';
import ReactFlow, {
  Background,
  Controls,
  useNodesState,
  useEdgesState,
} from 'reactflow';
import 'reactflow/dist/style.css';
import './styles.css'; // Ensure you create and import a styles.css file for custom styles

const MIN_NODE_HEIGHT = 100;
const SWIMLANE_WIDTH = 1000;
const SUBNODE_SIZE = { width: 200, height: 50 };

const SwimLaneNode = ({ id, data, selected }) => {
  const onMouseDown = (event) => {
    event.preventDefault();
    event.stopPropagation();

    const startY = event.clientY;
    const startHeight = data.height;

    const onMouseMove = (e) => {
      e.preventDefault();
      e.stopPropagation();
      const newHeight = Math.max(startHeight + (e.clientY - startY), MIN_NODE_HEIGHT);
      data.updateNodeHeight(id, newHeight);
    };

    const onMouseUp = (e) => {
      e.preventDefault();
      e.stopPropagation();
      document.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);
    };

    document.addEventListener('mousemove', onMouseMove);
    document.addEventListener('mouseup', onMouseUp);
  };

  return (
    <div
      className={`swimlane-node${selected ? ' selected' : ''}`}
      style={{ height: data.height, width: SWIMLANE_WIDTH }}
    >
      {data.label}
      <div className="resizer" onMouseDown={onMouseDown} />
    </div>
  );
};

const SubNode = ({ id, data, selected }) => {
  return (
    <div
      /* className={`sub-node1${selected ? ' selected' : ''}`} */
      style={{
        width: SUBNODE_SIZE.width,
        height: SUBNODE_SIZE.height,
        border: '1px solid black'
      }}
    >
      {data.label}
    </div>
  );
};

const initialNodes = [];
const initialEdges = [];

const nodeTypes = {
  swimlane: SwimLaneNode,
  subnode: SubNode,
};

const FlowComponent = () => {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

  const addSwimLane = useCallback(() => {
    setNodes((nds) => {
      const yPos = nds.reduce((acc, node) => acc + (node.type === 'swimlane' ? node.data.height : 0), 0);
      const newNode = {
        id: `${nds.length}`,
        type: 'swimlane',
        position: { x: 0, y: yPos },
        data: {
          label: `Swim Lane ${nds.length + 1}`,
          height: MIN_NODE_HEIGHT,
          updateNodeHeight: updateNodeHeight
        },
        draggable: false
      };
      return [...nds, newNode];
    });
  }, [setNodes]);

  const addSubNode = useCallback(() => {
    setNodes((nds) => {
      const swimLane = nds.find((node) => node.type === 'swimlane');
      if (!swimLane) return nds;

      const subNodesInLane = nds.filter((node) => node.data.parentId === swimLane.id);
      const nextY = subNodesInLane.reduce((acc, node) => acc + SUBNODE_SIZE.height, 0);

      const newSubNode = {
        id: `${nds.length}`,
        type: 'subnode',
        position: { x: 50, y: nextY },
        data: { label: `SubNode ${nds.length + 1}`, parentId: swimLane.id },
        parentNode: swimLane.id,
        extent: 'parent'
      };
      return [...nds, newSubNode];
    });
  }, [setNodes]);

  const updateNodeHeight = (id, newHeight) => {
    setNodes((nds) => {
      let updatedNodes = nds.map((node) => {
        if (node.id === id) {
          return {
            ...node,
            data: { ...node.data, height: newHeight },
          };
        }
        return node;
      });

      const index = updatedNodes.findIndex((node) => node.id === id);
      for (let i = index + 1; i < updatedNodes.length; i++) {
        updatedNodes[i] = {
          ...updatedNodes[i],
          position: {
            ...updatedNodes[i].position,
            y: updatedNodes[i - 1].position.y + updatedNodes[i - 1].data.height,
          },
        };
      }

      return updatedNodes;
    });
  };
  useEffect(()=>{
    console.log('\n\n\n nodes \n\n\n', nodes);
    for (let index = 0; index < nodes.length; index++) {
      console.log(index+')', nodes[index].extent)
    }
  }, [nodes]);

  const handleNodeDragStart = useCallback((event, node) => {
    let tempCopy = [...nodes];
    for (let nodesIndex = 0; nodesIndex < tempCopy.length; nodesIndex++) {
      if (tempCopy[nodesIndex].id === node.id) {
        delete tempCopy[nodesIndex].extent;
      }
    }
    setNodes(tempCopy);
  });

  const handleNodeDrag = useCallback((event, node) => {
  });

  const handleNodeDragStop = useCallback((event, node) => {
    setNodes((nds) => {
      const swimLanes = nds.filter((n) => n.type === 'swimlane');
      const subNodes = nds.filter((n) => n.type === 'subnode');
      console.log('\n\n\n11111\n\n\n')

      let updatedNodes = [...nds];

      return updatedNodes;
    });
  }, [setNodes]);

  return (
    <div id="react-flow-wrapper" style={{ height: '100vh', width: '100%' }}>
      <button onClick={addSwimLane}>Add Swim Lane</button>
      <button onClick={addSubNode}>Add SubNode</button>
      <ReactFlow
        nodes={nodes}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onNodeDragStart={handleNodeDragStart}
        onNodeDrag={handleNodeDrag}
        onNodeDragStop={handleNodeDragStop}
        nodeTypes={nodeTypes}
        fitView
        nodesConnectable={false}
        nodesDraggable={true}
        panOnDrag={false}
        panOnScroll
        panOnScrollMode="vertical"
      >
        <Background />
        <Controls />
      </ReactFlow>
    </div>
  );
};

export default FlowComponent;

`

### Steps to Reproduce the Bug or Issue

1. Create nodes with a parentNode and extent attributes. This so that the node can't move outside the parent node to create a subflow.
2. On onNodeDragStart remove the attributes or just the extent attribute so that in theory the node would be able to move outside the parent node.
3. The node can't be moved outside the parent node until you stop dragging the node, on the second attempt you will succeed.

### Expected behavior

As a user I am expecting for the removal of the attribute extent onNodeDragStart to allow me to move the node freely, but what I am experencing is that the node can only be moved outside the parent container until the second drag attempt.

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/11154263/1a847a1f-bbec-4838-8ac9-aeb511cb0ddb

### Platform

- OS: macOS
- Browser: Firefox
- Version: 126.0.1

### Additional context

Any help for getting to the desired functionaly will be greatly appreciated

_No response_

**Comment by bcakmakoglu** [comment]
> On onNodeDragStart remove the attributes or just the extent attribute so that in theory the node would be able to move outside the parent node.

What's the reasoning for doing this? Why apply an extent that is removed when dragging starts?

**Comment by dariovillalta** [comment]
> > On onNodeDragStart remove the attributes or just the extent attribute so that in theory the node would be able to move outside the parent node.
> 
> What's the reasoning for doing this? Why apply an extent that is removed when dragging starts?

So that it can be moved/dragged between different parent nodes, a more intuitive way to create subflows and change them on the fly.

Made a mistake in that video of not showing it but below of the node that says swim lane another node just like that may appear, and the idea is remove the extent attribute on drag start, on drag move capture the last entered swim lane and on drag stop apply the attribute extent again.

**Comment by bcakmakoglu** [comment]
Yeah but I still don't get why you need the extent at all if you're just gonna remove it on drag-start? 😄 
What use is the extent to you if it's supposed to *not* be applied during dragging?

**Comment by dariovillalta** [comment]
I may do something for visual purposes if I succeed but mostly so that the subnode can't be placed anywhere but inside any of the swim lanes.

**Comment by bcakmakoglu** [comment]
> I may do something for visual purposes if I succeed
Can you elaborate on that? What visual purposes would the extent fulfill if it's not applied during a drag?

>so that the subnode can't be placed anywhere but inside any of the swim lanes.
Not sure how this would apply either - the extent wouldn't be applied until you drag a node, until then even an extent set to `parent` would allow initial nodes etc. to be placed outside of the node as this extent is not initially enforced.

**Comment by dariovillalta** [comment]
https://github.com/xyflow/xyflow/assets/11154263/941fe3c5-c6b1-4873-b4cf-e9599147dde0

Ok so this is visually the effect I want to achieve, minus the fact that when I change the subnode to another swim lane it should move with the cursor.

Right now I'm doing it using the on node drag event, but there's a problem that when I change swim lane the drag of the subnode stops until I am deep enough on the other swim lane so it just goes at the bottom, it's the problem I've identified so far that I haven't fixed and may be the cause of the weird behaviour.

Right now in this video I am not removing the extent attribute, I just figure if I cant get to do it I will be able to achieve the desire behaviour without the visual effect of the subnode just sticking inside one of the swim lanes.

**Comment by dariovillalta** [comment]
Works on v12

Here's how I did it:
https://github.com/xyflow/xyflow/issues/4320

Thank you for your time @bcakmakoglu
