### ISSUE TITLE
Multiple dragging doesn't trigger onNodeDragStop event.

### ISSUE THREAD

**Issue by iam-frankqiu** [xyflow/xyflow#4312]
### Describe the Bug

on Mac pc, When you press shift and drag multiple nodes. It doesn't trigger onNodeDragStop event.

### Steps to Reproduce the Bug or Issue

https://codesandbox.io/p/sandbox/eager-golick-2wxq4g?file=%2FApp.js%3A128%2C23-128%2C37

### Expected behavior

onNodeDragStop event is triggered.

### Platform

- OS: [e.g. macOS, Windows, Linux] macOS
- Browser: [e.g. Chrome, Safari, Firefox] Chrome
- Version: [e.g. 91.1] all

**Comment by bcakmakoglu** [comment]
You need to differentiate between to concepts here
* Multiselect (by default using the Meta key and clicking multiple nodes one by one)
* Selection (by default Shift+Mouse to create a selection box)

These two are *not* the same thing
The first one will trigger `onNodeDragStop` the second one has their own event(s): https://reactflow.dev/api-reference/react-flow#on-selection-drag-start

**Comment by moklick** [comment]
This is confusing and we already changed it in React Flow 12 (https://github.com/xyflow/xyflow/discussions/3764). For v11 we will keep it as it is.
