### ISSUE TITLE
 How automatically enabled the lock viewport of controls in ReactFlow

### ISSUE THREAD

**Issue by gauravsingh7244** [xyflow/xyflow#4314]
### Please describe the feature that you want to propose

how we automatically enabled the lock feature of canvas viewport in controls

**Comment by bcakmakoglu** [comment]
The lock (interactive) button on the controls is controlled by 3 props: `s.nodesDraggable || s.nodesConnectable || s.elementsSelectable,`

If you set all of these to `false` on `<ReactFlow>` the icon would be locked, otherwise it's unlocked.

```tsx
<ReactFlow nodesDraggable={false} nodesConnectable={false} elementsSelectable={false} ...>
```
