### ISSUE TITLE
SvelteFlow: Copy/Paste (If not supported out-of-the-box, the easiest way to achieve it)

### ISSUE THREAD

**Issue by kerem0comert** [xyflow/xyflow#4317]
Hello,

I would like to be able to copy/paste single nodes or multiple nodes /edges grouped by either ```SHIFT```-based or ```CTRL```-based selection. Is this supported natively? If not, what would be the easiest approach to achieve this manually? At the moment I could find the following callback functions on the ```Flow``` component which might be relevant:

```svelte
<SvelteFlow
      fitView
      nodes={nodesWritable}
      edges={edgesWritable}
      {nodeTypes}
      on:nodecontextmenu={handleContextMenu}
      on:nodeclick={handleNodeClick}
      on:paneclick={handlePaneClick}
      on:dragover={onDragOver}
      on:drop={onDrop}
      on:selectionclick={() => { console.log('selectionclick') }}
      on:selectioncontextmenu={() => { console.log('selectioncontextmenu') }}
      on:selectstart={() => { console.log('selectstart') }}
      on:select={() => { console.log('select') }}
      on:nodemouseleave={() => { console.log('nodemouseleave') }}
      on:selectionchange={() => { console.log('selectionchange') }}
    >
```

But would be very happy if you have implemented this or have any suggestions in the right direction. Can I for instance use the ```useSvelteFlow``` hook to get currently selected nodes/edges and would this be the easiest way to achieve this (by writing the copy/paste functionality as an addition, as long as I can get the selected groups out)? Thanks!

**Comment by peterkogo** [comment]
`SHIFT` & `CTRL` based selection is nothing special, really. Both result in the nodes being selected. You can simply filter all nodes that have `selected = true` in your key listener for `META + C`, and than duplicate those elements with unique ids and add them to the nodes array. Maybe add a position offset, so they become visible.

**Comment by kerem0comert** [comment]
That's nice thank you. But the question is more about how exactly can I get these nodes in the first place. 

```svelte
      on:selectionclick={() => { console.log('selectionclick') }}
      on:selectioncontextmenu={() => { console.log('selectioncontextmenu') }}
      on:selectstart={() => { console.log('selectstart') }}
      on:select={() => { console.log('select') }}
```

does not really call the respective callbacks when I perform what I think the relevant UI actions, at least for me. 

When I have something like:
```svelte
 const { getNode } = useSvelteFlow()
const { getNodes } = useSvelteFlow()
const { getInternalNode } = useSvelteFlow()
const { getZoom } = useSvelteFlow()

onMount(() => {
  window.addEventListener('keydown', (e) => {
    if (e.ctrlKey && e.key === 'c') {
      console.log('ctrl+c')
      const nodes = getNodes()
      console.log('nodes', nodes)
      const internalNode = getInternalNode("1")
      console.log('internalNode', internalNode)
      const zoom = getZoom()
      console.log('zoom', zoom)
    }
  })
  })
```
Consider that my node information is in the ```nodesWritable``` variable and I can actually see them in the UI, but in the keydown callback what I get is:

```typescript
$nodesWritable
(2) [{…}, {…}] // as you can see nodes exist
0:
{id: '1', type: 'QUERY', data: {…}, position: {…}, style: undefined, …}
1:
{id: '2', type: 'METASTATE', data: {…}, position: {…}, style: undefined, …}

getNodes()
(0) []
getZoom()
1

getInternalNode("1")
undefined
```

What am I doing wrong here, do you have any suspicions? Thanks!

**Comment by bcakmakoglu** [comment]
Have you used `SvelteFlowProvider` first in a parent component? @kerem0comert 

```html
<SvelteFlowProvider>
	<App />
</SvelteFlowProvider>
```

**Comment by kerem0comert** [comment]
The following is in my ```+page.svelte```:

```svelte
<div class="flow">
        <SvelteFlowProvider>
          <Flow on:nodeclick={handleNodeClick} />
        </SvelteFlowProvider>
      </div>
```

where ```Flow.svelte``` is a custom component of mine, and looks like the following:
```svelte

```<SvelteFlowProvider>
  <div class="get-nodes">
    <Button buttonText="Get Nodes" />
  </div>

  {#if $nodesWritable}
    <div style="height:85vh; position:relative;" bind:clientHeight bind:clientWidth>
      <Palette />
      <SvelteFlow
        fitView
        nodes={nodesWritable}
        edges={edgesWritable}
        {nodeTypes}
        on:nodecontextmenu={handleContextMenu}
        on:paneclick={handlePaneClick}
        on:dragover={onDragOver}
        on:drop={onDrop}
        on:selectionclick={(e) => { console.log('selectionclick' + e.detail.nodes[0]) }}
        on:selectioncontextmenu={handleSelectionContextMenu }
        on:selectstart={() => { console.log('selectstart') }}
        on:select={() => { console.log('select') }}
        on:nodemouseleave={(e) => { console.log('nodemouseleave' + e.detail.node) }}
        on:selectionchange={() => { console.log('selectionchange') }}
      >
        <Controls />
        <Background variant={BackgroundVariant.Cross} />
        <MiniMap />
      </SvelteFlow>
      {#if contextMenuProps}
        <ContextMenu
          onClick={handlePaneClick}
          id={contextMenuProps.id}
          top={contextMenuProps.top}
          left={contextMenuProps.left}
          right={contextMenuProps.right}
          bottom={contextMenuProps.bottom}
        />
      {/if}
    </div>
  {/if}
</SvelteFlowProvider>
```

so it seems I have it in both at the moment actually, but I also tried other combinations. Perhaps if there is a specific way (```+page.svelte``` should have the ```SvelteFlowProvider``` but not the child ```Flow.svelte``` of mine) that would also be a step in the correct direction I guess.

**Comment by bcakmakoglu** [comment]
You shouldn't use it twice like that. It should only be in the wrapper (first code-block).

**Comment by kerem0comert** [comment]
Alright, with this arrangement everything seems to work and I can get them via ```selected = true```. Thanks for the help :)
