### ISSUE TITLE
Source and Target handle getting null

### ISSUE THREAD

**Issue by varun8255** [xyflow/xyflow#4318]
### Describe the Bug

While trying to add the edges using onConnect where we are using the hook to add the edges its throwing a warning like 

"Couldn't create edge for source handle id: "object-0.6916853697528522-handle-bottom-e1045f27-c677-4048-a78b-1c79adaacc17", edge id: edge-0.5969621633747138." and from the documentation its found that we have added the id property for the source handles as well.

On further debugging its found that the sourceHandle and targetHandle is getting null value due to which its throwing the error.

### Steps to Reproduce the Bug or Issue

1. Create two custom nodes
2. Add multiple handlers
3. Use a hook for the onConnect Props to add edges.
4. Try to draw an edge from one source handler to target handler
5. Edges are not visible.

### Expected behavior

As a user expect to see the edges from one node to another.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
OS :Windows
Browser: Chrome

**Comment by peterkogo** [comment]
Can you please create a [Sandbox](https://reactflow.dev/learn#play-online) with a reproduction for this? You can also fork an example if that's easier.

**Comment by varun8255** [comment]
@peterkogo Can you please help us to resolve the issue. We have added the code to code sandbox.

**Comment by bcakmakoglu** [comment]
Your sandbox has a number of issues that prevent one from even seeing the app :(
After I did some manual patches to get it working and looking at it (although still not quite working correctly) I believe your issue comes from the fact that you simply remove `<Handle>` components from the DOM when there's no `selectedLink` anymore.
That's not gonna work.
Edges *need to have a `<Handle>`* - it's not optional.
If you want to "hide" the handles, use `opacity: 0` for example. That way the handle is not visually not present but still in the DOM and can be used for calculations etc.

**Comment by nicolas-chalant** [comment]
Thank you for your help, you were right.
I changed my customNode handle logic from this : 

```jsx
{!isEmptyObject(selectedLink) && data && data.handleIds && (
        <>
          <Handle type="target" position={Position.Top} id={data.handleIds.top} />
          <Handle type="source" position={Position.Bottom} id={data.handleIds.bottom}  />
          <Handle type="target" position={Position.Left} id={data.handleIds.left}  />
          <Handle type="source" position={Position.Right} id={data.handleIds.right}  />
        </>
      )}
```

to that

```jsx
{data && data.handleIds && (
        <>
          <Handle
            type="target"
            position={Position.Top}
            id={data.handleIds.top}
            style={{ opacity: !isEmptyObject(selectedLink) ? 1 : 0 }}
          />
          <Handle
            type="source"
            position={Position.Bottom}
            id={data.handleIds.bottom}
            style={{ opacity: !isEmptyObject(selectedLink) ? 1 : 0 }}
          />
          <Handle
            type="target"
            position={Position.Left}
            id={data.handleIds.left}
            style={{ opacity: !isEmptyObject(selectedLink) ? 1 : 0 }}
          />
          <Handle
            type="source"
            position={Position.Right}
            id={data.handleIds.right}
            style={{ opacity: !isEmptyObject(selectedLink) ? 1 : 0 }}
          />
        </>
      )}
```

and it works perfectly.

![image](https://github.com/xyflow/xyflow/assets/73187667/c68cb12a-c5f8-4c56-b4ae-63ea4c3e7623)
