### ISSUE TITLE
SvelteFlow: Copy/Paste (continued issue)

### ISSUE THREAD

**Issue by kerem0comert** [xyflow/xyflow#4321]
### Please describe the feature that you want to propose

Hello,

This is a copy of [this issue](https://github.com/xyflow/xyflow/issues/4317) as it was closed but I could not reopen it. Please delete this issue if this is not how you prefer it. In either case, [please find my answer here](https://github.com/xyflow/xyflow/issues/4317#issuecomment-2144486572), which details my continued issue.

**Comment by moklick** [comment]
you should better open a new issue if it's a different topic.
