### ISSUE TITLE
Disable node drag on multitouch

### ISSUE THREAD

**Issue by danew** [xyflow/xyflow#4325]
### Describe the Bug

Currently if you pinch to zoom on a touch enabled device and one of your touches is on a node, the node will change position while the viewport scales.

### Steps to Reproduce the Bug or Issue

1. On a mobile device open the "Panning and Zooming" example https://lqlzyw.csb.app
2. Pinch to zoom the viewport with at least one finger within a Node

### Expected behavior

As a user, when I pinch to zoom the viewport, I expect the viewport to scale and the node positions to be unchanged.

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/5265684/a594fe1f-3519-45ef-82f7-63f411c8764b

### Platform

- OS: macOS 
- Browser: Brave 
- Version: Version 1.65.133 Chromium: 124.0.6367.208 (Official Build)

**Comment by peterkogo** [comment]
Thanks for raising this issue! This should be fixed in the next release of v12

**Comment by moklick** [comment]
Fixed in React Flow 12.0.0-next.20 and Svelte Flow 0.1.5

**Comment by danew** [comment]
Amazing thanks for the help! We're currently using v11 so I just ported your changes there is it possible we could release this there too?

https://github.com/xyflow/xyflow/pull/4372
