### ISSUE TITLE
Edges not initially rendered onlyRenderVisibleElements is set and connecting offscreen node has height set

### ISSUE THREAD

**Issue by ben-c-atlassian** [xyflow/xyflow#4329]
### Describe the Bug

There is an odd behavior where if ReactFlow is used with `onlyRenderVisibleElements` where if an edge is connected to a node that is offscreen and that offscreen node has a height set, the edge will no render until the map is panned so the node is rendered. After that point, the edge is rendered (added and removed from the DOM) as expected for onlyRenderVisibleElements

### Your Example Website or App

https://codesandbox.io/p/sandbox/v11-onlyrendervisibleelements-offscreen-edge-cjs5rl

### Steps to Reproduce the Bug or Issue

The behavior can be reproduced in the example by:
1. Open the sandbox and ensure the Preview window is small enough so that only the Default and Output nodes are shown.
   1. If you had to adjust the size, refresh the Preview
2. Notice there is no incoming edge shown for Default
3. Scroll/Pan to the right until the Input node is rendered
4. Notice Default node's incoming edge now renders.

If you remove the height attribute from the Input node in [nodes.ts](https://codesandbox.io/p/sandbox/v11-onlyrendervisibleelements-offscreen-edge-cjs5rl?file=%2Fnodes.ts%3A9%2C16-10%2C16), the issue no longer occurs.

### Expected behavior

As a user I would expect the edge rendering to behave the same regardless of if the offscreen node has height.

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/171610136/800c735b-f3f8-493b-82d5-60976d3481a4

### Platform

- OS: macOs
- Browser: Chrome, Firefox
- Version: ReactFlow v11.10.1

**Comment by moklick** [comment]
This is a weird (and bad) behaviour but we won't change it for v11. If you want to specify dimensions for a node, you need to use `node.style.width` / `node.style.height`. `node.width` and `node.height` is only used internally after a node is being measured. 

This behaviour will change with the next major release:  https://github.com/xyflow/xyflow/discussions/3764 - here you can use `node.width` and `node.height` as expected.
