### ISSUE TITLE
In SvelteFlow, setting viewport on initialization gets overridden on pan

### ISSUE THREAD

**Issue by adamdva** [xyflow/xyflow#4335]
### Describe the Bug

In a SvelteFlow initialization, setting a Writable viewport works to set the initial state of the flow viewport.

However, on panning the flow area, the viewport gets reset to {x: 0, y: 0, zoom: 1}

Expected Behavior:
viewport updated from initial setting, and not reset

### Steps to Reproduce the Bug or Issue

1. create the initial viewport:
let flowViewport = writable<Viewport>({x: 200, y: 200, zoom: 0.5})

2. set the viewport in <SvelteFlow>  
viewport={flowViewport}

3. on flow load, click on canvas to drag flow.
4.  will see viewport reset to {x: 0, y: 0, zoom: 1}

### Expected behavior

viewport updated from initial setting, and not reset

### Platform

- OS: Windows
- Browser: Chrome
- Version: Version 125.0.6422.141 (Official Build) (64-bit)

**Comment by moklick** [comment]
fixed in 0.1.4
