### ISSUE TITLE
Rename `updateEdge` to `reconnectEdge`

### ISSUE THREAD

**Issue by moklick** [xyflow/xyflow#4346]
### Please describe the feature that you want to propose

There is no good reason why we would only have those helpers just for nodes.

**Comment by bcakmakoglu** [comment]
There already is an `updateEdge` utility that updates an edge from one Node to another 🥲
Wouldn't it be confusing to have two utilities with the same naming?

**Comment by moklick** [comment]
The new helpers are added in 12.0.0-next.20. We now need to decide, if we want to rename the legacy `updateEdge` function and related handlers and attributes.

**Comment by moklick** [comment]
We will rename "updateEdge" to "reconnectEdge" and deprecate it for React Flow 11.
