### ISSUE TITLE
[React Flow]: Couldn't create edge for target handle id 

### ISSUE THREAD

**Issue by choiyounghun0712** [xyflow/xyflow#4360]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 10.3.17
- Browser and version: chrome  
- OS and version: 

### Live code example

https://codesandbox.io/p/sandbox/reactflow-9h9mfz?file=%2Fsrc%2Fcomponents%2FActionNode.tsx%3A85%2C1

### Describe the Bug

If you receive the data and move the mouse to ReactFlow, you will see [ReactFlow]: Could't create edge for source handle id: s-right; or [ReactFlow]: Could't create edge for source handle id: t-right; warning
Previously, I tried to ignore it, but when there is more data, more than 4000 alerts are accumulated, causing ReactFlow to stutter

Is there anything wrong with the code?

### Steps to reproduce the bug or issue

Moving the mouse into ReactFlow, as described in the bug description, displays a warning for [ReactFlow]: Couldn't create edge for source handle id: s-right; and [ReactFlow]: Couldn't create edge for target handle id: t-right.
I couldn't implement it as a sandbox because I was receiving data through a web socket

### Expected behavior

I checked the previous issues and changed the id to a string and checked other ways, but I don't know which one is the problem

### Additional context

I'm trying to optimize using react-window to solve the stuttering phenomenon additionally. I used the option you told me about before, but the scrolling lag didn't solve it.

I'd like to use a FixedSizeList to draw the current ReactFlow, any ideas?

https://codesandbox.io/p/sandbox/reactflow-forked-3ddgg6?file=%2Fsrc%2Fcomponents%2FCallFlow.tsx%3A273%2C10-273%2C23

**Comment by moklick** [comment]
Hey,

please update to the latest version of React Flow. You are using the deprecated "react-flow-renderer" package. We have a `onlyRenderVisibleElements` prop that you can use. There is no need to use an additional library for virtualization.

Please re-open with a codesandbox that uses React Flow 11 if the issue persists.

**Comment by choiyounghun0712** [comment]
I migrated to v11 and corrected the previous issues with the Module parse failed: Unexpected token error, but the error continues to appear.
The error details are as follows

./node_modules/@reactflow/node-resizer/dist/esm/index.js 44:38
Module parse failed: Unexpected token (44:38)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const getPointerPosition = useGetPointerPosition();
|     const defaultPosition = variant === ResizeControlVariant.Line ? 'right' : 'bottom-right';
>     const controlPosition = position ?? defaultPosition;
|     useEffect(() => {
|         if (!resizeControlRef.current || !id) {

How do I modify my racco.config when it is like this?

 webpack: {
      configure: (webpackConfig, { env, paths }) => {
        webpackConfig.module.rules.unshift(
          {
            test: /\.svg$/,
            use: [
              {
                loader: '@svgr/webpack',
                options: {
                  svgoConfig: {
                    plugins: [
                      {
                        removeViewBox: false,
                      },
                    ],
                  },
                },
              },
            ],
          },
          {
            test: /\.mjs$/,
            include: /node_modules/,
            type: 'javascript/auto',
          }
        );
        return webpackConfig;
      },
    },

**Comment by choiyounghun0712** [comment]
After installing with v11, talk error was displayed, so I tried the following method.
1. 1. yarn add --dev @babel/plugin-proposal-nullish-coalescing-operator

2. 2. craco.config에 

{
  test: /\.mjs$/,
  include: /node_modules/,
  type: 'javascript/auto',
  use: {
    loader: 'babel-loader',
    options: {
      presets: ['@babel/preset-env'],
      plugins: ['@babel/plugin-proposal-nullish-coalescing-operator'], // Add this line
    },
  },
},

Additional

3. install yarn

Even though I did this, I still get a token error

 webpack-merge "^4.2.2"

craco.config

`const CracoAlias = require('craco-alias');
const path = require('path');
const CracoEsbuildPlugin = require('craco-esbuild');

module.exports = (env) => {
  const isDevelopmenet = env.env === 'development';

  return {
    config: {
      devtool: 'cheap-module-source-map',
    },
    eslint: {
      enable: isDevelopmenet,
    },
    typescript: {
      enableTypeChecking: isDevelopmenet,
    },
    webpack: {
      configure: (webpackConfig, { env, paths }) => {
        webpackConfig.module.rules.unshift(
          {
            test: /\.svg$/,
            use: [
              {
                loader: '@svgr/webpack',
                options: {
                  svgoConfig: {
                    plugins: [
                      {
                        removeViewBox: false,
                      },
                    ],
                  },
                },
              },
            ],
          },
          {
            test: /\.mjs$/,
            include: /node_modules/,
            type: 'javascript/auto',
          }
        );
        return webpackConfig;
      },
    },
    module: {
      rules: [
        {
          test: /\.mp3$/,
          use: {
            loader: 'url-loader',
          },
        },
        {
          test: /\.worker\.js$/,
          use: { loader: 'worker-loader' },
        },
      ],
    },
    plugins: [
      {
        plugin: CracoAlias,
        options: {
          source: 'tsconfig',
          tsConfigPath: 'tsconfig.paths.json',
        },
      },

      {
        plugin: CracoEsbuildPlugin,
        options: {
          esbuildLoaderOptions: {
            // Optional. Defaults to auto-detect loader.
            loader: 'tsx', // Set the value to 'tsx' if you use typescript
            target: 'es2015',
          },
          esbuildMinimizerOptions: {
            // Optional. Defaults to:
            target: 'es2015',
            css: true, // if true, OptimizeCssAssetsWebpackPlugin will also be replaced by esbuild.
          },
        },
      },
    ],
  };
};
`
