### ISSUE TITLE
edge mouse enter and edge mouse leave not working

### ISSUE THREAD

**Issue by minaBemani** [xyflow/xyflow#4363]
### What platform were you using when you found the bug?

@xyflow/svelte: 0.1.6

### Describe the Bug

I requested for edgemouseenter and edgemouseleave events for svelte flow, and thankfully this feature was added but it does not work. I'm using svelte flow custom edge with a delete button to remove the edge and I need edge mouse enter and mouse leave events to make the delete button  initially hidden and appear on the edge when the edge is hovered. but the newly added edgemouseenter and edgemouseleave events don't work. I really appreciate if you fix it.

### Steps to reproduce the bug or issue

I requested for edgemouseenter and edgemouseleave events for svelte flow, and thankfully this feature was added but it does not work. I'm using svelte flow custom edge with a delete button to remove the edge and I need edge mouse enter and mouse leave events to make the delete button  initially hidden and appear on the edge when the edge is hovered. but the newly added edgemouseenter and edgemouseleave events don't work. I really appreciate if you fix it.

### Expected behavior

I wrote a test function to console.log a message when I hover the edge, but the edge mouse enter and leave events were not triggered and no message was console logged.

**Comment by peterkogo** [comment]
It seems to be working for me. [Here is a Sandbox](https://stackblitz.com/edit/svelte-flow-ts-ush5xw?file=src%2FFlow%2Findex.svelte).

**Comment by peterkogo** [comment]
Or are you looking for `edgemouseenter` and `edgemouseleave` on the `BaseEdge` component?

**Comment by moklick** [comment]
I will close this since it's working as expected. Feel free to re-open if you think that you've found a bug @minaBemani
