### ISSUE TITLE
my panel is displayed on the nodes

### ISSUE THREAD

**Issue by Muhammad1Siddique** [xyflow/xyflow#4368]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: React Flow
- Browser and version: Google Chrome
- OS and version: Linux ubuntu

### Describe the Bug

I faced a bug when I added to the panel display on the nodes but I want to display nodes after the panel 

### Steps to reproduce the bug or issue

![Screenshot from 2024-06-14 17-08-49](https://github.com/xyflow/xyflow/assets/48084054/90cc4634-40e8-44be-a25c-6678745f3d1f)

### Expected behavior

I want to display nodes after the panel I don't want to use panel space search, status and button

### Screenshots or Videos

![Screenshot from 2024-06-14 17-08-49](https://github.com/xyflow/xyflow/assets/48084054/a113040a-51f0-4406-943b-a99f8d4cf1af)

**Comment by bcakmakoglu** [comment]
1. What is the problem exactly? Your issue description isn't clear enough and doesn't, at least to me, communicate what the exact issue is.
2. Please provide a proper reproduction of the problem. You didn't provide any code, nothing, only a screenshot. You can't expect us to know what you've built and what the problem is.

**Comment by Muhammad1Siddique** [comment]
I'm encountering a bug where my nodes are being displayed behind the search input, status dropdown, and recent button. I want the nodes to be displayed after these elements. Can you help me resolve this issue?

<ReactFlow
        nodes={filteredNodes}
        edges={visibleEdges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onNodeClick={onNodeClick}
        proOptions={proOptions}
        nodeTypes={nodeTypes}
        nodesDraggable={true}
        nodesConnectable={false}
        className={`${FlowStyle.viewport}`}
        attributionPosition="top-left"
        zoomOnDoubleClick={true}
        elementsSelectable={true}>
        <NodeSearchPanel 
          onSearchChange={onSearchChange} 
          onStatusChange={onStatusChange} />
          <MiniMap
            nodeColor={(n) => n.data.color}
            nodeStrokeWidth={3}
            zoomable
            pannable
          />
          <Controls />

      </ReactFlow>
      
      import React from 'react';
import { Form } from 'react-bootstrap';
import { Panel } from 'reactflow';
import HistoryButtons from '../networkMap/HistoryButtons';

interface NodeSearchType {
  onSearchChange: (search: string) => void;
  onStatusChange: (status: string) => void;
}

const NodeSearchPanel = ({ onSearchChange, onStatusChange }: NodeSearchType) => {
  return (
    <Panel position="top-left" style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
      <Form.Control
        placeholder="Filter by Name..."
        onChange={(evt: { target: { value: string } }) => onSearchChange(evt.target.value)}
        style={{ width: 160 }}
      />
      <Form.Select
        onChange={(evt: { target: { value: string } }) => onStatusChange(evt.target.value)}
        style={{ width: 140 }}>
        <option value="">All Status</option>
        <option value="Ready">Ready</option>
        <option value="Pending">Pending</option>
        <option value="Running">Running</option>
        <option value="Succeeded">Succeeded</option>
        <option value="Failed">Failed</option>
        <option value="Unknown">Unknown</option>
      </Form.Select>
      <HistoryButtons />
    </Panel>
  );
};

export default NodeSearchPanel;
![Screenshot from 2024-06-14 17-08-49](https://github.com/xyflow/xyflow/assets/48084054/996a8e50-8a8d-41d4-921b-8d22c8b21632)

**Comment by bcakmakoglu** [comment]
>  I want the nodes to be displayed after these elements.

What is that supposed to mean? Your problem description is still vague and it's not clear what you want to achieve here and what your issues are, what you tried and what challenges you encountered.

Also the `<Panel>` component is rendered *on top* of the viewport. That's how it works.

**Comment by moklick** [comment]
Please re-open with a codesandbox https://new.reactflow.dev. A bunch of unformatted code is not helpful at all.
