### ISSUE TITLE
Can't create edges on react flow v12

### ISSUE THREAD

**Issue by dariovillalta** [xyflow/xyflow#4369]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: v12
Firefox: 126
MacOS: Monterey

### Describe the Bug

Hello everyone,

Found this bug where the exact code that you use to create edges for a custom node that worked in v11 doesn't work anymore on v12.

On v12 I get this warning which doesn't appear on v11:

`Handle: No node id found. Make sure to only use a Handle inside a custom Node.`

On v11 I get this warning which doesn't affect the functionality:

`It looks like you've created a new nodeTypes or edgeTypes object. If this wasn't on purpose please define the nodeTypes/edgeTypes outside of the component or memoize them.`

Here's the code.

Flow container:

> import React from 'react';
import  { ReactFlow,ReactFlowProvider, addEdge, useNodesState, useEdgesState } from '@xyflow/react';
import 'reactflow/dist/style.css';
import RhombusNode from './Condition';
const nodeTypes = {
  rhombus: RhombusNode,
};
const initialNodes = [
  {
    id: '1',
    type: 'rhombus',
    position: { x: 250, y: 5 },
    data: { label: 'Condition Node' },
  }
];
const initialEdges = [
];
const Flow = () => {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);
  const onConnect = (params) => setEdges((eds) => addEdge(params, eds));
  return (
    <ReactFlowProvider>
      <ReactFlow
        nodes={nodes}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        nodeTypes={nodeTypes}
        fitView
      />
    </ReactFlowProvider>
  );
};
export default Flow;

This is v12 and it doesn't works, if you change the import it works:

> import ReactFlow, { ReactFlowProvider, addEdge, useNodesState, useEdgesState } from 'reactflow';

And here's the custom node:

> import React, { useEffect, useState, useRef } from 'react';
import { Handle, Position } from 'reactflow';
import './Condition.css';
const RhombusNode = ({ data }) => {
    const textRef = useRef(null);
    const [size, setSize] = useState({ width: 100, height: 100 });
    useEffect(() => {
        if (textRef.current) {
            const { offsetWidth, offsetHeight } = textRef.current;
            setSize({
                width: Math.max(100, offsetWidth + 40),
                height: Math.max(100, offsetHeight + 40),
            });
        }
    }, [data.label]);
    const halfWidth = size.width / 2;
    const halfHeight = size.height / 2;
    return (
        <div className="rhombus-node" style={{ width: size.width, height: size.height }}>
            <svg width={size.width} height={size.height}>
                <polygon
                    points={`${halfWidth},0 ${size.width},${halfHeight} ${halfWidth},${size.height} 0,${halfHeight}`}
                    className="rhombus"
                />
            </svg>
            <div ref={textRef} className="text-container">
                {data.label}
            </div>
            <Handle
                type="source"
                position={Position.Top}
                id="top"
            />
            <Handle
                type="source"
                position={Position.Right}
                id="right"
            />
            <Handle
                type="source"
                position={Position.Bottom}
                id="bottom"
            />
            <Handle
                type="source"
                position={Position.Left}
                id="left"
            />
        </div>
    );
};
export default RhombusNode;

Css in case it helps:

> /* CustomNode.css */
.rhombus-node {
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .rhombus {
    fill: #ddd;
    stroke: #333;
    stroke-width: 1px;
  }
  .text-container {
    position: absolute;
    text-align: center;
    white-space: nowrap;
  }
  

As always, any help is appreciated

### Steps to reproduce the bug or issue

1. Create a react flow in v12
2. Create a custom node with handles
3. Try to drag a new edge

### Expected behavior

As a user I would expect to be able to create new edges on custom nodes but what i am experiencing is that on edge drag start no line from the edge is visible and can't connect edges.

**Comment by moklick** [comment]
You should not mix the packages `reactflow` and `@xyflow/react`.  You also need to import the correct styles from v12: `import '@xyflow/react/dist/style.css';`

**Comment by dariovillalta** [comment]
> You should not mix the packages `reactflow` and `@xyflow/react`. You also need to import the correct styles from v12: `import '@xyflow/react/dist/style.css';`

Thanks for the answer!

One follow up tho, does it mean custom nodes aren't available on react flow v12 or am I mixing up projects?

**Comment by dariovillalta** [comment]
> You should not mix the packages `reactflow` and `@xyflow/react`. You also need to import the correct styles from v12: `import '@xyflow/react/dist/style.css';`

Thanks for the reply!

For posterity, I was importing the old react flow library in the custom node 😅
