### ISSUE TITLE
v11 nodes, edges are not displayed

### ISSUE THREAD

**Issue by ggnu11** [xyflow/xyflow#4374]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version:  11.11.3
- Browser and version: chrome
- OS and version:

### Describe the Bug

Failed to draw edges, nodes after updating from v10 to v11.

### Steps to reproduce the bug or issue

It doesn't even show up in the code sandbox, it flashes for a moment and disappears on the screen I'm working on. When I modify overflow, it's on the screen, but when I apply overflow, it doesn't show up again

### Expected behavior

I have a bug where the screen disappears when I move the mouse to flow. This is my code

 ```
<ReactFlow
          elementsSelectable={false}
          selectNodesOnDrag={false}
          connectOnClick={false}
          nodesConnectable={false}
          nodesDraggable={false}
          panOnDrag={false}
          zoomOnScroll={false}
          zoomOnPinch={false}
          zoomOnDoubleClick={false}
          preventScrolling={false}
          style={{
            width: flowWidthSize,
            height: flowHeightSize,
            margin: '0',
          }}
          nodeTypes={nodeTypes}
          nodes={initialNodes}
          edges={initialEdges}
          onNodeMouseEnter={(e, node: any) => {
            setActiveSeq(node.seq);
          }}
          onNodeMouseLeave={() => {
            setActiveSeq(null);
          }}
          onEdgeMouseEnter={(e, node: any) => {
            setActiveSeq(node.seq);
          }}
          onEdgeMouseLeave={() => {
            setActiveSeq(null);
          }}
        />
```

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/130032473/e2e655c0-7d64-4e0e-becf-8d212aa035f1

### Additional context

https://codesandbox.io/p/sandbox/reactflow-v11-7txvtw?file=%2Fsrc%2Fcomponents%2Freactflow%2FReactFlow1.tsx

**Comment by ggnu11** [comment]
I solved it

**Comment by bcakmakoglu** [comment]
[The container in which you wrap ReactFlow has no proper height.](https://reactflow.dev/learn/troubleshooting#the-react-flow-parent-container-needs-a-width-and-a-height-to-render-the-graph)

Change that and it works:
<img width="1074" alt="image" src="https://github.com/xyflow/xyflow/assets/78412429/255dc6f3-0151-4e15-9f22-7dd428a53d77">

**Comment by ggnu11** [comment]
As you told me, I tried to correct the height, but the blinking phenomenon did not disappear. And after checking the link you sent me, I corrected the code that caused the error.

https://codesandbox.io/p/sandbox/reactflowv11-cj7cx8?file=%2Fsrc%2Fcomponent%2FReactFlow1.tsx%3A311%2C30

**Comment by ggnu11** [comment]
When I removed those options, I checked that the screen was displayed without blinking.(onEdgeMouseLeave, onEdgeMouseEnter, onNodeMouseLeave, onNodeMouseEnter )

When tested with only two options left, the node blinks every time it changes.(onNodeMouseEnter, onEdgeMouseEnter)

**Comment by ggnu11** [comment]
When I remove that option, the screen will appear.(onNodeMouseEnter, onEdgeMouseEnter, onEdgeMouseLeave, onNodeMouseLeave) 

 If you remove this option(onNodeMouseLeave), the screen will not disappear, but it will still blink. Is there no problem with the code I wrote? It worked fine in previous 10 versions
