### ISSUE TITLE
reactflow start

### ISSUE THREAD

**Issue by alihemmatnia** [xyflow/xyflow#4375]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 11.11.3
- Browser and version: edge 126
- OS and version: windows 11

### Describe the Bug

i after install reactflow and start react :
```
./node_modules/@reactflow/controls/dist/esm/index.js 109:13
Module parse failed: Unexpected token (109:13)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   const onZoomInHandler = () => {
|     zoomIn();
>     onZoomIn?.();
|   };
```
please help me

### Steps to reproduce the bug or issue

nothing

### Expected behavior

no

**Comment by bcakmakoglu** [comment]
[Please read this section of the docs.](https://reactflow.dev/learn/troubleshooting#i-get-an-error-when-building-my-app-with-webpack-4)

**Comment by moklick** [comment]
closed because it's a duplicate 👆
