### ISSUE TITLE
Add provision to control speed of panning of canvas while dragging the nodes

### ISSUE THREAD

**Issue by aman-observo** [xyflow/xyflow#4376]
Problem facing:
Currently when we drag the nodes to the boundaries of the viewport and `autoPanOnNodeDrag` is enabled, the pace of panning the canvas is very fast which sometimes leaves the content on the viewport illegible.

Feature request:
We would like to manually control & configure the speed of this panning process of the viewport.

**Comment by moklick** [comment]
I agree! It's a hardcoded value that could be replaced by a `autoPanSpeed` for example.

**Comment by moklick** [comment]
In 12.0.0-next.26 we added an `autoPanSpeed` prop.

**Comment by moklick** [comment]
`autoPanSpeed` prop was released with React Flow 12!
