### ISSUE TITLE
Flow with many lines makes dragging difficult

### ISSUE THREAD

**Issue by rafaelodassi** [xyflow/xyflow#4377]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: ^9.6.7
- Browser and version: Chrome 125.0.6422.176, 64 bits
- OS and version: Windows 11

### Describe the Bug

When I try to drag the flow, where there is the print element, I cannot drag it.

### Steps to reproduce the bug or issue

Create a flow with multiple curved lines.

### Expected behavior

Conseguir arrastar o fluxo normalmente.

### Screenshots or Videos

![image](https://github.com/xyflow/xyflow/assets/11441937/63013de8-39c9-4e7d-bfff-847a6536154a)

**Comment by bcakmakoglu** [comment]
> React Flow version: ^9.6.7

You really need to migrate to the latest version - I doubt that anyone will fix any issue for version **9** which is ... 2 years old now?

This problem shouldn't exist in v11 for example (and v12 is coming soon as well, making the version you use even more outdated 😅)

**Comment by peterkogo** [comment]
This is solved in later versions and we don't update v9 anymore.
