### ISSUE TITLE
Edges unmount when nodes change

### ISSUE THREAD

**Issue by claudiosc8** [xyflow/xyflow#4381]
### What platform were you using when you found the bug?

- React Flow version: 11.11.2
- Browser and version: Chrome 125.0.6422.142
- OS and version: macOS Sonoma

### Live code example

https://codesandbox.io/p/sandbox/keen-kirch-zqsqf4

### Describe the Bug

Edges unmount when nodes change. This makes them lose their internal state, however nodes seem to preserve their state instead.

### Steps to reproduce the bug or issue

1. Tick the checkbox on nodes and edges
2. Click on the "refresh" button in the bottom left corner
3. Edge lose their internal state, but nodes preserve it

### Expected behavior

As a user I expect the edges to keep their state if their id is the same as the previous render.

In the project I'm working on, each edge control a popover with a form that makes edits to the adjacent nodes. However the popover closes every time I submit the form, because the nodes have changed. I'd like to keep it open instead

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/10764307/0bc8e911-12c9-4944-8d16-3ddf989cb357

**Comment by peterkogo** [comment]
You do have to use ReactFlow the intended way for it to work.

```jsx
const EdgesFlow = () => {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      edgeTypes={edgeTypes}
      nodeTypes={nodeTypes}
      fitView
    >
[...]
```
