### ISSUE TITLE
scrolling function, data selection outside of viewport

### ISSUE THREAD

**Issue by ggnu11** [xyflow/xyflow#4385]
### Please describe the feature that you want to propose

I would like to display as many scrolls as overflows in the current reactflow.

I want to create scrolls as much as totalHeight drawing vertical lines, any good features?

And is there a function to cache data that is only displayed in viewport? If it is possible to add scrolls, I would like to make a function to remember the location of scrolls for each node

Additionally, I don't want to use all the features of the shift, is there a way? I added panOnScroll to enable vertical scrolling and added panOnScrollMode: 'vertical', and the box shows like this.

<img width="134" alt="image" src="https://github.com/xyflow/xyflow/assets/130032473/bd2608bc-1515-435d-b9cd-4ed5e8147e1a">

https://codesandbox.io/p/sandbox/reactflowv11-cj7cx8?file=%2Fsrc%2Fcomponent%2FReactFlow1.tsx%3A400%2C19

**Comment by moklick** [comment]
Hey @ggnu11 

this is not an issue with React Flow and not a feature request. Please use Discord or Stackoverflow for questions about specific use cases.
