### ISSUE TITLE
Disable shift click event

### ISSUE THREAD

**Issue by ggnu11** [xyflow/xyflow#4390]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 11.10.3
- Browser and version: 
- OS and version:

### Live code example

https://codesandbox.io/p/sandbox/reactflowv11-cj7cx8?file=%2Fsrc%2Fcomponent%2FReactFlow1.tsx%3A344%2C10

### Describe the Bug

Click the node or vertical line with shift+click to select it. Also, if you move left and right with the node selected with shift+click, the screen moves. I want to disable all the functions of shift, is there an option?

### Steps to reproduce the bug or issue

1. Select a node from shift+click status
2. Move left and right mouse while holding the shift+click

### Expected behavior

Options that are being processed as false do not work normally

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/130032473/044f62d2-ef2c-4cc1-bbf0-5a15af8b444d

**Comment by bcakmakoglu** [comment]
>  Disable shift click event

What is this supposed to mean?
Your "bug" report has no bug being reported and it's more than vague about what your problem is and what you want to resolve.

If you want to disable the pane being moved on node drag use the [`autoPanOnNodeDrag`](https://reactflow.dev/api-reference/react-flow#auto-pan-on-node-drag) prop and set it to `false`

**Comment by ggnu11** [comment]
I mean, when I press the shift key and click, I wanted to disable all the features that I support. When I migrated from the previous version 10 to version 11, I treated the click function as false, but it didn't work. If I press shift and click the edge as shown in the picture, the edge container box will be displayed, and I'm trying to prevent this
