### ISSUE TITLE
Naming custom node "group" causes UI bug

### ISSUE THREAD

**Issue by aes421** [xyflow/xyflow#4393]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: ReactFlow 11.11.4
- Browser and version: Chrome
- OS and version: Windows

### Describe the Bug

Naming a custom node "group" causes a bug where the node is outlined with a grey box.  I can repro in the codesandbox, but the grey box is even more pronounced in my local project.

### Steps to reproduce the bug or issue

https://codesandbox.io/embed/strange-shaw-dlrvmq

### Expected behavior

As a user, I would expect the custom node named group to appear like the other custom nodes with other names.

### Screenshots or Videos

![Screenshot 2024-06-23 141726](https://github.com/xyflow/xyflow/assets/10823042/7849c36d-7422-4c4f-b33e-277c31f1e3ac)

**Comment by bcakmakoglu** [comment]
This is not really a bug, it's because "group" is a built-in node type that comes with some default styles:
```css
.react-flow__node-default,
.react-flow__node-input,
.react-flow__node-output,
.react-flow__node-group {
  padding: 10px;
  border-radius: 3px;
  width: 150px;
  font-size: 12px;
  color: #222;
  text-align: center;
  border-width: 1px;
  border-style: solid;
  border-color: #1a192b;
  background-color: white;

 /* more styles */
```

You'd have to overwrite these styles or use a slightly different node type name.

**Comment by moklick** [comment]
I agree that it's a bit confusing but there are default styles for all built-in nodes. You need to overwrite them or chose another name for the node type. You can also import `reactflow/dist/base.css` which comes with fewer styling.

**Comment by hughlv** [comment]
> I agree that it's a bit confusing but there are default styles for all built-in nodes. You need to overwrite them or chose another name for the node type. You can also import `reactflow/dist/base.css` which comes with fewer styling.

You made my day. Thanks.
