### ISSUE TITLE
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import

### ISSUE THREAD

**Issue by qcynaut** [xyflow/xyflow#4401]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: Svelte Flow
- Browser and version: Chrome
- OS and version: MacOs sonoma

### Describe the Bug

failed to import "@xyflow/svelte"

### Steps to reproduce the bug or issue

1. `yarn add -D @xyflow/svelte`
2. `yarn dev`

### Expected behavior

It's should be working fine

**Comment by moklick** [comment]
How does your dev setup look like?

**Comment by mikenikles** [comment]
Hey @qcynaut, do you recall what the issue was and how you resolved it?
