### ISSUE TITLE
useOnSelectionChange returns previous selection

### ISSUE THREAD

**Issue by vsdsv285** [xyflow/xyflow#4409]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 11.11.4
- Browser and version: Firefox and Chrome
- OS and version: MacOS

### Describe the Bug

Whenever I click any node or edge for the first time, `useOnSelectionChange` is not getting triggered and for next clicks, it is getting triggered and returns the previous selection.

```
const SelectionChange = () => {
  const onChange = useCallback(({ nodes, edges }: OnSelectionChangeParams) => {
    console.log({ nodes, edges });
  }, []);

  useOnSelectionChange({
    onChange,
  });
  return null;
}
```

### Steps to reproduce the bug or issue

Listed above

### Expected behavior

`useOnSelectionChange` should return the current selected nodes and edges.

**Comment by moklick** [comment]
I can't reproduce this: https://codesandbox.io/p/sandbox/sharp-hill-ssqm5y?file=/src/App.tsx:26,6 

Please re-open with a codesandbox or repo.
