### ISSUE TITLE
Svelte: using `selectionOnDrag` breaks interaction with nodes and control panel

### ISSUE THREAD

**Issue by Apollo-Roboto** [xyflow/xyflow#4418]
### What platform were you using when you found the bug?

- Svelte Flow version: 0.1.8
- Browser and version: Edge (126.0.2592.87), Chrome (126.0.6478.127)
- OS and version: Windows 10 (22H2 build 19045.4598)

### Live code example

https://stackblitz.com/edit/svelte-flow-ts-q2lwzx?file=src%2FFlow%2Findex.svelte

### Describe the Bug

Using `selectionOnDrag` on `<SvelteFlow/>` prevents the interaction with components within nodes and the control panel.

### Steps to reproduce the bug or issue

*like shown in video*
*code example has been included*
1. use version 0.1.8
1. make a selection area by dragging on the panel
1. click on a component within the node
1. click on the control panel

### Expected behavior

From the stackblitz link, the color picker should show, the log button should log something, and the control panel should be intractable

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/41392253/62cefc9b-6ee6-4dd8-be0c-2b19e368cbe6

### Additional context

It's not a problem in Firefox

The bug seemed to have been introduced in recent versions:
Changing the version to 0.1.6, the node interaction works.
Changing the version to 0.1.4, the control panel works.

My current solution is to stick to 0.1.4 for now.

**Comment by bryant988** [comment]
I'm having the same issue with the latest react version upgrade 12.0.0.
I can't enable `selectionOnDrag` because it breaks regular node selection and double clicks.

**Comment by moklick** [comment]
Seems like a bug! We will check it!

**Comment by moklick** [comment]
@bryant988 how can I reproduce this for React Flow? Do you have a codesandbox?
