### ISSUE TITLE
Custom PanelPosition

### ISSUE THREAD

**Issue by thomas-xsell** [xyflow/xyflow#4419]
### Please describe the feature that you want to propose

From docs:

https://reactflow.dev/api-reference/types/panel-position

```
export type PanelPosition =
  | 'top-left'
  | 'top-center'
  | 'top-right'
  | 'bottom-left'
  | 'bottom-center'
  | 'bottom-right';
```

Is it possible to allow a customized PanelPosition ? 

I'd like to add 2 panels on bottom-left but both panel overlap each-other actually.

**Comment by bcakmakoglu** [comment]
What exactly is this customization supposed to do and how would it solve two panels at the same position?
You already can adjust the position of a `<Panel>` with css for example.

[Here's a sandbox demonstrating this.](https://codesandbox.io/p/sandbox/nervous-tesla-zk24wc?file=%2Fsrc%2FApp.tsx%3A47%2C55)

**Comment by moklick** [comment]
As @bcakmakoglu pointed out, you can adjust the position of a panel. You could also put two divs in a panel and adjust the positions of divs inside the panel.

**Comment by thomascouto** [comment]
Thanks for helping me out, issue is solved.
