### ISSUE TITLE
Dynamically removes edges based on handles？

### ISSUE THREAD

**Issue by coderlzw-cn** [xyflow/xyflow#4427]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and versio
- OS and version:

### Live code example

https://codesandbox.io/p/devbox/twilight-firefly-z9nxtm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clydzsqkz00073b6pwhxo5j4o%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clydzsqky00023b6ppc9chuz5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clydzsqkz00043b6p4iz6n7zj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clydzsqkz00063b6p8kaeqw97%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clydzsqky00023b6ppc9chuz5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clydzsqky00013b6pwehrbsbm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clye0b3k100023b6pn1k4z1yr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fassets%252Fglobal.css%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A70%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522clydzsqky00023b6ppc9chuz5%2522%252C%2522activeTabId%2522%253A%2522clye0b3k100023b6pn1k4z1yr%2522%257D%252C%2522clydzsqkz00063b6p8kaeqw97%2522%253A%257B%2522id%2522%253A%2522clydzsqkz00063b6p8kaeqw97%2522%252C%2522activeTabId%2522%253A%2522clye6is4j001j3b6pcdkx51lp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clydzsqkz00053b6p8ahjncb4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522clydzttue000d3b6pvjelwon1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522clydzw4bq00063b6pf2327pbz%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522clydzw4bq00073b6phmd3rc0q%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A35085%252C%2522id%2522%253A%2522clye6hm09000j3b6pr8iafoco%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clye6is4j001j3b6pcdkx51lp%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clydzsqkz00043b6p4iz6n7zj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clydzsqky00033b6pd9rfl7t3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clydzsqkz00043b6p4iz6n7zj%2522%252C%2522activeTabId%2522%253A%2522clydzsqky00033b6pd9rfl7t3%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Describe the Bug

Dynamically removes edges based on handles

### Steps to reproduce the bug or issue

Dynamically removes edges based on handles

### Expected behavior

Dynamically removes edges based on handles

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/55791848/154abcda-6056-4f4c-8ca1-361f4022b51a

**Comment by bcakmakoglu** [comment]
Removing handles isn't gonna magically remove their connected edges from the state.
If that's what you want to do you can either check if a handle has a connected edge and clean it up.

[Here's a very basic example.](https://codesandbox.io/p/sandbox/cranky-payne-yk9h9g?file=%2Fsrc%2Fnodes%2FPositionLoggerNode.tsx%3A40%2C47)

**Comment by coderlzw-cn** [comment]
Ok, I see. It seems that using deleteElements is the only viable option
