### ISSUE TITLE
Clicking a node doesn't select the node

### ISSUE THREAD

**Issue by arikchakma** [xyflow/xyflow#4436]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: @xyflow/react V12.0.0
- Browser and version: Brave 1.67.123 Chromium: 126.0.6478.126
- OS and version: macOS 14.5

### Live code example

https://codesandbox.io/s/xyflow-react-select-node-c7jvlg?file=/number-input.js:108-121

### Describe the Bug

Clicking a `node` doesn't select the `node` if you have `panOnDrag={false} panOnScroll={true} selectionOnDrag={true}` instead it selects the pane element.  Before migrating to `v12` it was working fine. Even the `onClick` event doesn't get fired.

### Steps to reproduce the bug or issue

1. Click any node
2. Notice that the node doesn't turn `red` i.e. not selected.
3. Also look at the `console` the node click event doesn't get triggered.

### Expected behavior

As a user, I expected that when I click any node it should select the node and turn red.

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/54026804/cfc038cc-269d-482d-a088-6468fc32ed46

**Comment by moklick** [comment]
Could you try 12.0.1?

**Comment by arikchakma** [comment]
It works fine now, we're still migrating to `v12`. We will let you know if we face any other issues. Thanks for the reply.

**Comment by moklick** [comment]
Perfect :)
