### ISSUE TITLE
Error if parent node is after child node in the list of nodes

### ISSUE THREAD

**Issue by Gomes117** [xyflow/xyflow#4438]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12
- Browser and version: chrome 126
- OS and version: linux mint 21

### Live code example

https://codesandbox.io/s/nice-euler-tnjckd

### Describe the Bug

Parent node not found error if parent node is after child node

### Steps to reproduce the bug or issue

Using the following node list will result in the error

```javascript
const nodes = [
  {
    id: "B",
    data: { label: "child node 1" },
    position: { x: 10, y: 10 },
    parentId: "A",
    extent: "parent"
  },
  {
    id: "A",
    type: "group",
    data: { label: null },
    position: { x: 0, y: 0 },
    style: {
      width: 170,
      height: 140
    }
  }
];

export default nodes;

```

### Expected behavior

B is child of A. State order shouldn't matter

**Comment by henriqueantonio** [comment]
It's not a bug.

As explained in the docs, to ensure correct processing, it's important that parent nodes appear before their children in the nodes/defaultNodes array.

https://reactflow.dev/learn/layouting/sub-flows

**Comment by Gomes117** [comment]
I see. Guess I failed to see the big yellow box
