### ISSUE TITLE
[V12] Missing types export: XYResizerParams and ResizeDragEvent

### ISSUE THREAD

**Issue by Pelv** [xyflow/xyflow#4439]
### What platform were you using when you found the bug?

- React Flow version: 12
- Browser and version: Brave latest
- OS and version: MacOS latest

### Describe the Bug

<img width="786" alt="Screenshot 2024-07-11 at 14 48 06" src="https://github.com/xyflow/xyflow/assets/6773886/7302f165-569b-4296-9b59-f6538bbf1a19">
I can find to get the type for XYResizerParams and ResizeDragEvent.

It's a meant to be this way or it's a missing type export? I was using them in the previous version.
<img width="1102" alt="Screenshot 2024-07-11 at 14 51 18" src="https://github.com/xyflow/xyflow/assets/6773886/f4e54650-6264-4c1a-a06d-567cd7c9276a">

Thanks for the help and the great work!

### Steps to reproduce the bug or issue

Just try to import the types.

### Expected behavior

I would love to be able to import them again.

### Screenshots or Videos

<img width="786" alt="Screenshot 2024-07-11 at 14 48 06" src="https://github.com/xyflow/xyflow/assets/6773886/f801f33a-2ce6-4e87-b1df-149d2ce30077">
<img width="1102" alt="Screenshot 2024-07-11 at 14 51 18" src="https://github.com/xyflow/xyflow/assets/6773886/1eff6b31-b713-4536-b46c-3132e0a6104c">

**Comment by moklick** [comment]
Thanks! This is fixed in 12.0.1

**Comment by Pelv** [comment]
@moklick thanks to you, i did nothing!!
One day i'll be able to fix those "small" things without bothering you guys.

So far, i loved reactflow and love xyflow/react even more (i have two application, one with the new version and the other migrating soon). 

Keep with the great work!
