### ISSUE TITLE
Reactflow: Problem when use mui Menu as node context menu 

### ISSUE THREAD

**Issue by FindDefinition** [xyflow/xyflow#4452]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: v12/v11
- Browser and version: safari
- OS and version:mac os 14.5

### Live code example

https://codesandbox.io/p/sandbox/hardcore-jennings-p8fpww?file=%2FApp.js%3A16%2C1

### Describe the Bug

use mui menu inside react flow have a strange problem, when I right click node and click some menu item, the pane of reactflow move to wrong position.

### Steps to reproduce the bug or issue

1. right click node `b` to enable mui context menu
2. click menu item to close mui menu

### Expected behavior

reactflow pane don't move during using context menu

### Screenshots or Videos

<img width="768" alt="screenshot" src="https://github.com/user-attachments/assets/011e39ab-14b7-41f3-9582-19e416c0fb45">

![output](https://github.com/user-attachments/assets/eb6d4eed-933e-4215-bdd5-2dd47a526efa)

**Comment by moklick** [comment]
There are different things you could do about it:

1. add `disableAutoFocus` and `autoFocus={false}` to the mui `Menu` component

or

2. add 

```css
.react-flow__renderer {
  position: fixed;
}
``` 

to your css (this only works for full screen apps)

**Comment by FindDefinition** [comment]
> There are different things you could do about it:
> 
> 1. add `disableAutoFocus` and `autoFocus={false}` to the mui `Menu` component
> 
> or
> 
> 2. add
> 
> ```css
> .react-flow__renderer {
>   position: fixed;
> }
> ```
> 
> to your css (this only works for full screen apps)
option 1. don't work
option 2. not possible
solved by add `disableRestoreFocus` to `Menu`.
