### ISSUE TITLE
TypeScript Error - Node.internals doesn't exist in the type export

### ISSUE THREAD

**Issue by peilingjiang** [xyflow/xyflow#4454]
### What platform were you using when you found the bug?

- React Flow version: 12.0.2
- Browser and version: Chrome (latest)
- OS and version: MacOS 14.5

### Describe the Bug

The `node.internals.positionAbsolute` triggers linting errors as `Property 'internals' does not exist on type 'Node'.ts(2339)`. The syntax is used in the Floating Edge example - and it currently works.

### Steps to reproduce the bug or issue

Check out the Floating Edge or Easy Connect examples.

### Expected behavior

Export the type so that the linting error goes away, or `Node.positionAbsolute` works.

**Comment by bcakmakoglu** [comment]
The `Node` type has no `internals` property anymore.
This only exists in `InternalNodeBase` type which is a type that is returned using `getInternalNode` or `useInternalNode` (which the Floating Edges example uses) 

```ts
const sourceNode = useInternalNode(source);
const targetNode = useInternalNode(target);

console.log(sourceNode.internals.positionAbsolute)
```
