### ISSUE TITLE
NodeResizer lineStyle boderStyle invalid

### ISSUE THREAD

**Issue by xiaoyaovo** [xyflow/xyflow#4461]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 11.11.4
- Browser and version: 126.0.2592.102
- OS and version: Windows 10

### Describe the Bug

Setting borderStyle is invalid. After making slight modifications in your official website example, the same problem occurred.
![Snipaste_2024-07-17_16-56-01](https://github.com/user-attachments/assets/81d5eb07-86d3-4110-a438-a096411b2632)

### Steps to reproduce the bug or issue

example address: https://reactflow.dev/examples/nodes/node-resizer.
souceCode like this: 
![Snipaste_2024-07-17_17-06-48](https://github.com/user-attachments/assets/559f2f86-c1b8-43ae-afe0-67e5011fd320)

### Expected behavior

thank you.

**Comment by bcakmakoglu** [comment]
The border style *is* solid **but** each line has a different direction of border applied by default.
The top line would usually have `border-top-width: 1px` applied to it.

By using `border: 2px solid` you create a border *all around* which makes it look like it's somehow a border with a transparent line through it, when in reality it's just a border on all sides inside of only *one* side.

Not sure if this is actually considered a "bug" since it's really just a side-effect of the style you're using (also the border is already *solid* by default, so why even attempt to change that? If it's about thicker lines, you might wanna create a custom resizer instead since this wouldn't work the way you want it to, or you can use CSS and apply the thicker border style per side).

**Comment by xiaoyaovo** [comment]
> The border style _is_ solid **but** each line has a different direction of border applied by default. The top line would usually have `border-top-width: 1px` applied to it.
> 
> By using `border: 2px solid` you create a border _all around_ which makes it look like it's somehow a border with a transparent line through it, when in reality it's just a border on all sides inside of only _one_ side.
> 
> Not sure if this is actually considered a "bug" since it's really just a side-effect of the style you're using (also the border is already _solid_ by default, so why even attempt to change that? If it's about thicker lines, you might wanna create a custom resizer instead since this wouldn't work the way you want it to, or you can use CSS and apply the thicker border style per side).

My custom node borderWidth is 2px, when i use NodeResizer, it so ugly.
![image](https://github.com/user-attachments/assets/82ae335c-677a-4308-aeb0-3b7a7aa01aa0)

so i want set NodeResizer boderWidth 2px. as you say, i set boder2px in NodeResizer, it also like this(I hope I didn't misunderstand your meaning).
![image](https://github.com/user-attachments/assets/07367b06-864c-4ffa-b742-f8921ffc952f)
![image](https://github.com/user-attachments/assets/6a73e775-1107-4ad0-83ee-6e28cf576c13)

**Comment by bcakmakoglu** [comment]
No, that's not gonna work, you're just describing each border side but it's still gonna be applied for *each line on each side*.
You have to understand that each side is a single line element, so if you define a border style like that it will go around each line element.
The lines are not a *single* element that go around the node, they are *four* different line elements.

What you would want to do is this:
```css
.react-flow__resize-control.line.top {
	border-top-width: 2px;
}

.react-flow__resize-control.line.right {
	border-right-width: 2px;
}

.react-flow__resize-control.line.left {
	border-left-width: 2px;
}

.react-flow__resize-control.line.bottom {
	border-bottom-width: 2px;
}
```

**Comment by xiaoyaovo** [comment]
Thank you very much for patiently solving my problem

**Comment by xiaoyaovo** [comment]
Thank you very much for patiently solving my problem . @bcakmakoglu

**Comment by moklick** [comment]
Thanks @bcakmakoglu !
