### ISSUE TITLE
 Documentation website UX issue

### ISSUE THREAD

**Issue by aviramdev** [xyflow/xyflow#4462]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Describe the Bug

There are some issues with the pro account dashboard. First of all I would love to have a quick transition from the dashboard to the normal screen where I see the documentation, currently I have to go back several times and it is less convenient than just a navigation button. Another thing is that in some of the examples it is written in the readme to install the package the old way 'npm install reactflow' but in the code sample it uses v12 "import {} from '@xyflow/react'" which is a bit confusing.
And one last thing after I log in and I go back to see the docs it shows me that I am no longer logged in but as soon as I click log in it logs me in

### Steps to reproduce the bug or issue

-

### Expected behavior

-

### Screenshots or Videos

https://github.com/user-attachments/assets/092e6cba-6197-47c2-8bcd-53ab470db8df

**Comment by moklick** [comment]
Thanks for the report. We just updated the readme files and check the login/signup flow asap.

**Comment by moklick** [comment]
Currently we don't have any information about your status as a subscriber in the normal docs. That's also true for the pro landing page. We might change that in the future to be able to improve the transition between docs and pro platform.

**Comment by aviramdev** [comment]
> Currently we don't have any information about your status as a subscriber in the normal docs. That's also true for the pro landing page. We might change that in the future to be able to improve the transition between docs and pro platform.

ok, thanks for taking your time to check it :)
