### ISSUE TITLE
How can i prevent or stop the mouse event when i render the three.js model in reactflow

### ISSUE THREAD

**Issue by yolkerrr** [xyflow/xyflow#4470]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: "@xyflow/react": "^12.0.2"
- Browser and version: chrome
- OS and version: window11

### Describe the Bug

the  problem is when i render the three.js model in my  custom node, i want to drag or rotate the model when i use mouse down and move, but the custom node move first, so how can i prevent or stop the custom node mouse event ,the three.js model render  result is a  canvas tag

### Steps to reproduce the bug or issue

1 the mouse move into and over the custom node which render threejs model
2 down the mouse left button and move the mouse,just i want to rotate the threejs model 
3 it not working according to my ideas，the custom node move first

### Expected behavior

i want to when i mouse over the threejs model node ,the reactflow can not listen the mouse move or down event ,but when i out the custom node  the reactflow can work normally

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/77f217f5-f9f2-410f-99f0-60f3311ec98e)

**Comment by yolkerrr** [comment]
i try to set the custom node draggable false and it work.but the new problem is the reactflow background will move also,and that is confuse me, how can i stop the reactflow background or view port move when i drag move the threejs model

**Comment by moklick** [comment]
You need to add the class name "nodrag" to the canvas element.

**Comment by yolkerrr** [comment]
> You need to add the class name "nodrag" to the canvas element.

now the custom node drag problem is resolved  when i add draggable 'false'.  see it:

![image](https://github.com/user-attachments/assets/62860955-29ce-45d4-91c1-23fa48df78e9)

but the new problem is when i drag in threejs model, the whole viewPort  will be move also.

or when i scroll the mouse wheel in threejs model to change model zoom,  the viewPort zoom also change.

how should i do

**Comment by yolkerrr** [comment]
> but the new problem is when i drag in threejs model, the whole viewPort will be move also.
> 
> or when i scroll the mouse wheel in threejs model to change model zoom, the viewPort zoom also change.
> 
> how should i do

i just  want the code to resolve the problem :  "when i put the pointer enter the threejs model custom node,whole viewPort will lock and not listen any event just like  drag,mouseove,mousewheel ..."

**Comment by bcakmakoglu** [comment]
Have you actually used the `nodrag` class name on the canvas element as suggested by Moritz?^^

**Comment by bcakmakoglu** [comment]
There's also a `nopan` class name that you'd have to apply if you wanna prevent the viewport being moved when dragging the canvas element.

**Comment by yolkerrr** [comment]
> Have you actually used the `nodrag` class name on the canvas element as suggested by Moritz?^^

very nice it!

**Comment by yolkerrr** [comment]
> There's also a `nopan` class name that you'd have to apply if you wanna prevent the viewport being moved when dragging the canvas element.

very thanks!

**Comment by yolkerrr** [comment]
good job for all reactflow developer!thanks so much!
