### ISSUE TITLE
Floating Edges Example have some issue

### ISSUE THREAD

**Issue by Eliwang4264** [xyflow/xyflow#4471]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Describe the Bug

`node.measured.positionAbsolute`  should be `node.internals.positionAbsolute`, right?

### Steps to reproduce the bug or issue

1. Access https://reactflow.dev/examples/edges/floating-edges

### Expected behavior

Correctly obtain the value of `nx` `ny`
<img width="259" alt="WXWorkCapture_17213636163102" src="https://github.com/user-attachments/assets/6372846c-6fef-4fbb-aaa8-85279cf31a07">

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/facd4b6f-8c09-40ad-9115-f771d841ba35)
<img width="271" alt="WXWorkCapture_17213634866734" src="https://github.com/user-attachments/assets/07a8c352-5ce6-4f46-aab4-c361a2464a19">

**Comment by peterkogo** [comment]
You are absolutely correct! Have pushed a fix, should be online in a couple of minutes.
