### ISSUE TITLE
useUpdateNodeInternals doesnot update node dimensions on dynamic increase of handles

### ISSUE THREAD

**Issue by Dyl777** [xyflow/xyflow#4473]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Live code example
This is my code :
const randomizeHandleCount = useCallback(() => {
    setHandleCount(Math.floor(Math.random() * 10) + 2);
    updateNodeInternals(id);
  }, []);

  useEffect(() => {
    updateNodeInternals(id);
  }, [handleCount, id, updateNodeInternals]);
   
  return (
    <>
    <span style={{ width: `auto`, height : `auto` }}>
      {Array.from({ length: handleCount }).map((_, index) => (
        <Handle
          key={index}
          type="target"
          position="left"
          id={`handle-${index}`}
           style={{ left: `${index * 30}px` }} // Adjust spacing between handles
        />
 ))}
      <--div>
        <--button onClick={randomizeHandleCount}>Randomize handle count<--/button-->
        <--p>There are {handleCount} handles on this node. I am adding -- to the html tag because the issue editor seems to be rendering it<--/p-->
      <--/div-->
      <--/span-->
     </>
  );
}

### Describe the Bug

I ran across this trying to create a node with dynamic number of handles.  I used the example from the documentation https://reactflow.dev/api-reference/hooks/use-update-node-internals
I have tried wrapping the custom node with a div tag with styling to increase the dimensions,
have tried to query the dimensions using useRef ,
when my number of handles are longer than the node dimensions, they just overflow and continue even without a corresponding change in the node dimensions.
Based on the implementation of useUpdateNodeInternals, it seems that such a thing was not added
import { useCallback } from 'react';
import type { UpdateNodeInternals, InternalNodeUpdate } from '@xyflow/system';

import { useStoreApi } from '../hooks/useStore';

/**
 * Hook for updating node internals.
 *
 * @public
 * @returns function for updating node internals
 */
export function useUpdateNodeInternals(): UpdateNodeInternals {
  const store = useStoreApi();

  return useCallback<UpdateNodeInternals>((id: string | string[]) => {
    const { domNode, updateNodeInternals } = store.getState();
    const updateIds = Array.isArray(id) ? id : [id];
    const updates = new Map<string, InternalNodeUpdate>();

    updateIds.forEach((updateId) => {
      const nodeElement = domNode?.querySelector(`.react-flow__node[data-id="${updateId}"]`) as HTMLDivElement;

      if (nodeElement) {
        updates.set(updateId, { id: updateId, nodeElement, force: true });
      }
    });

    requestAnimationFrame(() => updateNodeInternals(updates));
  }, []);
}

How do I make the number of handles to trigger a fitting node dimension then. I tried the above.

### Steps to reproduce the bug or issue

![Capture](https://github.com/user-attachments/assets/21b4d819-0991-4c5b-b4ea-d8ea5ef9bad7)

### Expected behavior

Expecting useRefs and/or requestAnimationFrames to have an effect on the dimensions of the node but none

**Comment by bcakmakoglu** [comment]
Updating node internals isn't magically going to extend your node, you might've misunderstood what the purpose of that function is.
You'll have to adjust the node size *yourself* in order to wrap around all handles you are generating.
Updating node internals only communicates to ReactFlow that a re-measure of the node is necessary (this does not mean the node size will be adjusted for you, it only means that the node is being *re-measured* and new handles, if any exist, recognized).

Seems to me you have to give your node styles a closer look and fix the issue there first.

**Comment by Dyl777** [comment]
Is there a de-facto way of extending the node size dynamically? because in the issue, I have tried using 'useDimensions' with useRef,  I have tried wrapping the custom node with a div tag with styling to increase the dimensions since the Handle tag is within. I have ran out of ideas and I can't even find any info on the closed issues actually solving this specifically

**Comment by bcakmakoglu** [comment]
> I have tried using 'useDimensions' with useRef

Not sure what this would even do?

>  I have tried wrapping the custom node with a div tag with styling to increase the dimensions since the Handle tag is within.

That should be the way you would want to do it. I'm assuming you simply haven't used the proper styles to allow the node to *actually* wrap around all handles.
Also consider that `<Handle>` components are positioned using `position: absolute`, so the wrapping div should use `position: relative` in order for the handles to actually relate to the wrapping div.

**Comment by peterkogo** [comment]
@Dyl777 does this answer your issue?

**Comment by moklick** [comment]
please re-open if the issue persists
