### ISSUE TITLE
Setting nodeExtent prevents group panning.

### ISSUE THREAD

**Issue by pycraft114** [xyflow/xyflow#4475]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.0.0
- Browser and version: chrome
- OS and version: mac

### Live code example

https://codesandbox.io/s/7wvrfw?file=/App.tsx:3836-3904&utm_medium=sandpack

### Describe the Bug

nodeExtent={[
        [0, 0],
        [Infinity, Infinity],
      ]}
      
      add this to ReactFlow component props and drag parent node. child node does not follow parent node

### Steps to reproduce the bug or issue

nodeExtent={[
        [0, 0],
        [Infinity, Infinity],
      ]}
      
      add this to ReactFlow component props and drag parent node. child node does not follow parent node

### Expected behavior

childnode should follow parent node despite of nodeExtent

**Comment by peterkogo** [comment]
This is definitely a bug! Thanks for reporting.

**Comment by pycraft114** [comment]
@peterkogo @moklick the bug behaviour still exist on 12.0.3 version
