### ISSUE TITLE
orientation prop missing on Control component

### ISSUE THREAD

**Issue by kranthi-thought-flow** [xyflow/xyflow#4476]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Describe the Bug

The documentation here https://reactflow.dev/api-reference/components/controls shows orientation as a prop on the Controls component. But I am not able to find it while creating the component 

### Steps to reproduce the bug or issue

Add control component in a typescript application and try to add orientation parameter. It shows an error mark

### Expected behavior

I would expect to be able to add orientation property in the Control component, but unable to 

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/f0e8d43f-7930-464c-9de7-64ff996475ce)

**Comment by bcakmakoglu** [comment]
For reference, here are the v11 docs: https://v11.reactflow.dev/
