### ISSUE TITLE
Calling `getNodes` does not return new added nodes using `addNodes`

### ISSUE THREAD

**Issue by vietmh** [xyflow/xyflow#4486]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.0.3
- Browser and version: Chrome 126.0.6478.182
- OS and version: Ubuntu 22.04

### Live code example

https://codesandbox.io/p/sandbox/vibrant-hermann-36pls8

### Describe the Bug

Hi,
I am appreciate your efforts on this wonderful library. I got an issue but not sure it's intent or it's a bug. Please tell me also if I'm using your library or understanding in a wrong way.

My scenario is:
- Having a button to add node.
- Whenever a node is added, the layout should be updated.

By this, I'm using `useReactFlow` to get the flow then calling `addNodes` to add node into the flow and `getNodes` to re-layout it using `dagre`.
The weird thing to me is that I don't see the new added node when calling `getNodes` right after `addNodes`.
Then I tried to play around a bit further, by trying access the nodes from `setNodes` or use the `useNodesInitialized`, I can see the new added node (This is how I'm working around for the moment).

One more thing I'm wondering is, as far as I understand from the documents, the `useNodesInitialized` will be triggered after the nodes has been updated theirs measures. But for layouting, I need some events to trigger after the nodes has been updated not only theirs measures but also theirs position. So that the `fitView` will work properly in my case.
```
useEffect(() => {
    if (nodesInitialized) {
      relayout_using_dagre();
      fitView();
    }
  }, [nodesInitialized]);
  ```
  

  
Best regards

### Steps to reproduce the bug or issue

1. Call `addNodes` to add new nodes
2. Call `getNodes` to get all the nodes including the new nodes

### Expected behavior

I expected to see the new added nodes when calling `getNodes`, but instead I'm seeing only the old nodes.

**Comment by moklick** [comment]
The reason for this is that `addNodes` and `setNodes` is batched and not processed when you call getNodes in the same render tick. I will see what we can do about it.

**Comment by vietmh** [comment]
@moklick ,
Is it possible for the `getNodes` to check against the batched when getting data from the store?

**Comment by moklick** [comment]
I don't think that we can/want to do anything about it. `getNodes` should return measured nodes and for that we need to wait for the next render. You could wait by using `requestAnimationFrame` or `queueMicrotask`:

```js
queueMicrotask(() => {
  setNodeCount(reactFlow.getNodes().length);
});
```

**Comment by vietmh** [comment]
Yes, It's OK for me as a work-around for the moment. Thank you.

**Comment by JoeGaffney** [comment]
Hey, this is quite confusing that getNodes only returns measured nodes how do we just get all nodes

**Comment by bcakmakoglu** [comment]
> But from a developer point of view the names getNodes does indicate that it would return alll the nodes that are visible.

If a node hasn't been measured it's not visible, so technically `getNodes` *does* only return nodes that are visible ^^
