### ISSUE TITLE
Can the Interactive button be set to default true or false?

### ISSUE THREAD

**Issue by biubiubiuG** [xyflow/xyflow#4487]
### Please describe the feature that you want to propose

I want to set ReactFlow to read-only for display purposes only, and all elements cannot be edited. What should I do?

**Comment by moklick** [comment]
For this you should set 

```js
<ReactFlow
  nodesDraggable={false}
  nodesConnectable={false}
  elementsSelectable={false}
  nodesFocusable={false}
  edgesFocusable={false}
/>
```

or you could use CSS:

```css
.react-flow {
  pointer-events: none;
}
```
