### ISSUE TITLE
[v12] getMarkerEnd not exported

### ISSUE THREAD

**Issue by Pelv** [xyflow/xyflow#4490]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version:  v12.0.3
- Browser and version: Brave [Version 1.68.128](https://brave.com/latest/)
- OS and version: MacOS v14.5

### Describe the Bug

ts bug: Module '"@xyflow/react"' has no exported member 'getMarkerEnd'

### Steps to reproduce the bug or issue

1. trying to import the function from "@xyflow/react"

### Expected behavior

As for the docs, should be exported.

### Screenshots or Videos

<img width="1118" alt="Screenshot 2024-07-25 at 15 19 02" src="https://github.com/user-attachments/assets/7efadf7a-c728-4db9-a3f8-4f622778baa6">

**Comment by bcakmakoglu** [comment]
`getMarkerEnd` doesn't exist anymore, the docs seem to be outdated in that regard.

What exactly do you need this function for?

**Comment by Pelv** [comment]
@bcakmakoglu ah, even in the migrate docs it's not specified. I was using it to get the id of the default markers. Maybe now it's static string that doesn't change?

**Comment by Pelv** [comment]
It doesn't work in my case unfortunately cause i have few different custom markers that i apply to my BaseEdge bases on edge.data, one of which is a simple arrow so i was using the library default one.

Anyway, since it's deprecated i'll just create another custom makers for the Arrow and that's ok.
Please update the doc when you guys have time 🙏 

P.S. i'm a bit new to git issues for open projects, should i close the issue or wait and let the dev close it?

**Comment by bcakmakoglu** [comment]
If you feel like your issue is resolved then you are free to close it, otherwise someone else would close it if they feel like the issue has been resolved 😅

**Comment by Pelv** [comment]
Closing the issue since it's a deprecated feature. Thanks @bcakmakoglu
