### ISSUE TITLE
ReactFlow v12 - class `nodrag` doesn't prevent selection as it did in previous versions

### ISSUE THREAD

**Issue by M-sleeper** [xyflow/xyflow#4493]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.0.3
- Browser and version: Google Chrome 126.0.6478.126
- OS and version: Ubuntu 24

### Live code example

https://codesandbox.io/p/sandbox/reactflow-nodrag-exmple-forked-fczk2z

### Describe the Bug

The class `nodrag` doesn't prevent selection in the new v12 Reactflow. This class was suggested in [this](https://github.com/xyflow/xyflow/issues/697) issue to prevent the selection on ex. input components. I couldn't find any official documentation elsewhere how to do it.

### Steps to reproduce the bug or issue

1. Go to https://codesandbox.io/p/sandbox/reactflow-nodrag-exmple-forked-fczk2z
2. Click on the node containing "Not selected"
3. Node's state changes to selected despite having the class `nodrag` on it

### Expected behavior

I expect the same behavior, meaning that the selection is prevented for class `nodrag` as in previous versions, see working example on v11.11.4 https://codesandbox.io/p/sandbox/reactflow-nodrag-exmple-forked-rq6gfv

### Additional context

Eventually, it would be more straight forward to have a dedicated class (and documentation) for preventing selection.

**Comment by bcakmakoglu** [comment]
`nodrag` behaves the same as it did in v11.
What did change though is the default value of `nodeDragThreshold` which in v11 was set to `0` (as to not introduce a breaking change) while v12 uses `1` as the default value.

If you want the same behavior as previously, set `nodeDragThreshold={0}` again.

For comparison a v11 sandbox with `nodeDragThreshold={1}` producing the same result as v12's default behavior: https://codesandbox.io/p/sandbox/dank-worker-c7f25r?file=%2FCircleNode.jsx%3A19%2C32

(use the input node on the bottom right and observe that it's gonna be selected/unselected)

And a v12 sandbox with `nodeDragTheshold={0}` producing the default behavior of v11: https://codesandbox.io/p/sandbox/reactflow-nodrag-exmple-forked-vtvz2d?file=%2Fsrc%2FApp.js%3A60%2C29

**Comment by M-sleeper** [comment]
@bcakmakoglu Thanks for the answer. Since having `nodeDragThreshold={1}` has other benefits, I decided to use the workaround suggested in the related [issue](https://github.com/xyflow/xyflow/issues/697#issue-746231429).
I still suggest to have a dedicated class for preventing selection.
