### ISSUE TITLE
Make ViewportPortal a ForwardRef Component

### ISSUE THREAD

**Issue by freehour** [xyflow/xyflow#4494]
### Please describe the feature that you want to propose

I need a `ref` to the `ViewportPortal` to use it with Radix popovers where you can explictly set the container where the popover is portaled to.
Currently I wrote a simple wrapper for the ViewportPortal
```typescript
const ForwardViewportPortal: ForwardRefRenderFunction<HTMLDivElement, PropsWithChildren> = ({ children }, ref) => {
    return (
        <Reactflow.ViewportPortal>
            <div ref={ref}>{children}</div>
        </Reactflow.ViewportPortal>
    );
};

export const ViewportPortal: ForwardRefExoticComponent<PropsWithChildren & RefAttributes<HTMLDivElement>> =
    forwardRef(ForwardViewportPortal);
```
This works fine however it creates an extra div. It would be nice if `ViewportPortal` could provide the `ref` directly.

**Comment by moklick** [comment]
It's a good idea but I don't want to add another element as a ref container and there is no way to pass a ref to the `createPortal` function that we are using here. I think it's fine to use the ref at child you are passing to the `ViewportPortal` as seen in your solution. Thanks for sharing!
