### ISSUE TITLE
Wrong Edges Position on Nested Flow Instances with Autolayout

### ISSUE THREAD

**Issue by ranjabi** [xyflow/xyflow#4495]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 11.11.4
- Browser and version: Chrome Version 126.0.6478.183
- OS and version: macOS Sonoma 14.2.1

### Live code example

https://codesandbox.io/p/sandbox/react-flow-issue-x4ryrc?file=%2Fsrc%2Findex.tsx

### Describe the Bug

I have a custom node that can render a div (like a normal node) or another react flow instance conditionally. The sandbox example is the simple version of my app that I am currently building. It will display a tree hierarchy, with each node can also be another tree hierarchy. I used nested flow instances approach instead of using Sub-Flows feature because the node size can be dynamic in my app and it equipped with auto layout. 

I also found it easier by having nested flow instances to manage the data. In this example, the nested flow instance will have it's nodes and edges stored inside **data** attributes on it's outer node.

For the normal/outer instance, I use elkjs for auto layout. For the nested flow instance, I use dagree since I don't need complex settings on it. I tried to use both elkjs but the issue still persist in nested flow instance.

My nested flow instance seems render edges in wrong position after auto layout is performed. It doesn't connected to the node handler.

### Steps to reproduce the bug or issue

1. Go to sandbox example.
2. Click **Nested Instances** button on the left top.

The nested nodes will render another tree hierarchy.

### Expected behavior

After clicking **Nested Instances** button, I expect the nested nodes will render another flow instance with the nodes and edges in correct position after performing auto layout. But instead the edges seems not in the right position, it's not connected to the nodes handler.

### Screenshots or Videos

Normal condition, custom node will display a div with node label.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/1af962eb-d9aa-42c8-ad93-d32423fd6130">

After clicling Nested Instances button, the nodes with nested flow instances will render another tree but the edges is misplaced.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e16a2b1c-e40d-4397-b5df-cb08270ad98a">

InitialNodes data structure. The nested flow instances nodes and edges stored in data attribute.
<img width="504" alt="image" src="https://github.com/user-attachments/assets/fc21f992-3f47-4b5c-9bcf-e01f3eff806d">

**Comment by bcakmakoglu** [comment]
Afaik, nested flows aren't supported so you'll have to render the "nested" one outside the `<ReactFlow>` tag otherwise you'll run into alignment issues with edges.

**Comment by peterkogo** [comment]
As this is the second issue I saw of someone trying to nest React Flow instances or apply transforms to the parent element (which both seem like sensible things to do, imo), there might be an easy way to figure out if any top level transforms have been applied while measuring the nodes. It is [surprisingly trivial](https://stackoverflow.com/questions/5603615/how-to-get-the-scale-value-of-an-html-element-using-javascript-or-jquery).

However, there might be more moving parts I am missing here, so no guarantees.

**Comment by simenravnik** [comment]
+1 same issue here with nested flows

**Comment by moklick** [comment]
Unfortunately nesting ReactFlow components is not supported. We've added the subflow feature for this https://reactflow.dev/learn/layouting/sub-flows
