### ISSUE TITLE
[v11] Deleting a sub flow node results in error "Parent node xyz not found"

### ISSUE THREAD

**Issue by sgehrig** [xyflow/xyflow#4497]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version:  11.11.4
- Browser and version: Google Chrome 126.0.6478.185 (but doesn't matter)
- OS and version: macOS 14.5 (but doesn't matter)

### Live code example

https://codesandbox.io/p/sandbox/beautiful-alex-6h3dfr?file=%2Fsrc%2Fnodes%2Findex.ts%3A14%2C2

### Describe the Bug

I know that there's #3432 and #3433 already but it seems that deleting a sub flow node still has some issues even when the nodes array is sorted (sub flow node first then children).

Deleting the sub flow node `g` in the example above results in an error

> Parent node g not found

### Steps to reproduce the bug or issue

1. Load example provided above
2. Select sub flow node (others are not selectable)
3. Press the delete key

### Expected behavior

As a user, I expect the sub flow node to be deleted, but instead I'm getting an error message `Parent node g not found`.

### Additional context

I'm pretty sure this worked previously but I've just updated to 11.11.4 and deleting the sub flow nodes does not work anymore. 

Thanks in advance for your efforts! This is much appreciated.

**Comment by sgehrig** [comment]
OK. I think I know the reason, but I'm not sure what's the correct or expected behaviour.
I my code all the child nodes are not `deletable` because the use must be able to select the node (to change some properties) but must not delete the node from within a sub flow. The sub flow itself is `deletable`. It seems as if the deletion code checks for the `deletable` property on child nodes and keeps them even though the parent sub flow has been deleted. What remains are the child nodes with a `parentId` set to a now non-existing sub flow.

What is the expected behaviour? And of this is the expected behaviour what would be a way to allow deletion of a sub flow but not of each individual child node?

**Comment by bcakmakoglu** [comment]
You could listen to removal changes in `onNodesChange` reassign `parentId` to `undefined` and adjust the node position so it doesn't jump somewhere else since the position, when using `parentId`, is in relation to the parent node.

[Something like this should work](https://codesandbox.io/p/sandbox/blissful-rosalind-k3gmj4?file=%2FApp.js%3A127%2C40), although it can probably be written a bit more elegantly 😅

**Comment by sgehrig** [comment]
@bcakmakoglu Thanks a lot for the quick response. I managed to update to `@xyflow/react ^12.0.0` and now I can use the `onBeforeDelete` hook to include the child nodes into the list of nodes to be deleted.

Not sure if this is still considered a bug. If not, please feel free to close it.
