### ISSUE TITLE
Issue with node multiples handles connections

### ISSUE THREAD

**Issue by GuillaumeOnepilot** [xyflow/xyflow#4506]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: @xyflow/react 12.0.3
- Browser and version: Google Chrome 126
- OS and version: macOS Sonoma 14.5 

### Describe the Bug

When starting a connection between 2 nodes and not finishing it, an edge is created for the first handle when making a second connection from the same node but on a different handle.

I'm trying to understand what I could be doing wrong to have this issue

### Steps to reproduce the bug or issue

I don't manage to reproduce the issue in a code sandbox, but it goes like this: 

1. Create a node with multiple source handles
2. Try to link the first handle to another node, but stop before finishing the connection
3. 2 edges are created when only 1 should have been

### Expected behavior

As a user, I expect the first edge to not appears when making the second connection

### Screenshots or Videos

https://github.com/user-attachments/assets/3d62abbe-46ff-4f12-9334-7164af0246ab

### Additional context

I made some validation check through the `isValidConnection` props, but since the handles act as the connection is valid it doesn't seem to come from there

**Comment by bcakmakoglu** [comment]
I believe this issue is fixed in `12.0.4`, can you try upgrading and checking if the issue persists?

**Comment by GuillaumeOnepilot** [comment]
Thanks for the fast answer, I will try to upgrade 👍

**Comment by GuillaumeOnepilot** [comment]
I upgraded, and it's indeed working as expected, thanks for the support
