### ISSUE TITLE
SvelteFlow: Attach an edge to an edge

### ISSUE THREAD

**Issue by kerem0comert** [xyflow/xyflow#4508]
### Please describe the feature that you want to propose

This is a long shot but I just wanted to know whether there is built-in functionality to attach a node to an edge, or if not  if there is an easy way to simulate this functionality. 

As you know the user can drag an edge by clicking on a node's `Handle` and if the user moves up the left click while hovering over another node's `Handle` that edge is considered to be formed between one node and another where the new object has the individual node's id's in its `source` and `target` attributes.

What I need is that after a user starts dragging an edge around with his mouse down, this edge being dragged should be formed if he moves the left click up near an edge. In this case the node that this is dragged from is the `source` and the edge on which the dragged edge is dropped is the `target`. And what is also important is that this newly created edge between another edge and a node gets correctly rendered as the nodes and edges are moved around? Is this possible?

I thought of a way of listening for left click up and if the user was indeed dragging an edge when the left click was up that an invisible node is created to create this new edge, but of course if the user starts dragging around the components this would be rather hard to maintain.

Looking forward to any help in the right direction!

**Comment by moklick** [comment]
I am not sure if I get your question right. Do you want to create a new node when you drop an edge?

**Comment by peterkogo** [comment]
This is something we do not support right now, but you can solve this by creating an invisible node with overlapping handles at the desired point along the edge, you'd like to connect to.

**Comment by kerem0comert** [comment]
> This is something we do not support right now, but you can solve this by creating an invisible node with overlapping handles at the desired point along the edge, you'd like to connect to. You have access to `onEdgeMouseEnter` events which would tell you when the user is hovering over an edge when creating a connection.

Thanks for the suggestion. I think this would indeed work, but consider this three state scenario:
![states](https://github.com/user-attachments/assets/26eb91e0-9c32-4a3b-9a0b-474e30b6bb63)

1- Initial state
2- User drops the edge being dropped from `n3` to the `n1-n2´ edge, invisible node `n4` gets created, everything looks nice
3- User decides to move `n2` to the right, the `n1-n2` edge naturally moves. `i4` is left in the wrong place.

Wouldn't this scenario occur, or am I missing something? If so, is there a possible fix? Thanks!

**Comment by bcakmakoglu** [comment]
You can just update the position of the node when the edge is changed due to the source/target nodes being moved.

[There's an old example for this here.](https://codesandbox.io/p/sandbox/nodeedge-example-rgdtyk?file=%2Fsrc%2FEdgeNode.tsx)

**Comment by kerem0comert** [comment]
Thank you, it seems that this should work!

**Comment by kerem0comert** [comment]
> This is something we do not support right now, but you can solve this by creating an invisible node with overlapping handles at the desired point along the edge, you'd like to connect to. You have access to `onEdgeMouseEnter` events which would tell you when the user is hovering over an edge when creating a connection.

I am not sure if I am missing it, but is it possible that `onEdgeMouseEnter` exists for `ReactFlow` but not for `SvelteFlow`? I could not find it in the IntelliSense or in the [API Reference](https://svelteflow.dev/api-reference/svelte-flow#edge-events). I see [another issue referencing it](https://github.com/xyflow/xyflow/issues/4523), but again for `ReactFlow`.

**Comment by moklick** [comment]
`<SvelteFlow on:edgemouseenter={..} />` should work.

**Comment by moklick** [comment]
can we close this issue @kerem0comert =

**Comment by kerem0comert** [comment]
So this issue is connected to the [other issue I opened here](https://github.com/xyflow/web/issues/465), where I am trying to drag a node from an external Palette and if it is dropped on an edge, the edge to node connection that I talk in this issue needs to be formed.

As such, the problem I have at the moment is while `on:edgemousenter` indeed works when no mouse button is down, it does not fire when the mouse actually does the exact same movement while still a `dragover` from the `Palette` into the `Flow` is taking place. In other words, I cannot get this event to fire whenever the user is dragging a node from the Palette and crosses an edge before dropping it.

My approximate solution would be that in the `on:drop` event of a node, I can iterate over the edges and based on the positions of the `source` and `target` nodes of a given edge, approximate the distance between where the new node is dropped and any given edge, to try to find out whether an edge is close enough to be considered that this node is indeed dropped on an edge, and then finally form the node to edge connection that I talk about in this issue.

Do you think there is an easier way, or nothing in this direction is supported at the moment?

**Comment by peterkogo** [comment]
@kerem0comert I would highly suggest you use a custom edge in this case. In hindsight, the whole idea that there are built-in nodes and edges that can be controlled by global event listeners like `on:edgemouseenter` was a mistake for reasons like this. 

If you just create a custom edge by copy and pasting the code of the bezier edge for instance, you are in full control about what events you attach to your edge. Then you can simply add an `on:dragenter` handler on your edge.

**Comment by kerem0comert** [comment]
Alright, thanks for the suggestion @peterkogo . I will be trying that out and updating my progress on this issue but not within this week potentially, so up to you if you want to keep this issue open or close it. In the latter case I can just reopen it I guess.

**Comment by kerem0comert** [comment]
I achieved roughly the desired result. Since my edges are straight, I did not use the Bezier curve methodology but rather a more straight-forward position calculation. Maybe because of this the `ÈdgeNode` is not exactly on the edge that it is "tied to", but I believe I can make this better with further adjustments later on.

For reference, I achieved it in the following way:

In my `Flow.svelte` I have the following callbacks on my `SvelteFlow` component:
```svelte
<div style="height:86vh; position:relative;" bind:clientHeight bind:clientWidth>
  <Palette />
  <SvelteFlow
    initialViewport={INITIAL_VIEWPORT}
    nodes={nodesWritable}
    edges={edgesWritable}
    nodeTypes={STATE_TYPE_TO_SVELTE_NODE_COMPONENT}
    edgeTypes={EDGE_TYPE_TO_SVELTE_EDGE_COMPONENT}
    on:nodecontextmenu={handleContextMenu}
    on:paneclick={handlePaneClick}
    on:dragstart={(e) => console.log('Drag start', e)}
    on:dragover={onDragOver}
    on:drop={onDrop}
    on:nodeclick={handleNodeClick}
    on:nodedragstop={handleNodeDragStop}
    on:nodedrag={handleNodeDrag}
    on:edgemouseenter={handleEdgeMouseEnter}
    on:edgeclick={handleEdgeClick}
    onconnectend={handleEdgeConnectEnd}
    onconnectstart={handleEdgeConnectStart}
    autoPanOnNodeDrag
  >
    <div class="controls">
      <Controls orientation="horizontal">
        <ControlButton on:click={() => console.log('⚡️')}>⚡️</ControlButton>
      </Controls>
    </div>
    <Background variant={BackgroundVariant.Lines} />
    <MiniMap />
  </SvelteFlow>
  {#if contextMenuProps}
    <NodeContextMenu
      onClick={handlePaneClick}
      on:nodeDeleted={(e) => handleNodeDeleted(e.detail.id)}
      on:nodeDuplicated={handleNodeDuplicated}
      id={contextMenuProps.id}
      top={contextMenuProps.top}
      left={contextMenuProps.left}
      right={contextMenuProps.right}
      bottom={contextMenuProps.bottom}
    />
  {/if}
</div>
```

where in the `handleOnDrop` function, I create the invisible `EdgeNode` and form the initial edge between it and the node being dropped:

```typescript
// ...some more logic...
const edgeCenter = getEdgeCenter({
        sourceX: sourceNode.position.x,
        sourceY: sourceNode.position.y,
        targetX: targetNode.position.x,
        targetY: targetNode.position.y
      })
  newEdgeNode = {
    id: generateId(),
    position: { x: edgeCenter[0], y: edgeCenter[1] } as XYPosition,
    type: 'EDGE_NODE',
    data: {
      source: edgesDroppedInto[0].source,
      target: edgesDroppedInto[0].target
    }
  } as Node

  nodesWritable.update((nodes) => [...nodes, newEdgeNode])
}
}

const newNode: Node = {
  id: newNodeId,
  position,
  type: nodeType,
  data: {}
}
if (newEdgeNode) {
  const edgeBetweenEdgeNodeAndReportingNode: Edge = {
    id: generateId(),
    source: newEdgeNode.id,
    target: newNode.id,
    type: EdgeType.STRAIGHT,
    data: { highlightDisabled: true }
  } as Edge
  edgesWritable.update((edges) => [...edges, edgeBetweenEdgeNodeAndReportingNode])
}
```

Later on at `handleNodeDrag` I check whether any `EdgeNode`s need to be updated if any of its `source` or `target` are being dragged:

```typescript
const handleNodeDrag = (event: CustomEvent) => {
    console.log('Node drag event', event.detail)
    const nodesBeingDragged: Node[] = event.detail.nodes
    const nodes: Node[] = getNodes()
    nodes.forEach((node) => {
      if (node.type === 'EDGE_NODE') {
        const edgeNode = node
        const sourceNode = nodes.find((n) => n.id === edgeNode.data.source)
        const targetNode = nodes.find((n) => n.id === edgeNode.data.target)
        if (
          sourceNode &&
          targetNode &&
          (nodesBeingDragged.some((n) => n.id === sourceNode.id) ||
            nodesBeingDragged.some((n) => n.id === targetNode.id))
        ) {
          const edgeCenter = getEdgeCenter({
            sourceX: sourceNode.position.x,
            sourceY: sourceNode.position.y,
            targetX: targetNode.position.x,
            targetY: targetNode.position.y
          })
          edgeNode.position = { x: edgeCenter[0], y: edgeCenter[1] } as XYPosition
          nodesWritable.update((currentNodes) =>
            currentNodes.map((n) => (n.id === edgeNode.id ? edgeNode : n))
          )
        }
      }
    })
    updateNodesAndEdges($nodesWritable, null)
  }
```

In this case, I do not need any further logic on the `EdgeNode´ itself:
```svelte
<script lang="ts">
  import { Handle, Position } from '@xyflow/svelte'
</script>

<div class="content"></div>
<Handle type="source" position={Position.Top} id="a" class="handle top-handle" />
<Handle type="source" position={Position.Right} id="b" class="handle right-handle" />
<Handle type="source" position={Position.Bottom} id="c" class="handle bottom-handle" />
<Handle type="source" position={Position.Left} id="d" class="handle left-handle" />

<style>
  .content {
    @apply w-[80px] h-[20px] opacity-0;
  }

  :global(.svelte-flow__node .svelte-flow__handle) {
    @apply w-0 h-0 bg-transparent border-none;
  }

  :global(.svelte-flow__handle.connectingto) {
    @apply bg-transparent;
  }

</style>
```

One problem I have though is that I use the `:global(.svelte-flow__node .svelte-flow__handle)` selector to style the `Handle`s of the `EdgeNode` to make it invisible. However, in my `Flow.svelte` I also style the `Handle`s using the same global selector, since for any other handle I need them to be **visible** and have a certain style. How to ensure that the `EdgeNode` handles have a specific style that is different than the global `Handle` style? Probably I am missing something very obvious, but so far removing the `global` keyword in `EdgeNode.svelte` did not help either.

Thanks! 


I am not sure if this is really the

**Comment by peterkogo** [comment]
When working in a custom node you can simply add another level of css specificity by adding the class `.svelte-flow__node-CUSTOM_NODE_NAME` to your selectors.

I will close this issue for now. We are happy to answer any of your questions on [Discord](https://discord.gg/RVmnytFmGW).
