### ISSUE TITLE
`nodesConnectable` prop doesn't seem to be reactive to value changes

### ISSUE THREAD

**Issue by mcmxcdev** [xyflow/xyflow#4509]
### What platform were you using when you found the bug?

- Svelte Flow version: 0.0.40
- Browser and version: Version 1.68.128 Chromium: 127.0.6533.73 (Official Build) (64-bit)
- OS and version: Ubuntu 24.04

### Live code example

https://stackblitz.com/edit/svelte-flow-ts-ppskg3?file=src%2FFlow%2Findex.svelte

### Describe the Bug

In the Stackblitz above, `elementsSelectable={!isLocked}` updates reactively, meaning that nodes are correctly not selectable if canvas is locked.

`nodesConnectable={!isLocked}` on the other hand does not seem to update reactively and nodes are still connectable even when `isLocked` is true

### Steps to reproduce the bug or issue

See Stackblitz for reproduction

### Expected behavior

I would expect not to be able to draw any edges between nodes whenever `nodesConnectable` evaluates to false.

**Comment by peterkogo** [comment]
This should be fixed in the newest update

**Comment by mcmxcdev** [comment]
Thanks, already using 0.1.15 which now works perfectly for our use case!
