### ISSUE TITLE
CSS: Selected node looks the same as focused node

### ISSUE THREAD

**Issue by pycraft114** [xyflow/xyflow#4513]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: "@xyflow/react": "^12.0.3",
- Browser and version: 
- OS and version:

### Live code example

https://codesandbox.io/s/7kn7kv?file=/App.js&utm_medium=sandpack

### Describe the Bug

clicking node while Meta key pressed (multi-selection mode) inconsistent behavior. While multi-selection mode is on, clicking after moving mouse subtly, it's unselection or selection gets jammed. 

### Steps to reproduce the bug or issue

in codesandbox
click node multiple times in multi selection mode.

### Expected behavior

has to be consistent

### Screenshots or Videos

https://github.com/user-attachments/assets/29bfcd67-ae3b-4767-9cf2-38e38e41ecb3

**Comment by peterkogo** [comment]
That is the new `nodeDragThreshold` at work. A click is not registered while moving the mouse. I suppose you are moving the mouse slightly while clicking.

However, fiddling around with your demo, especially with a higher threshold like 5, it is clear that a click is prevented even though the threshold has not been reached yet. We will investigate this!

**Comment by peterkogo** [comment]
Ok, I found out what's happening. The CSS for a focused node is the same as for a selected node. We might fix this in a default styling revamp in the future. I will leave this open for now.

**Comment by moklick** [comment]
I agree that it is a bit confusing that focused and selected nodes look the same but it was always like this and we won't change it (because it would be breaking). You can adjust the focused styles by overwriting:

```css
.react-flow .react-flow__node:focus {
  box-shadow: none;
}
```
