### ISSUE TITLE
onlyRenderVisibleElements with width and height set on node doesn't render edge if one of the nodes is offscreen

### ISSUE THREAD

**Issue by jagregory** [xyflow/xyflow#4516]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.0.4 (react)
- Browser and version: Chrome 126.0.6478.183
- OS and version: MacOS 14.5

### Live code example

https://codesandbox.io/s/prod-moon-8fw277?file=/App.tsx

### Describe the Bug

If `onlyRenderVisibleElements` is set and nodes have an explicit `width` and `height` set, then edges between nodes will not render if one of the nodes is initially offscreen. If I move the `width` and `height` into the `style` object then everything works as expected.

This may be user error, but it was quite frustrating because _everything else was working fine_, the only symptom of something being wrong was the edge not rendering if one node was offscreen.

### Steps to reproduce the bug or issue

1. Open the codesandbox link
2. See that "Node 1" is visible and there's no edge visible
3. Pan the screen down until "Node 2" appears
4. See an edge pop into existence

If you change the codesandbox and set `nodes={initialNodesWithStyles}` you'll see it behave as expected.

### Expected behavior

1. Edge should be immediately visible because one of the two nodes is visible.

### Screenshots or Videos

https://github.com/user-attachments/assets/b9b96a23-cbd3-46ac-828e-b329d73d3d05

**Comment by peterkogo** [comment]
That looks like a bug! Nice find.

**Comment by peterkogo** [comment]
We might need to find a better way to solve #3883 before we can tackle this.

@jagregory in your case: setting width and height directly on each node is used for server side rendering and resizing. For SSR you'd need to set handle positions manually as well - we forgot to think about the case where you set node dimensions without wanting SSR and while using onlyRenderVisibleElements.
A note of caution with onlyRenderVisibleElements you can [read about in this issue](https://github.com/xyflow/xyflow/issues/4239#issuecomment-2194870473).
