### ISSUE TITLE
getConnectedEdges returns a list of edges that connect nodes but not with each other as mentioned in docs

### ISSUE THREAD

**Issue by corinaivn** [xyflow/xyflow#4522]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Describe the Bug

As mentioned in documentation: https://reactflow.dev/api-reference/utils/get-connected-edges,
getConnectedEdges function should return an array of edges that connect any of the given nodes together but it returns all edges that have one end in the nodes array. I think the condition should use && instead of || 
return edges.filter((edge) => nodeIds.has(edge.source) && nodeIds.has(edge.target))

### Steps to reproduce the bug or issue

Use the getConnectedEdges function

### Expected behavior

I was expecting to receive a list with edges that connect any 2 nodes from the nodes array between each other.

**Comment by moklick** [comment]
Hey @corinaivn ! Thanks for bringing this up. It's the expected behaviour, but the docs are wrong. We will update it!

**Comment by hayleigh-dot-dev** [comment]
Thank you for raising this @corinaivn. As @moklick mentions the docs and expected behaviour were slightly misaligned here! For clarity the expected behaviour is that the returned array of edges contains all edges where _either_ the edge's source _or_ target are in the supplied nodes array.

For example:
```js
import { getConnectedEdges } from '@xyflow/react';

const nodes = [
  { id: 'a', position: { x: 0, y: 0 } },
  { id: 'b', position: { x: 100, y: 0 } },
];
const edges = [
  { id: 'a->c', source: 'a', target: 'c' },
  { id: 'c->d', source: 'c', target: 'd' }
];

const connectedEdges = getConnectedEdges(nodes, edges);
// => [{ id: 'a->c', source: 'a', target: 'c' }]
```
