### ISSUE TITLE
Custom Node Mouse Event Flickering in ReactFlow

### ISSUE THREAD

**Issue by shaiVast** [xyflow/xyflow#4523]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version:  ReactFlow version 11.11.3 , 12.0.4
- Browser and version:  Chrome, Safari, Firefox
- OS and version: MacOs Sonoma 14.5

### Describe the Bug

When using custom nodes in ReactFlow, there is an unexpected behavior in the mouse event handling. 
Specifically:

There exists a small area around the custom node where moving the mouse triggers both onNodeMouseEnter and onNodeMouseLeave events simultaneously or in rapid succession.

This behavior occurs even though the mouse is still within what should be considered the custom node's active area.

The result is a flickering effect or unstable hover state for the custom node, as the system rapidly toggles between considering the mouse as "entered" and "left" the node.

### Steps to reproduce the bug or issue

when using CostomNode, while the the mouse entered the node area.

` <ReactFlow
      proOptions={{hideAttribution: true}}
      nodes={nodes}
      edges={edges}
      fitView
      nodeTypes={nodeTypes}
      edgeTypes={edgeTypes}
      onEdgeMouseEnter={setEdgeHover}
      onEdgeMouseLeave={setEdgeHover}
      onNodeMouseEnter={nodeMouseEnter}
      onNodeMouseLeave={nodeMouseLeave}
      connectionLineType={ConnectionLineType.Straight}
      onEdgeClick={handleEdgeClick}
      onNodeContextMenu={onNodeContextMenu}
      onPaneClick={onPaneClick}
    >
    </ReactFlow>`

### Expected behavior

onNodeMouseEnter - should be triggered when the mouse enters the CustomNode area.
onNodeMouseLeave - should be triggered when the mouse leaves the CustomNode area.

### Screenshots or Videos

![Untitled](https://github.com/user-attachments/assets/e2742fd8-7945-48ae-847b-431a623362b8)

**Comment by bcakmakoglu** [comment]
In the gif image it looks like your nodes keep jumping from `visibility: hidden` to `visibility: visible`.
I'd wager you're doing some strange updates on your nodes on mouse-enter / mouse-leave which causes this jump 🤔

**Comment by shaiVast** [comment]
@peterkogo 
yes, i will try to do it soon.
@bcakmakoglu 
i think the mouse enter and leave events are causing updates in the my state management system. These state changes, in turn, trigger updates to the nodes and edges in reactflow. The rapid succession of these events, especially at node boundaries, results in frequent state updates and re-renders, leading to the visual flickering effect.

maybe debouncing it can reduce the volume of the flickering but its still not ideal.

**Comment by bcakmakoglu** [comment]
"Normal" updates to nodes shouldn't cause them to lose dimensions though, which is the condition for the visibility style.
If no dimensions exist yet -> hidden
If dimensions exist -> visible

**Comment by shaiVast** [comment]
@bcakmakoglu  thanks for your input and availability. 
i will try to investigate my nodes/edges update mechanism as well as reproduce it in an online example.

**Comment by peterkogo** [comment]
Are you by any chance not updating your nodes correctly? This can also happen if you delete the `measured` field out of your nodes.

**Comment by peterkogo** [comment]
Also, I am not sure what your end goal here is exactly, but if you want to react to hovering you should do this in your custom node directly. `onNodeMouseEnter` is just a global helper added if you are using built-in nodes - but you can listen to any kinds of events right in your custom node. Cosmetic changes like hover effects should be done with only css.

**Comment by moklick** [comment]
I can see that you are using `nodes` without implementing `onNodesChange`. Please read this https://reactflow.dev/learn/concepts/core-concepts and check if you can resolve the issue. Otherwise you can re-open this issue with a codesandbox https://new.reactflow.dev
