### ISSUE TITLE
[v12] Edge renderer size not expanding to fit the viewport

### ISSUE THREAD

**Issue by rafaelsilva81** [xyflow/xyflow#4526]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.0.4
- Browser and version: Brave 1.68.134 Chromium 127.0.6533.88
- OS and version: Windows 10

### Describe the Bug

I had this bug since upgrading to Reactflow v12
I am using Next 12.3.1 with TailwindCSS 3.2.4

The edges are only rendered on a specific space of the canvas (as seen on the screenshot below), i am using custom edge types, but even without them this bug still persists. The styles are being imported correctly. I've also tried removing both `fitView` and `onlyRenderVisibleElements` options, but without success

```tsx 
return (
    <>
      <FlowSidebar />

      <div className="size-full">
        <ReactFlow
          nodes={nodes}
          edges={edges}
          onlyRenderVisibleElements={true}
          nodeTypes={nodeCustomTypesList}
          edgeTypes={edgeTypes}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          onDrop={onDrop}
          fitView={true}
          onDragOver={onDragOver}
          onNodeClick={handleSelectNode}
          zoomOnDoubleClick={false}
        >
          <Background
            color="#bababa"
            variant={BackgroundVariant.Dots}
            size={1.5}
          />

          <Controls position="bottom-right" />
        </ReactFlow>
      </div>


    </>
  );
```

### Steps to reproduce the bug or issue

- Upgrade from v11 to v12 using nextjs 12.3.1 and tailwind 3.2.4

### Expected behavior

The edges should be rendered no matter the position on screen

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/4b3b61b3-82c6-451e-8c75-fdeb8d222482)
![image](https://github.com/user-attachments/assets/9a8a0a3d-e0fb-4701-a746-6d5fd7ad26a5)

On reactflow 11:
![image](https://github.com/user-attachments/assets/476cd985-3ac7-4a99-b31a-45b1864f7447)

**Comment by bcakmakoglu** [comment]
Are you sure that `overflow: visible` is active on the `react-flow__edges` class?
<img width="251" alt="image" src="https://github.com/user-attachments/assets/6f183107-51c6-4ca7-aca9-f8005f56d386">

**Comment by rafaelsilva81** [comment]
![image](https://github.com/user-attachments/assets/6d2e1db1-b599-485e-8bdd-e623a3a4c8f3)
You are right, it isn't. Its being overwritten by (I assume) the tailwind defaults

I was able to fix it by adding:
```css
.react-flow__edges svg {
  overflow: visible !important;
}
```
To my global.css file

Thanks for the help! but I still wonder if this is the expected behavior? On reactflow v11 this change wasn't needed

**Comment by peterkogo** [comment]
Odd. Why does `svg:not(:root)` have a higher specificity than `.react-flow__edges svg`? I'll leave this issue open to see if there might be a solution for this. I suppose more people will run into this.

**Comment by moklick** [comment]
In React Flow 11, the selector was `.react-flow .react-flow__edges` (is this one stronger than `.react-flow__edges svg`). If so, we could strengthen the current selector by putting `.react-flow` in front.
