### ISSUE TITLE
Different behaviour between coordinate extent and parent extent

### ISSUE THREAD

**Issue by Gomes117** [xyflow/xyflow#4529]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12

### Live code example

https://codesandbox.io/p/sandbox/frosty-raman-vz4qfz

### Describe the Bug

Extent "parent" will prevent the node from exiting the parent, while a coordinate extent will prevent only the node origin from exiting the extent.

### Steps to reproduce the bug or issue

Make a child node with coordinate extent

### Expected behavior

Child node is entirely limited to the extent same as when using "parent" extent

**Comment by peterkogo** [comment]
This is fixed in the newest release `12.3.0`
