### ISSUE TITLE
The Select or Dropdowns don't get triggered when using React Library

### ISSUE THREAD

**Issue by PraveenAsh** [xyflow/xyflow#4530]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version:  React
- Browser and version: Chrome
- OS and version: Window 10

### Describe the Bug

The Select or Drop downs don't get triggered on click. They seems to have disconnected with the event listeners. I have tried this with Material UI and Ant UI. It if failing for both. They work just fine outside of the "Nodes".

I first noticed it when using it in combination with `@rjsf` package on Material UI  skin. Later isolted it just for material, doesn't work.

```jsx
  <Select
    defaultValue="lucy"
    style={{
      width: 120,
    }}
    onChange={handleChange}
    options={[
      {
        value: 'jack',
        label: 'Jack',
      },
      {
        value: 'lucy',
        label: 'Lucy',
      },
      {
        value: 'Yiminghe',
        label: 'yiminghe',
      },
      {
        value: 'disabled',
        label: 'Disabled',
        disabled: true,
      },
    ]}
  />
```

In Ant UI the click is immediately reset. But in material UI is doesn't reset but doesn't show either. 

### Steps to reproduce the bug or issue

Add Material UI v5 or Ant UI latest and add `<Select/>` within the node.

### Expected behavior

The clicks are supposed to be triggered

### Screenshots or Videos

NA

**Comment by PraveenAsh** [comment]
wrote a custom select without any library it works. But the issue remains.

```jsx
const CustomSelect = ({ options, label, onChange }) => {
  const [selectedValue, setSelectedValue] = useState("");

  const handleChange = (event) => {
    const value = event.target.value;
    setSelectedValue(value);
    if (onChange) {
      onChange(value);
    }
  };

  return (
    <div className="custom-select-container">
      <label className="custom-select-label">{label}</label>
      <select className="custom-select" value={selectedValue} onChange={handleChange}>
        <option value="" disabled>
          Select an option
        </option>
        {options.map((option, index) => (
          <option key={index} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
    </div>
  );
};
```

**Comment by bcakmakoglu** [comment]
You need to add the `nodrag nopan` classNames to the select element.

**Comment by PraveenAsh** [comment]
Thanks a lot for the resolution. It works!

Please add common issues or best practices on the site for better debugging. Cheers!

**Comment by TrySpace** [comment]
> You need to add the `nodrag nopan` classNames to the select element.

Wow, I did not expect that to work! 🙏

(For @mui components I added the classes to the `ListItemButton` component)

**Comment by sachinNishalka** [comment]
this works, thanks brother
