### ISSUE TITLE
`Handle` type isn't exported correctly anymore.

### ISSUE THREAD

**Issue by alexanderhorner** [xyflow/xyflow#4535]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.0.4

### Describe the Bug

```ts
import { Handle } from '@xyflow/react'
```

There's no way to import the type [`Handle`](https://reactflow.dev/api-reference/types/handle) because the export is overwritten by another `Handle`

### Steps to reproduce the bug or issue

```ts
import { Handle } from '@xyflow/react'
```

### Expected behavior

Handle Type Interface is imported

**Comment by sepideh-shabani** [comment]
I use "**@xyflow/react": "^12.0.4**"
but after updating it, I have an Error where I use 'Handle' in the custom node component:

`
<Handle
  className="customHandle"
  position={Position.Right}
  type="source"
/>
`

**Error: 'Handle' only refers to a type, but is being used as a value here.**

**Comment by sepideh-shabani** [comment]
This is part of my yarn.lock that I get the error:
```
"@xyflow/react@^12.0.4":
  version "12.1.0"
  resolved "https://registry.yarnpkg.com/@xyflow/react/-/react-12.1.0.tgz#71a93eb514497b0ae3835b45df21ac14ce6e0812"
  integrity sha512-tlYBV8S27kTwLuKvKa3dX0yEJ6NgUup9BwXLWcdNKdZq+UvLfDr5JXHwzyRqT1XSlYFv+YgcfroGmir8krYXIg==
  dependencies:
    "@xyflow/system" "0.0.38"
    classcat "^5.0.3"
    zustand "^4.4.0"

"@xyflow/system@0.0.38":
  version "0.0.38"
  resolved "https://registry.yarnpkg.com/@xyflow/system/-/system-0.0.38.tgz#4bf67fa1adfba5cd3760d182ce645841fc652c69"
  integrity sha512-auJU8djbT59S5Afb9lFds1lQJvKIb0zUoHhO+il/ogDDG5BbFds6D8g5a8Q3oHdyR6dy0TaD1oZq9s7Ydhn41g==
  dependencies:
    "@types/d3-drag" "^3.0.7"
    "@types/d3-selection" "^3.0.10"
    "@types/d3-transition" "^3.0.8"
    "@types/d3-zoom" "^3.0.8"
    d3-drag "^3.0.0"
    d3-selection "^3.0.0"
    d3-zoom "^3.0.0"
```

in '@xyflow/system@0.0.37' version I haven't got any errors. In the custom node component:
```
import { memo } from 'react';
import { Handle, Position } from '@xyflow/react';

import { Port } from './port';
import { Tooltip } from '../tooltip';

import { TooltipContent } from './TooltipContent';
import { CustomNodeProps } from './types';

function CustomNode(props: CustomNodeProps) {
  const { data, selected, isConnectable } = props;
  return (
    <Tooltip title={<TooltipContent data={data.node} />} placement="top">
      <div className="flex flex-col justify-center items-center">
        <Port
          color={data.node.color}
          hasDescendant={data.node.hasDescendant}
          selected={selected}
          size="small"
        />
        <Handle
          type="target"
          position={Position.Top}
          style={{ width: '100%', height: '100%', opacity: 0}}
          id="target"
          isConnectable={isConnectable}
        />
        <Handle
          type="source"
          position={Position.Top}
          style={{ width: '100%', height: '100%', opacity: 0 }}
          id="source"
          isConnectable={isConnectable}
        />
      </div>
    </Tooltip>
  );
}

export default memo(CustomNode);
```

**Comment by peterkogo** [comment]
@sepideh-shabani have you tried renaming the handle type as this leads to a collision?
`import { type Handle as HandleType, Handle } from '@xyflow/react'`

**Comment by sepideh-shabani** [comment]
@peterkogo Yes, but the problem is somewhere else. In this file "...\node_modules\@xyflow\react\dist\esm\index.d.ts"
Line 2 has exported "Handle" as a component, but in line 36 it has been overwritten with a type. This second export does indeed overwrite the first Handle export.

**Comment by sepideh-shabani** [comment]
@peterkogo Yes, but the problem is somewhere else. In this file "...\node_modules\@xyflow\react\dist\esm\index.d.ts"
The Handle type is first exported from "./components/Handle" (line 2), but then it's overwritten by the Handle type imported from @xyflow/system and re-exported(line 36).

_**...\node_modules\@xyflow\react\dist\esm\index.d.ts**_

```
export { default as ReactFlow } from './container/ReactFlow';
export { Handle, type HandleProps } from './components/Handle';
.
.
.
import { type Handle as HandleBound } from '@xyflow/system';
export type Handle = HandleBound;
...

**Comment by moklick** [comment]
It's possible to export a type and a value with the same name in TS. What's your dev setup @sepideh-shabani ?

**Comment by sepideh-shabani** [comment]
@moklick You are right, there is a problem in the configuration because it worked correctly in another project. thank you
But in this project, we use **Menoropo** with this version of typescript:~4.7.2
This is the tsconfig file in the project that uses xyflow:

```
{
 "extends": "../../../tsconfig.base.json",
 "compilerOptions": {
 "jsx": "react-jsx",
 "allowJs": true,
 "esModuleInterop": true,
 "allowSyntheticDefaultImports": true,
 "forceConsistentCasingInFileNames": true,
 "strict": true,
 "noImplicitOverride": true,
 "noPropertyAccessFromIndexSignature": true,
 "noImplicitReturns": true,
 "noFallthroughCasesInSwitch": true,
 "resolveJsonModule": true
 },
 "files": [],
 "include": [],
 "references": [
 { "path": "./tsconfig.app.json" },
 { "path": "./tsconfig.spec.json" }
 ]
}
```

in **tsconfig.app.json** :
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../../dist/out-tsc",
    "types": ["node"]
  },
  "files": [
    "../../../node_modules/@nrwl/react/typings/cssmodule.d.ts",
    "../../../node_modules/@nrwl/react/typings/image.d.ts"
  ],
  "exclude": [
    "jest.config.ts",
    "**/*.spec.ts",
    "**/*.test.ts",
    "**/*.spec.tsx",
    "**/*.test.tsx",
    "**/*.spec.js",
    "**/*.test.js",
    "**/*.spec.jsx",
    "**/*.test.jsx"
  ],
  "include": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"]
}
```
And we also have a tsconfig.base with these values:
```
{
 "compileOnSave": false,
 "compilerOptions": {
 "rootDir": ".",
 "sourceMap": true,
 "declaration": false,
 "moduleResolution": "node",
 "emitDecoratorMetadata": true,
 "experimentalDecorators": true,
 "importHelpers": true,
 "target": "es2015",
 "module": "esnext",
 "lib": ["es2017", "dom"],
 "skipLibCheck": true,
 "skipDefaultLibCheck": true,
 "baseUrl": ".",
 "paths": {...},
 "exclude": ["node_modules", "tmp"]
}
```
Is there a mistake?

**Comment by moklick** [comment]
Sorry, I am not sure what's the issue here and I can't reproduce it.

**Comment by bogy0** [comment]
If someone is still facing this issue: upgrading the `typescript` package in our project helped resolve it.

before: 
`"typescript": "4.8.4",`

after:
`"typescript": "5.5.4",`

**Comment by boehlerlukas** [comment]
@bogy0 many thanks - saved my day!

**Comment by coded-by-sridhar** [comment]
But updating typescript to the next major version seems like a overkill for this issue. @moklick Can you rename the Handle Component or type to avoid the name collision?

**Comment by Hless** [comment]
I agree with @coded-by-sridhar but I have found a workaround for now. By explicitely importing the Type before importing the component you can avoid the naming collision:

```
import { ScenarioEntity, SceneEntity } from "@citychallenge/api-public";
import {
  Position,
  Node,
  NodeProps,
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  type Handle as HandleType,
  Handle as HandleComponent,
} from "@xyflow/react";

// Now use HandleComponent like so:
<HandleComponent type="target" position={Position.Left} />
```

**Comment by runoncedev** [comment]
> [@moklick](https://github.com/moklick) You are right, there is a problem in the configuration because it worked correctly in another project. thank you But in this project, we use **Menoropo** with this version of typescript:~4.7.2

Having same issue, also monorepo but I don't think it's related. Must be something with the `tsconfig.json` or similar.

**Update**:

After some digging, I think the problem might be related to Babel:

* https://github.com/babel/babel/issues/14421
* https://github.com/babel/babel/issues/15933
