### ISSUE TITLE
Dynamically handle scrolling

### ISSUE THREAD

**Issue by takyyon** [xyflow/xyflow#4542]
### Please describe the feature that you want to propose

I have a canvas which is bound by left and rightside panels where connections flow from one side to another. Try to add in a scroll behavior such that both the panels and canvas can be scrolled together. It would be great if it is possible to control the scrolling of canvas dynamically, i.e. stop or start scrolling canvas in connection with the side panels on either side.

**Comment by moklick** [comment]
Could you create a codesandbox for this https://new.reactflow.dev ?
