### ISSUE TITLE
On Drag of a single node, all the nodes get dragged together

### ISSUE THREAD

**Issue by pnaik07** [xyflow/xyflow#4552]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: ReactFlow
- Browser and version:  Chrome Latest
- OS and version: Windows 10

### Describe the Bug

This is issues is very inconsistent and RCA isn't done. 

### Steps to reproduce the bug or issue

Added 2-3 nodes, stored it into a DB. Fetch back and use `setNodes`. It magically moves all the nodes together.

Interestingly, the nodes that was active or dragged, the positions is recorded and correctly, but then again, all the nodes move on refresh. 

### Expected behavior

Only one node has to move. The identifiers for each node as different. Verified that!

### Screenshots or Videos

https://icecreamapps.com/v/fr4nztf

**Comment by bcakmakoglu** [comment]
Sounds like you're setting `selected: true` on all these nodes, causing them to be moved together when one node is dragged (basically a multi-selection).

**Comment by pnaik07** [comment]
you're right, the `onDrop={onDrop}` property adds somehow get's a additional property `selected`. I checked the documentation for similar stuff but couldn't find. Is it `react-draggable` that is adding the `selected` ?

the node seems to inherit the property, so now on node creation, I'm just deleting the property and it works. unfortunately this keyword got written in the DB as well, which is why the behavior. Will close this after a few tests.

thanks for the quick response

**Comment by pnaik07** [comment]
Closing this with usage comments

The node arguments received from the `onNodeDragStop` callback function has the `selected : true`. @bcakmakoglu this must be deleted by default as the drag and completed and no longer needs to be presented as `selected`. The problems picks up when you store the nodes as-is in a DB. where the `node` info isn't modified later, which also gets synced with the frontend in the subsequent calls.

fix:
```js
const unselect = (node) => {
  delete node.selected;
} 
```

do this before updation of node values
