### ISSUE TITLE
Node draggable: false disables double click

### ISSUE THREAD

**Issue by konarskis** [xyflow/xyflow#4559]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.0.3
- Browser and version: Latest Chrome
- OS and version: Latest MacOS

### Describe the Bug

When `draggable: false` is set on a node, `onNodeDoubleClick` stops working

### Steps to reproduce the bug or issue

🙃 

### Expected behavior

🙃

**Comment by peterkogo** [comment]
If nodes arn't draggable we let the pointer events pass to the pane, so the nodes are not in the way of dragging the pane.

Double click on the pane can be used to zoom, which in that case takes priority.

Solution: Either use `zoomOnDoubleClick={false}` or set `noPan` class on your nodes. Both leads to double clicks being registered on nodes again.

**Comment by konarskis** [comment]
Thank you very much!
