### ISSUE TITLE
Svelte: Intersections

### ISSUE THREAD

**Issue by 1bye** [xyflow/xyflow#4560]
### What platform were you using when you found the bug?

- Svelte Flow version: ^0.1.15
- Browser and version: Chrome Version 127.0.6533.99 (Official Build) (64-bit)
- OS and version: Ubuntu 22

### Live code example

https://stackblitz.com/edit/svelte-flow-ts-khgo2a?file=src%2FFlow%2Findex.svelte

### Describe the Bug

I’m not sure if this is a bug, but when I try to create dynamic grouping in Svelte Flow, similar to React Flow, I'm experiencing incorrect calculations. Specifically, when I drag a node into a group and change the `parentId` of the current node to the intersection group, the node briefly teleports to the top for about 1 millisecond before returning to its original position.
After that intersection works wrong.

I'm trying to using `useUpdateNodeInternals`, but don't work....

Please check attached video

Thanks

### Steps to reproduce the bug or issue

1. Grab custom node from repl
2. Move it to group
3. Then try go out from it
4. While doing it check console

Please check attached video

### Expected behavior

Should calculate intersection right

### Screenshots or Videos

https://www.loom.com/share/d46197ce6d694d59a74b8b88e44b8fa5?sid=1c316bd3-2af8-4828-9470-38d7dedf5407

### Additional context

Trying to play with bug in repl, while waiting for your response

**Comment by bcakmakoglu** [comment]
The jump happens because when you assign a `parentId` you change the relation of `node.position` from the viewport to the parent node.
Meaning `x: 0, y: 0` without a parentId is the top left corner of the *viewport* (given that the viewport has not been moved at all), while *with* a parentId it would be the top left corner of the parent node.

Since you're doing this during the drag, it jumps for a second and then corrects itself since afterwards it knows it's supposed to be related to the parent.

I'd just change this to `onNodeDragStop` and assign the parentId on drag stop and calculate the correct position.
Here's an example: https://stackblitz.com/edit/svelte-flow-ts-nkjcrk?file=src%2FFlow%2Findex.svelte,package.json

Although it seems like a bug that the intersections aren't working correcty :/
Looks like the calculation assumes the position of the node in relation to the viewport still but I'm not 100% sure about that, just my quick observation.

**Comment by 1bye** [comment]
@bcakmakoglu Thanks for quick response, your repl is good, but the calculations of intersections is wrong as you said. 
Currently checking react and svelte source code

**Comment by 1bye** [comment]
Hi again @bcakmakoglu I've made working example, but code is not good :)
You can check it here, once I transform it to my project, I'll share better code snippet: https://stackblitz.com/edit/svelte-flow-ts-qpaigw?file=src%2FFlow%2Findex.svelte

**Comment by 1bye** [comment]
Following code snippet works perfect:
```js
import { isNode, type Node, useStore, useSvelteFlow, useNodes } from "@xyflow/svelte";
import { nodeHasDimensions, nodeToRect, type Rect, isRectObject, getOverlappingArea } from "@xyflow/system";
import { get } from "svelte/store";

export function useCustomSvelteFlow(): ReturnType<typeof useSvelteFlow> {
    const { nodeLookup } = useStore();
    const svelteFlow = useSvelteFlow();

    const nodes = useNodes();

    const getNodeRect = (nodeOrRect: Node | { id: Node["id"] }): Rect | null => {
        const node =
            isNode(nodeOrRect) && nodeHasDimensions(nodeOrRect)
                ? nodeOrRect
                : get(nodeLookup).get(nodeOrRect.id);
        return node ? nodeToRect(node) : null;
    };

    function getIntersectingNodes(
        nodeOrRect: Node | { id: Node["id"] } | Rect,
        partially = true,
        nodesToIntersect?: Node[]
    ) {
        const isRect = isRectObject(nodeOrRect);
        const nodeRect = isRect ? nodeOrRect : getNodeRect(nodeOrRect);
        const node = get(nodes).find(_ => _.id === (nodeOrRect as Node).id);

        if (!nodeRect) {
            return [];
        }

        return (nodesToIntersect || get(nodes)).filter((n) => {
            const internalNode = get(nodeLookup).get(n.id);
            if (!internalNode || (!isRect && n.id === nodeOrRect.id)) {
                return false;
            }

            let nodeRectCopy = nodeRect;

            // Convert node's local coordinates to global if it has a parent
            let currNodeRect = nodeToRect(internalNode);

            if (node?.parentId) {
                const parent = get(nodeLookup).get(node.parentId);
                if (parent) {
                    const parentRect = nodeToRect(parent);
                    currNodeRect = {
                        x: currNodeRect.x + parentRect.x,
                        y: currNodeRect.y + parentRect.y,
                        width: currNodeRect.width,
                        height: currNodeRect.height
                    };
                    if (n.id === node.parentId)
                        nodeRectCopy = {
                            width: nodeRectCopy.width,
                            height: nodeRectCopy.height,
                            x: nodeRectCopy.x + currNodeRect.x,
                            y: nodeRectCopy.y + currNodeRect.y
                        }
                }
            }

            // console.log(n.id, node?.parentId, nodeRect, nodeRectCopy)

            const overlappingArea = getOverlappingArea(currNodeRect, nodeRectCopy);
            const partiallyVisible = partially && overlappingArea > 0;

            return partiallyVisible || overlappingArea >= nodeRectCopy.width * nodeRectCopy.height;
        });
    }

    return {
        ...svelteFlow,
        getIntersectingNodes
    }
}
```

And on `on:nodedrag` works good, with 1 issue when moving `to` or `from` group  happens "1ms jump", and Idk how to fix it, so if you have any idea, please share with me, thanks:
```js
function onNodeDrag({ detail: { targetNode } }: CustomEvent<{ targetNode: Node }>) {
        const intersections = getIntersectingNodes(targetNode).map((n) => n.id);

        if (intersections.length > 0) {
            const interGroup = $nodes.find(_ => _.type === "group" && intersections.includes(_.id));

            if (interGroup && !targetNode.parentId) {
                // Calculate the new position relative to the group
                const newPosition = {
                    x: targetNode.position.x - interGroup.position.x,
                    y: targetNode.position.y - interGroup.position.y
                };

                // Batch update node with parentId and new position
                updateNode(targetNode.id, {
                    parentId: interGroup.id,
                    position: newPosition
                });

                // Update internals
                updateNodeInternals(targetNode.id);
            }
        } else if (targetNode.parentId && !intersections.includes(targetNode.parentId)) {
            const parentGroup = $nodes.find(_ => _.id === targetNode.parentId);

            if (parentGroup) {
                // Calculate the new position relative to the viewport
                const newPosition = {
                    x: targetNode.position.x + parentGroup.position.x,
                    y: targetNode.position.y + parentGroup.position.y
                };

                console.log(newPosition, targetNode.position, parentGroup.position)

                // Remove parentId and update position in one operation
                updateNode(targetNode.id, {
                    parentId: undefined,
                    position: newPosition
                });

                // Update internals
                updateNodeInternals(targetNode.id);
            }
        }
    }
```

**Comment by peterkogo** [comment]
Thanks for bringing this up - this is definitely a bug!

**Comment by peterkogo** [comment]
This will be fixed in the next release

**Comment by 1bye** [comment]
Awesome

**Comment by 1bye** [comment]
@peterkogo  Do you think is works properly? https://stackblitz.com/edit/svelte-flow-ts-ebs9zw?file=src%2FFlow%2Findex.svelte

**Comment by moklick** [comment]
@1bye why did you remove the position update:

```js
position: {
  x: targetNode.position.x - interGroup.position.x,
  y: targetNode.position.y - interGroup.position.y
}
```

**Comment by 1bye** [comment]
@moklick My bad... Thanks
