### ISSUE TITLE
cursor: grab when 0 (for left click) is not in `panOnDrag`.

### ISSUE THREAD

**Issue by c0d3ster** [xyflow/xyflow#4564]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- 12.0.4
- Browser and version: 
- Occurs in Brave, Chrome, Safari
- OS and version:
MacOS Ventura 13.6.7

### Describe the Bug

The cursor is set to grab even though that doesn't align with the behavior of "selection". Pointer, default, or crosshair would be more appropriate (probably default so dev could potentially override it to another cursor)
I have not found a way to get around this besides completely setting `panOnDrag` to false which is not ideal because then users have no way to pan without using the keyboard shortcut.

### Steps to reproduce the bug or issue

1. set `panOnDrag` to [1] to allow only clicking the middle mouse to enable panning on drag.
2. Notice that cursor is set to drag even though the left click operation creates a selection box.
3. Note that the cursor goes to "grabbing" mode when the middle mouse button is clicked in which is what we would expect but would not expect grab when the left click is not going to pan on drag.

### Expected behavior

As a user I would expect that a selection mode would either have the cursor as a pointer, crosshair or default for selection box behavior. I would expect that when I click the middle mouse button (or whatever other button is assigned to `panOnDrag`) that's the point at which the cursor would switch over to grabbing indicator.

**Comment by peterkogo** [comment]
Thanks for bringing this up! Will be fixed in the next release.
