### ISSUE TITLE
Why the type ReactFlowStore's edges attribution been set to Edges instead of EdgeType

### ISSUE THREAD

**Issue by antxiaopa** [xyflow/xyflow#4566]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Describe the Bug

Why the type ReactFlowStore's edges attribution been set to Edges instead of EdgeType

[Source Code](https://github.com/xyflow/xyflow/blob/aaf130f6cb6ff443a0cac66267fe73b3a47859a9/packages/react/src/types/store.ts#L58)

### Steps to reproduce the bug or issue

Just confused  about a type

### Expected behavior

I expected this

```
export type ReactFlowStore<NodeType extends Node = Node, EdgeType extends Edge = Edge> = {
    edges: EdgeType[];
}
```

**Comment by peterkogo** [comment]
Thanks for bringing this up!  It should be EdgeType.
