### ISSUE TITLE
Connection limited not working when add Id to CustomHandle

### ISSUE THREAD

**Issue by dinhchien-zps** [xyflow/xyflow#4573]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: React Flow
- Browser and version: Chrome 127.0.6533.120
- OS and version: Windows 10

### Describe the Bug

Connection limited is not working when I add Id to CustomHandle like this: <CustomHandle
        id="a"
        type="target"
        position={Position.Left}
        connectionCount={1}
/> .
You can see the full example at https://codesandbox.io/p/sandbox/ecstatic-tdd-df75v9?file=%2FCustomNode.jsx&utm_medium=sandpack

### Steps to reproduce the bug or issue

1. Go to https://codesandbox.io/p/sandbox/ecstatic-tdd-df75v9?file=%2FCustomNode.jsx&utm_medium=sandpack
2. Add Id to the CustomHandle in the CustomNode file.
3. Test the connection and see the result

### Expected behavior

The connection is limited.

**Comment by moklick** [comment]
what is not working for you here? I can only create one connection as specified with `connectionCount={1}`.

**Comment by dinhchien-zps** [comment]
https://github.com/user-attachments/assets/4b5e8c75-7a4d-4abf-8f19-51458a67c2db

I can create two connections after adding a id. You can see it in this video.

**Comment by bcakmakoglu** [comment]
@dinhchien-zps 
You need to update the CustomHandle to check for handles with that specific id you assigned

```tsx
const CustomHandle = (props) => {
  const connections = useHandleConnections({
    id: props.id, // <--- add the id here!
    type: props.type,
  });

 // ... rest
```

**Comment by dinhchien-zps** [comment]
@bcakmakoglu Thank you so much. That helps me a lot.
