### ISSUE TITLE
Download image of a group Node along with its child nodes instead of full flow

### ISSUE THREAD

**Issue by nsarwar123** [xyflow/xyflow#4577]
### Please describe the feature that you want to propose

As in [download-image](https://reactflow.dev/examples/misc/download-image) example its using .react-flow__viewport class to take an image of all nodes in the flow.
In may case I have multiple group nodes and in every node, there are some child nodes. How can I make an image of any single group node including its child nodes as well.

I tried to target the group node to take image but its not showing child nodes in that.

![image](https://github.com/user-attachments/assets/47f11a53-015c-415c-8db4-814db6162efa)

**Comment by nsarwar123** [comment]
> Did you try to use a selector based on the data-id. For example if you want to make a screenshot of the node with id = "a", you could try to use `"[data-id='a']"` as a selector. Does that work?

Yes, I tried the following code, In which I am targeting every parent node. Its creating the pdf and in that only showing parent node which is empty. (Not showing its corresponding childrens.)

```
// printing all page nodes only (not including child nodes)
  const handlePDF = (isPrint?: boolean) => {
    const pdf = new jsPDF({
      orientation:
        selectedReport.orientation === 'horizontal' ? 'landscape' : 'portrait',
      unit: 'px',
      format: [pageDimensions.width, pageDimensions.height],
    });

    const borderedNodes = document.querySelectorAll('[id^="borderedNode"]');

    borderedNodes.forEach((node, index) => {
      if (node) {
        // Render each borderedNode to a PNG
        toPng(node as HTMLElement, {
          width: pageDimensions.width,
          height: pageDimensions.height,
          style: {
            width: `${pageDimensions.width}`,
            height: `${pageDimensions.height}`,
          },
        }).then((dataUrl: any) => {
          // Add the image to the PDF as a new page
          if (index > 0) {
            pdf.addPage(); // Add a new page only if it's not the first page
          }

          pdf.addImage(
            dataUrl,
            'PNG',
            0,
            0,
            pageDimensions.width,
            pageDimensions.height,
          );

          // If it's the last page, either save or print the PDF
          if (index === borderedNodes.length - 1) {
            if (isPrint) {
              const pdfBlob = new Blob([pdf.output('blob')], {
                type: 'application/pdf',
              });
              const pdfUrl = URL.createObjectURL(pdfBlob);
              const printWindow = window.open(pdfUrl, '_blank') as Window;
              printWindow.onload = () => {
                printWindow?.focus();
                printWindow?.print();
              };
            } else {
              const currentDate = new Date();
              pdf.save(
                `${reportSelected.name}_${dateObjectToHR(currentDate)}.pdf`,
              );
            }
          }
        });
      }
    });
  };
```

Here is an example of pdf page. Showing only bordered node. I also want to show its related child nodes.
![image](https://github.com/user-attachments/assets/415d12a3-2e03-42da-813a-729df1a25821)

**Comment by moklick** [comment]
sure! My fault .. the nodes are no children in the actual DOM. You could try to use the [`filter` function](https://github.com/bubkoo/html-to-image?tab=readme-ov-file#filter) to filter out nodes that are not part of the parent. You would also need to adjust the viewport for focusing each parent. 

I will close this issue because it's not about React Flow but the usage of the html-to-image library. If you have questions about custom implementations, please use GH discussions or our Discord.
