### ISSUE TITLE
Editable edge control point stays in screen after trying to remove

### ISSUE THREAD

**Issue by aldevv** [xyflow/xyflow#4581]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12
- Browser and version: firefox 129
- OS and version: linux

### Describe the Bug

control point stays in the screen when it should dissapear

### Steps to reproduce the bug or issue

1. create a control point
2. remove it
3. create the same control point again
4. remove it
now an unwanted control point will be stuck in the screen

### Expected behavior

when removing a control point it should remove the ones that where created

### Screenshots or Videos

https://www.loom.com/share/1b4bb0ec80084c0e8d1acd205a84f7d5?sid=00b61630-0bcb-4c34-9987-07fb1a624ea6

### Additional context

this also happens in the examples page:
https://reactflow.dev/examples/edges/editable-edge

**Comment by moklick** [comment]
Thanks! We will have a look.

**Comment by hayleigh-dot-dev** [comment]
Thanks for raising this @aldevv! Looks like it was some funkiness with the hook used to assign ids to the temporary control points. Fix is pushed and the example has been updated, thanks again!
