### ISSUE TITLE
While creating (dragging) a new edge with SmoothStepPath the arrow points in wrong direction

### ISSUE THREAD

**Issue by devnull69** [xyflow/xyflow#4583]
### What platform were you using when you found the bug?

- React Flow version: 11.11.1

### Describe the Bug

When you create (drag) a new custome edge with SmoothStepPath from a source handle to a target handle, the final part of the path always "points to the right" even when snapping to a target handle that has Position.Top

After letting go the mouse button, the edge path correctly switches to pointing down

But I'm requested to also show the dragging path as pointing down when snapped to a Position.top target handle

### Steps to reproduce the bug or issue

Create a custom edge with a SmoothStepPath. Then create two nodes where one of the nodes has a handle with Position.Top

Create/Drag a new edge between the two nodes and snap the edge to the target handle (without letting the mouse go). It will point to the right even though the target handle is Position.Top

Only after finishing (letting go the mouse button) the final edge path points down correctly

### Expected behavior

After snapping to a target handle with a position other than Position.left the edge path should point in the right direction

### Screenshots or Videos

![ReactFlowDragNewEdge](https://github.com/user-attachments/assets/1ffa3e6e-cdc1-4fa5-960f-24b8a791fe9c)

**Comment by moklick** [comment]
This is fixed in React Flow 12.
