### ISSUE TITLE
onConnectEnd prevent propogation

### ISSUE THREAD

**Issue by glenarama** [xyflow/xyflow#4589]
### Please describe the feature that you want to propose

Im trying to create a new Node on connect end, and id like this node to be selected by default (selected: true)

However, after the connect end a pane click event is emitted and deselects all nodes. preventDefault & stopPropagation do not prevent the event being handled by onPaneClick.

Is there a way to prevent the deselect action inside the onConnectEnd event?

**Comment by moklick** [comment]
As a workaround I would try to wrap the node creation with a `requestAnimationFrame` or `queueMicrotask`. Does that work?

**Comment by glenarama** [comment]
requestAnimationFrame works! Thanks.

FYI: queueMicrotask still ran the task prior to the paneClick event
