### ISSUE TITLE
When I don't pass onNodesChange to <ReactFlow />, there's no measure attribute on the nodes.

### ISSUE THREAD

**Issue by antxiaopa** [xyflow/xyflow#4598]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.1.1

### Describe the Bug

When I don't pass onNodesChange to <ReactFlow />, there's no measure attribute on the nodes.
I want to pass custom onNodeDrag / onNodeClick / onConnect / onConnectStart / onConnectEnd and etc. But if I don't pass onNodesChange, I can't get node's width and height.
Could anyone help me out ?

### Steps to reproduce the bug or issue

Just remove the onNodesChange

### Expected behavior

Expect that I can get node's measure

**Comment by bcakmakoglu** [comment]
If you want to use a *controlled* flow, you *have to pass a `onNodesChange` handler*.

[Read this section of the docs to learn more about controlled vs uncontrolled flows.](https://reactflow.dev/learn/concepts/core-concepts#controlled-or-uncontrolled)

**Comment by antxiaopa** [comment]
> If you want to use a _controlled_ flow, you _have to pass a `onNodesChange` handler_.
> 
> [Read this section of the docs to learn more about controlled vs uncontrolled flows.](https://reactflow.dev/learn/concepts/core-concepts#controlled-or-uncontrolled)

I find this as below
```
export type NodeChange<NodeType extends NodeBase = NodeBase> = NodeDimensionChange | NodePositionChange | NodeSelectionChange | NodeRemoveChange | NodeAddChange<NodeType> | NodeReplaceChange<NodeType>;
```
without onNodesChange
- I can pass onNodeDrag to handle NodePositionChange
- I can pass onNodeClick to handle NodeSelectionChange
- also I can handle NodeRemoveChange and NodeAddChange<NodeType>

but there's no handler call onNodeDimensionChange or something，I customized almost every handler besides dimension.
If I pass onNodesChange to <ReactFlow />, there might be conflicts between them. So I have such a confusion.

**Comment by bcakmakoglu** [comment]
Idk where you ever read that you should be listening to `onNodeDrag` and update positions yourself, even if that "works" it's not the intended way of applying changes.

Read the documentation link above, it explains what `onNodesChange` and `onEdgesChange` is for and why you have to add it.
You are free to customize the change application and handling but you still need to add one either way.

It just sounds to me like you're trying to work around something that isn't supposed to be worked around like you're attempting to and you haven't explained why you seem to think this workaround is necessary either.
Just stick to the implementation that is intended ^^

**Comment by moklick** [comment]
As @bcakmakoglu already explained, if you are working with a controlled flow, you have to add an `onNodesChange` handler. If you are fine with an uncontrolled one, you can use `defaultNodes` and `defaultEdges` without `onNodesChange`.

**Comment by antxiaopa** [comment]
@bcakmakoglu  Thank you for explaining patiently.
I am reading the source code of [Dify](https://github.com/langgenius/dify) which is using reactflow 11.

[https://github.com/langgenius/dify/blob/main/web/app/components/workflow/index.tsx#L320](https://github.com/langgenius/dify/blob/main/web/app/components/workflow/index.tsx#L320)

And there is no onNodesChange passed to ReactFlow but it can get the width and the height.
Thank you again. I'll do as you said.

**Comment by antxiaopa** [comment]
@bcakmakoglu  Thank you for explaining patiently.
I am reading the source code of [Dify](https://github.com/langgenius/dify) which is using reactflow 11.

[https://github.com/langgenius/dify/blob/main/web/app/components/workflow/index.tsx#L320](https://github.com/langgenius/dify/blob/main/web/app/components/workflow/index.tsx#L320)

And there is no onNodesChange passed to ReactFlow but it can get the width and the height.
Thank you again. I'll do as you said.
