### ISSUE TITLE
The “Handle” only indicates the type, but is used here as a value.

### ISSUE THREAD

**Issue by linyuling520** [xyflow/xyflow#4602]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: "@xyflow/react": "^12.1.1"
- Browser and version: 
- OS and version:

### Describe the Bug

In my custom node, the Handle component is used, but it exports as a type.

`
```
import { NodeProps, Position, Handle } from '@xyflow/react';
<Handle
        type="target"
        position={targetPosition as Position}
        isConnectable={isConnectable}
        style={{
          backgroundColor: '#4d53e8',
          width: 10,
          height: 10,
        }}
      />
```
`

### Steps to reproduce the bug or issue

I checked the source code and found that the exported type and the Handle component were renamed, and that the later exported type overwrote the component.
![reactflow-1](https://github.com/user-attachments/assets/264086cd-132b-40c6-8edc-96702a999820)
![reactflow-2](https://github.com/user-attachments/assets/e0f27720-260c-40c4-9032-8884a98aef8d)
![reactflow-3](https://github.com/user-attachments/assets/e71f34b5-8702-44e8-9a6e-f71e7cfa9810)

### Expected behavior

Expect to be able to export Handle components properly.

**Comment by moklick** [comment]
Which TS version are you using @linyuling520 ?

**Comment by tswistak** [comment]
I had the same problem in an old project with TypeScript 4.7.3. Upgrading to TypeScript 5.6.2 resolved it.
