### ISSUE TITLE
Version 11.11.3: onNodeClick Not Working with Touchpad Clicks

### ISSUE THREAD

**Issue by rubendevgo** [xyflow/xyflow#4604]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Describe the Bug

In version 11.11.3, the onNodeClick event sometimes does not respond when a node is clicked using a touchpad

### Steps to reproduce the bug or issue

1- Create two nodes in the React Flow diagram.
2- Use a touchpad to alternately click between the two nodes repeatedly.

### Expected behavior

onNodeClick should reliably work with touchpad clicks, selecting the clicked node as expected.

### Additional context

onNodeClick consistently triggers with a mouse click but occasionally fails with a touchpad click. It seems React Flow might be interpreting the touchpad click as a drag event. However, when the touchpad click fails, neither onDragStart nor onNodeClick events are triggered, which is unexpected.

```
 <Grid
            id="react-flow-wrapper"
            sx={{
                width: '100%',
                height: '100%'
            }}
            ref={reactFlowWrapperRef}
        >
            <ReactFlowProvider key={id}>
                <ReactFlow
                    id={id}
                    style={styles}
                    nodes={nodes}
                    edges={edges}
                    onNodesChange={onNodesChange}
                    onEdgesChange={onEdgesChange}
                    onConnect={onConnect}
                    nodeTypes={nodeTypes}
                    edgeTypes={edgeTypes}
                    onNodeDragStop={onNodeDragStop}
                    onNodeDragStart={onNodeDragStart}
                    onInit={(reactFlowInstance) => setReactFlowInstance(reactFlowInstance)}
                    onPaneClick={onPaneClick}
                    onNodeClick={onNodeClick}
                    nodesDraggable={false}
                    nodeDragThreshold={4}
                    minZoom={-Infinity}
                    deleteKeyCode="Delete"
                    onMouseMove={handleMouseMove}
                    fitView
                >
                    <Controls />
                    <MiniMap />
                </ReactFlow>
            </ReactFlowProvider>
        </Grid>
```

**Comment by andreyvolfman** [comment]
+1 I have same issue with macbook pro trackpad.

@peterkogo I see that tag topic:mobile was attached, but issue is reproducible on desktop devices like MacBook too.

**Comment by chrtze** [comment]
Hey @rubendevgo, @andreyvolfman! This could indeed happen because the node is dragged by a few pixels which will prevent the click event to propagate. Could you try adding [`nodeClickDistance`](https://reactflow.dev/api-reference/react-flow#node-click-distance) with a value < 0 to your app and see if the issue persists?

**Comment by andreyvolfman** [comment]
Hi @chrtze! Thank you for your help. Seems it works for me!
