### ISSUE TITLE
onNodeDrag handler returns NaN as the position when dragging.

### ISSUE THREAD

**Issue by HiChen404** [xyflow/xyflow#4605]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version:    "@xyflow/react": "^12.2.0"
- Browser and version:  Edge and Chrome latest
- OS and version: Windows 11 Latest

### Live code example

https://codesandbox.io/p/sandbox/distracted-butterfly-pxhq2t?utm_medium=sandpack&workspaceId=5a053b65-8f55-4d85-8822-9bd28586b999

### Describe the Bug

When dragging the node, the onDragNodeHandler function return  NaN in Position.

### Steps to reproduce the bug or issue

just drag the node.

### Expected behavior

Don't drag the node with NaN coordinates

**Comment by antxiaopa** [comment]
Maybe you should pass onNodesChange to ReactFlow
You can read [this issue](https://github.com/xyflow/xyflow/issues/4598) which is similar to yours

**Comment by HiChen404** [comment]
> Maybe you should pass onNodesChange to ReactFlow You can read [this issue](https://github.com/xyflow/xyflow/issues/4598) which is similar to yours

Thank you! It works.

However, I still think this is a bug.

**Comment by moklick** [comment]
If you are working with a controlled flow, you need to pass an `onNodesChange` handler. This is not a bug. If you don't need a controlled flow, you can use `defaultNodes` and `defaultEdges`.
