### ISSUE TITLE
any plan for education for lowest price for associated with reactflow pro ?

### ISSUE THREAD

**Issue by 13gucci** [xyflow/xyflow#4621]
### Please describe the feature that you want to propose

any plan for education for lowest price for associated with reactflow pro ?

**Comment by hayleigh-dot-dev** [comment]
You can reach out to us directly if you're working on something for school or open source and need access to a specific example. From the FAQ:

> If you need access to the Pro Example code for a non-commercial project:
> • For educational purposes, email us at info@xyflow.com using your university email address with a link to the example you're looking for.
> • For non-commercial open source projects, [contact us](https://xyflow.com/contact) with the link to the github or gitlab repository.
