### ISSUE TITLE
 Is there any way to customize the connecting lines or display self-looping nodes better?

### ISSUE THREAD

**Issue by wowok-ai** [xyflow/xyflow#4633]
### Please describe the feature that you want to propose

![image](https://github.com/user-attachments/assets/a0860bad-68c9-4dec-ac93-e5e8479d7ada)

The display effect of self-looping nodes is very poor. Is there any way to customize the connecting lines or display them better?

**Comment by bcakmakoglu** [comment]
[There's an old example on how to do something like that right here.](https://codesandbox.io/p/sandbox/sharp-orla-vyjqen)

**Comment by moklick** [comment]
You would need to implement a custom type for that as seen in the [custom edge example](https://reactflow.dev/examples/edges/custom-edges).
