### ISSUE TITLE
The onNodeMouseEnter/Leave events do not cover the area of the NodeToolBar

### ISSUE THREAD

**Issue by justin-ren** [xyflow/xyflow#4644]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.2.0
- Browser and version: chrome Version 128.0.6613.84 
- OS and version: Linux Mint 5.15.0-117-generic

### Describe the Bug

Based on the example from [React Flow’s Node Toolbar](https://reactflow.dev/examples/nodes/node-toolbar), I tried to modify it to show or hide the NodeToolbar using MouseEnter and MouseLeave events. However, as soon as the mouse leaves the node’s area, even if it enters the NodeToolbar area, React Flow still considers the MouseLeave event to have occurred, causing the NodeToolbar to be hidden.

### Steps to reproduce the bug or issue

Reproduce:  Please copy below code into App.js in sandbox https://codesandbox.io/p/sandbox/vrlcly

I have already added a delay for MouseLeave, and even though there is enough delay time, it is not the best solution. I still hope that React Flow will consider the NodeToolbar as part of the node and have the same MouseEnter/Leave area as the node.
```javascript
import { useCallback } from "react";
import {
  ReactFlow,
  ReactFlowProvider,
  Panel,
  NodeToolbar,
  Position,
  useNodesState,
} from "@xyflow/react";
import "@xyflow/react/dist/style.css";

const initialNodes = [
  {
    id: "1",
    position: { x: 0, y: 0 },
    type: "node-with-toolbar",
    data: {
      label: "Hover over me to show the toolbar",
      forceToolbarVisible: false,
    },
  },
];

const nodeTypes = {
  "node-with-toolbar": NodeWithToolbar,
};

function NodeWithToolbar({ data }) {
  // const handleMouseEnter = (event) => {
  //   console.log("enter");
  //   event.stopPropagation();
  // };

  // const handleMouseLeave = (event) => {
  //   event.stopPropagation();
  // };
  return (
    <div
      style={{ position: "relative" }}
      // onMouseLeave={handleMouseLeave}
      // onMouseEnter={handleMouseEnter}
    >
      <NodeToolbar
        isVisible={data.forceToolbarVisible}
        position={data.toolbarPosition}
      >
        <button>cut</button>
        <button>copy</button>
        <button>paste</button>
      </NodeToolbar>
      <div className="react-flow__node-default">{data?.label}</div>
    </div>
  );
}

function Flow() {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);

  const onNodeMouseEnter = useCallback(
    (event, node) => {
      setNodes((nds) =>
        nds.map((n) =>
          n.id === node.id
            ? { ...n, data: { ...n.data, forceToolbarVisible: true } }
            : n
        )
      );
    },
    [setNodes]
  );

  const onNodeMouseLeave = useCallback(
    (event, node) => {
      setTimeout(() => {
        setNodes((nds) =>
          nds.map((n) =>
            n.id === node.id
              ? { ...n, data: { ...n.data, forceToolbarVisible: false } }
              : n
          )
        );
      }, 200);
    },
    [setNodes]
  );

  const setPosition = useCallback(
    (pos) =>
      setNodes((nodes) =>
        nodes.map((node) => ({
          ...node,
          data: { ...node.data, toolbarPosition: pos },
        }))
      ),
    [setNodes]
  );

  const forceToolbarVisible = useCallback((enabled) =>
    setNodes((nodes) =>
      nodes.map((node) => ({
        ...node,
        data: { ...node.data, forceToolbarVisible: enabled },
      }))
    )
  );

  return (
    <ReactFlowProvider>
      <ReactFlow
        nodes={nodes}
        onNodesChange={onNodesChange}
        onNodeMouseEnter={onNodeMouseEnter}
        onNodeMouseLeave={onNodeMouseLeave}
        nodeTypes={nodeTypes}
        fitView
        preventScrolling={false}
      >
        <Panel>
          <h3>Node Toolbar position:</h3>
          <button onClick={() => setPosition(Position.Top)}>top</button>
          <button onClick={() => setPosition(Position.Right)}>right</button>
          <button onClick={() => setPosition(Position.Bottom)}>bottom</button>
          <button onClick={() => setPosition(Position.Left)}>left</button>
          <h3>Override Node Toolbar visibility</h3>
          <label>
            <input
              type="checkbox"
              onChange={(e) => forceToolbarVisible(e.target.checked)}
            />
            <span>Always show toolbar</span>
          </label>
        </Panel>
      </ReactFlow>
    </ReactFlowProvider>
  );
}

export default Flow;

```

### Expected behavior

Could you provide a method that allows the MouseEnter and MouseLeave events to apply not only to the node area but also to the NodeToolbar area? Thank you.

**Comment by moklick** [comment]
Hey! This is the expected behaviour. As a workaround you could extend your node on the top with an invisible rectangle that acts as an additional hover area: https://codesandbox.io/p/sandbox/sleepy-gianmarco-7pmmpq?file=/App.js:39,3-46,9

```jsx
<div
  style={{
    position: "absolute",
    width: "100%",
    height: 25,
    transform: "translate(0, -100%)",
  }}
/>
```

Does that work for you?

**Comment by justin-ren** [comment]
> Hey! This is the expected behaviour. As a workaround you could extend your node on the top with an invisible rectangle that acts as an additional hover area: https://codesandbox.io/p/sandbox/sleepy-gianmarco-7pmmpq?file=/App.js:39,3-46,9
> 
> ```js
> <div
>   style={{
>     position: "absolute",
>     width: "100%",
>     height: 25,
>     transform: "translate(0, -100%)",
>   }}
> />
> ```
> 
> Does that work for you?

Thank you very much for your quick response, and your method works for me. I tried placing the div component behind all elements, so the NodeToolbar can work properly at the bottom of the node.
```javascript
function NodeWithToolbar({ data }) {

  return (
    <>
      <NodeToolbar
        isVisible={data.forceToolbarVisible}
        position={data.toolbarPosition}
      >
        <button>cut</button>
        <button>copy</button>
        <button>paste</button>
      </NodeToolbar>
      <div className="react-flow__node-default">{data?.label}</div>
      <div
        style={{
          position: "absolute",
          width: "100%",
          height: 25,
          transform: "translate(0, 3%)",
        }}
      />
    </>
  );
}
```
 However, I would like to understand why this method works. Could you please explain it?

**Comment by moklick** [comment]
Sorry, but I don't get your question. Do you want to show the toolbar at the bottom of the node?

**Comment by justin-ren** [comment]
> Sorry, but I don't get your question. Do you want to show the toolbar at the bottom of the node?

No, according to your method, I was able to handle the NodeToolbar at the bottom. However, I don’t understand why your workaround works. This workaround seems quite magical. 
Do all divs in the custom node count as areas that can trigger the node’s MouseEnter/Leave events?
Could you give some explanation

**Comment by moklick** [comment]
Custom nodes are wrapped by ReactFlow with a div (.react-flow__node). That means, that everything you render in a custom node is inside that div. That's why `onMouseEnter` works on everything that is defined in your custom node. The `NodeToolbar` acts different, because it gets rendered in a Portal (so it's not a child of a node).
