### ISSUE TITLE
React flow edges are not getting mounted on UI if browser zoom level is reduced to 80%, 90% or increased to 110%

### ISSUE THREAD

**Issue by mahesh-vidhate** [xyflow/xyflow#4647]
### What platform were you using when you found the bug?

- React Flow : 11.10.1
- Browser and version: Chrome 127.0.6533.89
- OS and version: MacOS - 12.7.1 

### Describe the Bug

Firstly, Thanks for such nice library.
I am using react-flow in my application with custom edge and custom node for drawing graphs.
I am facing bit strange issue, where edges are **not getting mounted** when browser zoom level is changed **before** mounting/launching graph.
This is **only** happening when there are too many nodes and edges are present on the graph and browser zoom levels is set to 80%, 90% or 110%

Its working fine if graph level is set to 75%, 100%(default), 125% or 150%.

### Steps to reproduce the bug or issue

Having graph with custom node and edges.
1. Set browser zoom level to 80%, 90% or 110% before mounting graph.
2. Launch or mount the graph by visiting particular page. Graph must have large number of nodes and edges.
Issue-  Graph edges are getting mounted. Application is not even executing/calling the custom edge component code.

### Expected behavior

Graph edge should be visible even for other zoom levels

**Comment by peterkogo** [comment]
I cannot reproduce this on my end. Can you create a codesandbox via [new.reactflow.dev/ts](http://new.reactflow.dev/ts) with a reproduction?

**Comment by mahesh-vidhate** [comment]
Sure @peterkogo. Will prepare some example on codesandbox to reproduce this scenario, and will provide it within 2-3 days.
Thanks

**Comment by moklick** [comment]
Please re-open with a codesandbox or repo.
