### ISSUE TITLE
Rotation function, custom connection handle, the connection line is too far away from the handle

### ISSUE THREAD

**Issue by coderlzw-cn** [xyflow/xyflow#4659]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Live code example

https://codesandbox.io/p/sandbox/hungry-euclid-vmp2fz?workspaceId=03aed142-1c3e-4f87-8ec0-3edcf724a6ef&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm11iqyx100063b6lrqdrmyqw%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm11iqyx000023b6lwynespev%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm11iqyx100033b6l2rrngr1a%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm11iqyx100053b6lapr4lff0%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm11iqyx000023b6lwynespev%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm11iqyx000013b6ld0yrquau%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm11jcp3500023b6rjlxvqtu8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A91%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252FResizeRotateNode.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm11iqyx000023b6lwynespev%2522%252C%2522activeTabId%2522%253A%2522cm11jcp3500023b6rjlxvqtu8%2522%257D%252C%2522cm11iqyx100053b6lapr4lff0%2522%253A%257B%2522id%2522%253A%2522cm11iqyx100053b6lapr4lff0%2522%252C%2522activeTabId%2522%253A%2522cm11jcwe300133b6re5krksex%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm11iqyx100043b6lsr9j7ayu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm11ir2et00133b6ljrhhbgv1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm11jcwe300133b6re5krksex%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm11iqyx100033b6l2rrngr1a%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm11iqyx100033b6l2rrngr1a%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Describe the Bug

<img width="2194" alt="image" src="https://github.com/user-attachments/assets/f5e391e0-6076-48ab-a807-459c4b841303">

### Steps to reproduce the bug or issue

<img width="660" alt="image" src="https://github.com/user-attachments/assets/c51b6efd-80af-46e4-85cd-b7f462e0dbbc">

### Expected behavior

<img width="1087" alt="image" src="https://github.com/user-attachments/assets/55e4a454-bd78-4ab4-80eb-ed41b00eacde">

**Comment by coderlzw-cn** [comment]
> Unfortunately, I don't have access to the sandbox. Are you sure you are calling `updateNodeInternals` while rotating?

https://my5353.com/orh7J       

I used the demo provided by the official website and only changed the style of handle, even `const [rotation, setRotation] = useState(50);` In the first rendering is also not the expected effect
<img width="1498" alt="image" src="https://github.com/user-attachments/assets/39451509-7fe7-43ed-9979-4ae0962f9b9a">

**Comment by peterkogo** [comment]
We don't have first class support for rotations in the library and it works fine for handles that have the same height & width. I think you uncovered one of the limits of our implementation. Do you really need this feature or is this something you uncovored along the way?

**Comment by coderlzw-cn** [comment]
I think I need this function because I want to implement the image below, where the Handle is propped open by text. However, I found that the rotated lines could not be connected properly, and it would be better if the arrows could be configured to point over the edge of the Handle
![Kapture 2024-09-16 at 23 04 05](https://github.com/user-attachments/assets/f4a02a34-640e-4bca-9e84-6c54c698adfb)

**Comment by peterkogo** [comment]
Wait, I think these are 2 seperate issues.

1. We do not adjust for rotation when displaying the edges. If you really want a super long handle then I suggest you put the actual square handle component on the tip of that edge and just visually indicate it's length.

2. The video you have shown me is having issues with handle positions. Are you sure you are setting the property correctly when you rotate it? (top, right,bottom, left)

**Comment by coderlzw-cn** [comment]
Thanks for the Pointers

![Kapture 2024-09-17 at 17 51 00](https://github.com/user-attachments/assets/c636a144-d1a3-4b6d-8b2f-59a391719201)

**Comment by moklick** [comment]
This looks good. Can we close the issue @coderlzw-cn ?
