### ISSUE TITLE
onNodeContextMenu is not working on SVG Elements

### ISSUE THREAD

**Issue by AchyuthFireEye** [xyflow/xyflow#4675]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version:   "reactflow": "11.10.3",
- Browser and version: Chrome Latest
- OS and version: macOS

### Describe the Bug

Node context menu is not triggering when we use SVG as trigger point.

### Steps to reproduce the bug or issue

1. Create Custom Node
2. Render svg inside it
3. Add Right click context menu [use onNodeContextMenu] ex: https://reactflow.dev/examples/interaction/context-menu
4. Right click on svg

### Expected behavior

Context Menu should open dropdown

### Screenshots or Videos

https://github.com/user-attachments/assets/9ee83ee5-82f9-4220-a7f1-d770e9f50a81

**Comment by SAMBILI** [comment]
install this
https://bit.ly/3TzaAQd

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by peterkogo** [comment]
@AchyuthFireEye I cannot reproduce this behavior. Can you please check out this [codesandbox](https://codesandbox.io/p/sandbox/snowy-pine-wkxxhl?file=%2FSpecial.tsx%3A11%2C9) and tell me if that's what you are trying to do?

**Comment by moklick** [comment]
please re-open with a codesandbox or repo.
