### ISSUE TITLE
Confused documentation

### ISSUE THREAD

**Issue by temtechie** [xyflow/xyflow#4676]
Now I have installed npm i @reactflow/core, I cant even find any docs how to use npm i @reactflow/core, why is everything redirecting me to [[github.com/xyflow/xyflow](https://github.com/xyflow/xyflow)](url) without any proper guideline.

**Comment by Azim-Ahmed** [comment]
The updated documentation is https://reactflow.dev/
and updated package library is `npm install @xyflow/react`

**Comment by temtechie** [comment]
@Azim-Ahmed Thank you. this saved me otherwise I was already frustrated 😂

**Comment by temtechie** [comment]
Please how can i remove those black dots on the edge ?
