### ISSUE TITLE
Node Deleted During Drag Causes Issues

### ISSUE THREAD

**Issue by griffins-planera** [xyflow/xyflow#4677]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 11.10.3 and 12.2.1
- Browser and version: Chrome 128.0.6613.120
- OS and version: MacOs Sonoma 14.6.1 

### Live code example

https://new.reactflow.dev/js

### Describe the Bug

**What I've reproduced in v12 sandbox:**
If a node is deleted while dragging the library will throw an uncaught error on next cursor move. 
`Cannot read properties of undefined (reading 'parentId')`

**What I experience in our app using v11**
This manifest as a blank node re-appearing on next mouse move. On drag end an event is still fired with the new XY coordinates. This requires additional complexity down the line to ensure our own state is not polluted with nodes having undefined or blank properties. 

### Steps to reproduce the bug or issue

1) Click on a node so that it enters the selected state
2) Drag the node with a new click and hold (do not release the mouse)
3) Press delete/backspace key to delete the node
4) Without releasing the mouse continue dragging 
  - This should produce an error
5) Release the mouse to end the drag
  - This still fires an event with updated position for the deleted node
  
 There are likely other ways to produce this scenario, especially in apps with realtime collaboration. Fundamentally it occurs when a node goes missing during drag.

### Expected behavior

First I expect that users should not be able to delete a node during drag, or at least the drag action should exit gracefully if the node is deleted. No error and either no drag end event or an indication that it failed.  

The latter may be a more global approach as nodes can disappear for a variety of reasons in practice. Not just manual delete through keyboard.

### Screenshots or Videos

https://github.com/user-attachments/assets/58a794a3-57f9-43bd-9296-e80a79d930bf

**Comment by peterkogo** [comment]
This should be handled better. Thanks for reporting!

**Comment by moklick** [comment]
This is fixed in 12.3.1 !
