### ISSUE TITLE
useOnSelectionChange from Node to Edge

### ISSUE THREAD

**Issue by glenarama** [xyflow/xyflow#4679]
### What platform were you using when you found the bug?

- React Flow : 12.3.0
- Browser and version: Chrome
- OS and version: MacOS

### Describe the Bug

When selecting an edge while a node is currently selected, the edge is not propagated to useOnSelectChange. This only seems to occur when going from Node to edge, node to node, edge to node and edge to edge work. 

- If nothing is currently selected, new Edge is provided to useOnSelectChange
- If edge is currently selected, new Edge is provided to useOnSelectChange
- If Node is currently selected the Edge is not provided to useOnSelectChange

### Steps to reproduce the bug or issue

Reproduction:

Select any Node
Select an Edge 

useOnSelectChange edge array is empty.

### Expected behavior

useOnSelectChange should pass edge array with newly selected edge.

**Comment by peterkogo** [comment]
@glenarama I cannot reproduce this behavior. Here is a [codesandbox](https://codesandbox.io/p/sandbox/fast-sunset-6jgdk7?file=%2Fsrc%2FSelectionDisplay.tsx%3A5%2C35) for debugging `useOnSelectChange`. Can you specify what seems to be the issue?

**Comment by glenarama** [comment]
@peterkogo apologies - it does appear to be an error in my logic somewhere. 

Thanks for reviewing.
