### ISSUE TITLE
Custom node not impacted by nodeOrigin

### ISSUE THREAD

**Issue by Yoni-apex** [xyflow/xyflow#4686]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.3.0
- Browser and version: Chrome
- OS and version: MacOs

### Live code example

https://codesandbox.io/p/sandbox/842hfr

### Describe the Bug

Hi,
Made some custom nodes and no matter what I do, it seems `nodeOrigin` has 0 impact. As you can see in the repro, the bottom node is always aligned from its left side. I might be missing something obvious but spent many hours on it and decided to reproduce with the most generic version I managed.

Thanks!

### Steps to reproduce the bug or issue

1. Go to the reproduction (https://codesandbox.io/p/sandbox/842hfr)
2. Look at the bottom node (id: 4) alignment with the one on top (id: 2)

### Expected behavior

I expected the node 4 to be aligned by its center to the node 2.

**Comment by bcakmakoglu** [comment]
You're not using the `nodes` and `edges` props correctly.

[Read this section of the docs to understand the difference between `nodes` and `defaultNodes` props (same for edges).](https://reactflow.dev/learn/concepts/core-concepts#controlled-or-uncontrolled)

[Here's a corrected version of your sandbox.](https://codesandbox.io/p/sandbox/xyflow-react-nodeorigin-forked-6gwnzj)

**Comment by Yoni-apex** [comment]
Amazing thank you! Can't believe this was so simple. Another question if you don't mind, it broke the initial `fitView` now. Should I actually move to a controlled flow instead so it will update the view properly or is there another/better way?

**Comment by bcakmakoglu** [comment]
Try this `onInit={({ fitView }) => fitView()}`

**Comment by Yoni-apex** [comment]
@bcakmakoglu it worked perfectly!
Thank you very much for all the help 🙏🏻
