### ISSUE TITLE
The edges act like Windows XP issue

### ISSUE THREAD

**Issue by pnaik07** [xyflow/xyflow#4688]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Describe the Bug

On dragging the node, the edges get traced throughout the path and they are permanent

![image](https://github.com/user-attachments/assets/a691350a-25c6-45c4-a14e-11b1061f3712)

### Steps to reproduce the bug or issue

Couldn't reproduce it after 2 tests. But not sure of the root cause

### Expected behavior

normal drag

**Comment by pnaik07** [comment]
> Are you using Windows?

Yes! But how it that relevant? I'm using reactflow on chrome.

**Comment by pnaik07** [comment]
Will try out this solution. Did some digging. Turns out, these svg paths are persisting in the DOM. The paths are not getting cleared post locking into a position on the node, ie the svg elements are still in the DOM even on completing the Node Move event.

Weird observation, this doesn't happens only with a variant of node i'm using. 

Sounds similar to the #4355, this is happening with the edges though. Nodes are working fine. WIll update on testing!

**Comment by pnaik07** [comment]
@peterkogo 

Observation: Assume DAG with A and B being the parent of C(A->C, B->C). On deleting node B or A, the edge AC/BC remain in the memory but not visually shown. Now when C is moved, this cracked behavior is observed. My guess is that RF is trying to render both the edges, but the loop is not complete, it doesn't cleanup the rendered edge because of the dangling edge?? This is only an assumption right now.

I'm using useReactFlow to delete edges and nodes using an identifier for both. This is a recent addition and it has started to break since. Will provide more context soon!

**Comment by peterkogo** [comment]
Interesting. I think this issue originates from your custom edge implementation.

**Comment by peterkogo** [comment]
@pnaik07 any update on a possible reproduction or maybe providing us with your custom edge code?

**Comment by pnaik07** [comment]
Oops! Forgot to update

The issue was dangling edges. When two nodes are connected by an edge and one node is deleted without de-allocating the edge, it remains in memory.

In my case, one of the right node was deleted, leaving the edge connected only to the left node. The edge wasn't removed from `setEdges` or the context, causing duplicate SVGs to render in view. I suspect the deleted parent node prevented the old SVG path from being cleared.

Fix: Delete redundant edges from memory when a node is deleted. This ensures edges disappear if either connected node is removed. This worked for me!!
