### ISSUE TITLE
`onError` + `onNodeDoubleClick` causes rerenders for all nodes

### ISSUE THREAD

**Issue by hsab** [xyflow/xyflow#4693]
### What platform were you using when you found the bug?

```
  System:
    OS: Linux 6.6 Manjaro Linux
    CPU: (32) x64 AMD Ryzen Threadripper 1950X 16-Core Processor
    Memory: 41.24 GB / 62.65 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v18.19.0/bin/pnpm
  Browsers:
    Brave Browser: 128.1.69.162
    Chromium: 129.0.6668.58
  npmPackages:
    @xyflow/react: ^12.2.1 => 12.2.1

```

### Live code example

https://codesandbox.io/p/sandbox/cocky-ramanujan-836824?workspaceId=c253d918-6796-444c-b4e6-095cb0aede36

### Describe the Bug

Using `onError` and `onNodeDoubleClick` causes all nodes to rerender, effectively breaking the benefits of shallow equality checking. This bug took forever to figure out 😭 

### With `onError` and `onNodeDoubleClick`

https://github.com/user-attachments/assets/21d1df00-f6c1-41ea-8771-ceed0f5910f8

### Without

https://github.com/user-attachments/assets/313553da-3eda-475a-b9a0-a84e3e2f9d25

### Steps to reproduce the bug or issue

```tsx
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      onConnect={onConnect}
      fitView
      onError={() => {}} // <----------------
      onNodeDoubleClick={() => {console.log("dbl")}} // <----------------
    />
```

### Expected behavior

I expect only the "active" node rerender

**Comment by bcakmakoglu** [comment]
Have you tried wrapping your handlers in `useCallback`? That seems to resolve the issue if I see things right ^^

[Here's an example.](https://codesandbox.io/p/sandbox/fast-bush-t2rd8p?file=%2FApp.tsx%3A27%2C1-30%2C1)

**Comment by hsab** [comment]
@bcakmakoglu That fixed it! Tysm. One other related question. I have a flow with 10-15 connected nodes. When I move the root node (the very first node) I see all the edges in my flow rerender, even those deep in the graph and not connected to my root node. Is this expected behavior?

**Comment by hsab** [comment]
@bcakmakoglu nm! Figured `useMemo` / `memo` should fix the issue and it did! For anyone else running into this issue with custom edges, here's an example code snippet that helped prevent rerenders

```tsx
import {
  BaseEdge,
  EdgeProps,
  Position,
  getSimpleBezierPath,
} from '@xyflow/react';
import React, { memo, useMemo } from 'react';

import { cn } from '@acme/ui/utils';

const CustomEdge = ({
  sourceX,
  sourceY,
  targetX,
  targetY,
  ...props
}: EdgeProps) => {
  const [edgePath] = useMemo(() => {
    return getSimpleBezierPath({
      sourceX,
      sourceY,
      targetX,
      targetY,
      sourcePosition: Position.Right,
      targetPosition: Position.Left,
    });
  }, [sourceX, sourceY, targetX, targetY]);

  return (
    <BaseEdge
      path={edgePath}
      animated
      {...props}
      className={cn(
        props.selected && '!stroke-neutral-200 !stroke-2',
        !props.selected && '!stroke-neutral-500 !stroke-1',
      )}
      style={{
        strokeLinecap: 'round',
      }}
    />
  );
};

export default memo(CustomEdge);

```
