### ISSUE TITLE
colorMode

### ISSUE THREAD

**Issue by totoago** [xyflow/xyflow#4695]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Describe the Bug

import { ReactFlow, Controls, Background, MiniMap, useReactFlow, Panel } from 'reactflow';

![image](https://github.com/user-attachments/assets/648032d2-2e29-4bf8-8ed3-0bfed0b24d34)
import reactflow, colorMode  is lapse

### Steps to reproduce the bug or issue

bug

### Expected behavior

bug

**Comment by totoago** [comment]
Controls  style  lapse
![image](https://github.com/user-attachments/assets/28af2804-78da-4b4a-bf32-e31a864dc2bf)

**Comment by bcakmakoglu** [comment]
Not sure what the problem here is because you haven't really described it at all.
Might be you're trying to pass an invalid value as [colorMode](https://reactflow.dev/api-reference/hooks/use-key-press), which can be `light`, `dark` or `system`.

**Comment by peterkogo** [comment]
This issue is not actionable. Please add a full description of your issue with complete sentences before reopening. Plus, if this is not an issue but a question, please refer to our very active [Discord](https://discord.gg/RVmnytFmGW).
