### ISSUE TITLE
nopanClassName is not valid

### ISSUE THREAD

**Issue by wscymdb** [xyflow/xyflow#4696]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: "@xyflow/react": "^12.3.1",
- Browser and version:  129.0.6668.60
- OS and version:

### Describe the Bug

I followed the official website's tutorial [slidesShowAPP](https://reactflow.dev/learn/tutorials/slide-shows-with-react-flow). When I added the nopan class to `<footer className="slide__controls nopan"></footer>` in Slide.tsx, I found it to be ineffective. When I click the arrow, it still jumps.

### Steps to reproduce the bug or issue

![image](https://github.com/user-attachments/assets/fd89a882-0502-4a90-a7e3-e5bac519d34a)

### Expected behavior

If there are no issues, please let me know. Thank you

**Comment by wscymdb** [comment]
I know the reason now. You need to add e.stopPropagation() in the button click.

**Comment by wscymdb** [comment]
But nopan didn't work either.

**Comment by hsab** [comment]
nopan is supposed to prevent the panning of the canvas when you click and drag the element that has that class. It has nothing to do with programmatic zooming/fitting of the canvas happening with `moveToNextSlide` 

Look at the video below and pay attention to the touch indicator. When I drag on the arrow the canvas doesn't pan, but when I do it on the slide it does. 

https://github.com/user-attachments/assets/f995d32e-cf9f-4b8e-99c9-cfeec37ad1ae



https://reactflow.dev/api-reference/react-flow#no-wheel-class-name
