### ISSUE TITLE
Example Computing Flows breaks if all the edges are removed for ResultNode

### ISSUE THREAD

**Issue by sutharsha** [xyflow/xyflow#4699]
### What platform were you using when you found the bug?

- Svelte Flow version: 0.1.20
- Browser and version: Chrome Version 129.0.6668.60 (Official Build) (arm64)
- OS and version: Mac OS - Sequoia 15

### Describe the Bug

In the Computing Flows example when you delete all the edges connected to ResultNode it stops working. 

Error at 	{#if $nodesData.length === 0}
Getting Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')

### Steps to reproduce the bug or issue

1. Go to -> https://svelteflow.dev/examples/interaction/computing-flows
2. Select and delete all the edges connected to the ResultNode.
3. See the error -> Getting Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')

### Expected behavior

Not crash even if all the edges are removed. 

### Additional context

This exact issue is not there in the ReactFlow example. 
But there its another issue. If you delete the edge connected to the UpperCaseNode it crashes.

**Comment by peterkogo** [comment]
Thanks for the report, this is indeed a bug!
