### ISSUE TITLE
Performance issues with custom nodes (React)

### ISSUE THREAD

**Issue by 2cin** [xyflow/xyflow#4711]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: React Flow (@xyflow/react@12.3.1)
- Browser and version: Firefox 131.0 // Chrome Version 129.0.6668.90
- OS and version: macOS 15 // Windows 10

### Live code example

https://codesandbox.io/p/sandbox/blissful-sun-forked-mqs4fd

### Describe the Bug

I'm getting rather intense frame rate drops when dragging the background grid when using custom nodes. Interacting with individual nodes or changing their parameters performs very well as expected, however moving the background or zooming causes frame drops.

### Steps to reproduce the bug or issue

1. Go to the codesandbox above or [here](https://codesandbox.io/p/sandbox/blissful-sun-forked-mqs4fdl)
2. Wait for sandbox to load and then in the preview panel press "Add Nodes"
3. Move around the background and monitor FPS meter. Note: The larger you make the preview window (or if you open the window into its own page) the worse the performance.

### Expected behavior

I expected no frame drops and performance to stay steady considering the operation (to my knowledge) shouldn't be that intense.

### Screenshots or Videos

![gif](https://github.com/user-attachments/assets/8e7c3c0b-ab76-43c3-8e42-eaaa0dc2297d)
Note the above gif sort of destroys the visible FPS discrepancy however you can still see the FPS meter drop frames as I move the canvas around. You can try it on your end as well, I've had multiple people try this out on all sorts of hardware and browsers and we all experience the same issues.

**Comment by peterkogo** [comment]
I am hitting almost 120 fps with 300 nodes on screen. Looking at the perfromance graph, most of it is spent on layouting 300 overlapping nodes. I would say this is a very unrealistic benchmark, and you are hitting the limits of what browser compositing is capable on your machine.

<img width="827" alt="image" src="https://github.com/user-attachments/assets/c43cb804-3ffd-4aa1-a9cd-9b9beed8eac9">

**Comment by 2cin** [comment]
Interesting observation. I think you are right that this is an unrealistic benchmark, as spreading out the nodes more such that they are not heavily layered reduced the lag almost entirely! Is this just a browser thing or is there maybe some way to increase performance in the case of layered nodes? If not, all good. I think I overestimated the scope of the lag based on this heavily layered example thinking it was the number of nodes vs their location.

**Comment by 2cin** [comment]
Got it thanks for the insight. I'll build conscious of that fact.

**Comment by peterkogo** [comment]
@MrgSub You might have forgot to use `React.memo`. 
And what is happening in your flow? It is very hard to reason about this when there a million things changing on screen. How did you determine this is specifically connected to your custom nodes and not something else?

**Comment by florianbgt** [comment]
I had that issue, for me it was some css properties. To be specific `backdrop-filter: blur(2px);`. Removing that property solved it
See here: https://github.com/nanoapi-io/napi/pull/19/files#diff-496b310be54684663993206686f697dcf04e6a5fb3eccd97af1555a21eda8863L21
