### ISSUE TITLE
SvelteFlow: Not able to connect the correct handles

### ISSUE THREAD

**Issue by kerem0comert** [xyflow/xyflow#4715]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 0.1.20
- Browser and version:  Brave v.1.70.123
- OS and version: Windows 11

### Describe the Bug

Hello,

I have nodes with 4 `Handle`s in each side. I would like all Handles to be able to act as `source` and `target` handles, and I configured the parameter recommended [here](https://github.com/xyflow/xyflow/discussions/1537#discussioncomment-1725776) accordingly, and it works.

### Steps to reproduce the bug or issue

The problem is, in the following scenario (where the blue node is `node_a` and the green node is `node_b`):
- User starts dragging `handle_right` of `node_a`
- The edge being dragged seems to originate from `handle_top` of `node_a` instead
![drag_start](https://github.com/user-attachments/assets/75fdb2f3-e721-4377-b968-5a3570fd946d)
- The edge is dropped on the `handle_left` of `node_b` (the small green bubbles that form on 4 sides of `node_b` are my custom handles that become visible with the `.svelte-flow__handle.connectingto` CSS property
![drag_end](https://github.com/user-attachments/assets/b8a21758-df12-4f80-bd2a-493513cda099)
- The edge is wrongly formed between `handle_top` of both nodes. As can be seen, this causes the custom edge I have with the arrow pointer to be blocked by the node at some angles of the connection due to that
![drag_result](https://github.com/user-attachments/assets/7921ca17-138d-41ad-bc32-967942c8d8f6)

### Expected behavior

Is this the expected behavior? While the `connectionMode=loose` does make the handles work both as `target` and `source`, do they always form the edge on the top handles? Is there a way to override this behavior? Or do you think that this is unexpected and is probably a bug that is due to my custom implementation potentially (in which case I can share specific snippets)?

Thanks!

**Comment by bcakmakoglu** [comment]
Looks like you're trying to hide the Handle in a way that does not work.
Are you doing something like `display: none`?

**Comment by kerem-coemert** [comment]
My `style` section targeting handles look like:

```css

  :global(.svelte-flow .svelte-flow__handle.connectingto) {
    @apply bg-se-green-1 w-4 h-4 rounded-full m-0;
  }

  :global(.svelte-flow__handle) {
    @apply border-none bg-transparent rounded-none;
  }

  :global(.svelte-flow__handle-top, .svelte-flow__handle-bottom) {
    @apply w-40 h-4;
  }

  :global(.svelte-flow__handle-top) {
    @apply mt-2;
  }

  :global(.svelte-flow__handle-bottom) {
    @apply mb-2;
  }

  :global(.svelte-flow__handle-left, .svelte-flow__handle-right) {
    @apply w-4 h-20;
  }

  :global(.svelte-flow__handle-left) {
    @apply ml-2;
  }

  :global(.svelte-flow__handle-right) {
    @apply mr-2;
  }
  :global(.svelte-flow__handle.connectingto) {
    @apply bg-transparent;
  }
</style>
```

But even after removing all style references to `svelte-flow__handle`, the issue remains.

**Comment by bcakmakoglu** [comment]
You're using multiple handles, yes?
Do they have an id assigned to them?

**Comment by kerem0comert** [comment]
Alright, that was it - I was simply missing an `id´ on them =) Thanks for your on-point suggestions!
