### ISSUE TITLE
`selectNodesOnDrag={false}` mutates the underlying node objects whilst trying to deselect them

### ISSUE THREAD

**Issue by JackWH** [xyflow/xyflow#4716]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: `@xyflow/react` v12.3.1
- Browser and version: Chrome 129
- OS and version: macOS Sequoia

### Describe the Bug

When `selectNodesOnDrag={false}`, React Flow 12 mutates underlying node objects in order to deselect non-dragging nodes. This seems to be the only part of React Flow which behaves this way. Other updates create node changes which are turned into new node objects.

As my node objects are stored in `zustand` with the `immer` middleware, this throws a console error due to mutation every time a node is dragged around.

### Steps to reproduce the bug or issue

1. Use node objects with `immer` middleware in `zustand`
2. Set `selectNodesOnDrag={false}`
3. Try to drag the node around
4. Check the browser console

### Expected behavior

It should update the selection status using node changes, rather than object mutations.

### Screenshots or Videos

![Screenshot 2024-10-07 at 23 46 55@2x](https://github.com/user-attachments/assets/117f6f16-e960-4d66-86e0-47d5f8b40a4b)

![Screenshot 2024-10-07 at 23 46 26@2x](https://github.com/user-attachments/assets/65f876a2-50f4-415c-81f3-745219561e44)

### Additional context

I first noticed this after upgrading from React Flow 11 to 12. I assume this is a bug/unintentional, given the statement in the upgrade guide:

> We are not supporting node and edge updates with object mutations anymore. If you want to update a certain attribute, you need to create a new node / edge.

**Comment by peterkogo** [comment]
Thanks for bringing this to our attention. We will take a look.

**Comment by moklick** [comment]
This is fixed in 12.3.2

**Comment by HiChen404** [comment]
same problem in applyNodeChange when using immer.

**Comment by HiChen404** [comment]
> same problem in applyNodesChange when using immer.

same problem in applyNodesChange when using immer.

**Comment by JackWH** [comment]
@HiChen404 The bug seems to be fixed for me since 12.3.2. I'm using immer and no longer seeing any issues. Are you sure you're using the latest version? If so, maybe open a new issue or share a console trace.
