### ISSUE TITLE
Collaborative pro example isn't working

### ISSUE THREAD

**Issue by Toukassay** [xyflow/xyflow#4719]
### What platform were you using when you found the bug?

![image](https://github.com/user-attachments/assets/f56b2961-5b62-4b54-aaef-51e3e238a1bb)
Link : https://reactflow.dev/examples/interaction/collaborative

### Describe the Bug

Demo isn't working

### Steps to reproduce the bug or issue

1 - Go to https://reactflow.dev/examples/interaction/collaborative
2 - Test on two devices (it's working on just two tab on same device) 
3 - Also open the console, you'll see connection errors

### Expected behavior

Working on two seperate devices, as the notice said: 
> To see it working, you can [open this page in another tab](https://reactflow.dev/examples/interaction/collaborative) or on another device or browser.

**Comment by chrtze** [comment]
Thanks for opening this issue. It seems like the [default server for y-webrtc](https://github.com/yjs/y-webrtc/blob/master/src/y-webrtc.js#L601) is not working anymore. We'll investigate further.

**Comment by Toukassay** [comment]
> We are hosting our signaling server now, this should be fixed.

Could be something that we might be interested, would you mind sharing some doc about this ? Even if it's not XYFlow related.
Thanks.

**Comment by peterkogo** [comment]
@Toukassay I just forked [y-webrtc](https://github.com/yjs/y-webrtc), and ran `fly launch` (Dockerfile and fly.toml is already present). You don't even need to fork it if you are not interested in chaning anything :)

**Comment by Toukassay** [comment]
Hello again, I think it's dead again ?
https://reactflow.dev/examples/interaction/collaborative
Work on two tabs same browser but not on two devices..

**Comment by Toukassay** [comment]
I seen something on my app and you have the very same behaviour, it drives me crazy this I cannot make sense of that..

1 - Desktop device - On a browser, go on https://reactflow.dev/examples/interaction/collaborative
2 - Desktop device - On another device, go to https://reactflow.dev/examples/interaction/collaborative
3 - You should not see you modifications synced like I mention above
4 - Now the funny part.. Take your phone (Android for me), go to https://reactflow.dev/examples/interaction/collaborative
5 - It will sync all the 3 device and everything is working has expected...
6 - Close the tab on your mobile device, after few seconds, the desktop devices cannot see sync content.
6a - Burn the whole setup and take a break

**Comment by chrtze** [comment]
Hey @Toukassay, did you use your own signaling server in your app? I could imagine that this has something todo with the default maximum number of connections. The example is only for illustrative purposes but you'll need to setup your own server and eventually some custom logic to make this work. We'll make this more clear in the instructions for the example as well.
