### ISSUE TITLE
[SvelteFlow] Get the coordinates of the mouse cursor within the Flow

### ISSUE THREAD

**Issue by kerem-coemert** [xyflow/xyflow#4726]
### Please describe the feature that you want to propose

Hello,

This is probably a duplicate of #3750 that went unanswered. Is there a callback or a hook to be able to get what the current `X` and `Y` positions of the mouse cursor is, within the coordinate system of the `Flow`?

If I am over a `node` or an `edge`, I can kind of find my position by checking the coordinates of the node whose `id` is passed with the `on:nodedrag` event for instance, but is it possible to get my coordinates anytime I move the cursor?

Thanks!

**Comment by bcakmakoglu** [comment]
You can use [`screenToFlowPosition`](https://svelteflow.dev/api-reference/hooks/use-svelte-flow#screen-to-flow-position) of `useSvelteFlow` to determine the coordinates in the viewport based on the mouse position.

**Comment by kerem-coemert** [comment]
Perfect, thanks :)
