### ISSUE TITLE
When the parent node sets an opaque background color in subflow, the edges of the child node disappear

### ISSUE THREAD

**Issue by xiaoyaovo** [xyflow/xyflow#4729]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.3.1
- Browser and version: Microsoft Edge  129.0.2792.79
- OS and version: Windows 22H2

### Live code example

https://stackblitz.com/edit/t2rqgd?file=nodes.js,package-lock.json

### Describe the Bug

edge exit:
![image](https://github.com/user-attachments/assets/8dadfd93-4d92-4b65-b861-a9e02eebac0a)
edge not exit:
![image](https://github.com/user-attachments/assets/ae28a086-483d-4928-b0fe-99765c894975)

### Steps to reproduce the bug or issue

Open link:https://stackblitz.com/edit/t2rqgd?file=nodes.js,package-lock.json

### Expected behavior

Add this feature according to your progress

**Comment by moklick** [comment]
By default all edges are rendered below nodes. You can move them to the foreground by adjusting their `zIndex` https://reactflow.dev/api-reference/types/edge#z-index
