### ISSUE TITLE
dragging nodes inside a parent triggers autopan even if extent is reached

### ISSUE THREAD

**Issue by zhugexiaogou666** [xyflow/xyflow#4732]
### Please describe the feature that you want to propose

I want that when dragging a child node, the canvas will not continue to be dragged after reaching the parent node

https://github.com/user-attachments/assets/1717a84c-dab9-4eb7-936a-ec5e297dc355

**Comment by peterkogo** [comment]
Thanks for the issue! I noticed this behavior before and we should definitely change it!

**Comment by zhugexiaogou666** [comment]
I tried having the property set like this autoPanOnNodeDrag={false} and that seems to work
