### ISSUE TITLE
Connection Line Permanently Offset After Autofocus

### ISSUE THREAD

**Issue by griffins-planera** [xyflow/xyflow#4734]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 11.10.3 and 12.2.1
- Browser and version: Chrome 128.0.6613.120
- OS and version: MacOs Sonoma 14.6.1

### Live code example

https://codesandbox.io/p/sandbox/festive-hooks-pv3whs

### Describe the Bug

When a node contains an input with autoFocus enabled, the canvas can jump to bring the input in view. This causes a permanent offset for the edge connection line as well as various other visual offsets.

### Steps to reproduce the bug or issue

1) Click near the edge of canvas to create a custom node with an auto focused input
2) Notice the canvas jump to bring the input in view
3) Start a new connection from dragging on an edge handle

### Expected behavior

I expect that the canvas will either:
- Not become offset due to an offscreen input
- Return to its normal behavior after focus leaves the input

Also open to other solutions as I am not sure what the potential browser limitations are in this case

### Screenshots or Videos

https://github.com/user-attachments/assets/e8b8a4c8-9315-41b1-92ba-21b11b7cf0ff

**Comment by peterkogo** [comment]
This is unfortunately an unsolved problem. Focusing offscreen elements does not play nicely with custom viewports, and there is no reliable way to interfere with the browser behavior. See related issue #4667. 

I highly suggest you manage focus programmatically, by moving the node into view (or through `fitView`) and afterward focusing the input field. 

I will close this issue for now, you can track it's progress in #4667.
