### ISSUE TITLE
NodeResizer Height issue when changing height of Node Programmatically

### ISSUE THREAD

**Issue by react-universe** [xyflow/xyflow#4739]
### What platform were you using when you found the bug?

- React Flow : 12.3.0
- Browser and version: Google chrome (119.0.6045.105)
- OS and version: Ubuntu (20)

### Describe the Bug

I have a custom node type. In the custom node, I have a text area. So, basically, it's a node where the user can write and resize. For resizing, I used the NodeResizer (the default provided by React Flow). Now, the thing is, my node height can change if the text is bigger than the node. I am changing it programmatically. Initially, it worked fine. But once a node gets selected, NodeResizer comes and now if I change my node height programmatically then it doesn't get updated. 

Below Is my Node code. It just has the Textarea and I am changing my node's height. 

```
import React, { useEffect, useRef, useState } from "react";
import { TextArea } from "@/components/ui/text-area";
import {
  Node,
  NodeProps,
  NodeResizer,
  useUpdateNodeInternals,
} from "@xyflow/react";
import { useAppDispatch, useAppSelector } from "@/hooks/reduxHooks";
import { singleNodeUpdate } from "@/store/slices/workspaceSlice";

const TextNode = ({ id, selected, data, width }: NodeProps) => {
  const dispatch = useAppDispatch();
  const [height, setHeight] = useState("");
  const updateNodeInternals = useUpdateNodeInternals();

  const [textData, setTextData] = useState("");
  useEffect(() => {
    (document.querySelector(`#${id}`) as HTMLElement).focus();
  }, []);

  const handleTextAreaChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setTextData(e.target.value);
    setHeight(e.target.scrollHeight + "px");
    // Below is code to change the node's height, I have used Redux here so dispatching it.
    dispatch(
      singleNodeUpdate({
        id,
        measured: {
          width,
          height: e.target.scrollHeight,
        },
        selected: false,
      }),
    );

    // To tell react flow changes made in node
    updateNodeInternals(id);
  };

  return (
    <>
        <NodeResizer
          nodeId={id}
          isVisible={Boolean(selected)}
          lineClassName="!border-blue-400"
          onResize={(_, params) => {
            setHeight(params.height + "px");
          }}
          handleClassName="!h-3 !w-3 !bg-white !border-2 !rounded !border-blue-400"
        />
      <TextArea
        autoFocus
        tabIndex={-1}
        id={id}
        onBlur={() =>
          dispatch(
            singleNodeUpdate({
              id,
              data: { ...data, textData },
            }),
          )
        }
        style={{
          height: height || "auto",
        }}
        onChange={handleTextAreaChange}
        className="h-full resize-none overflow-hidden border-0 text-sm shadow-none focus-visible:ring-1 focus-visible:ring-blue-300 focus-visible:ring-offset-0"
      />
    </>
  );
};

export default TextNode;

```

### Steps to reproduce the bug or issue

Initially it works as node Resizer isn't come to the picture as I have a condition if the node is selected then show node Resizer. So initially it works. But once Node gets selected nodeResizer comes to the picture, Now when I change node size programmatically my height doesn't get updated. 

### Expected behavior

I want the Node Resizer to change the height if I change the Node's height Programmatically. 

### Screenshots or Videos

https://www.loom.com/share/a26b7686c2de41d98a600df7a8148a4e?sid=dcfc847d-e6cd-4588-9b25-35f1449d1ebe

So as shown in the picture, Initially I can write anything and it gets expanded but once NodeResizer comes, My textarea height changes but Node height remains the same. You can see 2 borders in the video. The smaller one is of node ( Node resizer gives the border to Node) and the second is for textarea.

**Comment by chrtze** [comment]
hey @react-universe, the nodes in react flow have a resize observer attached that measures them when their dimension changes. so it's not necessary to set the width or height of the node when you change the content of the textarea. maybe this is causing some issues here? it would be helpful if you could share a codesandbox that reproduces the issue if possible so that we can look into it further.

**Comment by peterkogo** [comment]
You have to be careful how you update your node. If you want to update the height, then do it by updating the height of the node. Also you don't have to manually react to height changes from the NodeResizer.

```ts
const ResizableNode = ({ data, id, width, height }) => {
  const { updateNode } = useReactFlow();

  const handleTextAreaChange = (e) => {
    updateNode(id, (node) => ({ ...node, height: e.target.scrollHeight }));
  };

  return (
    <>
      <NodeResizer nodeId={id} />
      <textarea
        class="nodrag"
        style={{
          height: height || 'auto',
        }}
        onChange={handleTextAreaChange}
      />
    </>
  );
};

export default ResizableNode;
```

If you need more help, please head over to our [Discord](https://discord.gg/RVmnytFmGW).
