### ISSUE TITLE
The MarkerType.ArrowClosed marker end is not being applied to edges in the second flow when the first flow is hidden

### ISSUE THREAD

**Issue by bsvetlik** [xyflow/xyflow#4748]
### What platform were you using when you found the bug?

@xyflow/react: 12.3.1
Chrome, Edge and Firefox latest versions
Windows 10 Pro

### Live code example

https://codesandbox.io/p/sandbox/modest-worker-6nwffq

### Describe the Bug

Arrow markers are disappearing on edges in new tabs when the first flow becomes hidden.
There are a few tabs in our web application. When we open the same or a different workflow in a new tab, the arrows that should be attached to the edge ends are missing. To simulate this issue, I created two root nodes with identical flows. As soon as the first flow becomes hidden, the arrows disappear. I used setTimeout() to make the bug more apparent. This bug can be reproduced with or without ReactFlowProvider container.

### Steps to reproduce the bug or issue

Load the linked example and see that that after 2 sec the arrow disappears.

### Expected behavior

Arrow markers should be displayed correctly on edges in all tabs (simulated by two root nodes), regardless of the visibility of other flows.

**Comment by vitorrsousaa** [comment]
I have the same problem. I rendered a react-flow by using tabs of ant-design. And When I add markers, it just rendered on the first flow.

**Comment by luciancaetano** [comment]
I am having the same problems, here occurs when using tabs component, when the first tab is set as display:none and the icons all disappear

**Comment by chrtze** [comment]
You need to pass an `id` prop if you want to render multiple flows on one page or in tabs. We are referencing the marker by id and if your flow doen't have an id itself, the marker from the hidden flow gets referenced. This is due to svg limitations. You can find an adjusted codesandbox [here](https://codesandbox.io/p/sandbox/practical-swartz-fcdg29?file=/src/index.jsx).

**Comment by bsvetlik** [comment]
Great job!
