### ISSUE TITLE
Webpack Module Resolution Issue: Incorrect File Loading (UMD vs. ESM)

### ISSUE THREAD

**Issue by bsvetlik** [xyflow/xyflow#4752]
### What platform were you using when you found the bug?

@xyflow/react: 12.3.1
Chrome, Edge and Firefox latest versions
Windows 10 Pro

### Describe the Bug

We're encountering an issue where Webpack is bundling files from the "@xyflow\react\dist\umd" folder instead of the intended "@xyflow\react\dist\esm" folder.

To resolve this problem, please consider to add the following line
`"module": "./dist/esm/index.js"`,
 to the  "@xyflow\react\package.json" and  "@xyflow\system\package.json" files:
```
  "exports": {
    ".": {
      "types": "./dist/esm/index.d.ts",
      "import": "./dist/esm/index.mjs",
      "module": "./dist/esm/index.js",
      "require": "./dist/umd/index.js"
    },
```

Implementing the suggested changes resolved the incorrect file loading issue in our project. The _module_ field in the _package.json_ was added to point to the ESM module file, ensuring that Webpack now bundles the appropriate files. The _index.js_ and _index.mjs_ files are functionally identical, so using either one will produce the same result.

### Steps to reproduce the bug or issue

1. Inspect Webpack Bundle: Analyze the generated Webpack bundle to verify which files are being included.
2. Debug with DevTools: Use your browser's developer tools to step through the code and inspect the imported modules. Pay attention to the file paths being resolved by Webpack.

### Expected behavior

When using the _import_ statement to import the @xyflow\react module, Webpack should correctly resolve and bundle the appropriate ES module file from the "@xyflow\react\dist\esm" folder.

**Comment by peterkogo** [comment]
Thanks for bringing this to our attention! Surprised that the `module` in `exports` has precedence over the main `module` field.
Should be released very soon! #4755

**Comment by peterkogo** [comment]
This should be fixed in React Flow 12.3.3.

**Comment by peterkogo** [comment]
@bsvetlik Can you please check if this resolves your problems? According to #4772 this does not seem to be the end of this story.

**Comment by peterkogo** [comment]
I just released a new version 12.3.4 which should hopefully address the issues once and for all.

**Comment by peterkogo** [comment]
@bsvetlik Can you tell me precisely what setup you are having issues with? I have tested the current exports in many configurations and it worked correctly.

**Comment by bsvetlik** [comment]
I changed the following setup files:
\node_modules\@xyflow\react\package.json
\node_modules\@xyflow\system\package.json

**Comment by peterkogo** [comment]
@bsvetlik I need a reproducible project to test the configuration in. I was asking what specifically your setup is you are having problems with as I cannot reproduce it.

**Comment by bsvetlik** [comment]
@peterkogo
We're building a complex dynamic setup in a mixed ESM/CommonJS environment. Adding the suggested line to project.js, if it passes tests, should be safe.

**Comment by bsvetlik** [comment]
@peterkogo
I respectfully request that this issue be reopened. My problem has not been addressed.

**Comment by chrtze** [comment]
Hi @bsvetlik, we need more information on your setup to reproduce this issue. It's not possible for us to make changes to the package json without reproducing the error. Thank you for your understanding.

**Comment by bsvetlik** [comment]
Hi @chrtze, These are our configurations:
[package-2024-11-13.json](https://github.com/user-attachments/files/17728525/package-2024-11-13.json)
[webpack5-config-options-2024-11-13.txt](https://github.com/user-attachments/files/17728530/webpack5-config-options-2024-11-13.txt)
[webpack-dev-server-v5-config-options-2024-11-13.txt](https://github.com/user-attachments/files/17728535/webpack-dev-server-v5-config-options-2024-11-13.txt)

**Comment by bsvetlik** [comment]
Hi Christopher,

I've attached all relevant configuration setups to  #4752
<https://github.com/xyflow/xyflow/issues/4752>.  Should this be sufficient
to resolve the issue?

Regards, Boris

**Comment by chrtze** [comment]
@bsvetlik, these files contain a lot of custom configuration which makes it impossible for us to reproduce. if you can create a  repository with a setup that we can run and that reproduces the error, I am happy to look into it.
