### ISSUE TITLE
Edges in minimap

### ISSUE THREAD

**Issue by parakh-gupta** [xyflow/xyflow#4757]
### Edges with minimap

Currently minimap only show nodes. It would be better to show edges as well or suggest some ways how to add edges.

**Comment by moklick** [comment]
Maybe we will create a canvas based minimap at some point but that is not for sure. If so I could imagine that we would add an option to show edges too. At this point we won't add such an option. The only way for you to show edges is to create your own minimap component. For that you could take the existing one as a starter and edges by yourself.
