### ISSUE TITLE
Set default toggle interactivity

### ISSUE THREAD

**Issue by Abhishek21k** [xyflow/xyflow#4759]
### Please describe the feature that you want to propose

- i want to set the default interacity button as true , but there is no option available for this.

![image](https://github.com/user-attachments/assets/f4aac464-30e8-4a0b-acdf-8505988bf0c0)

this toogle button to be enabled as default

**Comment by peterkogo** [comment]
If I understand you correctly, you want the interactivity to be disabled by default?

The interactivity is simply derived from 3 props on the React Flow Component. `nodesDraggable`, `nodesConnectable`, `elementsSelectable`. If you set those to false, interactivity is disabled from the start.

**Comment by chrtze** [comment]
> The interactivity is simply derived from 3 props on the React Flow Component. `nodesDraggable`, `nodesConnectable`, `elementsSelectable`. If you set those to false, interactivity is disabled from the start.

You can find a codesandbox [here](https://codesandbox.io/p/sandbox/xenodochial-nash-7kpzwh?file=/src/App.tsx:36,1-39,1).
