### ISSUE TITLE
Edges and Nodes misaligns after increasing the node height in auto-layout example

### ISSUE THREAD

**Issue by imsupercode** [xyflow/xyflow#4762]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.2.1
- Browser and version: Chrome
- OS and version: MacOS

### Describe the Bug

I'm a Pro user,  have tried the auto-layouting example from react-flow site with few changes. I need to increase the height of each node on demand but when I do that the edges and nodes are not aligned properly in the graph. I have tried with `dagre` and `d3-hierarchy` algorithms. 

Also when I try to add a Node using `+` button all nodes flicker before adding a new node to graph.

### Steps to reproduce the bug or issue

1. Click the `^` button.
2. Height of the node will increase
3. Edges will be misaligned

### Expected behavior

Expected behaviour: when I increase the height of the node it should start growing downwards.
Current behaviour: It moves the node up and changes the edges and nodes position.

### Screenshots or Videos

https://github.com/user-attachments/assets/ac22ee07-8b0a-4915-903d-e7779d1d001c

### Additional context

I can share the modified auto-layout-example either via mail or a private github repository.

**Comment by chrtze** [comment]
This is intentional. We offset the nodes by half of the width and height so that they are centered. If you want to disable this, you can change the following:

```ts
    const position = {
      x: x - (node.measured?.width ?? 0) / 2,
      y: y - (node.measured?.height ?? 0) / 2,
    };
```

to:

```ts
    const position = {
      x: x - (node.measured?.width ?? 0) / 2,
      y,
    };
```

**Comment by imsupercode** [comment]
But after making that change the node is overlapping with the bottom node, Could you please help me with that?

https://github.com/user-attachments/assets/b1794f24-64aa-4ae0-870f-b65fb04760c4
