### ISSUE TITLE
Constrain the scrollable area to the dimensions of the flow container

### ISSUE THREAD

**Issue by bsvetlik** [xyflow/xyflow#4763]
### Please describe the feature that you want to propose

I'd like to propose introducing a new property called scrollMode to achieve the same behavior as GoJS's scroll modes (example: https://gojs.net/latest/samples/scrollModes.html)

While I previously explored using the "translateExtent" property (referring to issue #4753), it didn't achieve the desired outcome. Implementing a dedicated scrollMode property would provide a more intuitive and user-friendly solution.

**Comment by zhugexiaogou666** [comment]
> bsvetlik

https://github.com/user-attachments/assets/13fc105a-9a64-4dda-9d91-4ff02b87e171



Do you want this effect? ​​If so, I can give you some ideas. I have encountered similar problems recently and have thought of some solutions.

**Comment by peterkogo** [comment]
Let's continue the discussion over at #4784. 
I would like to close this issue because we would rather not add a new prop similar to `scrollModes` in gojs. A more flexible solution would be great, where this is easily achievable by using `getNodesBounds(nodes)` to restrict the viewport.
