### ISSUE TITLE
multi call updateEdge not working

### ISSUE THREAD

**Issue by zhenghan2017** [xyflow/xyflow#4774]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.3.4
- Browser and version: Chorme 130.0.6723.70
- OS and version: macOS Sonoma 14.0

### Describe the Bug

When I call `updateEdge` in loop，only the first update is active.

like below code
```
for (const edgeUpdate of edgeUpdates) {
  updateEdge(edgeId, edgeUpdate);
}
```

### Steps to reproduce the bug or issue

I read  `useQuene` and find the code 

```
useIsomorphicLayoutEffect(() => {
    // Because we need to flip the state back to false after flushing, this should
    // trigger the hook again (!). If the hook is being run again we know that any
    // updates should have been processed by now and we can safely clear the queue
    // and bail early.
    if (!shouldFlush) {
      queue.reset();
      return;
    }

    const queueItems = queue.get();

    if (queueItems.length) {
      runQueue(queueItems);

      queue.reset();
    }

    // Because we're using reactive state to trigger this effect, we need to flip
    // it back to false.
    setShouldFlush(false);
  }, [shouldFlush]);
```

If push `updateEdge` Faster thanReact state update，the quene will be reset。

### Expected behavior

updateEdge can active all

**Comment by peterkogo** [comment]
Please create a minimal reproduction for this at [new.reactflow.dev/ts](https://new.reactflow.dev/ts).

**Comment by zhenghan2017** [comment]
I see the fixed, it's also good for me. thanks
