### ISSUE TITLE
Node dragging test fail when run on Redux example

### ISSUE THREAD

**Issue by chr11115** [xyflow/xyflow#4775]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.3.4
- Browser and version: playwright chromium latest (npm: 1.48.2)
- OS and version: Windows 10/11

### Describe the Bug

It's not possible to drag nodes with playwright since xyFlow/react v12 when using redux as a state manager.

### Steps to reproduce the bug or issue

1. Setup xyFlow/react playwright tests locally (from source)
2. Modify the "dragging" test to run on the redux example
"dragging test":
https://github.com/xyflow/xyflow/blob/97fdff59d40071aee0b3192f7b571c6bdd4d09fd/tests/playwright/e2e/nodes.spec.ts#L61
"redux example":
https://github.com/xyflow/xyflow/tree/main/examples/react/src/examples/Redux
Or online:
https://reactflow.dev/learn/advanced-use/state-management
3. Run test
4. Test fails ❌ (note that it passes on the original example if redux isn't involved)

### Expected behavior

Test should pass.

### Additional context

We use reactflow and test our application with playwright. Since upgrading to v12 moving nodes around in playwright doesn't properly work anymore.

It seems that modifying "steps" in the playwright "page.mouse.move(x,y,{steps:stepcount})" test code to a higher count will actually execute all steps until n - 1. This means in actual use this usually goes unnoticed, but still seems like a bug to me.

One workaround is to move the cursor 2x the distance and set steps to 2, since this will only execute the first step, but this doesn't sound like it should be the solution.

**Comment by peterkogo** [comment]
@chr11115 I tried replace the test with the redux version and it works for me. You can check it [out in this branch](https://github.com/xyflow/xyflow/tree/investigate/redux-tests). 

> One workaround is to move the cursor 2x the distance and set steps to 2, since this will only execute the first step, but this doesn't sound like it should be the solution.

This does not sound to far off. We set the `nodeDragThreshold` to 1 for the playwright tests. The default `nodeDragThreshold` changed in v12 which influences how much a node has to be moved until it is registered as a drag vs. a click.

**Comment by chr11115** [comment]
Ah cool thank you! So the main difference was that your Redux example just like our code did not change nodeDragThreshold back to 0 causing these tests to fail..
The behavior is still somewhat un-intuitive, but that explains it.
Thank you for looking into it!

**Comment by peterkogo** [comment]
> The behavior is still somewhat un-intuitive

It should have been the default from the get-go. A `nodeDragThreshold` of 1 delays dragging to commence until the node has been moved by 1 pixel, which is the standard for most dragging behaviors. 

Happy to hear you resolved the issue.
