### ISSUE TITLE
remove the default delete function

### ISSUE THREAD

**Issue by zhugexiaogou666** [xyflow/xyflow#4780]
### Please describe the feature that you want to propose

I want to remove the default delete function and replace it with a custom function. It seems that there is no API that can prevent the default delete event.

**Comment by bcakmakoglu** [comment]
If you're talking about the Backspace key to delete, you can disable it by setting `<ReactFlow deleteKeyCode={null} ...>`.

**Comment by zhugexiaogou666** [comment]
> If you're talking about the Backspace key to delete, you can disable it by setting `<ReactFlow deleteKeyCode={null} ...>`.如果您谈论的是要删除的 Backspace 键，您可以通过设置 `<ReactFlow deleteKeyCode={null} ...>` 来禁用它。

Thank you！I solved it
