### ISSUE TITLE
`getIntersectingNodes` does not work for nodes with a depth of 2 or more

### ISSUE THREAD

**Issue by frouene** [xyflow/xyflow#4781]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.2.1
- Browser and version: -
- OS and version: -

### Live code example

https://codesandbox.io/p/devbox/musing-microservice-sfcpd5

### Describe the Bug

With 3 nested nodes, when moving the highest-level one, the result of `getIntersectingNodes` is not correct (if the position of the nodes is different from (0,0)).
I think the problem comes from [evaluateAbsolutePosition](https://github.com/xyflow/xyflow/blob/main/packages/system/src/utils/general.ts#L248), where we shouldn't be summing up the `positionAbsolute` of all the parents, but rather the `position`

### Steps to reproduce the bug or issue

1. Create 3 nested nodes
2. Try to use `getIntersectingNodes` on the last child
3. The result is not correct

### Expected behavior

`getIntersectingNodes` should evaluate intersecting nodes correctly, whatever the depth of the nodes

### Screenshots or Videos

![getIntersectingNodes](https://github.com/user-attachments/assets/cdd37613-6392-49a1-a0b9-266d81e579ec)

**Comment by peterkogo** [comment]
Thanks so much for reporting this! Fixed in #4782 and will land in next release.

**Comment by peterkogo** [comment]
This is fixed in the newest release 12.3.5.
