### ISSUE TITLE
 Wrong connection line style

### ISSUE THREAD

**Issue by zhugexiaogou666** [xyflow/xyflow#4785]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version:  "^12.3.1"
- Browser and version: google
- OS and version: mac pro

### Describe the Bug

I want to intercept the control of the node size by the onNodesChange method, because I use a custom method to achieve it, but when I do this, the style of the connecting line will be wrong

### Steps to reproduce the bug or issue

1.	onNodesChange={onNewNodeChange}
2. 	const onNewNodeChange = useCallback(
		(changer: NodeChange<FlowNode>[]) => {
			if (changer[0].type !== 'dimensions') {
			onNodesChange(changer);
			}
		},
		[nodes],
	);

### Expected behavior

Correct display of connection lines

### Screenshots or Videos

https://github.com/user-attachments/assets/4ce81b58-39cc-42f4-a6da-e0a2dc8cd97b

**Comment by bcakmakoglu** [comment]
You can't "skip" applying dimension changes.
Without proper measurements of a node (which are stored as `node.measured.width/height`) calculations will not work properly.
So the change handler you're using above is not a valid change handler.

If you wanna change the size of a node you can always use `node.width` or `node.height` and assign a different size to it but simply omitting the change handler for it is not gonna work.

**Comment by zhugexiaogou666** [comment]
> You can't "skip" applying dimension changes.您不能 “跳过” 应用维度更改。 Without proper measurements of a node (which are stored as `node.measured.width/height`) calculations will not work properly.如果没有对节点进行适当的测量（存储为 `node.measured.width/height`），计算将无法正常工作。 So the change handler you're using above is not a valid change handler.因此，您在上面使用的 change 处理程序不是有效的 change 处理程序。
> 
> If you wanna change the size of a node you can always use `node.width` or `node.height` and assign a different size to it but simply omitting the change handler for it is not gonna work.如果你想改变一个节点的大小，你总是可以使用 `node.width` 或 `node.height` 并为其分配不同的大小，但简单地省略它的更改处理程序是行不通的。


I use it because when I enable: "dimensions", when I change the width of a node, an error pops up
![image](https://github.com/user-attachments/assets/d1792a95-8dca-4fe2-9740-0f99c8dfade3)

**Comment by bcakmakoglu** [comment]
You're probably doing something wrong then and using that as a workaround for the underlying issue isn't a solution 😄 
Can you provide a minimal reproduction of your problem? [You can find a template here](https://new.reactflow.dev/react-ts)

**Comment by peterkogo** [comment]
Is it possible you are trying to mutate the node objects directly? That won't work, they are immutable. Try destructuring it. 
```js 
node.width = 20; // Cannot assign to readonly property...
node = { ...node, width: 20 } // typescript happy
```

**Comment by zhugexiaogou666** [comment]
> Is it possible you are trying to mutate the node objects directly? That won't work, they are immutable. Try destructuring it.
> 
> ```js
> node.width = 20; // Cannot assign to readonly property...
> node = { ...node, width: 20 } // typescript happy
> ```

thank u ,I found the reason, I used immer intermediate keys in my state management library zustand, and his internal comparison method changed the properties incorrectly, I modified the method, and now it runs correctly

**Comment by zhugexiaogou666** [comment]
> You're probably doing something wrong then and using that as a workaround for the underlying issue isn't a solution 😄 Can you provide a minimal reproduction of your problem? [You can find a template here](https://new.reactflow.dev/react-ts)

I found the reason, I used immer intermediate keys in my state management library zustand, and his internal comparison method changed the properties incorrectly, I modified the method, and now it runs correctly
