### ISSUE TITLE
Scrolling while dragging nodes causes the node to jump (#3197 duplicate)

### ISSUE THREAD

**Issue by MiiZZo** [xyflow/xyflow#4786]
### What platform were you using when you found the bug?

- React Flow version: 11.11.4
- Browser and version: Chrome, 130.0.6723.92
- OS and version: Win10 22H2

### Live code example

https://stackblitz.com/edit/vitejs-vite-cserbh?file=src%2FApp.tsx

### Describe the Bug

https://github.com/user-attachments/assets/28c6ecd6-d211-4cad-8f1a-42ac1c7618ba

### Steps to reproduce the bug or issue

1. Open the example in stackblitz
2. Select a node
3. Start scrolling the canvas

### Expected behavior

node doesn't move when scrolling

**Comment by peterkogo** [comment]
Interesting. This only seems to happen when the flow is less than 100% of the height. Definitely a bug! Thanks for reporting.


related to #3197

**Comment by peterkogo** [comment]
This is fixed in the newest release 12.3.5.
