### ISSUE TITLE
I hope to get a callback when dragging edges

### ISSUE THREAD

**Issue by zhugexiaogou666** [xyflow/xyflow#4794]
I hope to get a callback when dragging edges, similar to onNodesDrag, because in some cases I want my edges style to change based on the mouse position.

**Comment by bcakmakoglu** [comment]
What do you mean "dragging" edges? Edges aren't draggable like nodes.
If you're talking about *connection lines* (lines that are drawn to connect nodes, which *result* in edges) you can customize those with a custom component - [see this example.](https://reactflow.dev/examples/edges/custom-connectionline)

[Or you can use some props.](https://reactflow.dev/api-reference/react-flow#connection-line-props)

**Comment by zhugexiaogou666** [comment]
> What do you mean "dragging" edges? Edges aren't draggable like nodes.“拖拽”边缘是什么意思？边不像节点那样是可拖动的。 If you're talking about _connection lines_ (lines that are drawn to connect nodes, which _result_ in edges) you can customize those with a custom component - [see this example.](https://reactflow.dev/examples/edges/custom-connectionline)如果你谈论_的是连接线_（绘制以连接节点的线，_会产生_边），你可以使用自定义组件自定义它们 - [请参阅此示例。](https://reactflow.dev/examples/edges/custom-connectionline)
> 
> [Or you can use some props.或者你可以使用一些 props。](https://reactflow.dev/api-reference/react-flow#connection-line-props)

https://github.com/user-attachments/assets/a73d46a9-aea1-4cf1-8f5e-197d31cc23a9



I want to be able to get the position of my mouse and the information about edges when connecting. For example, I want to change the color of the connection line when my mouse enters a certain area of ​​the flow.

**Comment by bcakmakoglu** [comment]
There are events you can listen for: https://reactflow.dev/api-reference/react-flow#connection-events

You can use the mouse events that are passed to you and translate them to viewport coordinates using [`screenToFlowPosition`](https://reactflow.dev/api-reference/types/react-flow-instance#screen-to-flow-position) and check if it intersects with the area you are looking for or not.

**Comment by zhugexiaogou666** [comment]
I found onConnectStart and onConnectEnd，

> There are events you can listen for: https://reactflow.dev/api-reference/react-flow#connection-events您可以监听以下事件：https://reactflow.dev/api-reference/react-flow#connection-events
> 
> You can use the mouse events that are passed to you and translate them to viewport coordinates using [`screenToFlowPosition`](https://reactflow.dev/api-reference/types/react-flow-instance#screen-to-flow-position) and check if it intersects with the area you are looking for or not.


Thank you, I'll give it a try, which means I need to monitor the mouse position and then perform the operations I want. Currently, there is no way to get the event like OnNodesDrag when connecting.Because I only found onConnectStart and onConnectEnd, I didn’t see the methods in the connect process.

**Comment by bcakmakoglu** [comment]
If you know that a connection *starts* and you know when it *ends* you can assume that after it starts and before it ends you can track the position of your mouse, for example using `document.addEventListener('mousemove', listener)` (and remove it when the connection *ends*) and check if the mouse is in the area you're looking for.

You don't need any additional events whatsoever to achieve this.

**Comment by peterkogo** [comment]
You can access all the information of the current connection via the [`useConnection](https://reactflow.dev/api-reference/hooks/use-connection)` hook. 

If you want to do much more advanced things I really suggest you create a custom ConnectionLine as bcakmakoglu suggested. You only have to invoke `useConnection` once, you draw the line and anything else you'd like to do in a single component.

**Comment by peterkogo** [comment]
@zhugexiaogou666 can you please ask these kinds of questions in our [Discord](https://discord.gg/RVmnytFmGW)? There are more people there to help you and Github Issues are first and foremost for Bug Reports & Feature Requests.

**Comment by AmyShieh** [comment]
> @zhugexiaogou666 can you please ask these kinds of questions in our [Discord](https://discord.gg/RVmnytFmGW)? There are more people there to help you and Github Issues are first and foremost for Bug Reports & Feature Requests.

could please re-send the invitation? it's expired

**Comment by bcakmakoglu** [comment]
@AmyShieh [Here you go.](https://discord.gg/QUCsW4GN)
