### ISSUE TITLE
When dragged to the boundary, setting the position doesn't take effect.

### ISSUE THREAD

**Issue by asurance** [xyflow/xyflow#4795]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.0.4
- Browser and version: Chrome  130.0.6723.93
- OS and version: Mac 

### Live code example

https://codesandbox.io/p/sandbox/zen-dawn-5kwrxc?file=%2Fsrc%2FApp.tsx%3A44%2C47

### Describe the Bug

I hope to be able to limit the axes of dragging by manually setting position in `onNodeDrag`, however it seems doesn't take effect when dragging to the boundary of ReactFlow

### Steps to reproduce the bug or issue

drag node to the boundary

### Expected behavior

setting position takes effect

### Screenshots or Videos

![20241108-122137](https://github.com/user-attachments/assets/4fbff0ae-ab56-480f-8899-89665c37db11)

**Comment by peterkogo** [comment]
There are a couple of things wrong here.

onNodeDrag only happens at the end of the drag loop. Mutating values inside nodes does not work. Nodes are immutable, use setNodes.

This is what the `onNodesChange` handler is for. You receive changes that you can modify, discard or you might even want to do something completely different. We have a section in the docs that discusses [handling change events](https://reactflow.dev/learn/getting-started/adding-interactivity#handle-change-events).

**Comment by asurance** [comment]
Thank you very much, it seems to be OK.
