### ISSUE TITLE
Listen document‘s events to trigger outside-clicks not work

### ISSUE THREAD

**Issue by AIEPhoenix** [xyflow/xyflow#4804]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Describe the Bug

A component library that listens to document events to trigger outside clicks, such as the Select component in Mantine, cannot close the dropdown by clicking on empty space
If add nopan classname to body can fix that but reactflow cannot pan.

### Steps to reproduce the bug or issue

Custom Node add any Mantine Combobox base Component, like Select or Popover

### Expected behavior

click blank area any dropdown can dismiss

**Comment by peterkogo** [comment]
@AIEPhoenix You need to provide a reproduction of this. [new.reactflow.dev/ts](https://new.reactflow.dev/ts)

**Comment by AIEPhoenix** [comment]
> @AIEPhoenix You need to provide a reproduction of this. [new.reactflow.dev/ts](https://new.reactflow.dev/ts)

Hi, https://codesandbox.io/p/sandbox/trusting-meadow-q5xlgp
This is a reproduction demo. You can see that when the select is expanded, clicking around and on the node cannot successfully make the dropdown disappear.
I found this, https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/hooks/src/use-click-outside/use-click-outside.ts
It looks like most of the mantine's component uses this hook for this type of ability.

**Comment by moklick** [comment]
The easiest way to work around this would be to set `panOnDrag={false}` when a `Select` component is open. We are using d3-zoom for handling panning and zooming. You need to disable it if you want to let Mantine catch the click event. Does this work for you?

**Comment by AIEPhoenix** [comment]
@moklick Yes, thank you for your help~
