### ISSUE TITLE
onNodeMouseEnter and onNodeMouseLeave Stop Working After Clicking on the Canvas

### ISSUE THREAD

**Issue by itsatan** [xyflow/xyflow#4808]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: "@xyflow/react": "^12.3.4",
- Browser and version: Chrome 130.0.6723.117
- OS and version:Mac

### Describe the Bug

I am encountering an issue with the onNodeMouseEnter and onNodeMouseLeave event handlers. When the page initially loads, these handlers work as expected. However, after clicking anywhere on the canvas, these event handlers no longer trigger.

### Steps to reproduce the bug or issue

1. Load the page.
2. Hover over a node — the onNodeMouseEnter and onNodeMouseLeave callbacks are triggered correctly.
3. Click anywhere on the canvas.
4. Try hovering over a node again — the callbacks are no longer triggered.

### Expected behavior

The onNodeMouseEnter and onNodeMouseLeave event handlers should continue to work even after interacting with the canvas.

### Additional context

What could be causing this behavior? Are there any known issues or workarounds for ensuring that these event handlers continue to work after interacting with the canvas?

Thank you in advance for your help!

**Comment by bcakmakoglu** [comment]
Can you provide a reproduction for this?
[Seems to work fine for me in a sandbox.](https://codesandbox.io/p/sandbox/cranky-pare-ymjxmg?file=%2Fsrc%2FApp.tsx%3A40%2C9)

**Comment by itsatan** [comment]
@bcakmakoglu Friend, thank you for your reply. I'm sorry, but I don't know how to use the sandbox. Following the instructions you provided, I found that the print action only occurs when clicking on a node. Moving the mouse over or out of a node does not trigger the print action.
I need an effect similar to hover, which is triggered both when entering and leaving.

**Comment by bcakmakoglu** [comment]
It works for me without clicking a node whatsoever.
I even dragged the viewport to make sure that no node is selected when I hover with the cursor.

https://github.com/user-attachments/assets/430aa3c7-abf0-4091-8aa4-631884cfc244

**Comment by itsatan** [comment]
@bcakmakoglu "Yes, I saw your video, and this is the behavior I expected. I copied your code entirely to my computer and ran it, but it still didn’t work. I might be facing some strange issue... It seems to only affect me. Anyway, thank you for your response. I may need to find the cause on my own."

**Comment by itsatan** [comment]
@bcakmakoglu "I found the reason. It's an issue with my secondary monitor. On my laptop, it works fine and triggers as expected, but when using an external monitor, for some reason, it doesn't display the latest output."

**Comment by peterkogo** [comment]
@itsatan what do you mean by "display the latest output"?

**Comment by itsatan** [comment]
@peterkogo 
The latest callback functions for onNodeMouseEnter and onNodeMouseLeave are being triggered, but it might be an issue with my computer. I'm not sure, but after switching to another monitor, it works fine now.
