### ISSUE TITLE
Question Regarding the Removal of className Prop from Handle Component

### ISSUE THREAD

**Issue by wsebapple** [xyflow/xyflow#4811]
### Please describe the feature that you want to propose

Hello team,

Thank you for all the great work on this project – it's been incredibly helpful and I truly appreciate the effort that goes into it.

I'm reaching out to understand why the className prop was removed from the handle component. I noticed this change, and I'd like to learn more about the reasoning behind it, as it impacts some of my use cases.

Thank you very much for your help!

Best regards,

P.S : https://v10.reactflow.dev/docs/api/nodes/handle/

**Comment by bcakmakoglu** [comment]
The handle component still accepts a classname prop (even though in the v11 docs it is missing from the list) in both v11 and v12.
