### ISSUE TITLE
getNodes() only updated when onNodesChange triggered/nodes are moved in memoized node

### ISSUE THREAD

**Issue by TrySpace** [xyflow/xyflow#4819]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version:   "@xyflow/react": "^12.3.5",

### Live code example

[Code Sandbox](https://codesandbox.io/p/sandbox/green-lake-wsjl8w)

### Describe the Bug

I have an issue when using and passing this to ReactFlow: 

```ts
 const [nodes, setNodes, onNodesChange] = useNodesState<Node<NodeData>>(
    initialNodes || []
  )
  const [edges, setEdges, onEdgesChange] = useEdgesState<Edge<EdgeData>>(
    initialEdges || []
  )
```

Everything works as expected, but when i use `const { setNodes } = useReactFlow()` somewhere in a child, then some states only update when I drag around a node; I assume triggering `onNodesChange `

### Steps to reproduce the bug or issue

See this example:
```tsx
const DetachDescendantsButton: React.FC<{
  id: string
}> = ({ id }) => {
  const { getNodes, setNodes } = useReactFlow()
  const nodes = getNodes()

  const updateNodeInternals = useUpdateNodeInternals()
  const removeParentIdFromMultipleNodes = useCallback(
    (parentIdToRemove: string) => {
      setNodes((nodes) => {
        const parentNode = nodes.find((n) => n.id === parentIdToRemove)

        return nodes.map((node) => {
          if (node.parentId === parentIdToRemove) {
            return getNodeDataWithoutParentId(node, parentNode)
          }
          return node
        })
      })

      updateNodeInternals(id)
    },
    [setNodes]
  )

  const hasDescendants = useCallback(
    (nodeId: string) => {
      return nodes.some((node) => node.parentId === nodeId)
    },
    [nodes, getNodes]
  )

  return (
    hasDescendants(id) && (
      <Tooltip title="Detach all descendants">
        <IconButton
          size="small"
          onClick={(e) => {
            removeParentIdFromMultipleNodes(id)
          }}
        >
          <Icon>clear</Icon>
        </IconButton>
      </Tooltip>
    )
  )
}
```

This button, and its hasDescendants() will only update when I move around the node where the button is in (in this case in the special Toolbar component), (or when unmounting and rerendering the toolbar/button)

I initially thought it was the lack of `updateNodeInternals()` that I needed to trigger after doing setNodes(), but this doesn't help.

### Expected behavior

I expected the `const nodes = getNodes()` to trigger an update whenever the nodes are changed.

But perhaps this was designed this way?
The docs have too many disparate and confusingly different ways to handle state and I'm not sure anymore which one would be the correct method.

### Additional context

I could only reproduce it until I memoized the PositionLoggerNode: https://codesandbox.io/p/sandbox/green-lake-wsjl8w

So it seems that an update from `getNodes()` only gets triggered when the node data changes (also when another node changes), and in a un-memoized node, it also re-renders when ... idk actually why...

So anyone have a better way to make this work while still using memoized  nodes? Or is this a bug?

**Comment by TrySpace** [comment]
I have the same issue now when I try to use `getInternalNode(id)`, and it will only have the latest state when I change something on the canvas like dragging a node.

this is solved by removing the `memo()` wrapper again.

Is this the intended behavior?

**Comment by TrySpace** [comment]
Additional explanation:

The state of a memoized Node will be behind one step, until a "global" change has triggered (e.g. you move a node). 
This doesn't occur when the node is not memoized, then the internal node state (i.e. the props) match the latest state .

So in short, when I do a `setNodes` somewhere in a Node's children, neither `getNodes`, or the Node's props are being triggered to update the component, IF it is wrapped in a `memo()`

**Comment by peterkogo** [comment]
As the name of those functions implies they are imperative and not hooks.
To actually trigger updates, you can just use the hooks `useNodes`, `useInternalNode`.
