### ISSUE TITLE
Edge render issue with a CustomEdge with a linearGradient stroke

### ISSUE THREAD

**Issue by TrySpace** [xyflow/xyflow#4822]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version:  "@xyflow/react": "12.3.5",
- Browser: Brave [Version 1.73.89 Chromium: 131.0.6778.69 (Official Build) (64-bit)]

### Live code example

https://codesandbox.io/p/sandbox/interesting-feather-9mhxq9

### Describe the Bug

Some of the edges don't render initially or after rearranging nodes the nodes via a dagre function. The edges data is correct, the rendering is not. Some edges render, other edges only render after dragging a node that the edge is attached to.

### Steps to reproduce the bug or issue

Reproduction: https://codesandbox.io/p/sandbox/interesting-feather-9mhxq9

I have this button on the topleft to change the layout with dagre, to continually recreate the issue. 

Some of the Edges in between don't get rendered, until you move around a node. This only happens when the edges have a gradient stroke stroke `url(#gradient-${id})` set and: 

```tsx
<linearGradient id={`gradient-${id}`} x1="0%" y1="0%" x2="100%" y2="0%">
      <stop
       offset="0%"
       style={{ stopColor: primaryColor, stopOpacity: 1 }}
     />
     <stop
       offset="100%"
        style={{ stopColor: secondaryColor, stopOpacity: 1 }}
      />
</linearGradient>
```

### Expected behavior

The initial render, or after rearrangement, to consistently render all gradient edges. Only the first few edges are rendered.

**Comment by XilinZhu** [comment]
+1. I met the same issue.

**Comment by TrySpace** [comment]
@peterkogo You're probably right, it's more likely an svg or browser renderer issue. I'll close it

**Comment by syed-danish-dev** [comment]
Any fix on this issue? i am facing the same issue with gradient edges. im trying to create dynamically gradient edges based on different nodes colors. some renders some dont. is it rendering issue? even though gradient is present in the dom but gradient not applied to the edge. 

<img width="1833" height="456" alt="Image" src="https://github.com/user-attachments/assets/051a6e5d-07ba-438e-9a1b-0824f2335c79" />
