### ISSUE TITLE
want specific styled type of Handle for Nodes

### ISSUE THREAD

**Issue by RanitManik** [xyflow/xyflow#4824]
## Reality
![image](https://github.com/user-attachments/assets/1b3dde1a-3bd3-457d-a0ef-5226e39cdd6c)

## Expectation
![image](https://github.com/user-attachments/assets/4b662f24-f120-45ce-bd4f-41073b4144f7)

### how can i make sure that my nodes have this specific type of handles?

_Originally posted by @RanitManik in https://github.com/xyflow/xyflow/discussions/4823_

**Comment by chrtze** [comment]
duplicate. please see: https://github.com/xyflow/xyflow/discussions/4823
