### ISSUE TITLE
Edge svg not loaded on DOM

### ISSUE THREAD

**Issue by acata8** [xyflow/xyflow#4825]
### What platform were you using when you found the bug?

- React Flow version: 12.3.5
- elkjs version:  0.9.3

### Describe the Bug

Hello, on drop of element the svg edge **sometimes** is not shown, but not loaded on the DOM.

The main problem is that this bug is random and does not always happen.
I’m also using elkjs for tree reformatting, but I don’t think it’s related to this. 

![image](https://github.com/user-attachments/assets/d0ea64d9-4c06-4567-a416-fe4d9f853049)

Those are my nodes: 
![image](https://github.com/user-attachments/assets/aa175600-42f9-4609-a5be-130a1c87f993)

And those are my edges:
![image](https://github.com/user-attachments/assets/6d03a6b3-9e86-4c3a-b259-6eeaccab7e15)

So nodes and edges are connected correctly.
If I remove the node and re-drop it on the panel, this edge is loaded correctly.  
It seems to be an edge rendering problem, but I can’t find the bug actually.

### Steps to reproduce the bug or issue

Just drag and drop courses from courses container. The error happens randomically.

I uploaded a video with the issue

### Expected behavior

![image](https://github.com/user-attachments/assets/fa2d0738-7729-48b0-b480-67ee5b19992e)

### Screenshots or Videos

[Bug.zip](https://github.com/user-attachments/files/17798174/Bug.zip)

### Additional context

[CODE SANDBOX](https://codesandbox.io/p/sandbox/distracted-rhodes-kjmzws)

**Comment by acata8** [comment]
PS: The bug appears when i migrate from v11 (reactflow) to v12 (xyflow/react). 
I tried to revert the version to v11 and everything works, but i need the v12 for some functionalities improvement

**Comment by chrtze** [comment]
could you create a codesandbox that reproduces the error? you can find a starter sandbox [here](https://new.reactflow.dev/react-ts).

**Comment by acata8** [comment]
Thank you. 
Yeah i have some constraint to validate inside the tree, as the prerequisites missing or not.
Can you explain better what do you want to suggest with treeNodes.length?

**Comment by bcakmakoglu** [comment]
I suggest that you remove the circular dependency you created in your effect and instead only run it when the number of nodes changes (node added/node removed).

**Comment by peterkogo** [comment]
Feel free to reopen this issue if you are still experiencing problems.
