### ISSUE TITLE
z-index not updating of edges while selecting the parent group node

### ISSUE THREAD

**Issue by RanitManik** [xyflow/xyflow#4831]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: `12.3.5`
- Browser and version: `131.0.6778.69/70`
- OS and version: `Ubuntu 24.04`

### Live code example

https://github.com/RanitManik/ReactFlow-prototype

### Describe the Bug

When I select my `customGroupNode`, the `customEdge` elements within the `customNode` components do not update their `z-index`. As a result, the edge appears beneath the group component, which decreases its visibility and makes it inaccessible for selection.

### Steps to reproduce the bug or issue

1. Go to [https://reactflow-pro.netlify.app/](https://reactflow-pro.netlify.app/).
2. Create a Stage Node.
3. Create minimum 2 process Nodes.
4. Connect them with edge.
5. Select the Stage Node by clicking on it.
6. Observe at the edge state before and after.

### Expected behavior

When a group (`stage`) nodes get selected the child(`process`) nodes update the z-index from 10 to 1000. But as for the `.react-flow__edgelabel-renderer` and `.react-flow__edges` the updation is not happening for some reason. I want it to be updating the `z-index` as it should. 

> [!NOTE]  
> I tried it to make the z-index a large number but that creates another issue. It made the edges always on top. so if i drag another something over the nodes the edges are still visible.

### Screenshots or Videos

[Screencast from 2024-11-19 19-32-29.webm](https://github.com/user-attachments/assets/e6f12fd3-d3ff-4e36-a7f8-2a3624eb0faa)

### Additional context

checkout the given website and the repo to find additional details about the behaviour. Thanks for your help.

**Comment by bcakmakoglu** [comment]
This isn't a bug. Edges don't auto z-index according to their group.

You can use the official [Discord](https://discord.gg/RVmnytFmGW) to ask questions like these and get responses since this one is a question that has been asked a couple of times already.

**Comment by RanitManik** [comment]
> This isn't a bug. Edges don't auto z-index according to their group.
> 
> You can use the official [Discord](https://discord.gg/RVmnytFmGW) to ask questions like these and get responses since this one is a question that has been asked a couple of times already.

Figured. Do you have any solutions for this. Isn't this a problem for this kind of situations where grouping is involved?

**Comment by RanitManik** [comment]
> This isn't a bug. Edges don't auto z-index according to their group.
> 
> You can use the official [Discord](https://discord.gg/RVmnytFmGW) to ask questions like these and get responses since this one is a question that has been asked a couple of times already.
> 
> One way to go about this would be to set z-indexes of nodes yourself For example
> 
> * Child Nodes z-index: 3
> * Parent Nodes z-index: 1
> * Edges z-index: 2
> 
> You can use `node.zIndex` to specify what index it should use (same for edges).
> 
> Be aware that [elevateNodesOnSelect](https://reactflow.dev/api-reference/react-flow#elevate-nodes-on-select) is true by default which will elevate a selected nodes z-index by 1000 so you might wanna disable that to make it work properly.

Ok let me try and catch up

**Comment by RanitManik** [comment]
`elevateNodesOnSelect={false}`
This solved my problem and fulfilled my requirement, as I don't have any issue with nodes not being on top when selected.

**Thanks for helping out**
