### ISSUE TITLE
Avoid edge overlap to a node

### ISSUE THREAD

**Issue by charlesnoqx** [xyflow/xyflow#4833]
### Please describe the feature that you want to propose

![Screenshot 2024-11-20 at 9 44 23 AM](https://github.com/user-attachments/assets/11d65fa6-dcd3-4779-8673-e8d4596c9e62)

Is it possible to move the edge connection split a bit to bottom near at the node to avoid overlapping edge and node

**Comment by moklick** [comment]
Unfortunately this is not possible with the current edge implementation. The only way to achieve this is to use an invisible ghost node right above the three nodes to fake the behaviour.

**Comment by awaisshah228** [comment]
This is solved by **[avoid-nodes-edge](https://www.npmjs.com/package/avoid-nodes-edge)** — edges automatically route around nodes and parallel edges are nudged apart so they never overlap.

**[Live Demo](https://avoid-nodes-pro-example.vercel.app)** | **[GitHub](https://github.com/awaisshah228/react-flow-avoid-nodes-routing)**

```bash
npm install avoid-nodes-edge libavoid-js
```

Works with React Flow v12+.

**Comment by tisoap** [comment]
I'm the creator of [react-flow-smart-edge](https://github.com/tisoap/react-flow-smart-edge) , a library that uses using A* pathfinding to route edges around other nodes, avoiding intersections. It has smart equivalents for every type of edge React Flow has. It's been updated to work with React Flow 12.
