### ISSUE TITLE
Editable Smooth-Step Edge in React Flow

### ISSUE THREAD

**Issue by Reshivam** [xyflow/xyflow#4836]
### Please describe the feature that you want to propose

**Description**
Add functionality to make Smooth-Step edges editable by allowing users to dynamically modify the edge's path. This enhancement would provide greater flexibility and control over edge shaping, enabling smoother customization of process flows and diagrams.

**Use Cases**

- Custom process diagrams where precise edge paths are needed to avoid overlapping nodes or other edges.
- Applications requiring enhanced aesthetics or clarity in edge visualization.
- Users creating complex workflows with dynamic node and edge configurations.

**Benefits**

- Provides users with a more intuitive and flexible way to design workflows.
- Reduces the need for custom code or external libraries for edge manipulation.
- Enhances the usability of React Flow for applications like mind maps, UML diagrams, and business process management tools.

**Sample**

![chrome-capture-2024-11-21](https://github.com/user-attachments/assets/133e2a1c-8a71-4d0e-8104-1039b04a41b5)

This feature would significantly improve the interactivity and customization capabilities of React Flow's smooth-step edge type.

**Note:** There should be some toggle behvaiour to either select whole edge or create control points to make edge editable.

**Comment by moklick** [comment]
I would love to see this :) We added editable edges for bezier types and we might add it for step edges too but it's not certain. 

We can continue the discussion here #1029

**Comment by NghiaDepTrai** [comment]
Do we have any solution for this?
