### ISSUE TITLE
Using `setNodes` in `onNodeDragStop` breaks default `dragging: false` state

### ISSUE THREAD

**Issue by TrySpace** [xyflow/xyflow#4839]
### What platform were you using when you found the bug?

See Sandbox ( xyflow: "12.3.5")

### Live code example

https://codesandbox.io/p/sandbox/magical-artem-n6frpw

### Describe the Bug

Passing the following onNodeDragStop to Reactflow, will break the `dragging` state and how selection is expected to work:

```ts
  const onNodeDragStop: OnNodeDrag<Node> = useCallback(
    (evt, dragNode: Node) => {
      // Update nodes here breaks the default behavior of setting the `dragging` state to false:
      setNodes(nodes.map((n) => ({ ...n, className: "" })));
    },
    [nodes]
  );
```

### Steps to reproduce the bug or issue

Uncomment either the `setNodes` or the `onNodeDragStop` line and the `dragging` state of the group node will get stuck on `true`.

Additionally this will have the side effect of when you try to select anything on the canvas (even nothing), it will automatically add all nodes that have `dragging: true` to the selection...

(You can select nodes and click the "group" button to make a new group)

### Expected behavior

I expect:
1. The internal dragging state to be consistent regardless of how you use `onNodeDragStop`
2. The `dragging` state to have no effect on which nodes get selected.

**Comment by bcakmakoglu** [comment]
Your sandbox is broken fyi.
<img width="697" alt="image" src="https://github.com/user-attachments/assets/574a92c0-f44e-4d63-9caf-d1a0d4e9492a">

**Comment by TrySpace** [comment]
@bcakmakoglu sorry, was editing it... ;p

**Comment by moklick** [comment]
I am not sure if I can reproduce it. What is the issue here? 

One thing you could change is to use `nodes` from `setNodes` instead of passing `nodes` as a dep to the `useCallback`:

```js
setNodes(nodes => nodes.map((n) => ({ ...n, className: "" })));
```

**Comment by TrySpace** [comment]
@moklick If you go to the [live code](https://codesandbox.io/p/sandbox/magical-artem-n6frpw) example I provided and try this:

![Cursor Gif Z](https://github.com/user-attachments/assets/3f77a904-101b-4e6e-b1e8-5a077091bbea)

You should have the same behavior

**Comment by TrySpace** [comment]
Even if I use the internal `nodes` for `setNodes` it still keeps `dragging: true` on the Node after dragging in the example. It seems to be the internal behavior of the shift+rectangle selection that is doing filtering in nodes with the `dragging` prop set to true, which in itself is weird unexpected behavior. 

So in my view there are 2 seperate issues that emerge from using a custom `onNodeDragStop` callback:
- dragging prop get stuck
- rectangle selection includes nodes with dragging prop for some unknown reason

**Comment by peterkogo** [comment]
You are basically overwriting the new nodes with an old reference to nodes. You should always use the nodes provided when passing a function to `setNodes`.

```ts
const onNodeDragStop: OnNodeDrag<Node> = useCallback(
    (evt, dragNode: Node) => {
      setNodes((nodes) => nodes.map((n) => ({ ...n, className: "" })));
    },
    []
);
```
