### ISSUE TITLE
Toggle interactive button on `<Control />`  breaks `nodesDraggable` setting on `<ReactFlow />`

### ISSUE THREAD

**Issue by bearguo** [xyflow/xyflow#4847]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version:  12.3.2
- Browser and version: Chrome 130.0.6723.59
- OS and version: MacOs 14.2 (23C64)

### Live code example

https://codesandbox.io/p/devbox/crimson-glitter-ws7vcy

### Describe the Bug

Nodes are able to be dragged when `nodesDraggable` is set false

### Steps to reproduce the bug or issue

1.  Toggle interactive button on `Control` Component to disable interactive
2. Toggle again to set able interactive
3. try to drag nodes
4. See error: nodes can be dragged event the `nodesDraggable` is false

### Expected behavior

Nodes can't be dragged when `nodesDraggable` is set false

### Screenshots or Videos

https://github.com/user-attachments/assets/8e75f198-9ac7-473c-9b56-a4d3c29d459d

**Comment by moklick** [comment]
This is not a bug but expected behaviour. When you set `nodesDraggable` explicitly, it outweighs the controls.

**Comment by bcakmakoglu** [comment]
@moklick Isn't the issue in this report that `nodesDraggable` *doesn't* outweigh controls though? 
That's how I understood it 🤔

**Comment by bearguo** [comment]
> @moklick Isn't the issue in this report that `nodesDraggable` _doesn't_ outweigh controls though? That's how I understood it 🤔
exactly
