### ISSUE TITLE
impossible to correctly type edge pathOptions in typescript

### ISSUE THREAD

**Issue by pseidemann** [xyflow/xyflow#4849]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.3.5
- Browser and version: Vivaldi latest
- OS and version: macOS 14.7

### Describe the Bug

when specifying `pathOptions` for any of the non-straight edge types, typescript complains about that the property is not existing.

however, the property itself is working.

```ts
const someEdge: Edge<{ foo: string }, 'smoothstep'> = {
  type: 'smoothstep',
  pathOptions: {  // error here
    borderRadius: 10,
  },
  data: {
    foo: 'bar',
  },
};
```

error:

Object literal may only specify known properties, and 'pathOptions' does not exist in type 'Edge<{ foo: string; }, "smoothstep">'.

I couldn't find any exported type which fixes this issue.

### Steps to reproduce the bug or issue

use code snippet above

### Expected behavior

no error for `pathOptions` from typescript

**Comment by peterkogo** [comment]
You have to use the `BuiltInEdge` type in this situation. Take a look in our [typescript guide](https://reactflow.dev/learn/advanced-use/typescript#node-and-edge-type-unions).

However, if you are planning to add data to edges (and use it inside the edge) anyway, I suggest you use custom edges for this.

**Comment by pseidemann** [comment]
@peterkogo,

I want to use the built-in edges but with custom data. it seems like this is not possible since the BuiltInEdge is not generic. with nodes this seems possible.

**Comment by peterkogo** [comment]
@pseidemann Then you need to extend the type of the built-in edges yourself. You can just create a new type union with the BuiltInEdges type for that. Typescript should not complain when the data property is extended.

**Comment by pseidemann** [comment]
@peterkogo,

thanks, this worked for me:

```ts
const someEdge: Edge<{ foo: string }, 'smoothstep'> & BuiltInEdge = {
  id: 'foo',
  source: 'foo',
  target: 'foo',
  type: 'smoothstep',
  pathOptions: {  // no error here
    borderRadius: 10,
  },
  data: {
    foo: 'bar',
  },
};
```
(~union~ intersection with `BuiltInEdge` needed)
