### ISSUE TITLE
NodePositionChange position coords Nan

### ISSUE THREAD

**Issue by lucapaolelli** [xyflow/xyflow#4852]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.3.5
- Browser and version: Chrome 131
- OS and version: macOS 15

### Describe the Bug

Sometimes the following change object appear. This bug was not here in v11.
`
{
    dragging: true,
    id: <nodeID>,
    position: {
        x: NaN, 
        y: NaN
    },
    type: "position"
}
`

### Steps to reproduce the bug or issue

drag a node with mouse

### Expected behavior

position coords must be valid coords

**Comment by peterkogo** [comment]
Can you please create a reproduction for this issue? [https://new.reactflow.dev/ts](https://new.reactflow.dev/ts)

**Comment by lucapaolelli** [comment]
I just attached onNodesChange prop on Reactflow component with a callback function, and print the position change event. Also nodes and edges are passed as props and managed as state by the component that wraps reactflow.

The problem appeared migrating from reacflow v11 to xyflow/react v12. I notice it in the browser console giving errors about nan values for svg on the minimap.

I'm working on my company's project so I cannot give deep details, but I'm rendering about 100 nodes and many edges. May the problem be related to the amount of rendered nodes, so lib not able to calculate the coords in time between two mouse movements?

**Comment by bcakmakoglu** [comment]
Are you sure that you read the [migration guide for v12 thoroughly](https://reactflow.dev/learn/troubleshooting/migrate-to-v12)?

Are you possibly mutating node objects somewhere (like in your store) and breaking them with that?
<img width="885" alt="image" src="https://github.com/user-attachments/assets/60ec7840-fe85-4edf-9828-e39d4e1c6e5d">

My assumption is that your code has some issue and nothing internal is going wrong since this problem has never happened to when I used RF in a project or a sandbox.

Hence why a *minimal* reproduction of the issue is essential, otherwise it's almost impossible to debug your problem properly and it's just guessing.

**Comment by lucapaolelli** [comment]
Let's add a snippet from my project

`
... from useReducer() reducer

        const activeTree = _getActiveTree(state);
        const activeSelection = state.selections.find(s => s.id == activeTree.selection);

        // change: { id, type, position?, dragging }
        const change = action.payload;

        // FIX: a @xyflow/react v12.x.x bug?
        if (!change.position)
            return state;
        if (isNaN(change.position.x) || isNaN(change.position.y)) {
            console.log("Got Nan coordinates!", change);
            return state;
        }

        // 1. obtain selected nodes

        if (activeSelection.elements.length == 0)
        {
            console.error("Almost one node must be selected during dragging!");
            return state;
        }

        const selectedNodes = state.nodes.filter(n => activeSelection.elements.some(s => s.id == n.id));
        const otherNodes = state.nodes.filter(n => !activeSelection.elements.some(s => s.id == n.id));

        // 2. calculate delta x and y

        const headNode = selectedNodes.find(n => n.id == change.id);
        if (!headNode)
        {
            // console.log("Not dragging a selected/head node");
            return state;
        }

        const diffX = change.position.x - headNode.position.x;
        const diffY = change.position.y - headNode.position.y;

        // 3. apply delta to all selected nodes

        for (var s = 0; s < selectedNodes.length; s++)
        {
            const newX = selectedNodes[s].position.x + diffX;
            const newY = selectedNodes[s].position.y + diffY;
            selectedNodes[s] = {...selectedNodes[s], position: {x: newX, y: newY}}
        }

        // 4. return new state and elevate selected nodes

        return { 
            ...state, 
            nodes: [ ...otherNodes, ...selectedNodes ]
        };
`
I also start to notice that sometimes node linked edges disappear from the graph and from the DOM and I think this is related but I don't know how.

Please, is this code correct?

**Comment by peterkogo** [comment]
Why are you handling the dragging of the nodes yourself? RF automatically handles dragging of all selected nodes.

I'm sorry but It is really hard to know what's wrong without a reproduction. Plus, if it is due to a mistake, you will see as soon as you try to extract the minimal code needed to make dragging work.

**Comment by lucapaolelli** [comment]
I agree with you it is really hard to debug without sharing the entire context of the project (not even possible without subscribing an nda).

So I try to explain more about the context. Nodes and edges are externally managed in the wrapper component state. Also selection, drag and drop, creation of new nodes/edges, deletion and viewport are externally managed. Also the state manages internal appareance of nodes based on a remote configuration.

Can this full-external state management solution lead to the problem we are trying to solve?

Let's remember that this problem was not here in v11.x.x and in v12.0.0 rcs (I verified all pre v12.3.5 releases), this is why I think this is an issue.

I migrated to v12 because viewport can externally managed while in v11 it was a pain to manage it.

**Comment by peterkogo** [comment]
I mean specifically selection and dragging. Both are fairly complicated procedures. You can take a look into [XYDrag](https://github.com/xyflow/xyflow/blob/main/packages/system/src/xydrag/XYDrag.ts) to see what kind of implications there are.

**Comment by lucapaolelli** [comment]
I will try to disable externally managed selection and dragging, I'll write back to this thread soon

**Comment by moklick** [comment]
I could imagine this comes from the change that we applied width and height to your nodes in v11. In v12 you need to add `measured.width` and `measured.height` after a dimension change otherwise your app will be broken.

**Comment by normad5342181** [comment]
> I could imagine this comes from the change that we applied width and height to your nodes in v11. In v12 you need to add `measured.width` and `measured.height` after a dimension change otherwise your app will be broken.

I also get the same problem as the author. And i found that it was because the return values or parameters of `getNodes` and `setNodes did not include the `measured` object. Therefore, I added this object when calling them, and it works. @moklick Thanks

**Comment by lucapaolelli** [comment]
I confirm this fixes the issue.

I precise that in my implementation nodes do not change their size.

Thank you for your support.
