### ISSUE TITLE
smoothStep bug

### ISSUE THREAD

**Issue by KobeZhou** [xyflow/xyflow#4860]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Describe the Bug

I use smoothStep edge to create line，not expected。 But I use Bezier，expected。

### Steps to reproduce the bug or issue

![image](https://github.com/user-attachments/assets/9fd15742-8e84-4eef-a88a-3d7ecdce3443)
 when I use smoothStep , it 's unexpectd line.

### Expected behavior

![image](https://github.com/user-attachments/assets/75accde9-b4e8-436f-8459-f8cd8ebcf53c)
when I use smoothStep， I expect this connection line position。

**Comment by peterkogo** [comment]
That's how the smooth step edge works. It is connected to the correct node, but it is just hidden behind the previous node...
<img width="449" alt="image" src="https://github.com/user-attachments/assets/07daeefc-ea6e-414d-a33d-9f3058fd1faf">

It overlays with the bezier edge. I don't
