### ISSUE TITLE
Dynamically change the position of Handles

### ISSUE THREAD

**Issue by rafaelsilva81** [xyflow/xyflow#4863]
### Please describe the feature that you want to propose

Hello everyone, I am currently trying to implement dynamic positions for the handles. However whenever I change the position the rendering of the edge doesn't follow the new position until i manually update the page. I think it would be interesting to have a way of dynamically updating the positions and have the edges follow

![image](https://github.com/user-attachments/assets/9b65e762-88ba-4cdf-9587-ab6451dbb1ea)

I am sorry if this is something that already exists somehow, but please let me know

**Comment by bcakmakoglu** [comment]
[You should read the section about dynamic handles](https://reactflow.dev/api-reference/components/handle#dynamic-handles) since what you're requesting is already possible.

**Comment by rafaelsilva81** [comment]
Thanks for the help. I wasn't able to find this at all yesterday. Marking this as closed
