### ISSUE TITLE
input select inside a node is not scrolling

### ISSUE THREAD

**Issue by tarcisioandrade** [xyflow/xyflow#4882]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.3.0
- Browser and version: Microsoft Edge Version 131.0.2903.86 (Official build) (64-bit)
- OS and version: Windows 11

### Describe the Bug

I have an input select inside a node and when I place the cursor inside the input where the expected behavior is to scroll the input, it is ignored and scroll the browser

Any suggestions to solve this?

### Steps to reproduce the bug or issue

1. Create a node with an input select inside
2. Try scroll the input

### Expected behavior

The expected behavior is to give privilege to scrolling where the mouse is

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/f9b24314-0ce7-4b21-8803-3279cb202db9)

**Comment by bcakmakoglu** [comment]
add the `nowheel` class name to the select, that should fix it.

[See this section of the docs.](https://reactflow.dev/api-reference/types/node-props#notes)

**Comment by tarcisioandrade** [comment]
> add the `nowheel` class name to the select, that should fix it.
> 
> [See this section of the docs.](https://reactflow.dev/api-reference/types/node-props#notes)

OMG 🤯, you are amazing bro, thank you
