### ISSUE TITLE
Incrementing / decrementing node with input type="number" causes value to change until the input is blurred

### ISSUE THREAD

**Issue by robert-westenberger** [xyflow/xyflow#4885]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.3.6
- Browser and version: Google Chrome Version 131.0.6778.140 (Official Build) (64-bit)
- OS and version: windows 11 home 23H2 22631.4460

### Live code example

https://stackblitz.com/edit/vitejs-vite-3zx58gsf?file=src%2FApp.tsx

### Describe the Bug

I have a custom node that renders a number input. I use updateNodeData destructured from useReactFlow in the input's onChange callback to change the value.

If i type in a digit, it works as expected. 
If i increment or decrement using the up or down keys on the keyboard, it also works as expected. If the value in the input is currently 1, and I hit the up arrow on the keyboard, the input becomes 2.

However, if i click the up or down arrows in the input to increment or decrement the value, it causes the value of the input to change rapidly. If the value in the current number input is 1, and I click on the increment button in the number input, the value becomes 2, then 3, then 4, and so on, very rapidly. This keeps happening until the input is blurred.

### Steps to reproduce the bug or issue

In one of the nodes that is rendering an input with type="number", click on the increment (up arrow) or decrement (down arrow) buttons. The value in the input will rapidly change until the input is blurred.

### Expected behavior

Clicking increment or decrement in an input with type="number" will increase the value by 1 or decrease the value by 1 respectively.

**Comment by bcakmakoglu** [comment]
Add `nopan nodrag` class names to your input element to stop that behavior.

```tsx
  <input
    className="nodrag nopan"
    // ... rest
  />

**Comment by robert-westenberger** [comment]
@bcakmakoglu thank you. Closing this.
