### ISSUE TITLE
Changing the inner content, without requring to re-implement the entire node

### ISSUE THREAD

**Issue by Nefcanto** [xyflow/xyflow#4906]
### Please describe the feature that you want to propose

After the discussion https://github.com/xyflow/xyflow/discussions/4905, I realized that if someone wants to change the content of a node, he needs to re-implement the entire node.

Consider this React component:

```
const Person = ({ data }) => {
  const { avatar, fullName, job, totalScore } = data;

  return (
    <div className='m-3 flex max-w-72 flex-col items-center gap-2 rounded-lg bg-slate-200 p-4 shadow-sm shadow-black'>
      <img
        className='rounded-full border-2 border-blue-400'
        src={avatar}
      />
      <div className=''>
        <h1 className='text-3xl font-semibold text-slate-800'>
          {fullName}
        </h1>
        <span className='text-xs'>
          <span>{job}</span>
          <sup>{totalScore}</sup>
        </span>
      </div>
    </div>
  );
};
```

Which renders a card like this:

![image](https://github.com/user-attachments/assets/339232c3-299c-4c3d-a903-9a7c901921b7)

Please provide a way to replace **only** the node's content with this component, while keeping everything else as the default. *Everything else* includes all of the warnings and errors that a person encounters as soon as he uses this node as a custom node, including but not limited to:

> It looks like you have created a new nodeTypes or edgeTypes object. If this wasn’t on purpose please define the nodeTypes/edgeTypes outside of the component or memoize them.

Or

> Node type not found. Using fallback type “default”.

Or

> Couldn’t create edge for source/target handle id: “some-id”; edge id:

And so on.

**Comment by peterkogo** [comment]
See my answer in your [discussion](https://github.com/xyflow/xyflow/discussions/4905)

**Comment by Nefcanto** [comment]
@moklick thank you for mentioning "reusable wrapper". Yep that's possible. Yet I didn't know that the default node is only 10 lines of code. I thought it should be 500 lines of code. @peterkogo thanks for linking to the default node.
