### ISSUE TITLE
Increase node's z-index on hover

### ISSUE THREAD

**Issue by AresEkb** [xyflow/xyflow#4914]
### Please describe the feature that you want to propose

My application shows a popup palette when a node is hovered:

![image](https://github.com/user-attachments/assets/2114cef8-0ca3-4cac-919e-ed28d013fe0f)

The palette is nested into a node so it can be easily positioned relative to the node. But the problem is that it's overlapped by a selected node. Is it possible to increase z-index of a hovered node and all its nested nodes?

The following works partly:

```css
.react-flow__node:hover {
  z-index: 2000 !important;
}
```

The palette appears fine, but all nested nodes disappears (the attribute in this example):

![image](https://github.com/user-attachments/assets/6ef15b03-1de7-4b0b-b4bd-5936099f0a72)

Another option is to use [anchor positioning](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_anchor_positioning/Using) and don't nest the palette into a node. But it [doesn't work with CSS translate](https://issues.chromium.org/issues/348333894)

Could you suggest a solution?

1. A way to increase z-index of a hovered node with all it's contents
2. A way to replace `CSS translate` for node positioning by something else
3. Or the only way is to calculate a palette position based on node position and size?

**Comment by bcakmakoglu** [comment]
Simplest solution to this is to utilize the [`NodeToolbar`](https://reactflow.dev/api-reference/components/node-toolbar) component.

[Here's an example.](https://codesandbox.io/p/devbox/tender-clarke-fgyzlp)

Just put your palette into the Toolbar component and you should be good to go.

**Comment by AresEkb** [comment]
Works perfect, thanks a lot!
