### ISSUE TITLE
Pane gets Freezed on pressing shift+cmd+4

### ISSUE THREAD

**Issue by agarwal00s** [xyflow/xyflow#824]
after taking a screenshot through shift+cmd+4, the pane gets freezed. 
<img width="1490" alt="Screenshot 2021-01-08 at 12 11 26 PM" src="https://user-images.githubusercontent.com/22545835/103984200-afc3c680-51ac-11eb-9764-a154469ec3b0.png">

**Comment by emielwit** [comment]
I had the same problem, changing the `selectionKeyCode` fixed this problem for me.

**Comment by moklick** [comment]
I tried to solve this but unfortunately I can't find a solution for this problem. The problem is that macos don't fire the keyup event after using a shortcut like shift+cmd+4. Other [libraries have this problem too](https://github.com/jaywcjlove/hotkeys/issues/98). For now the solution from @emielwit seems to be the best way.

**Comment by nmilev-cursive** [comment]
@emielwit Could you elaborate your proposed solution?

**Comment by emielwit** [comment]
@nmilev-cursive the default selection code is shift, which is currently conflicting with screenshots. If you add the following prop to your `ReactFlow` component this will be fixed ` selectionKeyCode={145}`. You can change it to whatever keycode you want.

**Comment by nmilev-cursive** [comment]
Thank you!

**Comment by kid-icarus** [comment]
This was really frustrating me so I spent a little bit of time tinkering and posted a comment [here](https://github.com/jaywcjlove/hotkeys/issues/98) and filed a chromium bug report [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1194004)

**Comment by moklick** [comment]
this is solved in React Flow 12.0.0 🚀
